import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";
import useSpacingProps from "../../utils/spacing-props";
import useWidthProps from "../../utils/width-props";
import useHeightProps from "../../utils/height-props";
import {
  alignItems,
  alignSelf,
  alignContent,
  animation,
  backdropFilter,
  background,
  bgColor,
  border,
  borderBottom,
  borderTop,
  borderLeft,
  borderRight,
  borderColor,
  borderWidth,
  borderRadius,
  bottom,
  boxShadow,
  boxSizing,
  clip,
  color,
  cursor,
  columnGap,
  display,
  filter,
  float,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontVariant,
  fontWeight,
  flexWrap,
  flexShrink,
  flexDirection,
  flexGrow,
  gridColumn,
  gridTemplateColumns,
  gridTemplateRows,
  gridTemplate,
  gap,
  height,
  justifyContent,
  justifyItems,
  justifySelf,
  left,
  letterSpacing,
  lineHeight,
  listStyle,
  listStyleImage,
  listStylePosition,
  listStyleType,
  margin,
  marginBottom,
  marginLeft,
  marginRight,
  marginTop,
  maxHeight,
  maxWidth,
  minHeight,
  minWidth,
  opacity,
  order,
  outline,
  outlineColor,
  outlineWidth,
  overflow,
  overflowX,
  overflowY,
  padding,
  paddingBottom,
  paddingTop,
  paddingLeft,
  paddingRight,
  pageBreakAfter,
  pageBreakBefore,
  pageBreakInside,
  pointerEvents,
  position,
  quotes,
  rowGap,
  resize,
  right,
  tabSize,
  tableLayout,
  textAlign,
  textDecoration,
  textIndent,
  textJustify,
  textOverflow,
  textShadow,
  textTransform,
  top,
  transform,
  transformOrigin,
  transformStyle,
  transition,
  verticalAlign,
  visibility,
  whiteSpace,
  width,
  wordBreak,
  wordSpacing,
  wordWrap,
  zIndex,
} from "../properties";

const StyledGrid = styled.div`
${alignItems}
${alignSelf}
${alignContent}
${animation}
${backdropFilter}
${background}
${bgColor}
${border}
${borderBottom}
${borderTop}
${borderLeft}
${borderRight}
${borderColor}
${borderWidth}
${borderRadius}
${bottom}
${boxShadow}
${boxSizing}
${clip}
${color}
${cursor}
${columnGap}
${display}
${filter}
${float}
${font}
${fontFamily}
${fontSize}
${fontStyle}
${fontVariant}
${fontWeight}
${flexWrap}
${flexShrink}
${flexDirection}
${flexGrow}
${gridColumn}
${gridTemplateColumns}
${gridTemplateRows}
${gridTemplate}
${gap}
${height}
${justifyContent}
${justifyItems}
${justifySelf}
${left}
${letterSpacing}
${lineHeight}
${listStyle}
${listStyleImage}
${listStylePosition}
${listStyleType}
${margin}
${marginBottom}
${marginLeft}
${marginRight}
${marginTop}
${maxHeight}
${maxWidth}
${minHeight}
${minWidth}
${opacity}
${order}
${outline}
${outlineColor}
${outlineWidth}
${overflow}
${overflowX}
${overflowY}
${padding}
${paddingBottom}
${paddingTop}
${paddingLeft}
${paddingRight}
${pageBreakAfter}
${pageBreakBefore}
${pageBreakInside}
${pointerEvents}
${position}
${quotes}
${rowGap}
${resize}
${right}
${tabSize}
${tableLayout}
${textAlign}
${textDecoration}
${textIndent}
${textJustify}
${textOverflow}
${textShadow}
${textTransform}
${top}
${transform}
${transformOrigin}
${transformStyle}
${transition}
${verticalAlign}
${visibility}
${whiteSpace}
${width}
${wordBreak}
${wordSpacing}
${wordWrap}
${zIndex}
`;

const Grid = ({ children, ...props }) => <StyledGrid {...props}>{children}</StyledGrid>;

Grid.propTypes = {
  columns: PropTypes.string,
  rows: PropTypes.string,
  gap: PropTypes.string,
  rowGrap: PropTypes.string,
  columnGap: PropTypes.string,
};

export default Grid;
