import  {
  BiAbacus,
  BiAccessibility,
  BiAddToQueue,
  BiAdjust,
  BiAlarmAdd,
  BiAlarmExclamation,
  BiAlarmOff,
  BiAlarmSnooze,
  BiAlarm,
  BiAlbum,
  BiAlignJustify,
  BiAlignLeft,
  BiAlignMiddle,
  BiAlignRight,
  BiAnalyse,
  BiAnchor,
  BiAngry,
  BiAperture,
  BiArch,
  BiArchiveIn,
  BiArchiveOut,
  BiArchive,
  BiArea,
  BiArrowBack,
  BiArrowFromBottom,
  BiArrowFromLeft,
  BiArrowFromRight,
  BiArrowFromTop,
  BiArrowToBottom,
  BiArrowToLeft,
  BiArrowToRight,
  BiArrowToTop,
  BiAt,
  BiAtom,
  BiAward,
  BiBadgeCheck,
  BiBadge,
  BiBall,
  BiBandAid,
  BiBarChartAlt2,
  BiBarChartAlt,
  BiBarChartSquare,
  BiBarChart,
  BiBarcodeReader,
  BiBarcode,
  BiBaseball,
  BiBasket,
  BiBasketball,
  BiBath,
  BiBattery,
  BiBed,
  BiBeenHere,
  BiBeer,
  BiBellMinus,
  BiBellOff,
  BiBellPlus,
  BiBell,
  BiBible,
  BiBitcoin,
  BiBlanket,
  BiBlock,
  BiBluetooth,
  BiBody,
  BiBold,
  BiBoltCircle,
  BiBomb,
  BiBone,
  BiBong,
  BiBookAdd,
  BiBookAlt,
  BiBookBookmark,
  BiBookContent,
  BiBookHeart,
  BiBookOpen,
  BiBookReader,
  BiBook,
  BiBookmarkAltMinus,
  BiBookmarkAltPlus,
  BiBookmarkAlt,
  BiBookmarkHeart,
  BiBookmarkMinus,
  BiBookmarkPlus,
  BiBookmark,
  BiBookmarks,
  BiBorderAll,
  BiBorderBottom,
  BiBorderInner,
  BiBorderLeft,
  BiBorderNone,
  BiBorderOuter,
  BiBorderRadius,
  BiBorderRight,
  BiBorderTop,
  BiBot,
  BiBowlingBall,
  BiBox,
  BiBracket,
  BiBraille,
  BiBrain,
  BiBriefcaseAlt2,
  BiBriefcaseAlt,
  BiBriefcase,
  BiBrightnessHalf,
  BiBrightness,
  BiBroadcast,
  BiBrushAlt,
  BiBrush,
  BiBugAlt,
  BiBug,
  BiBuildingHouse,
  BiBuilding,
  BiBuildings,
  BiBulb,
  BiBullseye,
  BiBuoy,
  BiBusSchool,
  BiBus,
  BiCabinet,
  BiCake,
  BiCalculator,
  BiCalendarAlt,
  BiCalendarCheck,
  BiCalendarEdit,
  BiCalendarEvent,
  BiCalendarExclamation,
  BiCalendarHeart,
  BiCalendarMinus,
  BiCalendarPlus,
  BiCalendarStar,
  BiCalendarWeek,
  BiCalendarX,
  BiCalendar,
  BiCameraHome,
  BiCameraMovie,
  BiCameraOff,
  BiCamera,
  BiCapsule,
  BiCaptions,
  BiCar,
  BiCard,
  BiCaretDownCircle,
  BiCaretDownSquare,
  BiCaretDown,
  BiCaretLeftCircle,
  BiCaretLeftSquare,
  BiCaretLeft,
  BiCaretRightCircle,
  BiCaretRightSquare,
  BiCaretRight,
  BiCaretUpCircle,
  BiCaretUpSquare,
  BiCaretUp,
  BiCarousel,
  BiCartAlt,
  BiCart,
  BiCast,
  BiCategoryAlt,
  BiCategory,
  BiCctv,
  BiCertification,
  BiChair,
  BiChalkboard,
  BiChart,
  BiChat,
  BiCheckCircle,
  BiCheckDouble,
  BiCheckShield,
  BiCheckSquare,
  BiCheck,
  BiCheckboxChecked,
  BiCheckboxMinus,
  BiCheckboxSquare,
  BiCheckbox,
  BiChevronDownCircle,
  BiChevronDownSquare,
  BiChevronDown,
  BiChevronLeftCircle,
  BiChevronLeftSquare,
  BiChevronLeft,
  BiChevronRightCircle,
  BiChevronRightSquare,
  BiChevronRight,
  BiChevronUpCircle,
  BiChevronUpSquare,
  BiChevronUp,
  BiChevronsDown,
  BiChevronsLeft,
  BiChevronsRight,
  BiChevronsUp,
  BiChip,
  BiChurch,
  BiCircle,
  BiClinic,
  BiClipboard,
  BiCloset,
  BiCloudDownload,
  BiCloudDrizzle,
  BiCloudLightRain,
  BiCloudLightning,
  BiCloudRain,
  BiCloudSnow,
  BiCloudUpload,
  BiCloud,
  BiCodeAlt,
  BiCodeBlock,
  BiCodeCurly,
  BiCode,
  BiCoffeeTogo,
  BiCoffee,
  BiCog,
  BiCoinStack,
  BiCoin,
  BiCollapse,
  BiCollection,
  BiColorFill,
  BiColumns,
  BiCommand,
  BiCommentAdd,
  BiCommentCheck,
  BiCommentDetail,
  BiCommentDots,
  BiCommentEdit,
  BiCommentError,
  BiCommentMinus,
  BiCommentX,
  BiComment,
  BiCompass,
  BiConfused,
  BiConversation,
  BiCookie,
  BiCool,
  BiCopyAlt,
  BiCopy,
  BiCopyright,
  BiCreditCardAlt,
  BiCreditCardFront,
  BiCreditCard,
  BiCrop,
  BiCrosshair,
  BiCrown,
  BiCubeAlt,
  BiCube,
  BiCuboid,
  BiCurrentLocation,
  BiCustomize,
  BiCut,
  BiCycling,
  BiCylinder,
  BiData,
  BiDesktop,
  BiDetail,
  BiDevices,
  BiDialpadAlt,
  BiDialpad,
  BiDiamond,
  BiDice1,
  BiDice2,
  BiDice3,
  BiDice4,
  BiDice5,
  BiDice6,
  BiDirections,
  BiDisc,
  BiDish,
  BiDislike,
  BiDizzy,
  BiDna,
  BiDockBottom,
  BiDockLeft,
  BiDockRight,
  BiDockTop,
  BiDollarCircle,
  BiDollar,
  BiDonateBlood,
  BiDonateHeart,
  BiDoorOpen,
  BiDotsHorizontalRounded,
  BiDotsHorizontal,
  BiDotsVerticalRounded,
  BiDotsVertical,
  BiDoughnutChart,
  BiDownArrowAlt,
  BiDownArrowCircle,
  BiDownArrow,
  BiDownload,
  BiDownvote,
  BiDrink,
  BiDroplet,
  BiDumbbell,
  BiDuplicate,
  BiEditAlt,
  BiEdit,
  BiEnvelopeOpen,
  BiEnvelope,
  BiEqualizer,
  BiEraser,
  BiErrorAlt,
  BiErrorCircle,
  BiError,
  BiEuro,
  BiExclude,
  BiExitFullscreen,
  BiExit,
  BiExpandAlt,
  BiExpand,
  BiExport,
  BiExtension,
  BiFace,
  BiFastForwardCircle,
  BiFastForward,
  BiFemaleSign,
  BiFemale,
  BiFileBlank,
  BiFileFind,
  BiFile,
  BiFilm,
  BiFilterAlt,
  BiFilter,
  BiFingerprint,
  BiFirstAid,
  BiFirstPage,
  BiFlag,
  BiFolderMinus,
  BiFolderOpen,
  BiFolderPlus,
  BiFolder,
  BiFontColor,
  BiFontFamily,
  BiFontSize,
  BiFont,
  BiFoodMenu,
  BiFoodTag,
  BiFootball,
  BiFridge,
  BiFullscreen,
  BiGame,
  BiGasPump,
  BiGhost,
  BiGift,
  BiGitBranch,
  BiGitCommit,
  BiGitCompare,
  BiGitMerge,
  BiGitPullRequest,
  BiGitRepoForked,
  BiGlassesAlt,
  BiGlasses,
  BiGlobeAlt,
  BiGlobe,
  BiGridAlt,
  BiGridHorizontal,
  BiGridSmall,
  BiGridVertical,
  BiGrid,
  BiGroup,
  BiHandicap,
  BiHappyAlt,
  BiHappyBeaming,
  BiHappyHeartEyes,
  BiHappy,
  BiHash,
  BiHdd,
  BiHeading,
  BiHeadphone,
  BiHealth,
  BiHeartCircle,
  BiHeartSquare,
  BiHeart,
  BiHelpCircle,
  BiHide,
  BiHighlight,
  BiHistory,
  BiHive,
  BiHomeAlt,
  BiHomeCircle,
  BiHomeHeart,
  BiHomeSmile,
  BiHome,
  BiHorizontalCenter,
  BiHotel,
  BiHourglass,
  BiIdCard,
  BiImageAdd,
  BiImageAlt,
  BiImage,
  BiImages,
  BiImport,
  BiInfinite,
  BiInfoCircle,
  BiInfoSquare,
  BiIntersect,
  BiItalic,
  BiJoystickAlt,
  BiJoystickButton,
  BiJoystick,
  BiKey,
  BiLabel,
  BiLandscape,
  BiLaptop,
  BiLastPage,
  BiLaugh,
  BiLayerMinus,
  BiLayerPlus,
  BiLayer,
  BiLayout,
  BiLeftArrowAlt,
  BiLeftArrowCircle,
  BiLeftArrow,
  BiLeftDownArrowCircle,
  BiLeftIndent,
  BiLeftTopArrowCircle,
  BiLibrary,
  BiLike,
  BiLineChartDown,
  BiLineChart,
  BiLinkAlt,
  BiLinkExternal,
  BiLink,
  BiLira,
  BiListCheck,
  BiListMinus,
  BiListOl,
  BiListPlus,
  BiListUl,
  BiLoaderAlt,
  BiLoaderCircle,
  BiLoader,
  BiLocationPlus,
  BiLockAlt,
  BiLockOpenAlt,
  BiLockOpen,
  BiLock,
  BiLogInCircle,
  BiLogIn,
  BiLogOutCircle,
  BiLogOut,
  BiLowVision,
  BiMagnet,
  BiMailSend,
  BiMaleSign,
  BiMale,
  BiMapAlt,
  BiMapPin,
  BiMap,
  BiMask,
  BiMedal,
  BiMehAlt,
  BiMehBlank,
  BiMeh,
  BiMemoryCard,
  BiMenuAltLeft,
  BiMenuAltRight,
  BiMenu,
  BiMerge,
  BiMessageAdd,
  BiMessageAltAdd,
  BiMessageAltCheck,
  BiMessageAltDetail,
  BiMessageAltDots,
  BiMessageAltEdit,
  BiMessageAltError,
  BiMessageAltMinus,
  BiMessageAltX,
  BiMessageAlt,
  BiMessageCheck,
  BiMessageDetail,
  BiMessageDots,
  BiMessageEdit,
  BiMessageError,
  BiMessageMinus,
  BiMessageRoundedAdd,
  BiMessageRoundedCheck,
  BiMessageRoundedDetail,
  BiMessageRoundedDots,
  BiMessageRoundedEdit,
  BiMessageRoundedError,
  BiMessageRoundedMinus,
  BiMessageRoundedX,
  BiMessageRounded,
  BiMessageSquareAdd,
  BiMessageSquareCheck,
  BiMessageSquareDetail,
  BiMessageSquareDots,
  BiMessageSquareEdit,
  BiMessageSquareError,
  BiMessageSquareMinus,
  BiMessageSquareX,
  BiMessageSquare,
  BiMessageX,
  BiMessage,
  BiMeteor,
  BiMicrochip,
  BiMicrophoneOff,
  BiMicrophone,
  BiMinusBack,
  BiMinusCircle,
  BiMinusFront,
  BiMinus,
  BiMobileAlt,
  BiMobileLandscape,
  BiMobileVibration,
  BiMobile,
  BiMoney,
  BiMoon,
  BiMouseAlt,
  BiMouse,
  BiMoveHorizontal,
  BiMoveVertical,
  BiMove,
  BiMoviePlay,
  BiMovie,
  BiMusic,
  BiNavigation,
  BiNetworkChart,
  BiNews,
  BiNoEntry,
  BiNote,
  BiNotepad,
  BiNotificationOff,
  BiNotification,
  BiOutline,
  BiPackage,
  BiPaintRoll,
  BiPaint,
  BiPalette,
  BiPaperPlane,
  BiPaperclip,
  BiParagraph,
  BiPaste,
  BiPauseCircle,
  BiPause,
  BiPen,
  BiPencil,
  BiPhoneCall,
  BiPhoneIncoming,
  BiPhoneOff,
  BiPhoneOutgoing,
  BiPhone,
  BiPhotoAlbum,
  BiPieChartAlt2,
  BiPieChartAlt,
  BiPieChart,
  BiPin,
  BiPlanet,
  BiPlayCircle,
  BiPlay,
  BiPlug,
  BiPlusCircle,
  BiPlusMedical,
  BiPlus,
  BiPodcast,
  BiPointer,
  BiPoll,
  BiPolygon,
  BiPound,
  BiPowerOff,
  BiPrinter,
  BiPulse,
  BiPurchaseTagAlt,
  BiPurchaseTag,
  BiPyramid,
  BiQrScan,
  BiQr,
  BiQuestionMark,
  BiRadar,
  BiRadioCircleMarked,
  BiRadioCircle,
  BiRadio,
  BiReceipt,
  BiRectangle,
  BiRecycle,
  BiRedo,
  BiRefresh,
  BiRegistered,
  BiRename,
  BiRepeat,
  BiReplyAll,
  BiReply,
  BiRepost,
  BiReset,
  BiRestaurant,
  BiRevision,
  BiRewindCircle,
  BiRewind,
  BiRightArrowAlt,
  BiRightArrowCircle,
  BiRightArrow,
  BiRightDownArrowCircle,
  BiRightIndent,
  BiRightTopArrowCircle,
  BiRocket,
  BiRotateLeft,
  BiRotateRight,
  BiRss,
  BiRuble,
  BiRuler,
  BiRun,
  BiRupee,
  BiSad,
  BiSave,
  BiScan,
  BiScreenshot,
  BiSearchAlt2,
  BiSearchAlt,
  BiSearch,
  BiSelectMultiple,
  BiSelection,
  BiSend,
  BiServer,
  BiShapeCircle,
  BiShapePolygon,
  BiShapeSquare,
  BiShapeTriangle,
  BiShareAlt,
  BiShare,
  BiShekel,
  BiShieldAlt2,
  BiShieldAlt,
  BiShieldQuarter,
  BiShieldX,
  BiShield,
  BiShocked,
  BiShoppingBag,
  BiShowAlt,
  BiShow,
  BiShuffle,
  BiSidebar,
  BiSitemap,
  BiSkipNextCircle,
  BiSkipNext,
  BiSkipPreviousCircle,
  BiSkipPrevious,
  BiSleepy,
  BiSliderAlt,
  BiSlider,
  BiSlideshow,
  BiSmile,
  BiSortAZ,
  BiSortAlt2,
  BiSortDown,
  BiSortUp,
  BiSortZA,
  BiSort,
  BiSpa,
  BiSpaceBar,
  BiSpeaker,
  BiSprayCan,
  BiSpreadsheet,
  BiSquareRounded,
  BiSquare,
  BiStar,
  BiStation,
  BiStats,
  BiSticker,
  BiStopCircle,
  BiStop,
  BiStopwatch,
  BiStoreAlt,
  BiStore,
  BiStreetView,
  BiStrikethrough,
  BiSubdirectoryLeft,
  BiSubdirectoryRight,
  BiSun,
  BiSupport,
  BiSwim,
  BiSync,
  BiTab,
  BiTable,
  BiTachometer,
  BiTagAlt,
  BiTag,
  BiTargetLock,
  BiTaskX,
  BiTask,
  BiTaxi,
  BiTennisBall,
  BiTerminal,
  BiTestTube,
  BiText,
  BiTimeFive,
  BiTime,
  BiTimer,
  BiTired,
  BiToggleLeft,
  BiToggleRight,
  BiTone,
  BiTrafficCone,
  BiTrain,
  BiTransferAlt,
  BiTransfer,
  BiTrashAlt,
  BiTrash,
  BiTrendingDown,
  BiTrendingUp,
  BiTrim,
  BiTrip,
  BiTrophy,
  BiTv,
  BiUnderline,
  BiUndo,
  BiUnite,
  BiUnlink,
  BiUpArrowAlt,
  BiUpArrowCircle,
  BiUpArrow,
  BiUpload,
  BiUpsideDown,
  BiUpvote,
  BiUsb,
  BiUserCheck,
  BiUserCircle,
  BiUserMinus,
  BiUserPin,
  BiUserPlus,
  BiUserVoice,
  BiUserX,
  BiUser,
  BiVector,
  BiVerticalCenter,
  BiVial,
  BiVideoOff,
  BiVideoPlus,
  BiVideoRecording,
  BiVideo,
  BiVoicemail,
  BiVolumeFull,
  BiVolumeLow,
  BiVolumeMute,
  BiVolume,
  BiWalk,
  BiWalletAlt,
  BiWallet,
  BiWater,
  BiWebcam,
  BiWifi0,
  BiWifi1,
  BiWifi2,
  BiWifiOff,
  BiWifi,
  BiWind,
  BiWindowAlt,
  BiWindowClose,
  BiWindowOpen,
  BiWindow,
  BiWindows,
  BiWine,
  BiWinkSmile,
  BiWinkTongue,
  BiWon,
  BiWorld,
  BiWrench,
  BiXCircle,
  BiX,
  BiYen,
  BiZoomIn,
  BiZoomOut,
} from "react-icons/bi";

export const BoxIcons = {
  "BiAbacus": BiAbacus,
  "BiAccessibility": BiAccessibility,
  "BiAddToQueue": BiAddToQueue,
  "BiAdjust": BiAdjust,
  "BiAlarmAdd": BiAlarmAdd,
  "BiAlarmExclamation": BiAlarmExclamation,
  "BiAlarmOff": BiAlarmOff,
  "BiAlarmSnooze": BiAlarmSnooze,
  "BiAlarm": BiAlarm,
  "BiAlbum": BiAlbum,
  "BiAlignJustify": BiAlignJustify,
  "BiAlignLeft": BiAlignLeft,
  "BiAlignMiddle": BiAlignMiddle,
  "BiAlignRight": BiAlignRight,
  "BiAnalyse": BiAnalyse,
  "BiAnchor": BiAnchor,
  "BiAngry": BiAngry,
  "BiAperture": BiAperture,
  "BiArch": BiArch,
  "BiArchiveIn": BiArchiveIn,
  "BiArchiveOut": BiArchiveOut,
  "BiArchive": BiArchive,
  "BiArea": BiArea,
  "BiArrowBack": BiArrowBack,
  "BiArrowFromBottom": BiArrowFromBottom,
  "BiArrowFromLeft": BiArrowFromLeft,
  "BiArrowFromRight": BiArrowFromRight,
  "BiArrowFromTop": BiArrowFromTop,
  "BiArrowToBottom": BiArrowToBottom,
  "BiArrowToLeft": BiArrowToLeft,
  "BiArrowToRight": BiArrowToRight,
  "BiArrowToTop": BiArrowToTop,
  "BiAt": BiAt,
  "BiAtom": BiAtom,
  "BiAward": BiAward,
  "BiBadgeCheck": BiBadgeCheck,
  "BiBadge": BiBadge,
  "BiBall": BiBall,
  "BiBandAid": BiBandAid,
  "BiBarChartAlt2": BiBarChartAlt2,
  "BiBarChartAlt": BiBarChartAlt,
  "BiBarChartSquare": BiBarChartSquare,
  "BiBarChart": BiBarChart,
  "BiBarcodeReader": BiBarcodeReader,
  "BiBarcode": BiBarcode,
  "BiBaseball": BiBaseball,
  "BiBasket": BiBasket,
  "BiBasketball": BiBasketball,
  "BiBath": BiBath,
  "BiBattery": BiBattery,
  "BiBed": BiBed,
  "BiBeenHere": BiBeenHere,
  "BiBeer": BiBeer,
  "BiBellMinus": BiBellMinus,
  "BiBellOff": BiBellOff,
  "BiBellPlus": BiBellPlus,
  "BiBell": BiBell,
  "BiBible": BiBible,
  "BiBitcoin": BiBitcoin,
  "BiBlanket": BiBlanket,
  "BiBlock": BiBlock,
  "BiBluetooth": BiBluetooth,
  "BiBody": BiBody,
  "BiBold": BiBold,
  "BiBoltCircle": BiBoltCircle,
  "BiBomb": BiBomb,
  "BiBone": BiBone,
  "BiBong": BiBong,
  "BiBookAdd": BiBookAdd,
  "BiBookAlt": BiBookAlt,
  "BiBookBookmark": BiBookBookmark,
  "BiBookContent": BiBookContent,
  "BiBookHeart": BiBookHeart,
  "BiBookOpen": BiBookOpen,
  "BiBookReader": BiBookReader,
  "BiBook": BiBook,
  "BiBookmarkAltMinus": BiBookmarkAltMinus,
  "BiBookmarkAltPlus": BiBookmarkAltPlus,
  "BiBookmarkAlt": BiBookmarkAlt,
  "BiBookmarkHeart": BiBookmarkHeart,
  "BiBookmarkMinus": BiBookmarkMinus,
  "BiBookmarkPlus": BiBookmarkPlus,
  "BiBookmark": BiBookmark,
  "BiBookmarks": BiBookmarks,
  "BiBorderAll": BiBorderAll,
  "BiBorderBottom": BiBorderBottom,
  "BiBorderInner": BiBorderInner,
  "BiBorderLeft": BiBorderLeft,
  "BiBorderNone": BiBorderNone,
  "BiBorderOuter": BiBorderOuter,
  "BiBorderRadius": BiBorderRadius,
  "BiBorderRight": BiBorderRight,
  "BiBorderTop": BiBorderTop,
  "BiBot": BiBot,
  "BiBowlingBall": BiBowlingBall,
  "BiBox": BiBox,
  "BiBracket": BiBracket,
  "BiBraille": BiBraille,
  "BiBrain": BiBrain,
  "BiBriefcaseAlt2": BiBriefcaseAlt2,
  "BiBriefcaseAlt": BiBriefcaseAlt,
  "BiBriefcase": BiBriefcase,
  "BiBrightnessHalf": BiBrightnessHalf,
  "BiBrightness": BiBrightness,
  "BiBroadcast": BiBroadcast,
  "BiBrushAlt": BiBrushAlt,
  "BiBrush": BiBrush,
  "BiBugAlt": BiBugAlt,
  "BiBug": BiBug,
  "BiBuildingHouse": BiBuildingHouse,
  "BiBuilding": BiBuilding,
  "BiBuildings": BiBuildings,
  "BiBulb": BiBulb,
  "BiBullseye": BiBullseye,
  "BiBuoy": BiBuoy,
  "BiBusSchool": BiBusSchool,
  "BiBus": BiBus,
  "BiCabinet": BiCabinet,
  "BiCake": BiCake,
  "BiCalculator": BiCalculator,
  "BiCalendarAlt": BiCalendarAlt,
  "BiCalendarCheck": BiCalendarCheck,
  "BiCalendarEdit": BiCalendarEdit,
  "BiCalendarEvent": BiCalendarEvent,
  "BiCalendarExclamation": BiCalendarExclamation,
  "BiCalendarHeart": BiCalendarHeart,
  "BiCalendarMinus": BiCalendarMinus,
  "BiCalendarPlus": BiCalendarPlus,
  "BiCalendarStar": BiCalendarStar,
  "BiCalendarWeek": BiCalendarWeek,
  "BiCalendarX": BiCalendarX,
  "BiCalendar": BiCalendar,
  "BiCameraHome": BiCameraHome,
  "BiCameraMovie": BiCameraMovie,
  "BiCameraOff": BiCameraOff,
  "BiCamera": BiCamera,
  "BiCapsule": BiCapsule,
  "BiCaptions": BiCaptions,
  "BiCar": BiCar,
  "BiCard": BiCard,
  "BiCaretDownCircle": BiCaretDownCircle,
  "BiCaretDownSquare": BiCaretDownSquare,
  "BiCaretDown": BiCaretDown,
  "BiCaretLeftCircle": BiCaretLeftCircle,
  "BiCaretLeftSquare": BiCaretLeftSquare,
  "BiCaretLeft": BiCaretLeft,
  "BiCaretRightCircle": BiCaretRightCircle,
  "BiCaretRightSquare": BiCaretRightSquare,
  "BiCaretRight": BiCaretRight,
  "BiCaretUpCircle": BiCaretUpCircle,
  "BiCaretUpSquare": BiCaretUpSquare,
  "BiCaretUp": BiCaretUp,
  "BiCarousel": BiCarousel,
  "BiCartAlt": BiCartAlt,
  "BiCart": BiCart,
  "BiCast": BiCast,
  "BiCategoryAlt": BiCategoryAlt,
  "BiCategory": BiCategory,
  "BiCctv": BiCctv,
  "BiCertification": BiCertification,
  "BiChair": BiChair,
  "BiChalkboard": BiChalkboard,
  "BiChart": BiChart,
  "BiChat": BiChat,
  "BiCheckCircle": BiCheckCircle,
  "BiCheckDouble": BiCheckDouble,
  "BiCheckShield": BiCheckShield,
  "BiCheckSquare": BiCheckSquare,
  "BiCheck": BiCheck,
  "BiCheckboxChecked": BiCheckboxChecked,
  "BiCheckboxMinus": BiCheckboxMinus,
  "BiCheckboxSquare": BiCheckboxSquare,
  "BiCheckbox": BiCheckbox,
  "BiChevronDownCircle": BiChevronDownCircle,
  "BiChevronDownSquare": BiChevronDownSquare,
  "BiChevronDown": BiChevronDown,
  "BiChevronLeftCircle": BiChevronLeftCircle,
  "BiChevronLeftSquare": BiChevronLeftSquare,
  "BiChevronLeft": BiChevronLeft,
  "BiChevronRightCircle": BiChevronRightCircle,
  "BiChevronRightSquare": BiChevronRightSquare,
  "BiChevronRight": BiChevronRight,
  "BiChevronUpCircle": BiChevronUpCircle,
  "BiChevronUpSquare": BiChevronUpSquare,
  "BiChevronUp": BiChevronUp,
  "BiChevronsDown": BiChevronsDown,
  "BiChevronsLeft": BiChevronsLeft,
  "BiChevronsRight": BiChevronsRight,
  "BiChevronsUp": BiChevronsUp,
  "BiChip": BiChip,
  "BiChurch": BiChurch,
  "BiCircle": BiCircle,
  "BiClinic": BiClinic,
  "BiClipboard": BiClipboard,
  "BiCloset": BiCloset,
  "BiCloudDownload": BiCloudDownload,
  "BiCloudDrizzle": BiCloudDrizzle,
  "BiCloudLightRain": BiCloudLightRain,
  "BiCloudLightning": BiCloudLightning,
  "BiCloudRain": BiCloudRain,
  "BiCloudSnow": BiCloudSnow,
  "BiCloudUpload": BiCloudUpload,
  "BiCloud": BiCloud,
  "BiCodeAlt": BiCodeAlt,
  "BiCodeBlock": BiCodeBlock,
  "BiCodeCurly": BiCodeCurly,
  "BiCode": BiCode,
  "BiCoffeeTogo": BiCoffeeTogo,
  "BiCoffee": BiCoffee,
  "BiCog": BiCog,
  "BiCoinStack": BiCoinStack,
  "BiCoin": BiCoin,
  "BiCollapse": BiCollapse,
  "BiCollection": BiCollection,
  "BiColorFill": BiColorFill,
  "BiColumns": BiColumns,
  "BiCommand": BiCommand,
  "BiCommentAdd": BiCommentAdd,
  "BiCommentCheck": BiCommentCheck,
  "BiCommentDetail": BiCommentDetail,
  "BiCommentDots": BiCommentDots,
  "BiCommentEdit": BiCommentEdit,
  "BiCommentError": BiCommentError,
  "BiCommentMinus": BiCommentMinus,
  "BiCommentX": BiCommentX,
  "BiComment": BiComment,
  "BiCompass": BiCompass,
  "BiConfused": BiConfused,
  "BiConversation": BiConversation,
  "BiCookie": BiCookie,
  "BiCool": BiCool,
  "BiCopyAlt": BiCopyAlt,
  "BiCopy": BiCopy,
  "BiCopyright": BiCopyright,
  "BiCreditCardAlt": BiCreditCardAlt,
  "BiCreditCardFront": BiCreditCardFront,
  "BiCreditCard": BiCreditCard,
  "BiCrop": BiCrop,
  "BiCrosshair": BiCrosshair,
  "BiCrown": BiCrown,
  "BiCubeAlt": BiCubeAlt,
  "BiCube": BiCube,
  "BiCuboid": BiCuboid,
  "BiCurrentLocation": BiCurrentLocation,
  "BiCustomize": BiCustomize,
  "BiCut": BiCut,
  "BiCycling": BiCycling,
  "BiCylinder": BiCylinder,
  "BiData": BiData,
  "BiDesktop": BiDesktop,
  "BiDetail": BiDetail,
  "BiDevices": BiDevices,
  "BiDialpadAlt": BiDialpadAlt,
  "BiDialpad": BiDialpad,
  "BiDiamond": BiDiamond,
  "BiDice1": BiDice1,
  "BiDice2": BiDice2,
  "BiDice3": BiDice3,
  "BiDice4": BiDice4,
  "BiDice5": BiDice5,
  "BiDice6": BiDice6,
  "BiDirections": BiDirections,
  "BiDisc": BiDisc,
  "BiDish": BiDish,
  "BiDislike": BiDislike,
  "BiDizzy": BiDizzy,
  "BiDna": BiDna,
  "BiDockBottom": BiDockBottom,
  "BiDockLeft": BiDockLeft,
  "BiDockRight": BiDockRight,
  "BiDockTop": BiDockTop,
  "BiDollarCircle": BiDollarCircle,
  "BiDollar": BiDollar,
  "BiDonateBlood": BiDonateBlood,
  "BiDonateHeart": BiDonateHeart,
  "BiDoorOpen": BiDoorOpen,
  "BiDotsHorizontalRounded": BiDotsHorizontalRounded,
  "BiDotsHorizontal": BiDotsHorizontal,
  "BiDotsVerticalRounded": BiDotsVerticalRounded,
  "BiDotsVertical": BiDotsVertical,
  "BiDoughnutChart": BiDoughnutChart,
  "BiDownArrowAlt": BiDownArrowAlt,
  "BiDownArrowCircle": BiDownArrowCircle,
  "BiDownArrow": BiDownArrow,
  "BiDownload": BiDownload,
  "BiDownvote": BiDownvote,
  "BiDrink": BiDrink,
  "BiDroplet": BiDroplet,
  "BiDumbbell": BiDumbbell,
  "BiDuplicate": BiDuplicate,
  "BiEditAlt": BiEditAlt,
  "BiEdit": BiEdit,
  "BiEnvelopeOpen": BiEnvelopeOpen,
  "BiEnvelope": BiEnvelope,
  "BiEqualizer": BiEqualizer,
  "BiEraser": BiEraser,
  "BiErrorAlt": BiErrorAlt,
  "BiErrorCircle": BiErrorCircle,
  "BiError": BiError,
  "BiEuro": BiEuro,
  "BiExclude": BiExclude,
  "BiExitFullscreen": BiExitFullscreen,
  "BiExit": BiExit,
  "BiExpandAlt": BiExpandAlt,
  "BiExpand": BiExpand,
  "BiExport": BiExport,
  "BiExtension": BiExtension,
  "BiFace": BiFace,
  "BiFastForwardCircle": BiFastForwardCircle,
  "BiFastForward": BiFastForward,
  "BiFemaleSign": BiFemaleSign,
  "BiFemale": BiFemale,
  "BiFileBlank": BiFileBlank,
  "BiFileFind": BiFileFind,
  "BiFile": BiFile,
  "BiFilm": BiFilm,
  "BiFilterAlt": BiFilterAlt,
  "BiFilter": BiFilter,
  "BiFingerprint": BiFingerprint,
  "BiFirstAid": BiFirstAid,
  "BiFirstPage": BiFirstPage,
  "BiFlag": BiFlag,
  "BiFolderMinus": BiFolderMinus,
  "BiFolderOpen": BiFolderOpen,
  "BiFolderPlus": BiFolderPlus,
  "BiFolder": BiFolder,
  "BiFontColor": BiFontColor,
  "BiFontFamily": BiFontFamily,
  "BiFontSize": BiFontSize,
  "BiFont": BiFont,
  "BiFoodMenu": BiFoodMenu,
  "BiFoodTag": BiFoodTag,
  "BiFootball": BiFootball,
  "BiFridge": BiFridge,
  "BiFullscreen": BiFullscreen,
  "BiGame": BiGame,
  "BiGasPump": BiGasPump,
  "BiGhost": BiGhost,
  "BiGift": BiGift,
  "BiGitBranch": BiGitBranch,
  "BiGitCommit": BiGitCommit,
  "BiGitCompare": BiGitCompare,
  "BiGitMerge": BiGitMerge,
  "BiGitPullRequest": BiGitPullRequest,
  "BiGitRepoForked": BiGitRepoForked,
  "BiGlassesAlt": BiGlassesAlt,
  "BiGlasses": BiGlasses,
  "BiGlobeAlt": BiGlobeAlt,
  "BiGlobe": BiGlobe,
  "BiGridAlt": BiGridAlt,
  "BiGridHorizontal": BiGridHorizontal,
  "BiGridSmall": BiGridSmall,
  "BiGridVertical": BiGridVertical,
  "BiGrid": BiGrid,
  "BiGroup": BiGroup,
  "BiHandicap": BiHandicap,
  "BiHappyAlt": BiHappyAlt,
  "BiHappyBeaming": BiHappyBeaming,
  "BiHappyHeartEyes": BiHappyHeartEyes,
  "BiHappy": BiHappy,
  "BiHash": BiHash,
  "BiHdd": BiHdd,
  "BiHeading": BiHeading,
  "BiHeadphone": BiHeadphone,
  "BiHealth": BiHealth,
  "BiHeartCircle": BiHeartCircle,
  "BiHeartSquare": BiHeartSquare,
  "BiHeart": BiHeart,
  "BiHelpCircle": BiHelpCircle,
  "BiHide": BiHide,
  "BiHighlight": BiHighlight,
  "BiHistory": BiHistory,
  "BiHive": BiHive,
  "BiHomeAlt": BiHomeAlt,
  "BiHomeCircle": BiHomeCircle,
  "BiHomeHeart": BiHomeHeart,
  "BiHomeSmile": BiHomeSmile,
  "BiHome": BiHome,
  "BiHorizontalCenter": BiHorizontalCenter,
  "BiHotel": BiHotel,
  "BiHourglass": BiHourglass,
  "BiIdCard": BiIdCard,
  "BiImageAdd": BiImageAdd,
  "BiImageAlt": BiImageAlt,
  "BiImage": BiImage,
  "BiImages": BiImages,
  "BiImport": BiImport,
  "BiInfinite": BiInfinite,
  "BiInfoCircle": BiInfoCircle,
  "BiInfoSquare": BiInfoSquare,
  "BiIntersect": BiIntersect,
  "BiItalic": BiItalic,
  "BiJoystickAlt": BiJoystickAlt,
  "BiJoystickButton": BiJoystickButton,
  "BiJoystick": BiJoystick,
  "BiKey": BiKey,
  "BiLabel": BiLabel,
  "BiLandscape": BiLandscape,
  "BiLaptop": BiLaptop,
  "BiLastPage": BiLastPage,
  "BiLaugh": BiLaugh,
  "BiLayerMinus": BiLayerMinus,
  "BiLayerPlus": BiLayerPlus,
  "BiLayer": BiLayer,
  "BiLayout": BiLayout,
  "BiLeftArrowAlt": BiLeftArrowAlt,
  "BiLeftArrowCircle": BiLeftArrowCircle,
  "BiLeftArrow": BiLeftArrow,
  "BiLeftDownArrowCircle": BiLeftDownArrowCircle,
  "BiLeftIndent": BiLeftIndent,
  "BiLeftTopArrowCircle": BiLeftTopArrowCircle,
  "BiLibrary": BiLibrary,
  "BiLike": BiLike,
  "BiLineChartDown": BiLineChartDown,
  "BiLineChart": BiLineChart,
  "BiLinkAlt": BiLinkAlt,
  "BiLinkExternal": BiLinkExternal,
  "BiLink": BiLink,
  "BiLira": BiLira,
  "BiListCheck": BiListCheck,
  "BiListMinus": BiListMinus,
  "BiListOl": BiListOl,
  "BiListPlus": BiListPlus,
  "BiListUl": BiListUl,
  "BiLoaderAlt": BiLoaderAlt,
  "BiLoaderCircle": BiLoaderCircle,
  "BiLoader": BiLoader,
  "BiLocationPlus": BiLocationPlus,
  "BiLockAlt": BiLockAlt,
  "BiLockOpenAlt": BiLockOpenAlt,
  "BiLockOpen": BiLockOpen,
  "BiLock": BiLock,
  "BiLogInCircle": BiLogInCircle,
  "BiLogIn": BiLogIn,
  "BiLogOutCircle": BiLogOutCircle,
  "BiLogOut": BiLogOut,
  "BiLowVision": BiLowVision,
  "BiMagnet": BiMagnet,
  "BiMailSend": BiMailSend,
  "BiMaleSign": BiMaleSign,
  "BiMale": BiMale,
  "BiMapAlt": BiMapAlt,
  "BiMapPin": BiMapPin,
  "BiMap": BiMap,
  "BiMask": BiMask,
  "BiMedal": BiMedal,
  "BiMehAlt": BiMehAlt,
  "BiMehBlank": BiMehBlank,
  "BiMeh": BiMeh,
  "BiMemoryCard": BiMemoryCard,
  "BiMenuAltLeft": BiMenuAltLeft,
  "BiMenuAltRight": BiMenuAltRight,
  "BiMenu": BiMenu,
  "BiMerge": BiMerge,
  "BiMessageAdd": BiMessageAdd,
  "BiMessageAltAdd": BiMessageAltAdd,
  "BiMessageAltCheck": BiMessageAltCheck,
  "BiMessageAltDetail": BiMessageAltDetail,
  "BiMessageAltDots": BiMessageAltDots,
  "BiMessageAltEdit": BiMessageAltEdit,
  "BiMessageAltError": BiMessageAltError,
  "BiMessageAltMinus": BiMessageAltMinus,
  "BiMessageAltX": BiMessageAltX,
  "BiMessageAlt": BiMessageAlt,
  "BiMessageCheck": BiMessageCheck,
  "BiMessageDetail": BiMessageDetail,
  "BiMessageDots": BiMessageDots,
  "BiMessageEdit": BiMessageEdit,
  "BiMessageError": BiMessageError,
  "BiMessageMinus": BiMessageMinus,
  "BiMessageRoundedAdd": BiMessageRoundedAdd,
  "BiMessageRoundedCheck": BiMessageRoundedCheck,
  "BiMessageRoundedDetail": BiMessageRoundedDetail,
  "BiMessageRoundedDots": BiMessageRoundedDots,
  "BiMessageRoundedEdit": BiMessageRoundedEdit,
  "BiMessageRoundedError": BiMessageRoundedError,
  "BiMessageRoundedMinus": BiMessageRoundedMinus,
  "BiMessageRoundedX": BiMessageRoundedX,
  "BiMessageRounded": BiMessageRounded,
  "BiMessageSquareAdd": BiMessageSquareAdd,
  "BiMessageSquareCheck": BiMessageSquareCheck,
  "BiMessageSquareDetail": BiMessageSquareDetail,
  "BiMessageSquareDots": BiMessageSquareDots,
  "BiMessageSquareEdit": BiMessageSquareEdit,
  "BiMessageSquareError": BiMessageSquareError,
  "BiMessageSquareMinus": BiMessageSquareMinus,
  "BiMessageSquareX": BiMessageSquareX,
  "BiMessageSquare": BiMessageSquare,
  "BiMessageX": BiMessageX,
  "BiMessage": BiMessage,
  "BiMeteor": BiMeteor,
  "BiMicrochip": BiMicrochip,
  "BiMicrophoneOff": BiMicrophoneOff,
  "BiMicrophone": BiMicrophone,
  "BiMinusBack": BiMinusBack,
  "BiMinusCircle": BiMinusCircle,
  "BiMinusFront": BiMinusFront,
  "BiMinus": BiMinus,
  "BiMobileAlt": BiMobileAlt,
  "BiMobileLandscape": BiMobileLandscape,
  "BiMobileVibration": BiMobileVibration,
  "BiMobile": BiMobile,
  "BiMoney": BiMoney,
  "BiMoon": BiMoon,
  "BiMouseAlt": BiMouseAlt,
  "BiMouse": BiMouse,
  "BiMoveHorizontal": BiMoveHorizontal,
  "BiMoveVertical": BiMoveVertical,
  "BiMove": BiMove,
  "BiMoviePlay": BiMoviePlay,
  "BiMovie": BiMovie,
  "BiMusic": BiMusic,
  "BiNavigation": BiNavigation,
  "BiNetworkChart": BiNetworkChart,
  "BiNews": BiNews,
  "BiNoEntry": BiNoEntry,
  "BiNote": BiNote,
  "BiNotepad": BiNotepad,
  "BiNotificationOff": BiNotificationOff,
  "BiNotification": BiNotification,
  "BiOutline": BiOutline,
  "BiPackage": BiPackage,
  "BiPaintRoll": BiPaintRoll,
  "BiPaint": BiPaint,
  "BiPalette": BiPalette,
  "BiPaperPlane": BiPaperPlane,
  "BiPaperclip": BiPaperclip,
  "BiParagraph": BiParagraph,
  "BiPaste": BiPaste,
  "BiPauseCircle": BiPauseCircle,
  "BiPause": BiPause,
  "BiPen": BiPen,
  "BiPencil": BiPencil,
  "BiPhoneCall": BiPhoneCall,
  "BiPhoneIncoming": BiPhoneIncoming,
  "BiPhoneOff": BiPhoneOff,
  "BiPhoneOutgoing": BiPhoneOutgoing,
  "BiPhone": BiPhone,
  "BiPhotoAlbum": BiPhotoAlbum,
  "BiPieChartAlt2": BiPieChartAlt2,
  "BiPieChartAlt": BiPieChartAlt,
  "BiPieChart": BiPieChart,
  "BiPin": BiPin,
  "BiPlanet": BiPlanet,
  "BiPlayCircle": BiPlayCircle,
  "BiPlay": BiPlay,
  "BiPlug": BiPlug,
  "BiPlusCircle": BiPlusCircle,
  "BiPlusMedical": BiPlusMedical,
  "BiPlus": BiPlus,
  "BiPodcast": BiPodcast,
  "BiPointer": BiPointer,
  "BiPoll": BiPoll,
  "BiPolygon": BiPolygon,
  "BiPound": BiPound,
  "BiPowerOff": BiPowerOff,
  "BiPrinter": BiPrinter,
  "BiPulse": BiPulse,
  "BiPurchaseTagAlt": BiPurchaseTagAlt,
  "BiPurchaseTag": BiPurchaseTag,
  "BiPyramid": BiPyramid,
  "BiQrScan": BiQrScan,
  "BiQr": BiQr,
  "BiQuestionMark": BiQuestionMark,
  "BiRadar": BiRadar,
  "BiRadioCircleMarked": BiRadioCircleMarked,
  "BiRadioCircle": BiRadioCircle,
  "BiRadio": BiRadio,
  "BiReceipt": BiReceipt,
  "BiRectangle": BiRectangle,
  "BiRecycle": BiRecycle,
  "BiRedo": BiRedo,
  "BiRefresh": BiRefresh,
  "BiRegistered": BiRegistered,
  "BiRename": BiRename,
  "BiRepeat": BiRepeat,
  "BiReplyAll": BiReplyAll,
  "BiReply": BiReply,
  "BiRepost": BiRepost,
  "BiReset": BiReset,
  "BiRestaurant": BiRestaurant,
  "BiRevision": BiRevision,
  "BiRewindCircle": BiRewindCircle,
  "BiRewind": BiRewind,
  "BiRightArrowAlt": BiRightArrowAlt,
  "BiRightArrowCircle": BiRightArrowCircle,
  "BiRightArrow": BiRightArrow,
  "BiRightDownArrowCircle": BiRightDownArrowCircle,
  "BiRightIndent": BiRightIndent,
  "BiRightTopArrowCircle": BiRightTopArrowCircle,
  "BiRocket": BiRocket,
  "BiRotateLeft": BiRotateLeft,
  "BiRotateRight": BiRotateRight,
  "BiRss": BiRss,
  "BiRuble": BiRuble,
  "BiRuler": BiRuler,
  "BiRun": BiRun,
  "BiRupee": BiRupee,
  "BiSad": BiSad,
  "BiSave": BiSave,
  "BiScan": BiScan,
  "BiScreenshot": BiScreenshot,
  "BiSearchAlt2": BiSearchAlt2,
  "BiSearchAlt": BiSearchAlt,
  "BiSearch": BiSearch,
  "BiSelectMultiple": BiSelectMultiple,
  "BiSelection": BiSelection,
  "BiSend": BiSend,
  "BiServer": BiServer,
  "BiShapeCircle": BiShapeCircle,
  "BiShapePolygon": BiShapePolygon,
  "BiShapeSquare": BiShapeSquare,
  "BiShapeTriangle": BiShapeTriangle,
  "BiShareAlt": BiShareAlt,
  "BiShare": BiShare,
  "BiShekel": BiShekel,
  "BiShieldAlt2": BiShieldAlt2,
  "BiShieldAlt": BiShieldAlt,
  "BiShieldQuarter": BiShieldQuarter,
  "BiShieldX": BiShieldX,
  "BiShield": BiShield,
  "BiShocked": BiShocked,
  "BiShoppingBag": BiShoppingBag,
  "BiShowAlt": BiShowAlt,
  "BiShow": BiShow,
  "BiShuffle": BiShuffle,
  "BiSidebar": BiSidebar,
  "BiSitemap": BiSitemap,
  "BiSkipNextCircle": BiSkipNextCircle,
  "BiSkipNext": BiSkipNext,
  "BiSkipPreviousCircle": BiSkipPreviousCircle,
  "BiSkipPrevious": BiSkipPrevious,
  "BiSleepy": BiSleepy,
  "BiSliderAlt": BiSliderAlt,
  "BiSlider": BiSlider,
  "BiSlideshow": BiSlideshow,
  "BiSmile": BiSmile,
  "BiSortAZ": BiSortAZ,
  "BiSortAlt2": BiSortAlt2,
  "BiSortDown": BiSortDown,
  "BiSortUp": BiSortUp,
  "BiSortZA": BiSortZA,
  "BiSort": BiSort,
  "BiSpa": BiSpa,
  "BiSpaceBar": BiSpaceBar,
  "BiSpeaker": BiSpeaker,
  "BiSprayCan": BiSprayCan,
  "BiSpreadsheet": BiSpreadsheet,
  "BiSquareRounded": BiSquareRounded,
  "BiSquare": BiSquare,
  "BiStar": BiStar,
  "BiStation": BiStation,
  "BiStats": BiStats,
  "BiSticker": BiSticker,
  "BiStopCircle": BiStopCircle,
  "BiStop": BiStop,
  "BiStopwatch": BiStopwatch,
  "BiStoreAlt": BiStoreAlt,
  "BiStore": BiStore,
  "BiStreetView": BiStreetView,
  "BiStrikethrough": BiStrikethrough,
  "BiSubdirectoryLeft": BiSubdirectoryLeft,
  "BiSubdirectoryRight": BiSubdirectoryRight,
  "BiSun": BiSun,
  "BiSupport": BiSupport,
  "BiSwim": BiSwim,
  "BiSync": BiSync,
  "BiTab": BiTab,
  "BiTable": BiTable,
  "BiTachometer": BiTachometer,
  "BiTagAlt": BiTagAlt,
  "BiTag": BiTag,
  "BiTargetLock": BiTargetLock,
  "BiTaskX": BiTaskX,
  "BiTask": BiTask,
  "BiTaxi": BiTaxi,
  "BiTennisBall": BiTennisBall,
  "BiTerminal": BiTerminal,
  "BiTestTube": BiTestTube,
  "BiText": BiText,
  "BiTimeFive": BiTimeFive,
  "BiTime": BiTime,
  "BiTimer": BiTimer,
  "BiTired": BiTired,
  "BiToggleLeft": BiToggleLeft,
  "BiToggleRight": BiToggleRight,
  "BiTone": BiTone,
  "BiTrafficCone": BiTrafficCone,
  "BiTrain": BiTrain,
  "BiTransferAlt": BiTransferAlt,
  "BiTransfer": BiTransfer,
  "BiTrashAlt": BiTrashAlt,
  "BiTrash": BiTrash,
  "BiTrendingDown": BiTrendingDown,
  "BiTrendingUp": BiTrendingUp,
  "BiTrim": BiTrim,
  "BiTrip": BiTrip,
  "BiTrophy": BiTrophy,
  "BiTv": BiTv,
  "BiUnderline": BiUnderline,
  "BiUndo": BiUndo,
  "BiUnite": BiUnite,
  "BiUnlink": BiUnlink,
  "BiUpArrowAlt": BiUpArrowAlt,
  "BiUpArrowCircle": BiUpArrowCircle,
  "BiUpArrow": BiUpArrow,
  "BiUpload": BiUpload,
  "BiUpsideDown": BiUpsideDown,
  "BiUpvote": BiUpvote,
  "BiUsb": BiUsb,
  "BiUserCheck": BiUserCheck,
  "BiUserCircle": BiUserCircle,
  "BiUserMinus": BiUserMinus,
  "BiUserPin": BiUserPin,
  "BiUserPlus": BiUserPlus,
  "BiUserVoice": BiUserVoice,
  "BiUserX": BiUserX,
  "BiUser": BiUser,
  "BiVector": BiVector,
  "BiVerticalCenter": BiVerticalCenter,
  "BiVial": BiVial,
  "BiVideoOff": BiVideoOff,
  "BiVideoPlus": BiVideoPlus,
  "BiVideoRecording": BiVideoRecording,
  "BiVideo": BiVideo,
  "BiVoicemail": BiVoicemail,
  "BiVolumeFull": BiVolumeFull,
  "BiVolumeLow": BiVolumeLow,
  "BiVolumeMute": BiVolumeMute,
  "BiVolume": BiVolume,
  "BiWalk": BiWalk,
  "BiWalletAlt": BiWalletAlt,
  "BiWallet": BiWallet,
  "BiWater": BiWater,
  "BiWebcam": BiWebcam,
  "BiWifi0": BiWifi0,
  "BiWifi1": BiWifi1,
  "BiWifi2": BiWifi2,
  "BiWifiOff": BiWifiOff,
  "BiWifi": BiWifi,
  "BiWind": BiWind,
  "BiWindowAlt": BiWindowAlt,
  "BiWindowClose": BiWindowClose,
  "BiWindowOpen": BiWindowOpen,
  "BiWindow": BiWindow,
  "BiWindows": BiWindows,
  "BiWine": BiWine,
  "BiWinkSmile": BiWinkSmile,
  "BiWinkTongue": BiWinkTongue,
  "BiWon": BiWon,
  "BiWorld": BiWorld,
  "BiWrench": BiWrench,
  "BiXCircle": BiXCircle,
  "BiX": BiX,
  "BiYen": BiYen,
  "BiZoomIn": BiZoomIn,
  "BiZoomOut": BiZoomOut,
};