//import {
//  CiAirportSign1,
//  CiAlarmOff,
//  CiAlarmOn,
//  CiAlignBottom,
//  CiAlignCenterH,
//  CiAlignCenterV,
//  CiAlignLeft,
//  CiAlignRight,
//  CiAlignTop,
//  CiApple,
//  CiAt,
//  CiAvocado,
//  CiBacon,
//  CiBadgeDollar,
//  CiBag1,
//  CiBandage,
//  CiBank,
//  CiBarcode,
//  CiBaseball,
//  CiBasketball,
//  CiBatteryCharging,
//  CiBatteryEmpty,
//  CiBatteryFull,
//  CiBeaker1,
//  CiBeerMugFull,
//  CiBellOff,
//  CiBellOn,
//  CiBezier,
//  CiBitcoin,
//  CiBluetooth,
//  CiBookmarkCheck,
//  CiBookmarkMinus,
//  CiBookmarkPlus,
//  CiBookmarkRemove,
//  CiBookmark,
//  CiBowlNoodles,
//  CiBoxList,
//  CiBoxes,
//  CiBrightnessDown,
//  CiBrightnessUp,
//  CiBullhorn,
//  CiBurger,
//  CiCalculator1,
//  CiCalculator2,
//  CiCalendarDate,
//  CiCalendar,
//  CiCamera,
//  CiChat1,
//  CiChat2,
//  CiCircleAlert,
//  CiCircleCheck,
//  CiCircleChevDown,
//  CiCircleChevLeft,
//  CiCircleChevRight,
//  CiCircleChevUp,
//  CiCircleInfo,
//  CiCircleList,
//  CiCircleMinus,
//  CiCircleMore,
//  CiCirclePlus,
//  CiCircleQuestion,
//  CiCircleRemove,
//  CiClock1,
//  CiClock2,
//  CiCloudDrizzle,
//  CiCloudMoon,
//  CiCloudOff,
//  CiCloudOn,
//  CiCloudRainbow,
//  CiCloudSun,
//  CiCloud,
//  CiCoffeeBean,
//  CiCoffeeCup,
//  CiCoinInsert,
//  CiCoins1,
//  CiCompass1,
//  CiCreditCard1,
//  CiCreditCard2,
//  CiCreditCardOff,
//  CiCrop,
//  CiDark,
//  CiDatabase,
//  CiDeliveryTruck,
//  CiDesktopMouse1,
//  CiDesktopMouse2,
//  CiDesktop,
//  CiDiscount1,
//  CiDollar,
//  CiDroplet,
//  CiDumbbell,
//  CiEdit,
//  CiEraser,
//  CiExport,
//  CiFaceFrown,
//  CiFaceMeh,
//  CiFaceSmile,
//  CiFacebook,
//  CiFileOff,
//  CiFileOn,
//  CiFilter,
//  CiFlag1,
//  CiFloppyDisk,
//  CiFolderOff,
//  CiFolderOn,
//  CiFootball,
//  CiForkAndKnife,
//  CiFries,
//  CiGift,
//  CiGlass,
//  CiGlobe,
//  CiGps,
//  CiGrid2H,
//  CiGrid2V,
//  CiGrid31,
//  CiGrid32,
//  CiGrid41,
//  CiGrid42,
//  CiHardDrive,
//  CiHashtag,
//  CiHeadphones,
//  CiHeart,
//  CiHome,
//  CiHospital1,
//  CiHotdog,
//  CiIceCream,
//  CiImageOff,
//  CiImageOn,
//  CiImport,
//  CiInboxIn,
//  CiInboxOut,
//  CiIndent,
//  CiInstagram,
//  CiKeyboard,
//  CiLaptop,
//  CiLemon,
//  CiLight,
//  CiLineHeight,
//  CiLink,
//  CiLinkedin,
//  CiLocationArrow1,
//  CiLocationOff,
//  CiLocationOn,
//  CiLock,
//  CiLogin,
//  CiLogout,
//  CiLollipop,
//  CiMail,
//  CiMapPin,
//  CiMap,
//  CiMaximize1,
//  CiMaximize2,
//  CiMedal,
//  CiMedicalCase,
//  CiMedicalClipboard,
//  CiMedicalCross,
//  CiMedicalMask,
//  CiMemoPad,
//  CiMicrochip,
//  CiMicrophoneOff,
//  CiMicrophoneOn,
//  CiMinimize1,
//  CiMinimize2,
//  CiMobile1,
//  CiMobile2,
//  CiMobile3,
//  CiMobile4,
//  CiMoneyBill,
//  CiMoneyCheck1,
//  CiMonitor,
//  CiMountain1,
//  CiMug1,
//  CiMusicNote1,
//  CiNoWaitingSign,
//  CiPalette,
//  CiPaperplane,
//  CiParking1,
//  CiPassport1,
//  CiPause1,
//  CiPen,
//  CiPenpot,
//  CiPercent,
//  CiPhone,
//  CiPickerEmpty,
//  CiPickerHalf,
//  CiPill,
//  CiPillsBottle1,
//  CiPizza,
//  CiPlane,
//  CiPlay1,
//  CiPlug1,
//  CiPower,
//  CiRainbow,
//  CiRead,
//  CiReceipt,
//  CiRedo,
//  CiRepeat,
//  CiRollingSuitcase,
//  CiRoute,
//  CiRouter,
//  CiRuler,
//  CiSatellite1,
//  CiSaveDown1,
//  CiSaveDown2,
//  CiSaveUp1,
//  CiSaveUp2,
//  CiSearch,
//  CiServer,
//  CiSettings,
//  CiShare1,
//  CiShare2,
//  CiShirt,
//  CiShop,
//  CiShoppingBasket,
//  CiShoppingCart,
//  CiShoppingTag,
//  CiShuffle,
//  CiSignpostDuo1,
//  CiSignpostL1,
//  CiSignpostR1,
//  CiSliderHorizontal,
//  CiSliderVertical,
//  CiSpeaker,
//  CiSquareAlert,
//  CiSquareCheck,
//  CiSquareChevDown,
//  CiSquareChevLeft,
//  CiSquareChevRight,
//  CiSquareChevUp,
//  CiSquareInfo,
//  CiSquareMinus,
//  CiSquareMore,
//  CiSquarePlus,
//  CiSquareQuestion,
//  CiSquareRemove,
//  CiStar,
//  CiStethoscope,
//  CiStickyNote,
//  CiStop1,
//  CiStopSign1,
//  CiStopwatch,
//  CiStreamOff,
//  CiStreamOn,
//  CiSun,
//  CiTablets1,
//  CiTempHigh,
//  CiTextAlignCenter,
//  CiTextAlignJustify,
//  CiTextAlignLeft,
//  CiTextAlignRight,
//  CiText,
//  CiTimer,
//  CiTrash,
//  CiTrophy,
//  CiTurnL1,
//  CiTurnR1,
//  CiTwitter,
//  CiUmbrella,
//  CiUndo,
//  CiUnlock,
//  CiUnread,
//  CiUsb,
//  CiUser,
//  CiVault,
//  CiVial,
//  CiVideoOff,
//  CiVideoOn,
//  CiViewBoard,
//  CiViewColumn,
//  CiViewList,
//  CiViewTable,
//  CiViewTimeline,
//  CiVirus,
//  CiVoicemail,
//  CiVolumeHigh,
//  CiVolumeMute,
//  CiVolume,
//  CiWallet,
//  CiWarning,
//  CiWavePulse1,
//  CiWheat,
//  CiWifiOff,
//  CiWifiOn,
//  CiYoutube,
//  CiZoomIn,
//  CiZoomOut
//} from "react-icons/ci";

//export const CircumIcons = {
//  "CiAirportSign1": CiAirportSign1,
//  "CiAlarmOff": CiAlarmOff,
//  "CiAlarmOn": CiAlarmOn,
//  "CiAlignBottom": CiAlignBottom,
//  "CiAlignCenterH": CiAlignCenterH,
//  "CiAlignCenterV": CiAlignCenterV,
//  "CiAlignLeft": CiAlignLeft,
//  "CiAlignRight": CiAlignRight,
//  "CiAlignTop": CiAlignTop,
//  "CiApple": CiApple,
//  "CiAt": CiAt,
//  "CiAvocado": CiAvocado,
//  "CiBacon": CiBacon,
//  "CiBadgeDollar": CiBadgeDollar,
//  "CiBag1": CiBag1,
//  "CiBandage": CiBandage,
//  "CiBank": CiBank,
//  "CiBarcode": CiBarcode,
//  "CiBaseball": CiBaseball,
//  "CiBasketball": CiBasketball,
//  "CiBatteryCharging": CiBatteryCharging,
//  "CiBatteryEmpty": CiBatteryEmpty,
//  "CiBatteryFull": CiBatteryFull,
//  "CiBeaker1": CiBeaker1,
//  "CiBeerMugFull": CiBeerMugFull,
//  "CiBellOff": CiBellOff,
//  "CiBellOn": CiBellOn,
//  "CiBezier": CiBezier,
//  "CiBitcoin": CiBitcoin,
//  "CiBluetooth": CiBluetooth,
//  "CiBookmarkCheck": CiBookmarkCheck,
//  "CiBookmarkMinus": CiBookmarkMinus,
//  "CiBookmarkPlus": CiBookmarkPlus,
//  "CiBookmarkRemove": CiBookmarkRemove,
//  "CiBookmark": CiBookmark,
//  "CiBowlNoodles": CiBowlNoodles,
//  "CiBoxList": CiBoxList,
//  "CiBoxes": CiBoxes,
//  "CiBrightnessDown": CiBrightnessDown,
//  "CiBrightnessUp": CiBrightnessUp,
//  "CiBullhorn": CiBullhorn,
//  "CiBurger": CiBurger,
//  "CiCalculator1": CiCalculator1,
//  "CiCalculator2": CiCalculator2,
//  "CiCalendarDate": CiCalendarDate,
//  "CiCalendar": CiCalendar,
//  "CiCamera": CiCamera,
//  "CiChat1": CiChat1,
//  "CiChat2": CiChat2,
//  "CiCircleAlert": CiCircleAlert,
//  "CiCircleCheck": CiCircleCheck,
//  "CiCircleChevDown": CiCircleChevDown,
//  "CiCircleChevLeft": CiCircleChevLeft,
//  "CiCircleChevRight": CiCircleChevRight,
//  "CiCircleChevUp": CiCircleChevUp,
//  "CiCircleInfo": CiCircleInfo,
//  "CiCircleList": CiCircleList,
//  "CiCircleMinus": CiCircleMinus,
//  "CiCircleMore": CiCircleMore,
//  "CiCirclePlus": CiCirclePlus,
//  "CiCircleQuestion": CiCircleQuestion,
//  "CiCircleRemove": CiCircleRemove,
//  "CiClock1": CiClock1,
//  "CiClock2": CiClock2,
//  "CiCloudDrizzle": CiCloudDrizzle,
//  "CiCloudMoon": CiCloudMoon,
//  "CiCloudOff": CiCloudOff,
//  "CiCloudOn": CiCloudOn,
//  "CiCloudRainbow": CiCloudRainbow,
//  "CiCloudSun": CiCloudSun,
//  "CiCloud": CiCloud,
//  "CiCoffeeBean": CiCoffeeBean,
//  "CiCoffeeCup": CiCoffeeCup,
//  "CiCoinInsert": CiCoinInsert,
//  "CiCoins1": CiCoins1,
//  "CiCompass1": CiCompass1,
//  "CiCreditCard1": CiCreditCard1,
//  "CiCreditCard2": CiCreditCard2,
//  "CiCreditCardOff": CiCreditCardOff,
//  "CiCrop": CiCrop,
//  "CiDark": CiDark,
//  "CiDatabase": CiDatabase,
//  "CiDeliveryTruck": CiDeliveryTruck,
//  "CiDesktopMouse1": CiDesktopMouse1,
//  "CiDesktopMouse2": CiDesktopMouse2,
//  "CiDesktop": CiDesktop,
//  "CiDiscount1": CiDiscount1,
//  "CiDollar": CiDollar,
//  "CiDroplet": CiDroplet,
//  "CiDumbbell": CiDumbbell,
//  "CiEdit": CiEdit,
//  "CiEraser": CiEraser,
//  "CiExport": CiExport,
//  "CiFaceFrown": CiFaceFrown,
//  "CiFaceMeh": CiFaceMeh,
//  "CiFaceSmile": CiFaceSmile,
//  "CiFacebook": CiFacebook,
//  "CiFileOff": CiFileOff,
//  "CiFileOn": CiFileOn,
//  "CiFilter": CiFilter,
//  "CiFlag1": CiFlag1,
//  "CiFloppyDisk": CiFloppyDisk,
//  "CiFolderOff": CiFolderOff,
//  "CiFolderOn": CiFolderOn,
//  "CiFootball": CiFootball,
//  "CiForkAndKnife": CiForkAndKnife,
//  "CiFries": CiFries,
//  "CiGift": CiGift,
//  "CiGlass": CiGlass,
//  "CiGlobe": CiGlobe,
//  "CiGps": CiGps,
//  "CiGrid2H": CiGrid2H,
//  "CiGrid2V": CiGrid2V,
//  "CiGrid31": CiGrid31,
//  "CiGrid32": CiGrid32,
//  "CiGrid41": CiGrid41,
//  "CiGrid42": CiGrid42,
//  "CiHardDrive": CiHardDrive,
//  "CiHashtag": CiHashtag,
//  "CiHeadphones": CiHeadphones,
//  "CiHeart": CiHeart,
//  "CiHome": CiHome,
//  "CiHospital1": CiHospital1,
//  "CiHotdog": CiHotdog,
//  "CiIceCream": CiIceCream,
//  "CiImageOff": CiImageOff,
//  "CiImageOn": CiImageOn,
//  "CiImport": CiImport,
//  "CiInboxIn": CiInboxIn,
//  "CiInboxOut": CiInboxOut,
//  "CiIndent": CiIndent,
//  "CiInstagram": CiInstagram,
//  "CiKeyboard": CiKeyboard,
//  "CiLaptop": CiLaptop,
//  "CiLemon": CiLemon,
//  "CiLight": CiLight,
//  "CiLineHeight": CiLineHeight,
//  "CiLink": CiLink,
//  "CiLinkedin": CiLinkedin,
//  "CiLocationArrow1": CiLocationArrow1,
//  "CiLocationOff": CiLocationOff,
//  "CiLocationOn": CiLocationOn,
//  "CiLock": CiLock,
//  "CiLogin": CiLogin,
//  "CiLogout": CiLogout,
//  "CiLollipop": CiLollipop,
//  "CiMail": CiMail,
//  "CiMapPin": CiMapPin,
//  "CiMap": CiMap,
//  "CiMaximize1": CiMaximize1,
//  "CiMaximize2": CiMaximize2,
//  "CiMedal": CiMedal,
//  "CiMedicalCase": CiMedicalCase,
//  "CiMedicalClipboard": CiMedicalClipboard,
//  "CiMedicalCross": CiMedicalCross,
//  "CiMedicalMask": CiMedicalMask,
//  "CiMemoPad": CiMemoPad,
//  "CiMicrochip": CiMicrochip,
//  "CiMicrophoneOff": CiMicrophoneOff,
//  "CiMicrophoneOn": CiMicrophoneOn,
//  "CiMinimize1": CiMinimize1,
//  "CiMinimize2": CiMinimize2,
//  "CiMobile1": CiMobile1,
//  "CiMobile2": CiMobile2,
//  "CiMobile3": CiMobile3,
//  "CiMobile4": CiMobile4,
//  "CiMoneyBill": CiMoneyBill,
//  "CiMoneyCheck1": CiMoneyCheck1,
//  "CiMonitor": CiMonitor,
//  "CiMountain1": CiMountain1,
//  "CiMug1": CiMug1,
//  "CiMusicNote1": CiMusicNote1,
//  "CiNoWaitingSign": CiNoWaitingSign,
//  "CiPalette": CiPalette,
//  "CiPaperplane": CiPaperplane,
//  "CiParking1": CiParking1,
//  "CiPassport1": CiPassport1,
//  "CiPause1": CiPause1,
//  "CiPen": CiPen,
//  "CiPenpot": CiPenpot,
//  "CiPercent": CiPercent,
//  "CiPhone": CiPhone,
//  "CiPickerEmpty": CiPickerEmpty,
//  "CiPickerHalf": CiPickerHalf,
//  "CiPill": CiPill,
//  "CiPillsBottle1": CiPillsBottle1,
//  "CiPizza": CiPizza,
//  "CiPlane": CiPlane,
//  "CiPlay1": CiPlay1,
//  "CiPlug1": CiPlug1,
//  "CiPower": CiPower,
//  "CiRainbow": CiRainbow,
//  "CiRead": CiRead,
//  "CiReceipt": CiReceipt,
//  "CiRedo": CiRedo,
//  "CiRepeat": CiRepeat,
//  "CiRollingSuitcase": CiRollingSuitcase,
//  "CiRoute": CiRoute,
//  "CiRouter": CiRouter,
//  "CiRuler": CiRuler,
//  "CiSatellite1": CiSatellite1,
//  "CiSaveDown1": CiSaveDown1,
//  "CiSaveDown2": CiSaveDown2,
//  "CiSaveUp1": CiSaveUp1,
//  "CiSaveUp2": CiSaveUp2,
//  "CiSearch": CiSearch,
//  "CiServer": CiServer,
//  "CiSettings": CiSettings,
//  "CiShare1": CiShare1,
//  "CiShare2": CiShare2,
//  "CiShirt": CiShirt,
//  "CiShop": CiShop,
//  "CiShoppingBasket": CiShoppingBasket,
//  "CiShoppingCart": CiShoppingCart,
//  "CiShoppingTag": CiShoppingTag,
//  "CiShuffle": CiShuffle,
//  "CiSignpostDuo1": CiSignpostDuo1,
//  "CiSignpostL1": CiSignpostL1,
//  "CiSignpostR1": CiSignpostR1,
//  "CiSliderHorizontal": CiSliderHorizontal,
//  "CiSliderVertical": CiSliderVertical,
//  "CiSpeaker": CiSpeaker,
//  "CiSquareAlert": CiSquareAlert,
//  "CiSquareCheck": CiSquareCheck,
//  "CiSquareChevDown": CiSquareChevDown,
//  "CiSquareChevLeft": CiSquareChevLeft,
//  "CiSquareChevRight": CiSquareChevRight,
//  "CiSquareChevUp": CiSquareChevUp,
//  "CiSquareInfo": CiSquareInfo,
//  "CiSquareMinus": CiSquareMinus,
//  "CiSquareMore": CiSquareMore,
//  "CiSquarePlus": CiSquarePlus,
//  "CiSquareQuestion": CiSquareQuestion,
//  "CiSquareRemove": CiSquareRemove,
//  "CiStar": CiStar,
//  "CiStethoscope": CiStethoscope,
//  "CiStickyNote": CiStickyNote,
//  "CiStop1": CiStop1,
//  "CiStopSign1": CiStopSign1,
//  "CiStopwatch": CiStopwatch,
//  "CiStreamOff": CiStreamOff,
//  "CiStreamOn": CiStreamOn,
//  "CiSun": CiSun,
//  "CiTablets1": CiTablets1,
//  "CiTempHigh": CiTempHigh,
//  "CiTextAlignCenter": CiTextAlignCenter,
//  "CiTextAlignJustify": CiTextAlignJustify,
//  "CiTextAlignLeft": CiTextAlignLeft,
//  "CiTextAlignRight": CiTextAlignRight,
//  "CiText": CiText,
//  "CiTimer": CiTimer,
//  "CiTrash": CiTrash,
//  "CiTrophy": CiTrophy,
//  "CiTurnL1": CiTurnL1,
//  "CiTurnR1": CiTurnR1,
//  "CiTwitter": CiTwitter,
//  "CiUmbrella": CiUmbrella,
//  "CiUndo": CiUndo,
//  "CiUnlock": CiUnlock,
//  "CiUnread": CiUnread,
//  "CiUsb": CiUsb,
//  "CiUser": CiUser,
//  "CiVault": CiVault,
//  "CiVial": CiVial,
//  "CiVideoOff": CiVideoOff,
//  "CiVideoOn": CiVideoOn,
//  "CiViewBoard": CiViewBoard,
//  "CiViewColumn": CiViewColumn,
//  "CiViewList": CiViewList,
//  "CiViewTable": CiViewTable,
//  "CiViewTimeline": CiViewTimeline,
//  "CiVirus": CiVirus,
//  "CiVoicemail": CiVoicemail,
//  "CiVolumeHigh": CiVolumeHigh,
//  "CiVolumeMute": CiVolumeMute,
//  "CiVolume": CiVolume,
//  "CiWallet": CiWallet,
//  "CiWarning": CiWarning,
//  "CiWavePulse1": CiWavePulse1,
//  "CiWheat": CiWheat,
//  "CiWifiOff": CiWifiOff,
//  "CiWifiOn": CiWifiOn,
//  "CiYoutube": CiYoutube,
//  "CiZoomIn": CiZoomIn,
//  "CiZoomOut": CiZoomOut,
//};