import { 
CgAbstract,
CgAddR,
CgAdd,
CgAdidas,
CgAirplane,
CgAlarm,
CgAlbum,
CgAlignBottom,
CgAlignCenter,
CgAlignLeft,
CgAlignMiddle,
CgAlignRight,
CgAlignTop,
CgAnchor,
CgAppleWatch,
CgArrangeBack,
CgArrangeFront,
CgArrowAlignH,
CgArrowAlignV,
CgArrowBottomLeftO,
CgArrowBottomLeftR,
CgArrowBottomLeft,
CgArrowBottomRightO,
CgArrowBottomRightR,
CgArrowBottomRight,
CgArrowDownO,
CgArrowDownR,
CgArrowDown,
CgArrowLeftO,
CgArrowLeftR,
CgArrowLeft,
CgArrowLongDownC,
CgArrowLongDownE,
CgArrowLongDownL,
CgArrowLongDownR,
CgArrowLongDown,
CgArrowLongLeftC,
CgArrowLongLeftE,
CgArrowLongLeftL,
CgArrowLongLeftR,
CgArrowLongLeft,
CgArrowLongRightC,
CgArrowLongRightE,
CgArrowLongRightL,
CgArrowLongRightR,
CgArrowLongRight,
CgArrowLongUpC,
CgArrowLongUpE,
CgArrowLongUpL,
CgArrowLongUpR,
CgArrowLongUp,
CgArrowRightO,
CgArrowRightR,
CgArrowRight,
CgArrowTopLeftO,
CgArrowTopLeftR,
CgArrowTopLeft,
CgArrowTopRightO,
CgArrowTopRightR,
CgArrowTopRight,
CgArrowUpO,
CgArrowUpR,
CgArrowUp,
CgArrowsBreakeH,
CgArrowsBreakeV,
CgArrowsExchangeAltV,
CgArrowsExchangeAlt,
CgArrowsExchangeV,
CgArrowsExchange,
CgArrowsExpandDownLeft,
CgArrowsExpandDownRight,
CgArrowsExpandLeftAlt,
CgArrowsExpandLeft,
CgArrowsExpandRightAlt,
CgArrowsExpandRight,
CgArrowsExpandUpLeft,
CgArrowsExpandUpRight,
CgArrowsHAlt,
CgArrowsH,
CgArrowsMergeAltH,
CgArrowsMergeAltV,
CgArrowsScrollH,
CgArrowsScrollV,
CgArrowsShrinkH,
CgArrowsShrinkV,
CgArrowsVAlt,
CgArrowsV,
CgAssign,
CgAsterisk,
CgAtlasian,
CgAttachment,
CgAttribution,
CgAwards,
CgBackspace,
CgBandAid,
CgBatteryEmpty,
CgBatteryFull,
CgBattery,
CgBee,
CgBell,
CgBitbucket,
CgBlock,
CgBmw,
CgBoard,
CgBolt,
CgBookmark,
CgBorderAll,
CgBorderBottom,
CgBorderLeft,
CgBorderRight,
CgBorderStyleDashed,
CgBorderStyleDotted,
CgBorderStyleSolid,
CgBorderTop,
CgBot,
CgBowl,
CgBox,
CgBoy,
CgBrackets,
CgBriefcase,
CgBrowse,
CgBrowser,
CgBrush,
CgBulb,
CgCPlusPlus,
CgCalculator,
CgCalendarDates,
CgCalendarDue,
CgCalendarNext,
CgCalendarToday,
CgCalendarTwo,
CgCalendar,
CgCalibrate,
CgCamera,
CgCap,
CgCaptions,
CgCardClubs,
CgCardDiamonds,
CgCardHearts,
CgCardSpades,
CgCarousel,
CgCast,
CgChanel,
CgChart,
CgCheckO,
CgCheckR,
CgCheck,
CgChevronDoubleDownO,
CgChevronDoubleDownR,
CgChevronDoubleDown,
CgChevronDoubleLeftO,
CgChevronDoubleLeftR,
CgChevronDoubleLeft,
CgChevronDoubleRightO,
CgChevronDoubleRightR,
CgChevronDoubleRight,
CgChevronDoubleUpO,
CgChevronDoubleUpR,
CgChevronDoubleUp,
CgChevronDownO,
CgChevronDownR,
CgChevronDown,
CgChevronLeftO,
CgChevronLeftR,
CgChevronLeft,
CgChevronRightO,
CgChevronRightR,
CgChevronRight,
CgChevronUpO,
CgChevronUpR,
CgChevronUp,
CgCircleci,
CgClapperBoard,
CgClipboard,
CgCloseO,
CgCloseR,
CgClose,
CgCloud,
CgCodeClimate,
CgCodeSlash,
CgCode,
CgCoffee,
CgCollage,
CgColorBucket,
CgColorPicker,
CgComedyCentral,
CgComment,
CgCommunity,
CgComponents,
CgCompressLeft,
CgCompressRight,
CgCompressV,
CgCompress,
CgController,
CgCopy,
CgCopyright,
CgCornerDoubleDownLeft,
CgCornerDoubleDownRight,
CgCornerDoubleLeftDown,
CgCornerDoubleLeftUp,
CgCornerDoubleRightDown,
CgCornerDoubleRightUp,
CgCornerDoubleUpLeft,
CgCornerDoubleUpRight,
CgCornerDownLeft,
CgCornerDownRight,
CgCornerLeftDown,
CgCornerLeftUp,
CgCornerRightDown,
CgCornerRightUp,
CgCornerUpLeft,
CgCornerUpRight,
CgCreditCard,
CgCrop,
CgCross,
CgCrowdfire,
CgCrown,
CgDanger,
CgDarkMode,
CgData,
CgDatabase,
CgDebug,
CgDesignmodo,
CgDesktop,
CgDetailsLess,
CgDetailsMore,
CgDialpad,
CgDice1,
CgDice2,
CgDice3,
CgDice4,
CgDice5,
CgDice6,
CgDigitalocean,
CgDisc,
CgDisplayFlex,
CgDisplayFullwidth,
CgDisplayGrid,
CgDisplaySpacing,
CgDistributeHorizontal,
CgDistributeVertical,
CgDockBottom,
CgDockLeft,
CgDockRight,
CgDockWindow,
CgDolby,
CgDollar,
CgDribbble,
CgDrive,
CgDropInvert,
CgDropOpacity,
CgDrop,
CgDuplicate,
CgEditBlackPoint,
CgEditContrast,
CgEditExposure,
CgEditFade,
CgEditFlipH,
CgEditFlipV,
CgEditHighlight,
CgEditMarkup,
CgEditMask,
CgEditNoise,
CgEditShadows,
CgEditStraight,
CgEditUnmask,
CgEject,
CgEnter,
CgErase,
CgEreader,
CgEricsson,
CgEthernet,
CgEuro,
CgEventbrite,
CgExpand,
CgExport,
CgExtensionAdd,
CgExtensionAlt,
CgExtensionRemove,
CgExtension,
CgExternal,
CgEyeAlt,
CgEye,
CgFacebook,
CgFeed,
CgFigma,
CgFileAdd,
CgFileDocument,
CgFileRemove,
CgFile,
CgFilm,
CgFilters,
CgFlagAlt,
CgFlag,
CgFolderAdd,
CgFolderRemove,
CgFolder,
CgFontHeight,
CgFontSpacing,
CgFormatBold,
CgFormatCenter,
CgFormatColor,
CgFormatHeading,
CgFormatIndentDecrease,
CgFormatIndentIncrease,
CgFormatItalic,
CgFormatJustify,
CgFormatLeft,
CgFormatLineHeight,
CgFormatRight,
CgFormatSeparator,
CgFormatSlash,
CgFormatStrike,
CgFormatText,
CgFormatUnderline,
CgFormatUppercase,
CgFramer,
CgGames,
CgGenderFemale,
CgGenderMale,
CgGhostCharacter,
CgGhost,
CgGift,
CgGirl,
CgGitBranch,
CgGitCommit,
CgGitFork,
CgGitPull,
CgGitter,
CgGlassAlt,
CgGlass,
CgGlobeAlt,
CgGlobe,
CgGoogleTasks,
CgGoogle,
CgGym,
CgHashtag,
CgHeadset,
CgHeart,
CgHello,
CgHomeAlt,
CgHomeScreen,
CgHome,
CgIcecream,
CgIfDesign,
CgImage,
CgImport,
CgInbox,
CgIndieHackers,
CgInfinity,
CgInfo,
CgInpicture,
CgInsertAfterO,
CgInsertAfterR,
CgInsertAfter,
CgInsertBeforeO,
CgInsertBeforeR,
CgInsertBefore,
CgInsights,
CgInstagram,
CgInternal,
CgKey,
CgKeyboard,
CgKeyhole,
CgLaptop,
CgLastpass,
CgLayoutGridSmall,
CgLayoutGrid,
CgLayoutList,
CgLayoutPin,
CgLinear,
CgLink,
CgListTree,
CgList,
CgLivePhoto,
CgLoadbarAlt,
CgLoadbarDoc,
CgLoadbarSound,
CgLoadbar,
CgLockUnlock,
CgLock,
CgLogIn,
CgLogOff,
CgLogOut,
CgLoupe,
CgMagnet,
CgMailForward,
CgMailOpen,
CgMailReply,
CgMail,
CgMathDivide,
CgMathEqual,
CgMathMinus,
CgMathPercent,
CgMathPlus,
CgMaximizeAlt,
CgMaximize,
CgMaze,
CgMediaLive,
CgMediaPodcast,
CgMenuBoxed,
CgMenuCake,
CgMenuCheese,
CgMenuGridO,
CgMenuGridR,
CgMenuHotdog,
CgMenuLeftAlt,
CgMenuLeft,
CgMenuMotion,
CgMenuOreos,
CgMenuRightAlt,
CgMenuRight,
CgMenuRound,
CgMenu,
CgMergeHorizontal,
CgMergeVertical,
CgMic,
CgMicrobit,
CgMicrosoft,
CgMiniPlayer,
CgMinimizeAlt,
CgMinimize,
CgModem,
CgMonday,
CgMoon,
CgMoreAlt,
CgMoreO,
CgMoreR,
CgMoreVerticalAlt,
CgMoreVerticalO,
CgMoreVerticalR,
CgMoreVertical,
CgMore,
CgMouse,
CgMoveDown,
CgMoveLeft,
CgMoveRight,
CgMoveTask,
CgMoveUp,
CgMusicNote,
CgMusicSpeaker,
CgMusic,
CgNametag,
CgNotes,
CgNotifications,
CgNpm,
CgOculus,
CgOpenCollective,
CgOptions,
CgOrganisation,
CgOverflow,
CgPacman,
CgPassword,
CgPathBack,
CgPathCrop,
CgPathDivide,
CgPathExclude,
CgPathFront,
CgPathIntersect,
CgPathOutline,
CgPathTrim,
CgPathUnite,
CgPatreon,
CgPaypal,
CgPen,
CgPentagonBottomLeft,
CgPentagonBottomRight,
CgPentagonDown,
CgPentagonLeft,
CgPentagonRight,
CgPentagonTopLeft,
CgPentagonTopRight,
CgPentagonUp,
CgPerformance,
CgPexels,
CgPhone,
CgPhotoscan,
CgPiano,
CgPill,
CgPinAlt,
CgPinBottom,
CgPinTop,
CgPin,
CgPlayBackwards,
CgPlayButtonO,
CgPlayButtonR,
CgPlayButton,
CgPlayForwards,
CgPlayListAdd,
CgPlayListCheck,
CgPlayListRemove,
CgPlayListSearch,
CgPlayList,
CgPlayPauseO,
CgPlayPauseR,
CgPlayPause,
CgPlayStopO,
CgPlayStopR,
CgPlayStop,
CgPlayTrackNextO,
CgPlayTrackNextR,
CgPlayTrackNext,
CgPlayTrackPrevO,
CgPlayTrackPrevR,
CgPlayTrackPrev,
CgPlug,
CgPocket,
CgPokemon,
CgPolaroid,
CgPoll,
CgPresentation,
CgPrinter,
CgProductHunt,
CgProfile,
CgPullClear,
CgPushChevronDownO,
CgPushChevronDownR,
CgPushChevronDown,
CgPushChevronLeftO,
CgPushChevronLeftR,
CgPushChevronLeft,
CgPushChevronRightO,
CgPushChevronRightR,
CgPushChevronRight,
CgPushChevronUpO,
CgPushChevronUpR,
CgPushChevronUp,
CgPushDown,
CgPushLeft,
CgPushRight,
CgPushUp,
CgQr,
CgQuoteO,
CgQuote,
CgRadioCheck,
CgRadioChecked,
CgRatio,
CgRead,
CgReadme,
CgRecord,
CgRedo,
CgRemote,
CgRemoveR,
CgRemove,
CgRename,
CgReorder,
CgRepeat,
CgRing,
CgRowFirst,
CgRowLast,
CgRuler,
CgSandClock,
CgScan,
CgScreenMirror,
CgScreenShot,
CgScreenWide,
CgScreen,
CgScrollH,
CgScrollV,
CgSearchFound,
CgSearchLoading,
CgSearch,
CgSelectO,
CgSelectR,
CgSelect,
CgServer,
CgServerless,
CgShapeCircle,
CgShapeHalfCircle,
CgShapeHexagon,
CgShapeRhombus,
CgShapeSquare,
CgShapeTriangle,
CgShapeZigzag,
CgShare,
CgShield,
CgShoppingBag,
CgShoppingCart,
CgShortcut,
CgShutterstock,
CgSidebarOpen,
CgSidebarRight,
CgSidebar,
CgSignal,
CgSize,
CgSketch,
CgSlack,
CgSleep,
CgSmartHomeBoiler,
CgSmartHomeCooker,
CgSmartHomeHeat,
CgSmartHomeLight,
CgSmartHomeRefrigerator,
CgSmartHomeWashMachine,
CgSmartphoneChip,
CgSmartphoneRam,
CgSmartphoneShake,
CgSmartphone,
CgSmileMouthOpen,
CgSmileNeutral,
CgSmileNoMouth,
CgSmileNone,
CgSmileSad,
CgSmileUpside,
CgSmile,
CgSoftwareDownload,
CgSoftwareUpload,
CgSortAz,
CgSortZa,
CgSpaceBetweenV,
CgSpaceBetween,
CgSpectrum,
CgSpinnerAlt,
CgSpinnerTwoAlt,
CgSpinnerTwo,
CgSpinner,
CgSquare,
CgStack,
CgStark,
CgStopwatch,
CgStories,
CgStudio,
CgStyle,
CgSun,
CgSupport,
CgSwapVertical,
CgSwap,
CgSweden,
CgSwiss,
CgSync,
CgTab,
CgTag,
CgTally,
CgTapDouble,
CgTapSingle,
CgTemplate,
CgTennis,
CgTerminal,
CgTerrain,
CgThermometer,
CgThermostat,
CgTikcode,
CgTime,
CgTimelapse,
CgTimer,
CgToday,
CgToggleOff,
CgToggleOn,
CgToggleSquareOff,
CgToggleSquare,
CgToolbarBottom,
CgToolbarLeft,
CgToolbarRight,
CgToolbarTop,
CgToolbox,
CgTouchpad,
CgTrack,
CgTranscript,
CgTrashEmpty,
CgTrash,
CgTree,
CgTrees,
CgTrello,
CgTrendingDown,
CgTrending,
CgTrophy,
CgTv,
CgTwilio,
CgTwitter,
CgUiKit,
CgUmbrella,
CgUnavailable,
CgUnblock,
CgUndo,
CgUnfold,
CgUnsplash,
CgUsbC,
CgUsb,
CgUserAdd,
CgUserList,
CgUserRemove,
CgUser,
CgUserlane,
CgViewCols,
CgViewComfortable,
CgViewDay,
CgViewGrid,
CgViewList,
CgViewMonth,
CgViewSplit,
CgVinyl,
CgVoicemailO,
CgVoicemailR,
CgVoicemail,
CgVolume,
CgWebcam,
CgWebsite,
CgWindows,
CgWorkAlt,
CgYinyang,
CgYoutube,
CgZeit,
CgZoomIn,
CgZoomOut
 } from "react-icons/cg";

export const cssGgIcons = {
    "CgAbstract": CgAbstract,
    "CgAddR": CgAddR,
    "CgAdd": CgAdd,
    "CgAdidas": CgAdidas,
    "CgAirplane": CgAirplane,
    "CgAlarm": CgAlarm,
    "CgAlbum": CgAlbum,
    "CgAlignBottom": CgAlignBottom,
    "CgAlignCenter": CgAlignCenter,
    "CgAlignLeft": CgAlignLeft,
    "CgAlignMiddle": CgAlignMiddle,
    "CgAlignRight": CgAlignRight,
    "CgAlignTop": CgAlignTop,
    "CgAnchor": CgAnchor,
    "CgAppleWatch": CgAppleWatch,
    "CgArrangeBack": CgArrangeBack,
    "CgArrangeFront": CgArrangeFront,
    "CgArrowAlignH": CgArrowAlignH,
    "CgArrowAlignV": CgArrowAlignV,
    "CgArrowBottomLeftO": CgArrowBottomLeftO,
    "CgArrowBottomLeftR": CgArrowBottomLeftR,
    "CgArrowBottomLeft": CgArrowBottomLeft,
    "CgArrowBottomRightO": CgArrowBottomRightO,
    "CgArrowBottomRightR": CgArrowBottomRightR,
    "CgArrowBottomRight": CgArrowBottomRight,
    "CgArrowDownO": CgArrowDownO,
    "CgArrowDownR": CgArrowDownR,
    "CgArrowDown": CgArrowDown,
    "CgArrowLeftO": CgArrowLeftO,
    "CgArrowLeftR": CgArrowLeftR,
    "CgArrowLeft": CgArrowLeft,
    "CgArrowLongDownC": CgArrowLongDownC,
    "CgArrowLongDownE": CgArrowLongDownE,
    "CgArrowLongDownL": CgArrowLongDownL,
    "CgArrowLongDownR": CgArrowLongDownR,
    "CgArrowLongDown": CgArrowLongDown,
    "CgArrowLongLeftC": CgArrowLongLeftC,
    "CgArrowLongLeftE": CgArrowLongLeftE,
    "CgArrowLongLeftL": CgArrowLongLeftL,
    "CgArrowLongLeftR": CgArrowLongLeftR,
    "CgArrowLongLeft": CgArrowLongLeft,
    "CgArrowLongRightC": CgArrowLongRightC,
    "CgArrowLongRightE": CgArrowLongRightE,
    "CgArrowLongRightL": CgArrowLongRightL,
    "CgArrowLongRightR": CgArrowLongRightR,
    "CgArrowLongRight": CgArrowLongRight,
    "CgArrowLongUpC": CgArrowLongUpC,
    "CgArrowLongUpE": CgArrowLongUpE,
    "CgArrowLongUpL": CgArrowLongUpL,
    "CgArrowLongUpR": CgArrowLongUpR,
    "CgArrowLongUp": CgArrowLongUp,
    "CgArrowRightO": CgArrowRightO,
    "CgArrowRightR": CgArrowRightR,
    "CgArrowRight": CgArrowRight,
    "CgArrowTopLeftO": CgArrowTopLeftO,
    "CgArrowTopLeftR": CgArrowTopLeftR,
    "CgArrowTopLeft": CgArrowTopLeft,
    "CgArrowTopRightO": CgArrowTopRightO,
    "CgArrowTopRightR": CgArrowTopRightR,
    "CgArrowTopRight": CgArrowTopRight,
    "CgArrowUpO": CgArrowUpO,
    "CgArrowUpR": CgArrowUpR,
    "CgArrowUp": CgArrowUp,
    "CgArrowsBreakeH": CgArrowsBreakeH,
    "CgArrowsBreakeV": CgArrowsBreakeV,
    "CgArrowsExchangeAltV": CgArrowsExchangeAltV,
    "CgArrowsExchangeAlt": CgArrowsExchangeAlt,
    "CgArrowsExchangeV": CgArrowsExchangeV,
    "CgArrowsExchange": CgArrowsExchange,
    "CgArrowsExpandDownLeft": CgArrowsExpandDownLeft,
    "CgArrowsExpandDownRight": CgArrowsExpandDownRight,
    "CgArrowsExpandLeftAlt": CgArrowsExpandLeftAlt,
    "CgArrowsExpandLeft": CgArrowsExpandLeft,
    "CgArrowsExpandRightAlt": CgArrowsExpandRightAlt,
    "CgArrowsExpandRight": CgArrowsExpandRight,
    "CgArrowsExpandUpLeft": CgArrowsExpandUpLeft,
    "CgArrowsExpandUpRight": CgArrowsExpandUpRight,
    "CgArrowsHAlt": CgArrowsHAlt,
    "CgArrowsH": CgArrowsH,
    "CgArrowsMergeAltH": CgArrowsMergeAltH,
    "CgArrowsMergeAltV": CgArrowsMergeAltV,
    "CgArrowsScrollH": CgArrowsScrollH,
    "CgArrowsScrollV": CgArrowsScrollV,
    "CgArrowsShrinkH": CgArrowsShrinkH,
    "CgArrowsShrinkV": CgArrowsShrinkV,
    "CgArrowsVAlt": CgArrowsVAlt,
    "CgArrowsV": CgArrowsV,
    "CgAssign": CgAssign,
    "CgAsterisk": CgAsterisk,
    "CgAtlasian": CgAtlasian,
    "CgAttachment": CgAttachment,
    "CgAttribution": CgAttribution,
    "CgAwards": CgAwards,
    "CgBackspace": CgBackspace,
    "CgBandAid": CgBandAid,
    "CgBatteryEmpty": CgBatteryEmpty,
    "CgBatteryFull": CgBatteryFull,
    "CgBattery": CgBattery,
    "CgBee": CgBee,
    "CgBell": CgBell,
    "CgBitbucket": CgBitbucket,
    "CgBlock": CgBlock,
    "CgBmw": CgBmw,
    "CgBoard": CgBoard,
    "CgBolt": CgBolt,
    "CgBookmark": CgBookmark,
    "CgBorderAll": CgBorderAll,
    "CgBorderBottom": CgBorderBottom,
    "CgBorderLeft": CgBorderLeft,
    "CgBorderRight": CgBorderRight,
    "CgBorderStyleDashed": CgBorderStyleDashed,
    "CgBorderStyleDotted": CgBorderStyleDotted,
    "CgBorderStyleSolid": CgBorderStyleSolid,
    "CgBorderTop": CgBorderTop,
    "CgBot": CgBot,
    "CgBowl": CgBowl,
    "CgBox": CgBox,
    "CgBoy": CgBoy,
    "CgBrackets": CgBrackets,
    "CgBriefcase": CgBriefcase,
    "CgBrowse": CgBrowse,
    "CgBrowser": CgBrowser,
    "CgBrush": CgBrush,
    "CgBulb": CgBulb,
    "CgCPlusPlus": CgCPlusPlus,
    "CgCalculator": CgCalculator,
    "CgCalendarDates": CgCalendarDates,
    "CgCalendarDue": CgCalendarDue,
    "CgCalendarNext": CgCalendarNext,
    "CgCalendarToday": CgCalendarToday,
    "CgCalendarTwo": CgCalendarTwo,
    "CgCalendar": CgCalendar,
    "CgCalibrate": CgCalibrate,
    "CgCamera": CgCamera,
    "CgCap": CgCap,
    "CgCaptions": CgCaptions,
    "CgCardClubs": CgCardClubs,
    "CgCardDiamonds": CgCardDiamonds,
    "CgCardHearts": CgCardHearts,
    "CgCardSpades": CgCardSpades,
    "CgCarousel": CgCarousel,
    "CgCast": CgCast,
    "CgChanel": CgChanel,
    "CgChart": CgChart,
    "CgCheckO": CgCheckO,
    "CgCheckR": CgCheckR,
    "CgCheck": CgCheck,
    "CgChevronDoubleDownO": CgChevronDoubleDownO,
    "CgChevronDoubleDownR": CgChevronDoubleDownR,
    "CgChevronDoubleDown": CgChevronDoubleDown,
    "CgChevronDoubleLeftO": CgChevronDoubleLeftO,
    "CgChevronDoubleLeftR": CgChevronDoubleLeftR,
    "CgChevronDoubleLeft": CgChevronDoubleLeft,
    "CgChevronDoubleRightO": CgChevronDoubleRightO,
    "CgChevronDoubleRightR": CgChevronDoubleRightR,
    "CgChevronDoubleRight": CgChevronDoubleRight,
    "CgChevronDoubleUpO": CgChevronDoubleUpO,
    "CgChevronDoubleUpR": CgChevronDoubleUpR,
    "CgChevronDoubleUp": CgChevronDoubleUp,
    "CgChevronDownO": CgChevronDownO,
    "CgChevronDownR": CgChevronDownR,
    "CgChevronDown": CgChevronDown,
    "CgChevronLeftO": CgChevronLeftO,
    "CgChevronLeftR": CgChevronLeftR,
    "CgChevronLeft": CgChevronLeft,
    "CgChevronRightO": CgChevronRightO,
    "CgChevronRightR": CgChevronRightR,
    "CgChevronRight": CgChevronRight,
    "CgChevronUpO": CgChevronUpO,
    "CgChevronUpR": CgChevronUpR,
    "CgChevronUp": CgChevronUp,
    "CgCircleci": CgCircleci,
    "CgClapperBoard": CgClapperBoard,
    "CgClipboard": CgClipboard,
    "CgCloseO": CgCloseO,
    "CgCloseR": CgCloseR,
    "CgClose": CgClose,
    "CgCloud": CgCloud,
    "CgCodeClimate": CgCodeClimate,
    "CgCodeSlash": CgCodeSlash,
    "CgCode": CgCode,
    "CgCoffee": CgCoffee,
    "CgCollage": CgCollage,
    "CgColorBucket": CgColorBucket,
    "CgColorPicker": CgColorPicker,
    "CgComedyCentral": CgComedyCentral,
    "CgComment": CgComment,
    "CgCommunity": CgCommunity,
    "CgComponents": CgComponents,
    "CgCompressLeft": CgCompressLeft,
    "CgCompressRight": CgCompressRight,
    "CgCompressV": CgCompressV,
    "CgCompress": CgCompress,
    "CgController": CgController,
    "CgCopy": CgCopy,
    "CgCopyright": CgCopyright,
    "CgCornerDoubleDownLeft": CgCornerDoubleDownLeft,
    "CgCornerDoubleDownRight": CgCornerDoubleDownRight,
    "CgCornerDoubleLeftDown": CgCornerDoubleLeftDown,
    "CgCornerDoubleLeftUp": CgCornerDoubleLeftUp,
    "CgCornerDoubleRightDown": CgCornerDoubleRightDown,
    "CgCornerDoubleRightUp": CgCornerDoubleRightUp,
    "CgCornerDoubleUpLeft": CgCornerDoubleUpLeft,
    "CgCornerDoubleUpRight": CgCornerDoubleUpRight,
    "CgCornerDownLeft": CgCornerDownLeft,
    "CgCornerDownRight": CgCornerDownRight,
    "CgCornerLeftDown": CgCornerLeftDown,
    "CgCornerLeftUp": CgCornerLeftUp,
    "CgCornerRightDown": CgCornerRightDown,
    "CgCornerRightUp": CgCornerRightUp,
    "CgCornerUpLeft": CgCornerUpLeft,
    "CgCornerUpRight": CgCornerUpRight,
    "CgCreditCard": CgCreditCard,
    "CgCrop": CgCrop,
    "CgCross": CgCross,
    "CgCrowdfire": CgCrowdfire,
    "CgCrown": CgCrown,
    "CgDanger": CgDanger,
    "CgDarkMode": CgDarkMode,
    "CgData": CgData,
    "CgDatabase": CgDatabase,
    "CgDebug": CgDebug,
    "CgDesignmodo": CgDesignmodo,
    "CgDesktop": CgDesktop,
    "CgDetailsLess": CgDetailsLess,
    "CgDetailsMore": CgDetailsMore,
    "CgDialpad": CgDialpad,
    "CgDice1": CgDice1,
    "CgDice2": CgDice2,
    "CgDice3": CgDice3,
    "CgDice4": CgDice4,
    "CgDice5": CgDice5,
    "CgDice6": CgDice6,
    "CgDigitalocean": CgDigitalocean,
    "CgDisc": CgDisc,
    "CgDisplayFlex": CgDisplayFlex,
    "CgDisplayFullwidth": CgDisplayFullwidth,
    "CgDisplayGrid": CgDisplayGrid,
    "CgDisplaySpacing": CgDisplaySpacing,
    "CgDistributeHorizontal": CgDistributeHorizontal,
    "CgDistributeVertical": CgDistributeVertical,
    "CgDockBottom": CgDockBottom,
    "CgDockLeft": CgDockLeft,
    "CgDockRight": CgDockRight,
    "CgDockWindow": CgDockWindow,
    "CgDolby": CgDolby,
    "CgDollar": CgDollar,
    "CgDribbble": CgDribbble,
    "CgDrive": CgDrive,
    "CgDropInvert": CgDropInvert,
    "CgDropOpacity": CgDropOpacity,
    "CgDrop": CgDrop,
    "CgDuplicate": CgDuplicate,
    "CgEditBlackPoint": CgEditBlackPoint,
    "CgEditContrast": CgEditContrast,
    "CgEditExposure": CgEditExposure,
    "CgEditFade": CgEditFade,
    "CgEditFlipH": CgEditFlipH,
    "CgEditFlipV": CgEditFlipV,
    "CgEditHighlight": CgEditHighlight,
    "CgEditMarkup": CgEditMarkup,
    "CgEditMask": CgEditMask,
    "CgEditNoise": CgEditNoise,
    "CgEditShadows": CgEditShadows,
    "CgEditStraight": CgEditStraight,
    "CgEditUnmask": CgEditUnmask,
    "CgEject": CgEject,
    "CgEnter": CgEnter,
    "CgErase": CgErase,
    "CgEreader": CgEreader,
    "CgEricsson": CgEricsson,
    "CgEthernet": CgEthernet,
    "CgEuro": CgEuro,
    "CgEventbrite": CgEventbrite,
    "CgExpand": CgExpand,
    "CgExport": CgExport,
    "CgExtensionAdd": CgExtensionAdd,
    "CgExtensionAlt": CgExtensionAlt,
    "CgExtensionRemove": CgExtensionRemove,
    "CgExtension": CgExtension,
    "CgExternal": CgExternal,
    "CgEyeAlt": CgEyeAlt,
    "CgEye": CgEye,
    "CgFacebook": CgFacebook,
    "CgFeed": CgFeed,
    "CgFigma": CgFigma,
    "CgFileAdd": CgFileAdd,
    "CgFileDocument": CgFileDocument,
    "CgFileRemove": CgFileRemove,
    "CgFile": CgFile,
    "CgFilm": CgFilm,
    "CgFilters": CgFilters,
    "CgFlagAlt": CgFlagAlt,
    "CgFlag": CgFlag,
    "CgFolderAdd": CgFolderAdd,
    "CgFolderRemove": CgFolderRemove,
    "CgFolder": CgFolder,
    "CgFontHeight": CgFontHeight,
    "CgFontSpacing": CgFontSpacing,
    "CgFormatBold": CgFormatBold,
    "CgFormatCenter": CgFormatCenter,
    "CgFormatColor": CgFormatColor,
    "CgFormatHeading": CgFormatHeading,
    "CgFormatIndentDecrease": CgFormatIndentDecrease,
    "CgFormatIndentIncrease": CgFormatIndentIncrease,
    "CgFormatItalic": CgFormatItalic,
    "CgFormatJustify": CgFormatJustify,
    "CgFormatLeft": CgFormatLeft,
    "CgFormatLineHeight": CgFormatLineHeight,
    "CgFormatRight": CgFormatRight,
    "CgFormatSeparator": CgFormatSeparator,
    "CgFormatSlash": CgFormatSlash,
    "CgFormatStrike": CgFormatStrike,
    "CgFormatText": CgFormatText,
    "CgFormatUnderline": CgFormatUnderline,
    "CgFormatUppercase": CgFormatUppercase,
    "CgFramer": CgFramer,
    "CgGames": CgGames,
    "CgGenderFemale": CgGenderFemale,
    "CgGenderMale": CgGenderMale,
    "CgGhostCharacter": CgGhostCharacter,
    "CgGhost": CgGhost,
    "CgGift": CgGift,
    "CgGirl": CgGirl,
    "CgGitBranch": CgGitBranch,
    "CgGitCommit": CgGitCommit,
    "CgGitFork": CgGitFork,
    "CgGitPull": CgGitPull,
    "CgGitter": CgGitter,
    "CgGlassAlt": CgGlassAlt,
    "CgGlass": CgGlass,
    "CgGlobeAlt": CgGlobeAlt,
    "CgGlobe": CgGlobe,
    "CgGoogleTasks": CgGoogleTasks,
    "CgGoogle": CgGoogle,
    "CgGym": CgGym,
    "CgHashtag": CgHashtag,
    "CgHeadset": CgHeadset,
    "CgHeart": CgHeart,
    "CgHello": CgHello,
    "CgHomeAlt": CgHomeAlt,
    "CgHomeScreen": CgHomeScreen,
    "CgHome": CgHome,
    "CgIcecream": CgIcecream,
    "CgIfDesign": CgIfDesign,
    "CgImage": CgImage,
    "CgImport": CgImport,
    "CgInbox": CgInbox,
    "CgIndieHackers": CgIndieHackers,
    "CgInfinity": CgInfinity,
    "CgInfo": CgInfo,
    "CgInpicture": CgInpicture,
    "CgInsertAfterO": CgInsertAfterO,
    "CgInsertAfterR": CgInsertAfterR,
    "CgInsertAfter": CgInsertAfter,
    "CgInsertBeforeO": CgInsertBeforeO,
    "CgInsertBeforeR": CgInsertBeforeR,
    "CgInsertBefore": CgInsertBefore,
    "CgInsights": CgInsights,
    "CgInstagram": CgInstagram,
    "CgInternal": CgInternal,
    "CgKey": CgKey,
    "CgKeyboard": CgKeyboard,
    "CgKeyhole": CgKeyhole,
    "CgLaptop": CgLaptop,
    "CgLastpass": CgLastpass,
    "CgLayoutGridSmall": CgLayoutGridSmall,
    "CgLayoutGrid": CgLayoutGrid,
    "CgLayoutList": CgLayoutList,
    "CgLayoutPin": CgLayoutPin,
    "CgLinear": CgLinear,
    "CgLink": CgLink,
    "CgListTree": CgListTree,
    "CgList": CgList,
    "CgLivePhoto": CgLivePhoto,
    "CgLoadbarAlt": CgLoadbarAlt,
    "CgLoadbarDoc": CgLoadbarDoc,
    "CgLoadbarSound": CgLoadbarSound,
    "CgLoadbar": CgLoadbar,
    "CgLockUnlock": CgLockUnlock,
    "CgLock": CgLock,
    "CgLogIn": CgLogIn,
    "CgLogOff": CgLogOff,
    "CgLogOut": CgLogOut,
    "CgLoupe": CgLoupe,
    "CgMagnet": CgMagnet,
    "CgMailForward": CgMailForward,
    "CgMailOpen": CgMailOpen,
    "CgMailReply": CgMailReply,
    "CgMail": CgMail,
    "CgMathDivide": CgMathDivide,
    "CgMathEqual": CgMathEqual,
    "CgMathMinus": CgMathMinus,
    "CgMathPercent": CgMathPercent,
    "CgMathPlus": CgMathPlus,
    "CgMaximizeAlt": CgMaximizeAlt,
    "CgMaximize": CgMaximize,
    "CgMaze": CgMaze,
    "CgMediaLive": CgMediaLive,
    "CgMediaPodcast": CgMediaPodcast,
    "CgMenuBoxed": CgMenuBoxed,
    "CgMenuCake": CgMenuCake,
    "CgMenuCheese": CgMenuCheese,
    "CgMenuGridO": CgMenuGridO,
    "CgMenuGridR": CgMenuGridR,
    "CgMenuHotdog": CgMenuHotdog,
    "CgMenuLeftAlt": CgMenuLeftAlt,
    "CgMenuLeft": CgMenuLeft,
    "CgMenuMotion": CgMenuMotion,
    "CgMenuOreos": CgMenuOreos,
    "CgMenuRightAlt": CgMenuRightAlt,
    "CgMenuRight": CgMenuRight,
    "CgMenuRound": CgMenuRound,
    "CgMenu": CgMenu,
    "CgMergeHorizontal": CgMergeHorizontal,
    "CgMergeVertical": CgMergeVertical,
    "CgMic": CgMic,
    "CgMicrobit": CgMicrobit,
    "CgMicrosoft": CgMicrosoft,
    "CgMiniPlayer": CgMiniPlayer,
    "CgMinimizeAlt": CgMinimizeAlt,
    "CgMinimize": CgMinimize,
    "CgModem": CgModem,
    "CgMonday": CgMonday,
    "CgMoon": CgMoon,
    "CgMoreAlt": CgMoreAlt,
    "CgMoreO": CgMoreO,
    "CgMoreR": CgMoreR,
    "CgMoreVerticalAlt": CgMoreVerticalAlt,
    "CgMoreVerticalO": CgMoreVerticalO,
    "CgMoreVerticalR": CgMoreVerticalR,
    "CgMoreVertical": CgMoreVertical,
    "CgMore": CgMore,
    "CgMouse": CgMouse,
    "CgMoveDown": CgMoveDown,
    "CgMoveLeft": CgMoveLeft,
    "CgMoveRight": CgMoveRight,
    "CgMoveTask": CgMoveTask,
    "CgMoveUp": CgMoveUp,
    "CgMusicNote": CgMusicNote,
    "CgMusicSpeaker": CgMusicSpeaker,
    "CgMusic": CgMusic,
    "CgNametag": CgNametag,
    "CgNotes": CgNotes,
    "CgNotifications": CgNotifications,
    "CgNpm": CgNpm,
    "CgOculus": CgOculus,
    "CgOpenCollective": CgOpenCollective,
    "CgOptions": CgOptions,
    "CgOrganisation": CgOrganisation,
    "CgOverflow": CgOverflow,
    "CgPacman": CgPacman,
    "CgPassword": CgPassword,
    "CgPathBack": CgPathBack,
    "CgPathCrop": CgPathCrop,
    "CgPathDivide": CgPathDivide,
    "CgPathExclude": CgPathExclude,
    "CgPathFront": CgPathFront,
    "CgPathIntersect": CgPathIntersect,
    "CgPathOutline": CgPathOutline,
    "CgPathTrim": CgPathTrim,
    "CgPathUnite": CgPathUnite,
    "CgPatreon": CgPatreon,
    "CgPaypal": CgPaypal,
    "CgPen": CgPen,
    "CgPentagonBottomLeft": CgPentagonBottomLeft,
    "CgPentagonBottomRight": CgPentagonBottomRight,
    "CgPentagonDown": CgPentagonDown,
    "CgPentagonLeft": CgPentagonLeft,
    "CgPentagonRight": CgPentagonRight,
    "CgPentagonTopLeft": CgPentagonTopLeft,
    "CgPentagonTopRight": CgPentagonTopRight,
    "CgPentagonUp": CgPentagonUp,
    "CgPerformance": CgPerformance,
    "CgPexels": CgPexels,
    "CgPhone": CgPhone,
    "CgPhotoscan": CgPhotoscan,
    "CgPiano": CgPiano,
    "CgPill": CgPill,
    "CgPinAlt": CgPinAlt,
    "CgPinBottom": CgPinBottom,
    "CgPinTop": CgPinTop,
    "CgPin": CgPin,
    "CgPlayBackwards": CgPlayBackwards,
    "CgPlayButtonO": CgPlayButtonO,
    "CgPlayButtonR": CgPlayButtonR,
    "CgPlayButton": CgPlayButton,
    "CgPlayForwards": CgPlayForwards,
    "CgPlayListAdd": CgPlayListAdd,
    "CgPlayListCheck": CgPlayListCheck,
    "CgPlayListRemove": CgPlayListRemove,
    "CgPlayListSearch": CgPlayListSearch,
    "CgPlayList": CgPlayList,
    "CgPlayPauseO": CgPlayPauseO,
    "CgPlayPauseR": CgPlayPauseR,
    "CgPlayPause": CgPlayPause,
    "CgPlayStopO": CgPlayStopO,
    "CgPlayStopR": CgPlayStopR,
    "CgPlayStop": CgPlayStop,
    "CgPlayTrackNextO": CgPlayTrackNextO,
    "CgPlayTrackNextR": CgPlayTrackNextR,
    "CgPlayTrackNext": CgPlayTrackNext,
    "CgPlayTrackPrevO": CgPlayTrackPrevO,
    "CgPlayTrackPrevR": CgPlayTrackPrevR,
    "CgPlayTrackPrev": CgPlayTrackPrev,
    "CgPlug": CgPlug,
    "CgPocket": CgPocket,
    "CgPokemon": CgPokemon,
    "CgPolaroid": CgPolaroid,
    "CgPoll": CgPoll,
    "CgPresentation": CgPresentation,
    "CgPrinter": CgPrinter,
    "CgProductHunt": CgProductHunt,
    "CgProfile": CgProfile,
    "CgPullClear": CgPullClear,
    "CgPushChevronDownO": CgPushChevronDownO,
    "CgPushChevronDownR": CgPushChevronDownR,
    "CgPushChevronDown": CgPushChevronDown,
    "CgPushChevronLeftO": CgPushChevronLeftO,
    "CgPushChevronLeftR": CgPushChevronLeftR,
    "CgPushChevronLeft": CgPushChevronLeft,
    "CgPushChevronRightO": CgPushChevronRightO,
    "CgPushChevronRightR": CgPushChevronRightR,
    "CgPushChevronRight": CgPushChevronRight,
    "CgPushChevronUpO": CgPushChevronUpO,
    "CgPushChevronUpR": CgPushChevronUpR,
    "CgPushChevronUp": CgPushChevronUp,
    "CgPushDown": CgPushDown,
    "CgPushLeft": CgPushLeft,
    "CgPushRight": CgPushRight,
    "CgPushUp": CgPushUp,
    "CgQr": CgQr,
    "CgQuoteO": CgQuoteO,
    "CgQuote": CgQuote,
    "CgRadioCheck": CgRadioCheck,
    "CgRadioChecked": CgRadioChecked,
    "CgRatio": CgRatio,
    "CgRead": CgRead,
    "CgReadme": CgReadme,
    "CgRecord": CgRecord,
    "CgRedo": CgRedo,
    "CgRemote": CgRemote,
    "CgRemoveR": CgRemoveR,
    "CgRemove": CgRemove,
    "CgRename": CgRename,
    "CgReorder": CgReorder,
    "CgRepeat": CgRepeat,
    "CgRing": CgRing,
    "CgRowFirst": CgRowFirst,
    "CgRowLast": CgRowLast,
    "CgRuler": CgRuler,
    "CgSandClock": CgSandClock,
    "CgScan": CgScan,
    "CgScreenMirror": CgScreenMirror,
    "CgScreenShot": CgScreenShot,
    "CgScreenWide": CgScreenWide,
    "CgScreen": CgScreen,
    "CgScrollH": CgScrollH,
    "CgScrollV": CgScrollV,
    "CgSearchFound": CgSearchFound,
    "CgSearchLoading": CgSearchLoading,
    "CgSearch": CgSearch,
    "CgSelectO": CgSelectO,
    "CgSelectR": CgSelectR,
    "CgSelect": CgSelect,
    "CgServer": CgServer,
    "CgServerless": CgServerless,
    "CgShapeCircle": CgShapeCircle,
    "CgShapeHalfCircle": CgShapeHalfCircle,
    "CgShapeHexagon": CgShapeHexagon,
    "CgShapeRhombus": CgShapeRhombus,
    "CgShapeSquare": CgShapeSquare,
    "CgShapeTriangle": CgShapeTriangle,
    "CgShapeZigzag": CgShapeZigzag,
    "CgShare": CgShare,
    "CgShield": CgShield,
    "CgShoppingBag": CgShoppingBag,
    "CgShoppingCart": CgShoppingCart,
    "CgShortcut": CgShortcut,
    "CgShutterstock": CgShutterstock,
    "CgSidebarOpen": CgSidebarOpen,
    "CgSidebarRight": CgSidebarRight,
    "CgSidebar": CgSidebar,
    "CgSignal": CgSignal,
    "CgSize": CgSize,
    "CgSketch": CgSketch,
    "CgSlack": CgSlack,
    "CgSleep": CgSleep,
    "CgSmartHomeBoiler": CgSmartHomeBoiler,
    "CgSmartHomeCooker": CgSmartHomeCooker,
    "CgSmartHomeHeat": CgSmartHomeHeat,
    "CgSmartHomeLight": CgSmartHomeLight,
    "CgSmartHomeRefrigerator": CgSmartHomeRefrigerator,
    "CgSmartHomeWashMachine": CgSmartHomeWashMachine,
    "CgSmartphoneChip": CgSmartphoneChip,
    "CgSmartphoneRam": CgSmartphoneRam,
    "CgSmartphoneShake": CgSmartphoneShake,
    "CgSmartphone": CgSmartphone,
    "CgSmileMouthOpen": CgSmileMouthOpen,
    "CgSmileNeutral": CgSmileNeutral,
    "CgSmileNoMouth": CgSmileNoMouth,
    "CgSmileNone": CgSmileNone,
    "CgSmileSad": CgSmileSad,
    "CgSmileUpside": CgSmileUpside,
    "CgSmile": CgSmile,
    "CgSoftwareDownload": CgSoftwareDownload,
    "CgSoftwareUpload": CgSoftwareUpload,
    "CgSortAz": CgSortAz,
    "CgSortZa": CgSortZa,
    "CgSpaceBetweenV": CgSpaceBetweenV,
    "CgSpaceBetween": CgSpaceBetween,
    "CgSpectrum": CgSpectrum,
    "CgSpinnerAlt": CgSpinnerAlt,
    "CgSpinnerTwoAlt": CgSpinnerTwoAlt,
    "CgSpinnerTwo": CgSpinnerTwo,
    "CgSpinner": CgSpinner,
    "CgSquare": CgSquare,
    "CgStack": CgStack,
    "CgStark": CgStark,
    "CgStopwatch": CgStopwatch,
    "CgStories": CgStories,
    "CgStudio": CgStudio,
    "CgStyle": CgStyle,
    "CgSun": CgSun,
    "CgSupport": CgSupport,
    "CgSwapVertical": CgSwapVertical,
    "CgSwap": CgSwap,
    "CgSweden": CgSweden,
    "CgSwiss": CgSwiss,
    "CgSync": CgSync,
    "CgTab": CgTab,
    "CgTag": CgTag,
    "CgTally": CgTally,
    "CgTapDouble": CgTapDouble,
    "CgTapSingle": CgTapSingle,
    "CgTemplate": CgTemplate,
    "CgTennis": CgTennis,
    "CgTerminal": CgTerminal,
    "CgTerrain": CgTerrain,
    "CgThermometer": CgThermometer,
    "CgThermostat": CgThermostat,
    "CgTikcode": CgTikcode,
    "CgTime": CgTime,
    "CgTimelapse": CgTimelapse,
    "CgTimer": CgTimer,
    "CgToday": CgToday,
    "CgToggleOff": CgToggleOff,
    "CgToggleOn": CgToggleOn,
    "CgToggleSquareOff": CgToggleSquareOff,
    "CgToggleSquare": CgToggleSquare,
    "CgToolbarBottom": CgToolbarBottom,
    "CgToolbarLeft": CgToolbarLeft,
    "CgToolbarRight": CgToolbarRight,
    "CgToolbarTop": CgToolbarTop,
    "CgToolbox": CgToolbox,
    "CgTouchpad": CgTouchpad,
    "CgTrack": CgTrack,
    "CgTranscript": CgTranscript,
    "CgTrashEmpty": CgTrashEmpty,
    "CgTrash": CgTrash,
    "CgTree": CgTree,
    "CgTrees": CgTrees,
    "CgTrello": CgTrello,
    "CgTrendingDown": CgTrendingDown,
    "CgTrending": CgTrending,
    "CgTrophy": CgTrophy,
    "CgTv": CgTv,
    "CgTwilio": CgTwilio,
    "CgTwitter": CgTwitter,
    "CgUiKit": CgUiKit,
    "CgUmbrella": CgUmbrella,
    "CgUnavailable": CgUnavailable,
    "CgUnblock": CgUnblock,
    "CgUndo": CgUndo,
    "CgUnfold": CgUnfold,
    "CgUnsplash": CgUnsplash,
    "CgUsbC": CgUsbC,
    "CgUsb": CgUsb,
    "CgUserAdd": CgUserAdd,
    "CgUserList": CgUserList,
    "CgUserRemove": CgUserRemove,
    "CgUser": CgUser,
    "CgUserlane": CgUserlane,
    "CgViewCols": CgViewCols,
    "CgViewComfortable": CgViewComfortable,
    "CgViewDay": CgViewDay,
    "CgViewGrid": CgViewGrid,
    "CgViewList": CgViewList,
    "CgViewMonth": CgViewMonth,
    "CgViewSplit": CgViewSplit,
    "CgVinyl": CgVinyl,
    "CgVoicemailO": CgVoicemailO,
    "CgVoicemailR": CgVoicemailR,
    "CgVoicemail": CgVoicemail,
    "CgVolume": CgVolume,
    "CgWebcam": CgWebcam,
    "CgWebsite": CgWebsite,
    "CgWindows": CgWindows,
    "CgWorkAlt": CgWorkAlt,
    "CgYinyang": CgYinyang,
    "CgYoutube": CgYoutube,
    "CgZeit": CgZeit,
    "CgZoomIn": CgZoomIn,
    "CgZoomOut": CgZoomOut
}