import { DiAndroid,
  DiAngularSimple,
  DiAppcelerator,
  DiApple,
  DiAppstore,
  DiAptana,
  DiAsterisk,
  DiAtlassian,
  DiAtom,
  DiAws,
  DiBackbone,
  DiBingSmall,
  DiBintray,
  DiBitbucket,
  DiBlackberry,
  DiBootstrap,
  DiBower,
  DiBrackets,
  DiBugsense,
  DiCelluloid,
  DiChrome,
  DiCisco,
  DiClojureAlt,
  DiClojure,
  DiCloud9,
  DiCoda,
  DiCodeBadge,
  DiCode,
  DiCodeigniter,
  DiCodepen,
  DiCodrops,
  DiCoffeescript,
  DiCompass,
  DiComposer,
  DiCreativecommonsBadge,
  DiCreativecommons,
  DiCssTricks,
  DiCss3Full,
  DiCss3,
  DiCssdeck,
  DiDart,
  DiDatabase,
  DiDebian,
  DiDigitalOcean,
  DiDjango,
  DiDlang,
  DiDocker,
  DiDoctrine,
  DiDojo,
  DiDotnet,
  DiDreamweaver,
  DiDropbox,
  DiDrupal,
  DiEclipse,
  DiEmber,
  DiEnvato,
  DiErlang,
  DiExtjs,
  DiFirebase,
  DiFirefox,
  DiFsharp,
  DiGhostSmall,
  DiGhost,
  DiGitBranch,
  DiGitCommit,
  DiGitCompare,
  DiGitMerge,
  DiGitPullRequest,
  DiGit,
  DiGithubAlt,
  DiGithubBadge,
  DiGithubFull,
  DiGithub,
  DiGnu,
  DiGo,
  DiGoogleAnalytics,
  DiGoogleDrive,
  DiGoogleCloudPlatform,
  DiGrails,
  DiGroovy,
  DiGrunt,
  DiGulp,
  DiHackernews,
  DiHaskell,
  DiHeroku,
  DiHtml53DEffects,
  DiHtml5Connectivity,
  DiHtml5DeviceAccess,
  DiHtml5Multimedia,
  DiHtml5,
  DiIe,
  DiIllustrator,
  DiIntellij,
  DiIonic,
  DiJava,
  DiJavascript1,
  DiJavascript,
  DiJekyllSmall,
  DiJenkins,
  DiJira,
  DiJoomla,
  DiJqueryLogo,
  DiJqueryUiLogo,
  DiJsBadge,
  DiKomodo,
  DiKrakenjsBadge,
  DiKrakenjs,
  DiLaravel,
  DiLess,
  DiLinux,
  DiMagento,
  DiMailchimp,
  DiMarkdown,
  DiMaterializecss,
  DiMeteor,
  DiMeteorfull,
  DiMitlicence,
  DiModernizr,
  DiMongodb,
  DiMootoolsBadge,
  DiMootools,
  DiMozilla,
  DiMsqlServer,
  DiMysql,
  DiNancy,
  DiNetbeans,
  DiNetmagazine,
  DiNginx,
  DiNodejsSmall,
  DiNodejs,
  DiNpm,
  DiOnedrive,
  DiOpenshift,
  DiOpensource,
  DiOpera,
  DiPerl,
  DiPhonegap,
  DiPhotoshop,
  DiPhp,
  DiPostgresql,
  DiProlog,
  DiPython,
  DiRackspace,
  DiRaphael,
  DiRasberryPi,
  DiReact,
  DiRedhat,
  DiRedis,
  DiRequirejs,
  DiResponsive,
  DiRor,
  DiRubyRough,
  DiRuby,
  DiRust,
  DiSafari,
  DiSass,
  DiScala,
  DiScriptcs,
  DiScrum,
  DiSenchatouch,
  DiSizzlejs,
  DiSmashingMagazine,
  DiSnapSvg,
  DiSpark,
  DiSqllite,
  DiStackoverflow,
  DiStreamline,
  DiStylus,
  DiSublime,
  DiSwift,
  DiSymfonyBadge,
  DiSymfony,
  DiTechcrunch,
  DiTerminalBadge,
  DiTerminal,
  DiTravis,
  DiTrello,
  DiTypo3,
  DiUbuntu,
  DiUikit,
  DiUnitySmall,
  DiVim,
  DiVisualstudio,
  DiW3C,
  DiWebplatform,
  DiWindows,
  DiWordpress,
  DiYahooSmall,
  DiYahoo,
  DiYeoman,
  DiYii,
  DiZend
} from "react-icons/di";

export const DevIcons = {
  "DiAndroid": DiAndroid,
  "DiAngularSimple": DiAngularSimple,
  "DiAppcelerator": DiAppcelerator,
  "DiApple": DiApple,
  "DiAppstore": DiAppstore,
  "DiAptana": DiAptana,
  "DiAsterisk": DiAsterisk,
  "DiAtlassian": DiAtlassian,
  "DiAtom": DiAtom,
  "DiAws": DiAws,
  "DiBackbone": DiBackbone,
  "DiBingSmall": DiBingSmall,
  "DiBintray": DiBintray,
  "DiBitbucket": DiBitbucket,
  "DiBlackberry": DiBlackberry,
  "DiBootstrap": DiBootstrap,
  "DiBower": DiBower,
  "DiBrackets": DiBrackets,
  "DiBugsense": DiBugsense,
  "DiCelluloid": DiCelluloid,
  "DiChrome": DiChrome,
  "DiCisco": DiCisco,
  "DiClojureAlt": DiClojureAlt,
  "DiClojure": DiClojure,
  "DiCloud9": DiCloud9,
  "DiCoda": DiCoda,
  "DiCodeBadge": DiCodeBadge,
  "DiCode": DiCode,
  "DiCodeigniter": DiCodeigniter,
  "DiCodepen": DiCodepen,
  "DiCodrops": DiCodrops,
  "DiCoffeescript": DiCoffeescript,
  "DiCompass": DiCompass,
  "DiComposer": DiComposer,
  "DiCreativecommonsBadge": DiCreativecommonsBadge,
  "DiCreativecommons": DiCreativecommons,
  "DiCssTricks": DiCssTricks,
  "DiCss3Full": DiCss3Full,
  "DiCss3": DiCss3,
  "DiCssdeck": DiCssdeck,
  "DiDart": DiDart,
  "DiDatabase": DiDatabase,
  "DiDebian": DiDebian,
  "DiDigitalOcean": DiDigitalOcean,
  "DiDjango": DiDjango,
  "DiDlang": DiDlang,
  "DiDocker": DiDocker,
  "DiDoctrine": DiDoctrine,
  "DiDojo": DiDojo,
  "DiDotnet": DiDotnet,
  "DiDreamweaver": DiDreamweaver,
  "DiDropbox": DiDropbox,
  "DiDrupal": DiDrupal,
  "DiEclipse": DiEclipse,
  "DiEmber": DiEmber,
  "DiEnvato": DiEnvato,
  "DiErlang": DiErlang,
  "DiExtjs": DiExtjs,
  "DiFirebase": DiFirebase,
  "DiFirefox": DiFirefox,
  "DiFsharp": DiFsharp,
  "DiGhostSmall": DiGhostSmall,
  "DiGhost": DiGhost,
  "DiGitBranch": DiGitBranch,
  "DiGitCommit": DiGitCommit,
  "DiGitCompare": DiGitCompare,
  "DiGitMerge": DiGitMerge,
  "DiGitPullRequest": DiGitPullRequest,
  "DiGit": DiGit,
  "DiGithubAlt": DiGithubAlt,
  "DiGithubBadge": DiGithubBadge,
  "DiGithubFull": DiGithubFull,
  "DiGithub": DiGithub,
  "DiGnu": DiGnu,
  "DiGo": DiGo,
  "DiGoogleAnalytics": DiGoogleAnalytics,
  "DiGoogleDrive": DiGoogleDrive,
  "DiGoogleCloudPlatform": DiGoogleCloudPlatform,
  "DiGrails": DiGrails,
  "DiGroovy": DiGroovy,
  "DiGrunt": DiGrunt,
  "DiGulp": DiGulp,
  "DiHackernews": DiHackernews,
  "DiHaskell": DiHaskell,
  "DiHeroku": DiHeroku,
  "DiHtml53DEffects": DiHtml53DEffects,
  "DiHtml5Connectivity": DiHtml5Connectivity,
  "DiHtml5DeviceAccess": DiHtml5DeviceAccess,
  "DiHtml5Multimedia": DiHtml5Multimedia,
  "DiHtml5": DiHtml5,
  "DiIe": DiIe,
  "DiIllustrator": DiIllustrator,
  "DiIntellij": DiIntellij,
  "DiIonic": DiIonic,
  "DiJava": DiJava,
  "DiJavascript1": DiJavascript1,
  "DiJavascript": DiJavascript,
  "DiJekyllSmall": DiJekyllSmall,
  "DiJenkins": DiJenkins,
  "DiJira": DiJira,
  "DiJoomla": DiJoomla,
  "DiJqueryLogo": DiJqueryLogo,
  "DiJqueryUiLogo": DiJqueryUiLogo,
  "DiJsBadge": DiJsBadge,
  "DiKomodo": DiKomodo,
  "DiKrakenjsBadge": DiKrakenjsBadge,
  "DiKrakenjs": DiKrakenjs,
  "DiLaravel": DiLaravel,
  "DiLess": DiLess,
  "DiLinux": DiLinux,
  "DiMagento": DiMagento,
  "DiMailchimp": DiMailchimp,
  "DiMarkdown": DiMarkdown,
  "DiMaterializecss": DiMaterializecss,
  "DiMeteor": DiMeteor,
  "DiMeteorfull": DiMeteorfull,
  "DiMitlicence": DiMitlicence,
  "DiModernizr": DiModernizr,
  "DiMongodb": DiMongodb,
  "DiMootoolsBadge": DiMootoolsBadge,
  "DiMootools": DiMootools,
  "DiMozilla": DiMozilla,
  "DiMsqlServer": DiMsqlServer,
  "DiMysql": DiMysql,
  "DiNancy": DiNancy,
  "DiNetbeans": DiNetbeans,
  "DiNetmagazine": DiNetmagazine,
  "DiNginx": DiNginx,
  "DiNodejsSmall": DiNodejsSmall,
  "DiNodejs": DiNodejs,
  "DiNpm": DiNpm,
  "DiOnedrive": DiOnedrive,
  "DiOpenshift": DiOpenshift,
  "DiOpensource": DiOpensource,
  "DiOpera": DiOpera,
  "DiPerl": DiPerl,
  "DiPhonegap": DiPhonegap,
  "DiPhotoshop": DiPhotoshop,
  "DiPhp": DiPhp,
  "DiPostgresql": DiPostgresql,
  "DiProlog": DiProlog,
  "DiPython": DiPython,
  "DiRackspace": DiRackspace,
  "DiRaphael": DiRaphael,
  "DiRasberryPi": DiRasberryPi,
  "DiReact": DiReact,
  "DiRedhat": DiRedhat,
  "DiRedis": DiRedis,
  "DiRequirejs": DiRequirejs,
  "DiResponsive": DiResponsive,
  "DiRor": DiRor,
  "DiRubyRough": DiRubyRough,
  "DiRuby": DiRuby,
  "DiRust": DiRust,
  "DiSafari": DiSafari,
  "DiSass": DiSass,
  "DiScala": DiScala,
  "DiScriptcs": DiScriptcs,
  "DiScrum": DiScrum,
  "DiSenchatouch": DiSenchatouch,
  "DiSizzlejs": DiSizzlejs,
  "DiSmashingMagazine": DiSmashingMagazine,
  "DiSnapSvg": DiSnapSvg,
  "DiSpark": DiSpark,
  "DiSqllite": DiSqllite,
  "DiStackoverflow": DiStackoverflow,
  "DiStreamline": DiStreamline,
  "DiStylus": DiStylus,
  "DiSublime": DiSublime,
  "DiSwift": DiSwift,
  "DiSymfonyBadge": DiSymfonyBadge,
  "DiSymfony": DiSymfony,
  "DiTechcrunch": DiTechcrunch,
  "DiTerminalBadge": DiTerminalBadge,
  "DiTerminal": DiTerminal,
  "DiTravis": DiTravis,
  "DiTrello": DiTrello,
  "DiTypo3": DiTypo3,
  "DiUbuntu": DiUbuntu,
  "DiUikit": DiUikit,
  "DiUnitySmall": DiUnitySmall,
  "DiVim": DiVim,
  "DiVisualstudio": DiVisualstudio,
  "DiW3C": DiW3C,
  "DiWebplatform": DiWebplatform,
  "DiWindows": DiWindows,
  "DiWordpress": DiWordpress,
  "DiYahooSmall": DiYahooSmall,
  "DiYahoo": DiYahoo,
  "DiYeoman": DiYeoman,
  "DiYii": DiYii,
  "DiZend": DiZend,
};