import { 
  FiActivity,
  FiAirplay,
  FiAlertCircle,
  FiAlertOctagon,
  FiAlertTriangle,
  FiAlignCenter,
  FiAlignJustify,
  FiAlignLeft,
  FiAlignRight,
  FiAnchor,
  FiAperture,
  FiArchive,
  FiArrowDownCircle,
  FiArrowDownLeft,
  FiArrowDownRight,
  FiArrowDown,
  FiArrowLeftCircle,
  FiArrowLeft,
  FiArrowRightCircle,
  FiArrowRight,
  FiArrowUpCircle,
  FiArrowUpLeft,
  FiArrowUpRight,
  FiArrowUp,
  FiAtSign,
  FiAward,
  FiBarChart2,
  FiBarChart,
  FiBatteryCharging,
  FiBattery,
  FiBellOff,
  FiBell,
  FiBluetooth,
  FiBold,
  FiBookOpen,
  FiBook,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCameraOff,
  FiCamera,
  FiCast,
  FiCheckCircle,
  FiCheckSquare,
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsDown,
  FiChevronsLeft,
  FiChevronsRight,
  FiChevronsUp,
  FiChrome,
  FiCircle,
  FiClipboard,
  FiClock,
  FiCloudDrizzle,
  FiCloudLightning,
  FiCloudOff,
  FiCloudRain,
  FiCloudSnow,
  FiCloud,
  FiCode,
  FiCodepen,
  FiCodesandbox,
  FiCoffee,
  FiColumns,
  FiCommand,
  FiCompass,
  FiCopy,
  FiCornerDownLeft,
  FiCornerDownRight,
  FiCornerLeftDown,
  FiCornerLeftUp,
  FiCornerRightDown,
  FiCornerRightUp,
  FiCornerUpLeft,
  FiCornerUpRight,
  FiCpu,
  FiCreditCard,
  FiCrop,
  FiCrosshair,
  FiDatabase,
  FiDelete,
  FiDisc,
  FiDivideCircle,
  FiDivideSquare,
  FiDivide,
  FiDollarSign,
  FiDownloadCloud,
  FiDownload,
  FiDribbble,
  FiDroplet,
  FiEdit2,
  FiEdit3,
  FiEdit,
  FiExternalLink,
  FiEyeOff,
  FiEye,
  FiFacebook,
  FiFastForward,
  FiFeather,
  FiFigma,
  FiFileMinus,
  FiFilePlus,
  FiFileText,
  FiFile,
  FiFilm,
  FiFilter,
  FiFlag,
  FiFolderMinus,
  FiFolderPlus,
  FiFolder,
  FiFramer,
  FiFrown,
  FiGift,
  FiGitBranch,
  FiGitCommit,
  FiGitMerge,
  FiGitPullRequest,
  FiGithub,
  FiGitlab,
  FiGlobe,
  FiGrid,
  FiHardDrive,
  FiHash,
  FiHeadphones,
  FiHeart,
  FiHelpCircle,
  FiHexagon,
  FiHome,
  FiImage,
  FiInbox,
  FiInfo,
  FiInstagram,
  FiItalic,
  FiKey,
  FiLayers,
  FiLayout,
  FiLifeBuoy,
  FiLink2,
  FiLink,
  FiLinkedin,
  FiList,
  FiLoader,
  FiLock,
  FiLogIn,
  FiLogOut,
  FiMail,
  FiMapPin,
  FiMap,
  FiMaximize2,
  FiMaximize,
  FiMeh,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMicOff,
  FiMic,
  FiMinimize2,
  FiMinimize,
  FiMinusCircle,
  FiMinusSquare,
  FiMinus,
  FiMonitor,
  FiMoon,
  FiMoreHorizontal,
  FiMoreVertical,
  FiMousePointer,
  FiMove,
  FiMusic,
  FiNavigation2,
  FiNavigation,
  FiOctagon,
  FiPackage,
  FiPaperclip,
  FiPauseCircle,
  FiPause,
  FiPenTool,
  FiPercent,
  FiPhoneCall,
  FiPhoneForwarded,
  FiPhoneIncoming,
  FiPhoneMissed,
  FiPhoneOff,
  FiPhoneOutgoing,
  FiPhone,
  FiPieChart,
  FiPlayCircle,
  FiPlay,
  FiPlusCircle,
  FiPlusSquare,
  FiPlus,
  FiPocket,
  FiPower,
  FiPrinter,
  FiRadio,
  FiRefreshCcw,
  FiRefreshCw,
  FiRepeat,
  FiRewind,
  FiRotateCcw,
  FiRotateCw,
  FiRss,
  FiSave,
  FiScissors,
  FiSearch,
  FiSend,
  FiServer,
  FiSettings,
  FiShare2,
  FiShare,
  FiShieldOff,
  FiShield,
  FiShoppingBag,
  FiShoppingCart,
  FiShuffle,
  FiSidebar,
  FiSkipBack,
  FiSkipForward,
  FiSlack,
  FiSlash,
  FiSliders,
  FiSmartphone,
  FiSmile,
  FiSpeaker,
  FiSquare,
  FiStar,
  FiStopCircle,
  FiSun,
  FiSunrise,
  FiSunset,
  FiTablet,
  FiTag,
  FiTarget,
  FiTerminal,
  FiThermometer,
  FiThumbsDown,
  FiThumbsUp,
  FiToggleLeft,
  FiToggleRight,
  FiTool,
  FiTrash2,
  FiTrash,
  FiTrello,
  FiTrendingDown,
  FiTrendingUp,
  FiTriangle,
  FiTruck,
  FiTv,
  FiTwitch,
  FiTwitter,
  FiType,
  FiUmbrella,
  FiUnderline,
  FiUnlock,
  FiUploadCloud,
  FiUpload,
  FiUserCheck,
  FiUserMinus,
  FiUserPlus,
  FiUserX,
  FiUser,
  FiUsers,
  FiVideoOff,
  FiVideo,
  FiVoicemail,
  FiVolume1,
  FiVolume2,
  FiVolumeX,
  FiVolume,
  FiWatch,
  FiWifiOff,
  FiWifi,
  FiWind,
  FiXCircle,
  FiXOctagon,
  FiXSquare,
  FiX,
  FiYoutube,
  FiZapOff,
  FiZap,
  FiZoomIn,
  FiZoomOut
} from "react-icons/fi";

export const FeatherIcons = {
  "FiActivity": FiActivity,
  "FiAirplay": FiAirplay,
  "FiAlertCircle": FiAlertCircle,
  "FiAlertOctagon": FiAlertOctagon,
  "FiAlertTriangle": FiAlertTriangle,
  "FiAlignCenter": FiAlignCenter,
  "FiAlignJustify": FiAlignJustify,
  "FiAlignLeft": FiAlignLeft,
  "FiAlignRight": FiAlignRight,
  "FiAnchor": FiAnchor,
  "FiAperture": FiAperture,
  "FiArchive": FiArchive,
  "FiArrowDownCircle": FiArrowDownCircle,
  "FiArrowDownLeft": FiArrowDownLeft,
  "FiArrowDownRight": FiArrowDownRight,
  "FiArrowDown": FiArrowDown,
  "FiArrowLeftCircle": FiArrowLeftCircle,
  "FiArrowLeft": FiArrowLeft,
  "FiArrowRightCircle": FiArrowRightCircle,
  "FiArrowRight": FiArrowRight,
  "FiArrowUpCircle": FiArrowUpCircle,
  "FiArrowUpLeft": FiArrowUpLeft,
  "FiArrowUpRight": FiArrowUpRight,
  "FiArrowUp": FiArrowUp,
  "FiAtSign": FiAtSign,
  "FiAward": FiAward,
  "FiBarChart2": FiBarChart2,
  "FiBarChart": FiBarChart,
  "FiBatteryCharging": FiBatteryCharging,
  "FiBattery": FiBattery,
  "FiBellOff": FiBellOff,
  "FiBell": FiBell,
  "FiBluetooth": FiBluetooth,
  "FiBold": FiBold,
  "FiBookOpen": FiBookOpen,
  "FiBook": FiBook,
  "FiBookmark": FiBookmark,
  "FiBox": FiBox,
  "FiBriefcase": FiBriefcase,
  "FiCalendar": FiCalendar,
  "FiCameraOff": FiCameraOff,
  "FiCamera": FiCamera,
  "FiCast": FiCast,
  "FiCheckCircle": FiCheckCircle,
  "FiCheckSquare": FiCheckSquare,
  "FiCheck": FiCheck,
  "FiChevronDown": FiChevronDown,
  "FiChevronLeft": FiChevronLeft,
  "FiChevronRight": FiChevronRight,
  "FiChevronUp": FiChevronUp,
  "FiChevronsDown": FiChevronsDown,
  "FiChevronsLeft": FiChevronsLeft,
  "FiChevronsRight": FiChevronsRight,
  "FiChevronsUp": FiChevronsUp,
  "FiChrome": FiChrome,
  "FiCircle": FiCircle,
  "FiClipboard": FiClipboard,
  "FiClock": FiClock,
  "FiCloudDrizzle": FiCloudDrizzle,
  "FiCloudLightning": FiCloudLightning,
  "FiCloudOff": FiCloudOff,
  "FiCloudRain": FiCloudRain,
  "FiCloudSnow": FiCloudSnow,
  "FiCloud": FiCloud,
  "FiCode": FiCode,
  "FiCodepen": FiCodepen,
  "FiCodesandbox": FiCodesandbox,
  "FiCoffee": FiCoffee,
  "FiColumns": FiColumns,
  "FiCommand": FiCommand,
  "FiCompass": FiCompass,
  "FiCopy": FiCopy,
  "FiCornerDownLeft": FiCornerDownLeft,
  "FiCornerDownRight": FiCornerDownRight,
  "FiCornerLeftDown": FiCornerLeftDown,
  "FiCornerLeftUp": FiCornerLeftUp,
  "FiCornerRightDown": FiCornerRightDown,
  "FiCornerRightUp": FiCornerRightUp,
  "FiCornerUpLeft": FiCornerUpLeft,
  "FiCornerUpRight": FiCornerUpRight,
  "FiCpu": FiCpu,
  "FiCreditCard": FiCreditCard,
  "FiCrop": FiCrop,
  "FiCrosshair": FiCrosshair,
  "FiDatabase": FiDatabase,
  "FiDelete": FiDelete,
  "FiDisc": FiDisc,
  "FiDivideCircle": FiDivideCircle,
  "FiDivideSquare": FiDivideSquare,
  "FiDivide": FiDivide,
  "FiDollarSign": FiDollarSign,
  "FiDownloadCloud": FiDownloadCloud,
  "FiDownload": FiDownload,
  "FiDribbble": FiDribbble,
  "FiDroplet": FiDroplet,
  "FiEdit2": FiEdit2,
  "FiEdit3": FiEdit3,
  "FiEdit": FiEdit,
  "FiExternalLink": FiExternalLink,
  "FiEyeOff": FiEyeOff,
  "FiEye": FiEye,
  "FiFacebook": FiFacebook,
  "FiFastForward": FiFastForward,
  "FiFeather": FiFeather,
  "FiFigma": FiFigma,
  "FiFileMinus": FiFileMinus,
  "FiFilePlus": FiFilePlus,
  "FiFileText": FiFileText,
  "FiFile": FiFile,
  "FiFilm": FiFilm,
  "FiFilter": FiFilter,
  "FiFlag": FiFlag,
  "FiFolderMinus": FiFolderMinus,
  "FiFolderPlus": FiFolderPlus,
  "FiFolder": FiFolder,
  "FiFramer": FiFramer,
  "FiFrown": FiFrown,
  "FiGift": FiGift,
  "FiGitBranch": FiGitBranch,
  "FiGitCommit": FiGitCommit,
  "FiGitMerge": FiGitMerge,
  "FiGitPullRequest": FiGitPullRequest,
  "FiGithub": FiGithub,
  "FiGitlab": FiGitlab,
  "FiGlobe": FiGlobe,
  "FiGrid": FiGrid,
  "FiHardDrive": FiHardDrive,
  "FiHash": FiHash,
  "FiHeadphones": FiHeadphones,
  "FiHeart": FiHeart,
  "FiHelpCircle": FiHelpCircle,
  "FiHexagon": FiHexagon,
  "FiHome": FiHome,
  "FiImage": FiImage,
  "FiInbox": FiInbox,
  "FiInfo": FiInfo,
  "FiInstagram": FiInstagram,
  "FiItalic": FiItalic,
  "FiKey": FiKey,
  "FiLayers": FiLayers,
  "FiLayout": FiLayout,
  "FiLifeBuoy": FiLifeBuoy,
  "FiLink2": FiLink2,
  "FiLink": FiLink,
  "FiLinkedin": FiLinkedin,
  "FiList": FiList,
  "FiLoader": FiLoader,
  "FiLock": FiLock,
  "FiLogIn": FiLogIn,
  "FiLogOut": FiLogOut,
  "FiMail": FiMail,
  "FiMapPin": FiMapPin,
  "FiMap": FiMap,
  "FiMaximize2": FiMaximize2,
  "FiMaximize": FiMaximize,
  "FiMeh": FiMeh,
  "FiMenu": FiMenu,
  "FiMessageCircle": FiMessageCircle,
  "FiMessageSquare": FiMessageSquare,
  "FiMicOff": FiMicOff,
  "FiMic": FiMic,
  "FiMinimize2": FiMinimize2,
  "FiMinimize": FiMinimize,
  "FiMinusCircle": FiMinusCircle,
  "FiMinusSquare": FiMinusSquare,
  "FiMinus": FiMinus,
  "FiMonitor": FiMonitor,
  "FiMoon": FiMoon,
  "FiMoreHorizontal": FiMoreHorizontal,
  "FiMoreVertical": FiMoreVertical,
  "FiMousePointer": FiMousePointer,
  "FiMove": FiMove,
  "FiMusic": FiMusic,
  "FiNavigation2": FiNavigation2,
  "FiNavigation": FiNavigation,
  "FiOctagon": FiOctagon,
  "FiPackage": FiPackage,
  "FiPaperclip": FiPaperclip,
  "FiPauseCircle": FiPauseCircle,
  "FiPause": FiPause,
  "FiPenTool": FiPenTool,
  "FiPercent": FiPercent,
  "FiPhoneCall": FiPhoneCall,
  "FiPhoneForwarded": FiPhoneForwarded,
  "FiPhoneIncoming": FiPhoneIncoming,
  "FiPhoneMissed": FiPhoneMissed,
  "FiPhoneOff": FiPhoneOff,
  "FiPhoneOutgoing": FiPhoneOutgoing,
  "FiPhone": FiPhone,
  "FiPieChart": FiPieChart,
  "FiPlayCircle": FiPlayCircle,
  "FiPlay": FiPlay,
  "FiPlusCircle": FiPlusCircle,
  "FiPlusSquare": FiPlusSquare,
  "FiPlus": FiPlus,
  "FiPocket": FiPocket,
  "FiPower": FiPower,
  "FiPrinter": FiPrinter,
  "FiRadio": FiRadio,
  "FiRefreshCcw": FiRefreshCcw,
  "FiRefreshCw": FiRefreshCw,
  "FiRepeat": FiRepeat,
  "FiRewind": FiRewind,
  "FiRotateCcw": FiRotateCcw,
  "FiRotateCw": FiRotateCw,
  "FiRss": FiRss,
  "FiSave": FiSave,
  "FiScissors": FiScissors,
  "FiSearch": FiSearch,
  "FiSend": FiSend,
  "FiServer": FiServer,
  "FiSettings": FiSettings,
  "FiShare2": FiShare2,
  "FiShare": FiShare,
  "FiShieldOff": FiShieldOff,
  "FiShield": FiShield,
  "FiShoppingBag": FiShoppingBag,
  "FiShoppingCart": FiShoppingCart,
  "FiShuffle": FiShuffle,
  "FiSidebar": FiSidebar,
  "FiSkipBack": FiSkipBack,
  "FiSkipForward": FiSkipForward,
  "FiSlack": FiSlack,
  "FiSlash": FiSlash,
  "FiSliders": FiSliders,
  "FiSmartphone": FiSmartphone,
  "FiSmile": FiSmile,
  "FiSpeaker": FiSpeaker,
  "FiSquare": FiSquare,
  "FiStar": FiStar,
  "FiStopCircle": FiStopCircle,
  "FiSun": FiSun,
  "FiSunrise": FiSunrise,
  "FiSunset": FiSunset,
  "FiTablet": FiTablet,
  "FiTag": FiTag,
  "FiTarget": FiTarget,
  "FiTerminal": FiTerminal,
  "FiThermometer": FiThermometer,
  "FiThumbsDown": FiThumbsDown,
  "FiThumbsUp": FiThumbsUp,
  "FiToggleLeft": FiToggleLeft,
  "FiToggleRight": FiToggleRight,
  "FiTool": FiTool,
  "FiTrash2": FiTrash2,
  "FiTrash": FiTrash,
  "FiTrello": FiTrello,
  "FiTrendingDown": FiTrendingDown,
  "FiTrendingUp": FiTrendingUp,
  "FiTriangle": FiTriangle,
  "FiTruck": FiTruck,
  "FiTv": FiTv,
  "FiTwitch": FiTwitch,
  "FiTwitter": FiTwitter,
  "FiType": FiType,
  "FiUmbrella": FiUmbrella,
  "FiUnderline": FiUnderline,
  "FiUnlock": FiUnlock,
  "FiUploadCloud": FiUploadCloud,
  "FiUpload": FiUpload,
  "FiUserCheck": FiUserCheck,
  "FiUserMinus": FiUserMinus,
  "FiUserPlus": FiUserPlus,
  "FiUserX": FiUserX,
  "FiUser": FiUser,
  "FiUsers": FiUsers,
  "FiVideoOff": FiVideoOff,
  "FiVideo": FiVideo,
  "FiVoicemail": FiVoicemail,
  "FiVolume1": FiVolume1,
  "FiVolume2": FiVolume2,
  "FiVolumeX": FiVolumeX,
  "FiVolume": FiVolume,
  "FiWatch": FiWatch,
  "FiWifiOff": FiWifiOff,
  "FiWifi": FiWifi,
  "FiWind": FiWind,
  "FiXCircle": FiXCircle,
  "FiXOctagon": FiXOctagon,
  "FiXSquare": FiXSquare,
  "FiX": FiX,
  "FiYoutube": FiYoutube,
  "FiZapOff": FiZapOff,
  "FiZap": FiZap,
  "FiZoomIn": FiZoomIn,
  "FiZoomOut": FiZoomOut,
};