import { 
    GoAlert,
GoArchive,
GoArrowBoth,
GoArrowDown,
GoArrowLeft,
GoArrowRight,
GoArrowSmallDown,
GoArrowSmallLeft,
GoArrowSmallRight,
GoArrowSmallUp,
GoArrowUp,
GoBeaker,
GoBell,
GoBold,
GoBook,
GoBookmark,
GoBriefcase,
GoBroadcast,
GoBrowser,
GoBug,
GoCalendar,
GoCheck,
GoChecklist,
GoChevronDown,
GoChevronLeft,
GoChevronRight,
GoChevronUp,
GoCircleSlash,
GoCircuitBoard,
GoClippy,
GoClock,
GoCloudDownload,
GoCloudUpload,
GoCode,
GoCommentDiscussion,
GoComment,
GoCreditCard,
GoDash,
GoDashboard,
GoDatabase,
GoDesktopDownload,
GoDeviceCameraVideo,
GoDeviceCamera,
GoDeviceDesktop,
GoDeviceMobile,
GoDiffAdded,
GoDiffIgnored,
GoDiffModified,
GoDiffRemoved,
GoDiffRenamed,
GoDiff,
GoEllipsis,
GoEyeClosed,
GoEye,
GoFileBinary,
GoFileCode,
GoFileDirectory,
GoFileMedia,
GoFilePdf,
GoFileSubmodule,
GoFileSymlinkDirectory,
GoFileSymlinkFile,
GoFileZip,
GoFile,
GoFlame,
GoFoldDown,
GoFoldUp,
GoFold,
GoGear,
GoGift,
GoGistSecret,
GoGist,
GoGitBranch,
GoGitCommit,
GoGitCompare,
GoGitMerge,
GoGitPullRequest,
GoGithubAction,
GoGlobe,
GoGrabber,
GoGraph,
GoHeart,
GoHistory,
GoHome,
GoHorizontalRule,
GoHubot,
GoInbox,
GoInfo,
GoIssueClosed,
GoIssueOpened,
GoIssueReopened,
GoItalic,
GoJersey,
GoKebabHorizontal,
GoKebabVertical,
GoKey,
GoKeyboard,
GoLaw,
GoLightBulb,
GoLinkExternal,
GoLink,
GoListOrdered,
GoListUnordered,
GoLocation,
GoLock,
GoLogoGist,
GoLogoGithub,
GoMailRead,
GoMail,
GoMarkGithub,
GoMarkdown,
GoMegaphone,
GoMention,
GoMilestone,
GoMirror,
GoMortarBoard,
GoMute,
GoNoNewline,
GoNote,
GoOctoface,
GoOrganization,
GoPackage,
GoPaintcan,
GoPencil,
GoPerson,
GoPin,
GoPlay,
GoPlug,
GoPlusSmall,
GoPlus,
GoPrimitiveDot,
GoPrimitiveSquare,
GoProject,
GoPulse,
GoQuestion,
GoQuote,
GoRadioTower,
GoReply,
GoRepoClone,
GoRepoForcePush,
GoRepoForked,
GoRepoPull,
GoRepoPush,
GoRepo,
GoReport,
GoRequestChanges,
GoRocket,
GoRss,
GoRuby,
GoScreenFull,
GoScreenNormal,
GoSearch,
GoServer,
GoSettings,
GoShield,
GoSignIn,
GoSignOut,
GoSmiley,
GoSquirrel,
GoStar,
GoStop,
GoSync,
GoTag,
GoTasklist,
GoTelescope,
GoTerminal,
GoTextSize,
GoThreeBars,
GoThumbsdown,
GoThumbsup,
GoTools,
GoTrashcan,
GoTriangleDown,
GoTriangleLeft,
GoTriangleRight,
GoTriangleUp,
GoUnfold,
GoUnmute,
GoUnverified,
GoVerified,
GoVersions,
GoWatch,
GoX,
GoZap
 } from "react-icons/go";

export const GithubIcons = {
    "GoAlert": GoAlert,
    "GoArchive": GoArchive,
    "GoArrowBoth": GoArrowBoth,
    "GoArrowDown": GoArrowDown,
    "GoArrowLeft": GoArrowLeft,
    "GoArrowRight": GoArrowRight,
    "GoArrowSmallDown": GoArrowSmallDown,
    "GoArrowSmallLeft": GoArrowSmallLeft,
    "GoArrowSmallRight": GoArrowSmallRight,
    "GoArrowSmallUp": GoArrowSmallUp,
    "GoArrowUp": GoArrowUp,
    "GoBeaker": GoBeaker,
    "GoBell": GoBell,
    "GoBold": GoBold,
    "GoBook": GoBook,
    "GoBookmark": GoBookmark,
    "GoBriefcase": GoBriefcase,
    "GoBroadcast": GoBroadcast,
    "GoBrowser": GoBrowser,
    "GoBug": GoBug,
    "GoCalendar": GoCalendar,
    "GoCheck": GoCheck,
    "GoChecklist": GoChecklist,
    "GoChevronDown": GoChevronDown,
    "GoChevronLeft": GoChevronLeft,
    "GoChevronRight": GoChevronRight,
    "GoChevronUp": GoChevronUp,
    "GoCircleSlash": GoCircleSlash,
    "GoCircuitBoard": GoCircuitBoard,
    "GoClippy": GoClippy,
    "GoClock": GoClock,
    "GoCloudDownload": GoCloudDownload,
    "GoCloudUpload": GoCloudUpload,
    "GoCode": GoCode,
    "GoCommentDiscussion": GoCommentDiscussion,
    "GoComment": GoComment,
    "GoCreditCard": GoCreditCard,
    "GoDash": GoDash,
    "GoDashboard": GoDashboard,
    "GoDatabase": GoDatabase,
    "GoDesktopDownload": GoDesktopDownload,
    "GoDeviceCameraVideo": GoDeviceCameraVideo,
    "GoDeviceCamera": GoDeviceCamera,
    "GoDeviceDesktop": GoDeviceDesktop,
    "GoDeviceMobile": GoDeviceMobile,
    "GoDiffAdded": GoDiffAdded,
    "GoDiffIgnored": GoDiffIgnored,
    "GoDiffModified": GoDiffModified,
    "GoDiffRemoved": GoDiffRemoved,
    "GoDiffRenamed": GoDiffRenamed,
    "GoDiff": GoDiff,
    "GoEllipsis": GoEllipsis,
    "GoEyeClosed": GoEyeClosed,
    "GoEye": GoEye,
    "GoFileBinary": GoFileBinary,
    "GoFileCode": GoFileCode,
    "GoFileDirectory": GoFileDirectory,
    "GoFileMedia": GoFileMedia,
    "GoFilePdf": GoFilePdf,
    "GoFileSubmodule": GoFileSubmodule,
    "GoFileSymlinkDirectory": GoFileSymlinkDirectory,
    "GoFileSymlinkFile": GoFileSymlinkFile,
    "GoFileZip": GoFileZip,
    "GoFile": GoFile,
    "GoFlame": GoFlame,
    "GoFoldDown": GoFoldDown,
    "GoFoldUp": GoFoldUp,
    "GoFold": GoFold,
    "GoGear": GoGear,
    "GoGift": GoGift,
    "GoGistSecret": GoGistSecret,
    "GoGist": GoGist,
    "GoGitBranch": GoGitBranch,
    "GoGitCommit": GoGitCommit,
    "GoGitCompare": GoGitCompare,
    "GoGitMerge": GoGitMerge,
    "GoGitPullRequest": GoGitPullRequest,
    "GoGithubAction": GoGithubAction,
    "GoGlobe": GoGlobe,
    "GoGrabber": GoGrabber,
    "GoGraph": GoGraph,
    "GoHeart": GoHeart,
    "GoHistory": GoHistory,
    "GoHome": GoHome,
    "GoHorizontalRule": GoHorizontalRule,
    "GoHubot": GoHubot,
    "GoInbox": GoInbox,
    "GoInfo": GoInfo,
    "GoIssueClosed": GoIssueClosed,
    "GoIssueOpened": GoIssueOpened,
    "GoIssueReopened": GoIssueReopened,
    "GoItalic": GoItalic,
    "GoJersey": GoJersey,
    "GoKebabHorizontal": GoKebabHorizontal,
    "GoKebabVertical": GoKebabVertical,
    "GoKey": GoKey,
    "GoKeyboard": GoKeyboard,
    "GoLaw": GoLaw,
    "GoLightBulb": GoLightBulb,
    "GoLinkExternal": GoLinkExternal,
    "GoLink": GoLink,
    "GoListOrdered": GoListOrdered,
    "GoListUnordered": GoListUnordered,
    "GoLocation": GoLocation,
    "GoLock": GoLock,
    "GoLogoGist": GoLogoGist,
    "GoLogoGithub": GoLogoGithub,
    "GoMailRead": GoMailRead,
    "GoMail": GoMail,
    "GoMarkGithub": GoMarkGithub,
    "GoMarkdown": GoMarkdown,
    "GoMegaphone": GoMegaphone,
    "GoMention": GoMention,
    "GoMilestone": GoMilestone,
    "GoMirror": GoMirror,
    "GoMortarBoard": GoMortarBoard,
    "GoMute": GoMute,
    "GoNoNewline": GoNoNewline,
    "GoNote": GoNote,
    "GoOctoface": GoOctoface,
    "GoOrganization": GoOrganization,
    "GoPackage": GoPackage,
    "GoPaintcan": GoPaintcan,
    "GoPencil": GoPencil,
    "GoPerson": GoPerson,
    "GoPin": GoPin,
    "GoPlay": GoPlay,
    "GoPlug": GoPlug,
    "GoPlusSmall": GoPlusSmall,
    "GoPlus": GoPlus,
    "GoPrimitiveDot": GoPrimitiveDot,
    "GoPrimitiveSquare": GoPrimitiveSquare,
    "GoProject": GoProject,
    "GoPulse": GoPulse,
    "GoQuestion": GoQuestion,
    "GoQuote": GoQuote,
    "GoRadioTower": GoRadioTower,
    "GoReply": GoReply,
    "GoRepoClone": GoRepoClone,
    "GoRepoForcePush": GoRepoForcePush,
    "GoRepoForked": GoRepoForked,
    "GoRepoPull": GoRepoPull,
    "GoRepoPush": GoRepoPush,
    "GoRepo": GoRepo,
    "GoReport": GoReport,
    "GoRequestChanges": GoRequestChanges,
    "GoRocket": GoRocket,
    "GoRss": GoRss,
    "GoRuby": GoRuby,
    "GoScreenFull": GoScreenFull,
    "GoScreenNormal": GoScreenNormal,
    "GoSearch": GoSearch,
    "GoServer": GoServer,
    "GoSettings": GoSettings,
    "GoShield": GoShield,
    "GoSignIn": GoSignIn,
    "GoSignOut": GoSignOut,
    "GoSmiley": GoSmiley,
    "GoSquirrel": GoSquirrel,
    "GoStar": GoStar,
    "GoStop": GoStop,
    "GoSync": GoSync,
    "GoTag": GoTag,
    "GoTasklist": GoTasklist,
    "GoTelescope": GoTelescope,
    "GoTerminal": GoTerminal,
    "GoTextSize": GoTextSize,
    "GoThreeBars": GoThreeBars,
    "GoThumbsdown": GoThumbsdown,
    "GoThumbsup": GoThumbsup,
    "GoTools": GoTools,
    "GoTrashcan": GoTrashcan,
    "GoTriangleDown": GoTriangleDown,
    "GoTriangleLeft": GoTriangleLeft,
    "GoTriangleRight": GoTriangleRight,
    "GoTriangleUp": GoTriangleUp,
    "GoUnfold": GoUnfold,
    "GoUnmute": GoUnmute,
    "GoUnverified": GoUnverified,
    "GoVerified": GoVerified,
    "GoVersions": GoVersions,
    "GoWatch": GoWatch,
    "GoX": GoX,
    "GoZap": GoZap
}