import { GrAccessibility,
    GrAchievement,
    GrAction,
    GrActions,
    GrAd,
    GrAddCircle,
    GrAdd,
    GrAed,
    GrAggregate,
    GrAidOption,
    GrAid,
    GrAlarm,
    GrAlert,
    GrAmazon,
    GrAmex,
    GrAnalytics,
    GrAnchor,
    GrAndroid,
    GrAnnounce,
    GrAppleAppStore,
    GrApple,
    GrAppsRounded,
    GrApps,
    GrArchive,
    GrArchlinux,
    GrArticle,
    GrAruba,
    GrAscend,
    GrAscending,
    GrAssistListening,
    GrAtm,
    GrAttachment,
    GrAttraction,
    GrBaby,
    GrBackTen,
    GrBarChart,
    GrBar,
    GrBasket,
    GrBeacon,
    GrBike,
    GrBitcoin,
    GrBladesHorizontal,
    GrBladesVertical,
    GrBlockQuote,
    GrBlog,
    GrBluetooth,
    GrBold,
    GrBook,
    GrBookmark,
    GrBottomCorner,
    GrBraille,
    GrBriefcase,
    GrBrush,
    GrBug,
    GrBundle,
    GrBus,
    GrBusinessService,
    GrCafeteria,
    GrCalculator,
    GrCalendar,
    GrCamera,
    GrCapacity,
    GrCar,
    GrCaretDownFill,
    GrCaretDown,
    GrCaretLeftFill,
    GrCaretNext,
    GrCaretPrevious,
    GrCaretRightFill,
    GrCaretUpFill,
    GrCaretUp,
    GrCart,
    GrCatalogOption,
    GrCatalog,
    GrCentos,
    GrCertificate,
    GrChannel,
    GrChapterAdd,
    GrChapterNext,
    GrChapterPrevious,
    GrChatOption,
    GrChat,
    GrCheckboxSelected,
    GrCheckbox,
    GrCheckmark,
    GrChrome,
    GrCircleAlert,
    GrCircleInformation,
    GrCirclePlay,
    GrCircleQuestion,
    GrClearOption,
    GrClear,
    GrCli,
    GrClipboard,
    GrClock,
    GrClone,
    GrClose,
    GrClosedCaption,
    GrCloudComputer,
    GrCloudDownload,
    GrCloudSoftware,
    GrCloudUpload,
    GrCloud,
    GrCloudlinux,
    GrCluster,
    GrCoatCheck,
    GrCodeSandbox,
    GrCode,
    GrCodepen,
    GrCoffee,
    GrColumns,
    GrCommand,
    GrCompare,
    GrCompass,
    GrCompliance,
    GrConfigure,
    GrConnect,
    GrConnectivity,
    GrConsole,
    GrContactInfo,
    GrContact,
    GrContract,
    GrCopy,
    GrCpu,
    GrCreativeCommons,
    GrCreditCard,
    GrCss3,
    GrCube,
    GrCubes,
    GrCurrency,
    GrCursor,
    GrCut,
    GrCycle,
    GrDashboard,
    GrDatabase,
    GrDebian,
    GrDeliver,
    GrDeploy,
    GrDescend,
    GrDescending,
    GrDesktop,
    GrDetach,
    GrDevice,
    GrDiamond,
    GrDirections,
    GrDisabledOutline,
    GrDisc,
    GrDislike,
    GrDocker,
    GrDocumentCloud,
    GrDocumentConfig,
    GrDocumentCsv,
    GrDocumentDownload,
    GrDocumentExcel,
    GrDocumentImage,
    GrDocumentLocked,
    GrDocumentMissing,
    GrDocumentNotes,
    GrDocumentOutlook,
    GrDocumentPdf,
    GrDocumentPerformance,
    GrDocumentPpt,
    GrDocumentRtf,
    GrDocumentSound,
    GrDocumentStore,
    GrDocumentTest,
    GrDocumentText,
    GrDocumentThreat,
    GrDocumentTime,
    GrDocumentTransfer,
    GrDocumentTxt,
    GrDocumentUpdate,
    GrDocumentUpload,
    GrDocumentUser,
    GrDocumentVerified,
    GrDocumentVideo,
    GrDocumentWindows,
    GrDocumentWord,
    GrDocumentZip,
    GrDocument,
    GrDomain,
    GrDos,
    GrDown,
    GrDownloadOption,
    GrDownload,
    GrDrag,
    GrDrawer,
    GrDribbble,
    GrDriveCage,
    GrDropbox,
    GrDuplicate,
    GrDxc,
    GrEbay,
    GrEdge,
    GrEdit,
    GrEject,
    GrElevator,
    GrEmergency,
    GrEmoji,
    GrEmptyCircle,
    GrErase,
    GrEscalator,
    GrExpand,
    GrEzmeral,
    GrFacebookOption,
    GrFacebook,
    GrFanOption,
    GrFan,
    GrFastForward,
    GrFavorite,
    GrFedora,
    GrFigma,
    GrFilter,
    GrFingerPrint,
    GrFireball,
    GrFirefox,
    GrFirewall,
    GrFlagFill,
    GrFlag,
    GrFlows,
    GrFolderCycle,
    GrFolderOpen,
    GrFolder,
    GrFormAdd,
    GrFormAttachment,
    GrFormCalendar,
    GrFormCheckmark,
    GrFormClock,
    GrFormClose,
    GrFormCut,
    GrFormDown,
    GrFormEdit,
    GrFormFilter,
    GrFormFolder,
    GrFormLocation,
    GrFormLock,
    GrFormNextLink,
    GrFormNext,
    GrFormPreviousLink,
    GrFormPrevious,
    GrFormRefresh,
    GrFormSchedule,
    GrFormSearch,
    GrFormSubtract,
    GrFormTrash,
    GrFormUp,
    GrFormUpload,
    GrFormViewHide,
    GrFormView,
    GrForwardTen,
    GrFreebsd,
    GrGallery,
    GrGamepad,
    GrGateway,
    GrGatsbyjs,
    GrGem,
    GrGift,
    GrGithub,
    GrGlobe,
    GrGolang,
    GrGooglePlay,
    GrGooglePlus,
    GrGoogleWallet,
    GrGoogle,
    GrGraphQl,
    GrGremlin,
    GrGrid,
    GrGrommet,
    GrGroup,
    GrGrow,
    GrHadoop,
    GrHalt,
    GrHelpOption,
    GrHelp,
    GrHeroku,
    GrHide,
    GrHistory,
    GrHomeOption,
    GrHomeRounded,
    GrHome,
    GrHorton,
    GrHostMaintenance,
    GrHost,
    GrHp,
    GrHpeLabs,
    GrHpe,
    GrHpi,
    GrHtml5,
    GrIceCream,
    GrImage,
    GrImpact,
    GrInProgress,
    GrInbox,
    GrIndicator,
    GrInfo,
    GrInherit,
    GrInsecure,
    GrInspect,
    GrInstagram,
    GrInstallOption,
    GrInstall,
    GrIntegration,
    GrInternetExplorer,
    GrItalic,
    GrIteration,
    GrJava,
    GrJs,
    GrKey,
    GrKeyboard,
    GrLanguage,
    GrLastfm,
    GrLaunch,
    GrLayer,
    GrLicense,
    GrLike,
    GrLineChart,
    GrLinkBottom,
    GrLinkDown,
    GrLinkNext,
    GrLinkPrevious,
    GrLinkTop,
    GrLinkUp,
    GrLink,
    GrLinkedinOption,
    GrLinkedin,
    GrList,
    GrLocal,
    GrLocationPin,
    GrLocation,
    GrLock,
    GrLogin,
    GrLogout,
    GrLounge,
    GrMagic,
    GrMailOption,
    GrMail,
    GrMandriva,
    GrManual,
    GrMapLocation,
    GrMap,
    GrMastercard,
    GrMedium,
    GrMemory,
    GrMenu,
    GrMicrofocus,
    GrMicrophone,
    GrMoney,
    GrMonitor,
    GrMonospace,
    GrMoon,
    GrMoreVertical,
    GrMore,
    GrMouse,
    GrMultimedia,
    GrMultiple,
    GrMusic,
    GrMysql,
    GrNavigate,
    GrNetworkDrive,
    GrNetwork,
    GrNewWindow,
    GrNew,
    GrNext,
    GrNode,
    GrNodes,
    GrNorton,
    GrNote,
    GrNotes,
    GrNotification,
    GrNpm,
    GrObjectGroup,
    GrObjectUngroup,
    GrOfflineStorage,
    GrOnedrive,
    GrOpera,
    GrOptimize,
    GrOracle,
    GrOrderedList,
    GrOrganization,
    GrOverview,
    GrPackage,
    GrPaint,
    GrPan,
    GrPauseFill,
    GrPause,
    GrPaypal,
    GrPerformance,
    GrPersonalComputer,
    GrPhoneFlip,
    GrPhoneHorizontal,
    GrPhoneVertical,
    GrPhone,
    GrPieChart,
    GrPiedPiper,
    GrPin,
    GrPinterest,
    GrPlan,
    GrPlayFill,
    GrPlay,
    GrPlug,
    GrPocket,
    GrPowerCycle,
    GrPowerForceShutdown,
    GrPowerReset,
    GrPowerShutdown,
    GrPower,
    GrPrevious,
    GrPrint,
    GrProductHunt,
    GrProjects,
    GrQr,
    GrRadialSelected,
    GrRadial,
    GrRaspberry,
    GrReactjs,
    GrReddit,
    GrRedhat,
    GrRedo,
    GrRefresh,
    GrResources,
    GrRestaurant,
    GrRestroomMen,
    GrRestroomWomen,
    GrRestroom,
    GrResume,
    GrReturn,
    GrRevert,
    GrRewind,
    GrRisk,
    GrRobot,
    GrRotateLeft,
    GrRotateRight,
    GrRss,
    GrRun,
    GrSafariOption,
    GrSans,
    GrSatellite,
    GrSave,
    GrScan,
    GrScheduleNew,
    GrSchedulePlay,
    GrSchedule,
    GrSchedules,
    GrSco,
    GrScorecard,
    GrScript,
    GrSd,
    GrSearchAdvanced,
    GrSearch,
    GrSecure,
    GrSelect,
    GrSelection,
    GrSemantics,
    GrSend,
    GrServerCluster,
    GrServer,
    GrServers,
    GrServicePlay,
    GrServices,
    GrSettingsOption,
    GrShareOption,
    GrShareRounded,
    GrShare,
    GrShieldSecurity,
    GrShield,
    GrShift,
    GrShop,
    GrSidebar,
    GrSign,
    GrSkype,
    GrSlack,
    GrSnapchat,
    GrSolaris,
    GrSort,
    GrSoundcloud,
    GrSpa,
    GrSpectrum,
    GrSplit,
    GrSplits,
    GrSpotify,
    GrSquare,
    GrStackOverflow,
    GrStakeholder,
    GrStarHalf,
    GrStar,
    GrStatusCriticalSmall,
    GrStatusCritical,
    GrStatusDisabledSmall,
    GrStatusDisabled,
    GrStatusGoodSmall,
    GrStatusGood,
    GrStatusInfoSmall,
    GrStatusInfo,
    GrStatusPlaceholderSmall,
    GrStatusPlaceholder,
    GrStatusUnknownSmall,
    GrStatusUnknown,
    GrStatusWarningSmall,
    GrStatusWarning,
    GrStepsOption,
    GrSteps,
    GrStopFill,
    GrStop,
    GrStorage,
    GrStreetView,
    GrStrikeThrough,
    GrStripe,
    GrSubscript,
    GrSubtractCircle,
    GrSubtract,
    GrSun,
    GrSuperscript,
    GrSupport,
    GrSuse,
    GrSwift,
    GrSwim,
    GrSwitch,
    GrSync,
    GrSystem,
    GrTableAdd,
    GrTable,
    GrTag,
    GrTapeOption,
    GrTape,
    GrTarget,
    GrTask,
    GrTasks,
    GrTechnology,
    GrTemplate,
    GrTerminal,
    GrTestDesktop,
    GrTest,
    GrTextAlignCenter,
    GrTextAlignFull,
    GrTextAlignLeft,
    GrTextAlignRight,
    GrTextWrap,
    GrThreats,
    GrThreeDEffects,
    GrThreeD,
    GrTicket,
    GrTictok,
    GrTime,
    GrTip,
    GrToast,
    GrTools,
    GrTooltip,
    GrTopCorner,
    GrTrain,
    GrTransaction,
    GrTrash,
    GrTreeOption,
    GrTree,
    GrTrigger,
    GrTrophy,
    GrTroubleshoot,
    GrTty,
    GrTumblr,
    GrTurbolinux,
    GrTwitter,
    GrUbuntu,
    GrUnderline,
    GrUndo,
    GrUnlink,
    GrUnlock,
    GrUnorderedList,
    GrUnsorted,
    GrUp,
    GrUpdate,
    GrUpgrade,
    GrUploadOption,
    GrUpload,
    GrUsbKey,
    GrUserAdd,
    GrUserAdmin,
    GrUserExpert,
    GrUserFemale,
    GrUserManager,
    GrUserNew,
    GrUserPolice,
    GrUserSettings,
    GrUserWorker,
    GrUser,
    GrValidate,
    GrVend,
    GrVideo,
    GrView,
    GrVimeo,
    GrVirtualMachine,
    GrVirtualStorage,
    GrVisa,
    GrVmMaintenance,
    GrVmware,
    GrVolumeControl,
    GrVolumeLow,
    GrVolumeMute,
    GrVolume,
    GrVulnerability,
    GrWaypoint,
    GrWebcam,
    GrWheelchairActive,
    GrWheelchair,
    GrWifiLow,
    GrWifiMedium,
    GrWifiNone,
    GrWifi,
    GrWindowsLegacy,
    GrWindows,
    GrWordpress,
    GrWorkshop,
    GrYoga,
    GrYoutube,
    GrZoomIn,
    GrZoomOut,
    GrZoom
 } from "react-icons/gr";

export const GrommetIcons = {
    "GrAccessibility": GrAccessibility,
    "GrAchievement": GrAchievement,
    "GrAction": GrAction,
    "GrActions": GrActions,
    "GrAd": GrAd,
    "GrAddCircle": GrAddCircle,
    "GrAdd": GrAdd,
    "GrAed": GrAed,
    "GrAggregate": GrAggregate,
    "GrAidOption": GrAidOption,
    "GrAid": GrAid,
    "GrAlarm": GrAlarm,
    "GrAlert": GrAlert,
    "GrAmazon": GrAmazon,
    "GrAmex": GrAmex,
    "GrAnalytics": GrAnalytics,
    "GrAnchor": GrAnchor,
    "GrAndroid": GrAndroid,
    "GrAnnounce": GrAnnounce,
    "GrAppleAppStore": GrAppleAppStore,
    "GrApple": GrApple,
    "GrAppsRounded": GrAppsRounded,
    "GrApps": GrApps,
    "GrArchive": GrArchive,
    "GrArchlinux": GrArchlinux,
    "GrArticle": GrArticle,
    "GrAruba": GrAruba,
    "GrAscend": GrAscend,
    "GrAscending": GrAscending,
    "GrAssistListening": GrAssistListening,
    "GrAtm": GrAtm,
    "GrAttachment": GrAttachment,
    "GrAttraction": GrAttraction,
    "GrBaby": GrBaby,
    "GrBackTen": GrBackTen,
    "GrBarChart": GrBarChart,
    "GrBar": GrBar,
    "GrBasket": GrBasket,
    "GrBeacon": GrBeacon,
    "GrBike": GrBike,
    "GrBitcoin": GrBitcoin,
    "GrBladesHorizontal": GrBladesHorizontal,
    "GrBladesVertical": GrBladesVertical,
    "GrBlockQuote": GrBlockQuote,
    "GrBlog": GrBlog,
    "GrBluetooth": GrBluetooth,
    "GrBold": GrBold,
    "GrBook": GrBook,
    "GrBookmark": GrBookmark,
    "GrBottomCorner": GrBottomCorner,
    "GrBraille": GrBraille,
    "GrBriefcase": GrBriefcase,
    "GrBrush": GrBrush,
    "GrBug": GrBug,
    "GrBundle": GrBundle,
    "GrBus": GrBus,
    "GrBusinessService": GrBusinessService,
    "GrCafeteria": GrCafeteria,
    "GrCalculator": GrCalculator,
    "GrCalendar": GrCalendar,
    "GrCamera": GrCamera,
    "GrCapacity": GrCapacity,
    "GrCar": GrCar,
    "GrCaretDownFill": GrCaretDownFill,
    "GrCaretDown": GrCaretDown,
    "GrCaretLeftFill": GrCaretLeftFill,
    "GrCaretNext": GrCaretNext,
    "GrCaretPrevious": GrCaretPrevious,
    "GrCaretRightFill": GrCaretRightFill,
    "GrCaretUpFill": GrCaretUpFill,
    "GrCaretUp": GrCaretUp,
    "GrCart": GrCart,
    "GrCatalogOption": GrCatalogOption,
    "GrCatalog": GrCatalog,
    "GrCentos": GrCentos,
    "GrCertificate": GrCertificate,
    "GrChannel": GrChannel,
    "GrChapterAdd": GrChapterAdd,
    "GrChapterNext": GrChapterNext,
    "GrChapterPrevious": GrChapterPrevious,
    "GrChatOption": GrChatOption,
    "GrChat": GrChat,
    "GrCheckboxSelected": GrCheckboxSelected,
    "GrCheckbox": GrCheckbox,
    "GrCheckmark": GrCheckmark,
    "GrChrome": GrChrome,
    "GrCircleAlert": GrCircleAlert,
    "GrCircleInformation": GrCircleInformation,
    "GrCirclePlay": GrCirclePlay,
    "GrCircleQuestion": GrCircleQuestion,
    "GrClearOption": GrClearOption,
    "GrClear": GrClear,
    "GrCli": GrCli,
    "GrClipboard": GrClipboard,
    "GrClock": GrClock,
    "GrClone": GrClone,
    "GrClose": GrClose,
    "GrClosedCaption": GrClosedCaption,
    "GrCloudComputer": GrCloudComputer,
    "GrCloudDownload": GrCloudDownload,
    "GrCloudSoftware": GrCloudSoftware,
    "GrCloudUpload": GrCloudUpload,
    "GrCloud": GrCloud,
    "GrCloudlinux": GrCloudlinux,
    "GrCluster": GrCluster,
    "GrCoatCheck": GrCoatCheck,
    "GrCodeSandbox": GrCodeSandbox,
    "GrCode": GrCode,
    "GrCodepen": GrCodepen,
    "GrCoffee": GrCoffee,
    "GrColumns": GrColumns,
    "GrCommand": GrCommand,
    "GrCompare": GrCompare,
    "GrCompass": GrCompass,
    "GrCompliance": GrCompliance,
    "GrConfigure": GrConfigure,
    "GrConnect": GrConnect,
    "GrConnectivity": GrConnectivity,
    "GrConsole": GrConsole,
    "GrContactInfo": GrContactInfo,
    "GrContact": GrContact,
    "GrContract": GrContract,
    "GrCopy": GrCopy,
    "GrCpu": GrCpu,
    "GrCreativeCommons": GrCreativeCommons,
    "GrCreditCard": GrCreditCard,
    "GrCss3": GrCss3,
    "GrCube": GrCube,
    "GrCubes": GrCubes,
    "GrCurrency": GrCurrency,
    "GrCursor": GrCursor,
    "GrCut": GrCut,
    "GrCycle": GrCycle,
    "GrDashboard": GrDashboard,
    "GrDatabase": GrDatabase,
    "GrDebian": GrDebian,
    "GrDeliver": GrDeliver,
    "GrDeploy": GrDeploy,
    "GrDescend": GrDescend,
    "GrDescending": GrDescending,
    "GrDesktop": GrDesktop,
    "GrDetach": GrDetach,
    "GrDevice": GrDevice,
    "GrDiamond": GrDiamond,
    "GrDirections": GrDirections,
    "GrDisabledOutline": GrDisabledOutline,
    "GrDisc": GrDisc,
    "GrDislike": GrDislike,
    "GrDocker": GrDocker,
    "GrDocumentCloud": GrDocumentCloud,
    "GrDocumentConfig": GrDocumentConfig,
    "GrDocumentCsv": GrDocumentCsv,
    "GrDocumentDownload": GrDocumentDownload,
    "GrDocumentExcel": GrDocumentExcel,
    "GrDocumentImage": GrDocumentImage,
    "GrDocumentLocked": GrDocumentLocked,
    "GrDocumentMissing": GrDocumentMissing,
    "GrDocumentNotes": GrDocumentNotes,
    "GrDocumentOutlook": GrDocumentOutlook,
    "GrDocumentPdf": GrDocumentPdf,
    "GrDocumentPerformance": GrDocumentPerformance,
    "GrDocumentPpt": GrDocumentPpt,
    "GrDocumentRtf": GrDocumentRtf,
    "GrDocumentSound": GrDocumentSound,
    "GrDocumentStore": GrDocumentStore,
    "GrDocumentTest": GrDocumentTest,
    "GrDocumentText": GrDocumentText,
    "GrDocumentThreat": GrDocumentThreat,
    "GrDocumentTime": GrDocumentTime,
    "GrDocumentTransfer": GrDocumentTransfer,
    "GrDocumentTxt": GrDocumentTxt,
    "GrDocumentUpdate": GrDocumentUpdate,
    "GrDocumentUpload": GrDocumentUpload,
    "GrDocumentUser": GrDocumentUser,
    "GrDocumentVerified": GrDocumentVerified,
    "GrDocumentVideo": GrDocumentVideo,
    "GrDocumentWindows": GrDocumentWindows,
    "GrDocumentWord": GrDocumentWord,
    "GrDocumentZip": GrDocumentZip,
    "GrDocument": GrDocument,
    "GrDomain": GrDomain,
    "GrDos": GrDos,
    "GrDown": GrDown,
    "GrDownloadOption": GrDownloadOption,
    "GrDownload": GrDownload,
    "GrDrag": GrDrag,
    "GrDrawer": GrDrawer,
    "GrDribbble": GrDribbble,
    "GrDriveCage": GrDriveCage,
    "GrDropbox": GrDropbox,
    "GrDuplicate": GrDuplicate,
    "GrDxc": GrDxc,
    "GrEbay": GrEbay,
    "GrEdge": GrEdge,
    "GrEdit": GrEdit,
    "GrEject": GrEject,
    "GrElevator": GrElevator,
    "GrEmergency": GrEmergency,
    "GrEmoji": GrEmoji,
    "GrEmptyCircle": GrEmptyCircle,
    "GrErase": GrErase,
    "GrEscalator": GrEscalator,
    "GrExpand": GrExpand,
    "GrEzmeral": GrEzmeral,
    "GrFacebookOption": GrFacebookOption,
    "GrFacebook": GrFacebook,
    "GrFanOption": GrFanOption,
    "GrFan": GrFan,
    "GrFastForward": GrFastForward,
    "GrFavorite": GrFavorite,
    "GrFedora": GrFedora,
    "GrFigma": GrFigma,
    "GrFilter": GrFilter,
    "GrFingerPrint": GrFingerPrint,
    "GrFireball": GrFireball,
    "GrFirefox": GrFirefox,
    "GrFirewall": GrFirewall,
    "GrFlagFill": GrFlagFill,
    "GrFlag": GrFlag,
    "GrFlows": GrFlows,
    "GrFolderCycle": GrFolderCycle,
    "GrFolderOpen": GrFolderOpen,
    "GrFolder": GrFolder,
    "GrFormAdd": GrFormAdd,
    "GrFormAttachment": GrFormAttachment,
    "GrFormCalendar": GrFormCalendar,
    "GrFormCheckmark": GrFormCheckmark,
    "GrFormClock": GrFormClock,
    "GrFormClose": GrFormClose,
    "GrFormCut": GrFormCut,
    "GrFormDown": GrFormDown,
    "GrFormEdit": GrFormEdit,
    "GrFormFilter": GrFormFilter,
    "GrFormFolder": GrFormFolder,
    "GrFormLocation": GrFormLocation,
    "GrFormLock": GrFormLock,
    "GrFormNextLink": GrFormNextLink,
    "GrFormNext": GrFormNext,
    "GrFormPreviousLink": GrFormPreviousLink,
    "GrFormPrevious": GrFormPrevious,
    "GrFormRefresh": GrFormRefresh,
    "GrFormSchedule": GrFormSchedule,
    "GrFormSearch": GrFormSearch,
    "GrFormSubtract": GrFormSubtract,
    "GrFormTrash": GrFormTrash,
    "GrFormUp": GrFormUp,
    "GrFormUpload": GrFormUpload,
    "GrFormViewHide": GrFormViewHide,
    "GrFormView": GrFormView,
    "GrForwardTen": GrForwardTen,
    "GrFreebsd": GrFreebsd,
    "GrGallery": GrGallery,
    "GrGamepad": GrGamepad,
    "GrGateway": GrGateway,
    "GrGatsbyjs": GrGatsbyjs,
    "GrGem": GrGem,
    "GrGift": GrGift,
    "GrGithub": GrGithub,
    "GrGlobe": GrGlobe,
    "GrGolang": GrGolang,
    "GrGooglePlay": GrGooglePlay,
    "GrGooglePlus": GrGooglePlus,
    "GrGoogleWallet": GrGoogleWallet,
    "GrGoogle": GrGoogle,
    "GrGraphQl": GrGraphQl,
    "GrGremlin": GrGremlin,
    "GrGrid": GrGrid,
    "GrGrommet": GrGrommet,
    "GrGroup": GrGroup,
    "GrGrow": GrGrow,
    "GrHadoop": GrHadoop,
    "GrHalt": GrHalt,
    "GrHelpOption": GrHelpOption,
    "GrHelp": GrHelp,
    "GrHeroku": GrHeroku,
    "GrHide": GrHide,
    "GrHistory": GrHistory,
    "GrHomeOption": GrHomeOption,
    "GrHomeRounded": GrHomeRounded,
    "GrHome": GrHome,
    "GrHorton": GrHorton,
    "GrHostMaintenance": GrHostMaintenance,
    "GrHost": GrHost,
    "GrHp": GrHp,
    "GrHpeLabs": GrHpeLabs,
    "GrHpe": GrHpe,
    "GrHpi": GrHpi,
    "GrHtml5": GrHtml5,
    "GrIceCream": GrIceCream,
    "GrImage": GrImage,
    "GrImpact": GrImpact,
    "GrInProgress": GrInProgress,
    "GrInbox": GrInbox,
    "GrIndicator": GrIndicator,
    "GrInfo": GrInfo,
    "GrInherit": GrInherit,
    "GrInsecure": GrInsecure,
    "GrInspect": GrInspect,
    "GrInstagram": GrInstagram,
    "GrInstallOption": GrInstallOption,
    "GrInstall": GrInstall,
    "GrIntegration": GrIntegration,
    "GrInternetExplorer": GrInternetExplorer,
    "GrItalic": GrItalic,
    "GrIteration": GrIteration,
    "GrJava": GrJava,
    "GrJs": GrJs,
    "GrKey": GrKey,
    "GrKeyboard": GrKeyboard,
    "GrLanguage": GrLanguage,
    "GrLastfm": GrLastfm,
    "GrLaunch": GrLaunch,
    "GrLayer": GrLayer,
    "GrLicense": GrLicense,
    "GrLike": GrLike,
    "GrLineChart": GrLineChart,
    "GrLinkBottom": GrLinkBottom,
    "GrLinkDown": GrLinkDown,
    "GrLinkNext": GrLinkNext,
    "GrLinkPrevious": GrLinkPrevious,
    "GrLinkTop": GrLinkTop,
    "GrLinkUp": GrLinkUp,
    "GrLink": GrLink,
    "GrLinkedinOption": GrLinkedinOption,
    "GrLinkedin": GrLinkedin,
    "GrList": GrList,
    "GrLocal": GrLocal,
    "GrLocationPin": GrLocationPin,
    "GrLocation": GrLocation,
    "GrLock": GrLock,
    "GrLogin": GrLogin,
    "GrLogout": GrLogout,
    "GrLounge": GrLounge,
    "GrMagic": GrMagic,
    "GrMailOption": GrMailOption,
    "GrMail": GrMail,
    "GrMandriva": GrMandriva,
    "GrManual": GrManual,
    "GrMapLocation": GrMapLocation,
    "GrMap": GrMap,
    "GrMastercard": GrMastercard,
    "GrMedium": GrMedium,
    "GrMemory": GrMemory,
    "GrMenu": GrMenu,
    "GrMicrofocus": GrMicrofocus,
    "GrMicrophone": GrMicrophone,
    "GrMoney": GrMoney,
    "GrMonitor": GrMonitor,
    "GrMonospace": GrMonospace,
    "GrMoon": GrMoon,
    "GrMoreVertical": GrMoreVertical,
    "GrMore": GrMore,
    "GrMouse": GrMouse,
    "GrMultimedia": GrMultimedia,
    "GrMultiple": GrMultiple,
    "GrMusic": GrMusic,
    "GrMysql": GrMysql,
    "GrNavigate": GrNavigate,
    "GrNetworkDrive": GrNetworkDrive,
    "GrNetwork": GrNetwork,
    "GrNewWindow": GrNewWindow,
    "GrNew": GrNew,
    "GrNext": GrNext,
    "GrNode": GrNode,
    "GrNodes": GrNodes,
    "GrNorton": GrNorton,
    "GrNote": GrNote,
    "GrNotes": GrNotes,
    "GrNotification": GrNotification,
    "GrNpm": GrNpm,
    "GrObjectGroup": GrObjectGroup,
    "GrObjectUngroup": GrObjectUngroup,
    "GrOfflineStorage": GrOfflineStorage,
    "GrOnedrive": GrOnedrive,
    "GrOpera": GrOpera,
    "GrOptimize": GrOptimize,
    "GrOracle": GrOracle,
    "GrOrderedList": GrOrderedList,
    "GrOrganization": GrOrganization,
    "GrOverview": GrOverview,
    "GrPackage": GrPackage,
    "GrPaint": GrPaint,
    "GrPan": GrPan,
    "GrPauseFill": GrPauseFill,
    "GrPause": GrPause,
    "GrPaypal": GrPaypal,
    "GrPerformance": GrPerformance,
    "GrPersonalComputer": GrPersonalComputer,
    "GrPhoneFlip": GrPhoneFlip,
    "GrPhoneHorizontal": GrPhoneHorizontal,
    "GrPhoneVertical": GrPhoneVertical,
    "GrPhone": GrPhone,
    "GrPieChart": GrPieChart,
    "GrPiedPiper": GrPiedPiper,
    "GrPin": GrPin,
    "GrPinterest": GrPinterest,
    "GrPlan": GrPlan,
    "GrPlayFill": GrPlayFill,
    "GrPlay": GrPlay,
    "GrPlug": GrPlug,
    "GrPocket": GrPocket,
    "GrPowerCycle": GrPowerCycle,
    "GrPowerForceShutdown": GrPowerForceShutdown,
    "GrPowerReset": GrPowerReset,
    "GrPowerShutdown": GrPowerShutdown,
    "GrPower": GrPower,
    "GrPrevious": GrPrevious,
    "GrPrint": GrPrint,
    "GrProductHunt": GrProductHunt,
    "GrProjects": GrProjects,
    "GrQr": GrQr,
    "GrRadialSelected": GrRadialSelected,
    "GrRadial": GrRadial,
    "GrRaspberry": GrRaspberry,
    "GrReactjs": GrReactjs,
    "GrReddit": GrReddit,
    "GrRedhat": GrRedhat,
    "GrRedo": GrRedo,
    "GrRefresh": GrRefresh,
    "GrResources": GrResources,
    "GrRestaurant": GrRestaurant,
    "GrRestroomMen": GrRestroomMen,
    "GrRestroomWomen": GrRestroomWomen,
    "GrRestroom": GrRestroom,
    "GrResume": GrResume,
    "GrReturn": GrReturn,
    "GrRevert": GrRevert,
    "GrRewind": GrRewind,
    "GrRisk": GrRisk,
    "GrRobot": GrRobot,
    "GrRotateLeft": GrRotateLeft,
    "GrRotateRight": GrRotateRight,
    "GrRss": GrRss,
    "GrRun": GrRun,
    "GrSafariOption": GrSafariOption,
    "GrSans": GrSans,
    "GrSatellite": GrSatellite,
    "GrSave": GrSave,
    "GrScan": GrScan,
    "GrScheduleNew": GrScheduleNew,
    "GrSchedulePlay": GrSchedulePlay,
    "GrSchedule": GrSchedule,
    "GrSchedules": GrSchedules,
    "GrSco": GrSco,
    "GrScorecard": GrScorecard,
    "GrScript": GrScript,
    "GrSd": GrSd,
    "GrSearchAdvanced": GrSearchAdvanced,
    "GrSearch": GrSearch,
    "GrSecure": GrSecure,
    "GrSelect": GrSelect,
    "GrSelection": GrSelection,
    "GrSemantics": GrSemantics,
    "GrSend": GrSend,
    "GrServerCluster": GrServerCluster,
    "GrServer": GrServer,
    "GrServers": GrServers,
    "GrServicePlay": GrServicePlay,
    "GrServices": GrServices,
    "GrSettingsOption": GrSettingsOption,
    "GrShareOption": GrShareOption,
    "GrShareRounded": GrShareRounded,
    "GrShare": GrShare,
    "GrShieldSecurity": GrShieldSecurity,
    "GrShield": GrShield,
    "GrShift": GrShift,
    "GrShop": GrShop,
    "GrSidebar": GrSidebar,
    "GrSign": GrSign,
    "GrSkype": GrSkype,
    "GrSlack": GrSlack,
    "GrSnapchat": GrSnapchat,
    "GrSolaris": GrSolaris,
    "GrSort": GrSort,
    "GrSoundcloud": GrSoundcloud,
    "GrSpa": GrSpa,
    "GrSpectrum": GrSpectrum,
    "GrSplit": GrSplit,
    "GrSplits": GrSplits,
    "GrSpotify": GrSpotify,
    "GrSquare": GrSquare,
    "GrStackOverflow": GrStackOverflow,
    "GrStakeholder": GrStakeholder,
    "GrStarHalf": GrStarHalf,
    "GrStar": GrStar,
    "GrStatusCriticalSmall": GrStatusCriticalSmall,
    "GrStatusCritical": GrStatusCritical,
    "GrStatusDisabledSmall": GrStatusDisabledSmall,
    "GrStatusDisabled": GrStatusDisabled,
    "GrStatusGoodSmall": GrStatusGoodSmall,
    "GrStatusGood": GrStatusGood,
    "GrStatusInfoSmall": GrStatusInfoSmall,
    "GrStatusInfo": GrStatusInfo,
    "GrStatusPlaceholderSmall": GrStatusPlaceholderSmall,
    "GrStatusPlaceholder": GrStatusPlaceholder,
    "GrStatusUnknownSmall": GrStatusUnknownSmall,
    "GrStatusUnknown": GrStatusUnknown,
    "GrStatusWarningSmall": GrStatusWarningSmall,
    "GrStatusWarning": GrStatusWarning,
    "GrStepsOption": GrStepsOption,
    "GrSteps": GrSteps,
    "GrStopFill": GrStopFill,
    "GrStop": GrStop,
    "GrStorage": GrStorage,
    "GrStreetView": GrStreetView,
    "GrStrikeThrough": GrStrikeThrough,
    "GrStripe": GrStripe,
    "GrSubscript": GrSubscript,
    "GrSubtractCircle": GrSubtractCircle,
    "GrSubtract": GrSubtract,
    "GrSun": GrSun,
    "GrSuperscript": GrSuperscript,
    "GrSupport": GrSupport,
    "GrSuse": GrSuse,
    "GrSwift": GrSwift,
    "GrSwim": GrSwim,
    "GrSwitch": GrSwitch,
    "GrSync": GrSync,
    "GrSystem": GrSystem,
    "GrTableAdd": GrTableAdd,
    "GrTable": GrTable,
    "GrTag": GrTag,
    "GrTapeOption": GrTapeOption,
    "GrTape": GrTape,
    "GrTarget": GrTarget,
    "GrTask": GrTask,
    "GrTasks": GrTasks,
    "GrTechnology": GrTechnology,
    "GrTemplate": GrTemplate,
    "GrTerminal": GrTerminal,
    "GrTestDesktop": GrTestDesktop,
    "GrTest": GrTest,
    "GrTextAlignCenter": GrTextAlignCenter,
    "GrTextAlignFull": GrTextAlignFull,
    "GrTextAlignLeft": GrTextAlignLeft,
    "GrTextAlignRight": GrTextAlignRight,
    "GrTextWrap": GrTextWrap,
    "GrThreats": GrThreats,
    "GrThreeDEffects": GrThreeDEffects,
    "GrThreeD": GrThreeD,
    "GrTicket": GrTicket,
    "GrTictok": GrTictok,
    "GrTime": GrTime,
    "GrTip": GrTip,
    "GrToast": GrToast,
    "GrTools": GrTools,
    "GrTooltip": GrTooltip,
    "GrTopCorner": GrTopCorner,
    "GrTrain": GrTrain,
    "GrTransaction": GrTransaction,
    "GrTrash": GrTrash,
    "GrTreeOption": GrTreeOption,
    "GrTree": GrTree,
    "GrTrigger": GrTrigger,
    "GrTrophy": GrTrophy,
    "GrTroubleshoot": GrTroubleshoot,
    "GrTty": GrTty,
    "GrTumblr": GrTumblr,
    "GrTurbolinux": GrTurbolinux,
    "GrTwitter": GrTwitter,
    "GrUbuntu": GrUbuntu,
    "GrUnderline": GrUnderline,
    "GrUndo": GrUndo,
    "GrUnlink": GrUnlink,
    "GrUnlock": GrUnlock,
    "GrUnorderedList": GrUnorderedList,
    "GrUnsorted": GrUnsorted,
    "GrUp": GrUp,
    "GrUpdate": GrUpdate,
    "GrUpgrade": GrUpgrade,
    "GrUploadOption": GrUploadOption,
    "GrUpload": GrUpload,
    "GrUsbKey": GrUsbKey,
    "GrUserAdd": GrUserAdd,
    "GrUserAdmin": GrUserAdmin,
    "GrUserExpert": GrUserExpert,
    "GrUserFemale": GrUserFemale,
    "GrUserManager": GrUserManager,
    "GrUserNew": GrUserNew,
    "GrUserPolice": GrUserPolice,
    "GrUserSettings": GrUserSettings,
    "GrUserWorker": GrUserWorker,
    "GrUser": GrUser,
    "GrValidate": GrValidate,
    "GrVend": GrVend,
    "GrVideo": GrVideo,
    "GrView": GrView,
    "GrVimeo": GrVimeo,
    "GrVirtualMachine": GrVirtualMachine,
    "GrVirtualStorage": GrVirtualStorage,
    "GrVisa": GrVisa,
    "GrVmMaintenance": GrVmMaintenance,
    "GrVmware": GrVmware,
    "GrVolumeControl": GrVolumeControl,
    "GrVolumeLow": GrVolumeLow,
    "GrVolumeMute": GrVolumeMute,
    "GrVolume": GrVolume,
    "GrVulnerability": GrVulnerability,
    "GrWaypoint": GrWaypoint,
    "GrWebcam": GrWebcam,
    "GrWheelchairActive": GrWheelchairActive,
    "GrWheelchair": GrWheelchair,
    "GrWifiLow": GrWifiLow,
    "GrWifiMedium": GrWifiMedium,
    "GrWifiNone": GrWifiNone,
    "GrWifi": GrWifi,
    "GrWindowsLegacy": GrWindowsLegacy,
    "GrWindows": GrWindows,
    "GrWordpress": GrWordpress,
    "GrWorkshop": GrWorkshop,
    "GrYoga": GrYoga,
    "GrYoutube": GrYoutube,
    "GrZoomIn": GrZoomIn,
    "GrZoomOut": GrZoomOut,
    "GrZoom": GrZoom,
}