import { HiAcademicCap,
    HiAdjustments,
    HiAnnotation,
    HiArchive,
    HiArrowCircleDown,
    HiArrowCircleLeft,
    HiArrowCircleRight,
    HiArrowCircleUp,
    HiArrowDown,
    HiArrowLeft,
    HiArrowNarrowDown,
    HiArrowNarrowLeft,
    HiArrowNarrowRight,
    HiArrowNarrowUp,
    HiArrowRight,
    HiArrowSmDown,
    HiArrowSmLeft,
    HiArrowSmRight,
    HiArrowSmUp,
    HiArrowUp,
    HiArrowsExpand,
    HiAtSymbol,
    HiBackspace,
    HiBadgeCheck,
    HiBan,
    HiBeaker,
    HiBell,
    HiBookOpen,
    HiBookmarkAlt,
    HiBookmark,
    HiBriefcase,
    HiCake,
    HiCalculator,
    HiCalendar,
    HiCamera,
    HiCash,
    HiChartBar,
    HiChartPie,
    HiChartSquareBar,
    HiChatAlt2,
    HiChatAlt,
    HiChat,
    HiCheckCircle,
    HiCheck,
    HiChevronDoubleDown,
    HiChevronDoubleLeft,
    HiChevronDoubleRight,
    HiChevronDoubleUp,
    HiChevronDown,
    HiChevronLeft,
    HiChevronRight,
    HiChevronUp,
    HiChip,
    HiClipboardCheck,
    HiClipboardCopy,
    HiClipboardList,
    HiClipboard,
    HiClock,
    HiCloudDownload,
    HiCloudUpload,
    HiCloud,
    HiCode,
    HiCog,
    HiCollection,
    HiColorSwatch,
    HiCreditCard,
    HiCubeTransparent,
    HiCube,
    HiCurrencyBangladeshi,
    HiCurrencyDollar,
    HiCurrencyEuro,
    HiCurrencyPound,
    HiCurrencyRupee,
    HiCurrencyYen,
    HiCursorClick,
    HiDatabase,
    HiDesktopComputer,
    HiDeviceMobile,
    HiDeviceTablet,
    HiDocumentAdd,
    HiDocumentDownload,
    HiDocumentDuplicate,
    HiDocumentRemove,
    HiDocumentReport,
    HiDocumentSearch,
    HiDocumentText,
    HiDocument,
    HiDotsCircleHorizontal,
    HiDotsHorizontal,
    HiDotsVertical,
    HiDownload,
    HiDuplicate,
    HiEmojiHappy,
    HiEmojiSad,
    HiExclamationCircle,
    HiExclamation,
    HiExternalLink,
    HiEyeOff,
    HiEye,
    HiFastForward,
    HiFilm,
    HiFilter,
    HiFingerPrint,
    HiFire,
    HiFlag,
    HiFolderAdd,
    HiFolderDownload,
    HiFolderOpen,
    HiFolderRemove,
    HiFolder,
    HiGift,
    HiGlobeAlt,
    HiGlobe,
    HiHand,
    HiHashtag,
    HiHeart,
    HiHome,
    HiIdentification,
    HiInboxIn,
    HiInbox,
    HiInformationCircle,
    HiKey,
    HiLibrary,
    HiLightBulb,
    HiLightningBolt,
    HiLink,
    HiLocationMarker,
    HiLockClosed,
    HiLockOpen,
    HiLogin,
    HiLogout,
    HiMailOpen,
    HiMail,
    HiMap,
    HiMenuAlt1,
    HiMenuAlt2,
    HiMenuAlt3,
    HiMenuAlt4,
    HiMenu,
    HiMicrophone,
    HiMinusCircle,
    HiMinusSm,
    HiMinus,
    HiMoon,
    HiMusicNote,
    HiNewspaper,
    HiOfficeBuilding,
    HiPaperAirplane,
    HiPaperClip,
    HiPause,
    HiPencilAlt,
    HiPencil,
    HiPhoneIncoming,
    HiPhoneMissedCall,
    HiPhoneOutgoing,
    HiPhone,
    HiPhotograph,
    HiPlay,
    HiPlusCircle,
    HiPlusSm,
    HiPlus,
    HiPresentationChartBar,
    HiPresentationChartLine,
    HiPrinter,
    HiPuzzle,
    HiQrcode,
    HiQuestionMarkCircle,
    HiReceiptRefund,
    HiReceiptTax,
    HiRefresh,
    HiReply,
    HiRewind,
    HiRss,
    HiSaveAs,
    HiSave,
    HiScale,
    HiScissors,
    HiSearchCircle,
    HiSearch,
    HiSelector,
    HiServer,
    HiShare,
    HiShieldCheck,
    HiShieldExclamation,
    HiShoppingBag,
    HiShoppingCart,
    HiSortAscending,
    HiSortDescending,
    HiSparkles,
    HiSpeakerphone,
    HiStar,
    HiStatusOffline,
    HiStatusOnline,
    HiStop,
    HiSun,
    HiSupport,
    HiSwitchHorizontal,
    HiSwitchVertical,
    HiTable,
    HiTag,
    HiTemplate,
    HiTerminal,
    HiThumbDown,
    HiThumbUp,
    HiTicket,
    HiTranslate,
    HiTrash,
    HiTrendingDown,
    HiTrendingUp,
    HiTruck,
    HiUpload,
    HiUserAdd,
    HiUserCircle,
    HiUserGroup,
    HiUserRemove,
    HiUser,
    HiUsers,
    HiVariable,
    HiVideoCamera,
    HiViewBoards,
    HiViewGridAdd,
    HiViewGrid,
    HiViewList,
    HiVolumeOff,
    HiVolumeUp,
    HiWifi,
    HiXCircle,
    HiX,
    HiZoomIn,
    HiZoomOut,
    HiOutlineAcademicCap,
    HiOutlineAdjustments,
    HiOutlineAnnotation,
    HiOutlineArchive,
    HiOutlineArrowCircleDown,
    HiOutlineArrowCircleLeft,
    HiOutlineArrowCircleRight,
    HiOutlineArrowCircleUp,
    HiOutlineArrowDown,
    HiOutlineArrowLeft,
    HiOutlineArrowNarrowDown,
    HiOutlineArrowNarrowLeft,
    HiOutlineArrowNarrowRight,
    HiOutlineArrowNarrowUp,
    HiOutlineArrowRight,
    HiOutlineArrowSmDown,
    HiOutlineArrowSmLeft,
    HiOutlineArrowSmRight,
    HiOutlineArrowSmUp,
    HiOutlineArrowUp,
    HiOutlineArrowsExpand,
    HiOutlineAtSymbol,
    HiOutlineBackspace,
    HiOutlineBadgeCheck,
    HiOutlineBan,
    HiOutlineBeaker,
    HiOutlineBell,
    HiOutlineBookOpen,
    HiOutlineBookmarkAlt,
    HiOutlineBookmark,
    HiOutlineBriefcase,
    HiOutlineCake,
    HiOutlineCalculator,
    HiOutlineCalendar,
    HiOutlineCamera,
    HiOutlineCash,
    HiOutlineChartBar,
    HiOutlineChartPie,
    HiOutlineChartSquareBar,
    HiOutlineChatAlt2,
    HiOutlineChatAlt,
    HiOutlineChat,
    HiOutlineCheckCircle,
    HiOutlineCheck,
    HiOutlineChevronDoubleDown,
    HiOutlineChevronDoubleLeft,
    HiOutlineChevronDoubleRight,
    HiOutlineChevronDoubleUp,
    HiOutlineChevronDown,
    HiOutlineChevronLeft,
    HiOutlineChevronRight,
    HiOutlineChevronUp,
    HiOutlineChip,
    HiOutlineClipboardCheck,
    HiOutlineClipboardCopy,
    HiOutlineClipboardList,
    HiOutlineClipboard,
    HiOutlineClock,
    HiOutlineCloudDownload,
    HiOutlineCloudUpload,
    HiOutlineCloud,
    HiOutlineCode,
    HiOutlineCog,
    HiOutlineCollection,
    HiOutlineColorSwatch,
    HiOutlineCreditCard,
    HiOutlineCubeTransparent,
    HiOutlineCube,
    HiOutlineCurrencyBangladeshi,
    HiOutlineCurrencyDollar,
    HiOutlineCurrencyEuro,
    HiOutlineCurrencyPound,
    HiOutlineCurrencyRupee,
    HiOutlineCurrencyYen,
    HiOutlineCursorClick,
    HiOutlineDatabase,
    HiOutlineDesktopComputer,
    HiOutlineDeviceMobile,
    HiOutlineDeviceTablet,
    HiOutlineDocumentAdd,
    HiOutlineDocumentDownload,
    HiOutlineDocumentDuplicate,
    HiOutlineDocumentRemove,
    HiOutlineDocumentReport,
    HiOutlineDocumentSearch,
    HiOutlineDocumentText,
    HiOutlineDocument,
    HiOutlineDotsCircleHorizontal,
    HiOutlineDotsHorizontal,
    HiOutlineDotsVertical,
    HiOutlineDownload,
    HiOutlineDuplicate,
    HiOutlineEmojiHappy,
    HiOutlineEmojiSad,
    HiOutlineExclamationCircle,
    HiOutlineExclamation,
    HiOutlineExternalLink,
    HiOutlineEyeOff,
    HiOutlineEye,
    HiOutlineFastForward,
    HiOutlineFilm,
    HiOutlineFilter,
    HiOutlineFingerPrint,
    HiOutlineFire,
    HiOutlineFlag,
    HiOutlineFolderAdd,
    HiOutlineFolderDownload,
    HiOutlineFolderOpen,
    HiOutlineFolderRemove,
    HiOutlineFolder,
    HiOutlineGift,
    HiOutlineGlobeAlt,
    HiOutlineGlobe,
    HiOutlineHand,
    HiOutlineHashtag,
    HiOutlineHeart,
    HiOutlineHome,
    HiOutlineIdentification,
    HiOutlineInboxIn,
    HiOutlineInbox,
    HiOutlineInformationCircle,
    HiOutlineKey,
    HiOutlineLibrary,
    HiOutlineLightBulb,
    HiOutlineLightningBolt,
    HiOutlineLink,
    HiOutlineLocationMarker,
    HiOutlineLockClosed,
    HiOutlineLockOpen,
    HiOutlineLogin,
    HiOutlineLogout,
    HiOutlineMailOpen,
    HiOutlineMail,
    HiOutlineMap,
    HiOutlineMenuAlt1,
    HiOutlineMenuAlt2,
    HiOutlineMenuAlt3,
    HiOutlineMenuAlt4,
    HiOutlineMenu,
    HiOutlineMicrophone,
    HiOutlineMinusCircle,
    HiOutlineMinusSm,
    HiOutlineMinus,
    HiOutlineMoon,
    HiOutlineMusicNote,
    HiOutlineNewspaper,
    HiOutlineOfficeBuilding,
    HiOutlinePaperAirplane,
    HiOutlinePaperClip,
    HiOutlinePause,
    HiOutlinePencilAlt,
    HiOutlinePencil,
    HiOutlinePhoneIncoming,
    HiOutlinePhoneMissedCall,
    HiOutlinePhoneOutgoing,
    HiOutlinePhone,
    HiOutlinePhotograph,
    HiOutlinePlay,
    HiOutlinePlusCircle,
    HiOutlinePlusSm,
    HiOutlinePlus,
    HiOutlinePresentationChartBar,
    HiOutlinePresentationChartLine,
    HiOutlinePrinter,
    HiOutlinePuzzle,
    HiOutlineQrcode,
    HiOutlineQuestionMarkCircle,
    HiOutlineReceiptRefund,
    HiOutlineReceiptTax,
    HiOutlineRefresh,
    HiOutlineReply,
    HiOutlineRewind,
    HiOutlineRss,
    HiOutlineSaveAs,
    HiOutlineSave,
    HiOutlineScale,
    HiOutlineScissors,
    HiOutlineSearchCircle,
    HiOutlineSearch,
    HiOutlineSelector,
    HiOutlineServer,
    HiOutlineShare,
    HiOutlineShieldCheck,
    HiOutlineShieldExclamation,
    HiOutlineShoppingBag,
    HiOutlineShoppingCart,
    HiOutlineSortAscending,
    HiOutlineSortDescending,
    HiOutlineSparkles,
    HiOutlineSpeakerphone,
    HiOutlineStar,
    HiOutlineStatusOffline,
    HiOutlineStatusOnline,
    HiOutlineStop,
    HiOutlineSun,
    HiOutlineSupport,
    HiOutlineSwitchHorizontal,
    HiOutlineSwitchVertical,
    HiOutlineTable,
    HiOutlineTag,
    HiOutlineTemplate,
    HiOutlineTerminal,
    HiOutlineThumbDown,
    HiOutlineThumbUp,
    HiOutlineTicket,
    HiOutlineTranslate,
    HiOutlineTrash,
    HiOutlineTrendingDown,
    HiOutlineTrendingUp,
    HiOutlineTruck,
    HiOutlineUpload,
    HiOutlineUserAdd,
    HiOutlineUserCircle,
    HiOutlineUserGroup,
    HiOutlineUserRemove,
    HiOutlineUser,
    HiOutlineUsers,
    HiOutlineVariable,
    HiOutlineVideoCamera,
    HiOutlineViewBoards,
    HiOutlineViewGridAdd,
    HiOutlineViewGrid,
    HiOutlineViewList,
    HiOutlineVolumeOff,
    HiOutlineVolumeUp,
    HiOutlineWifi,
    HiOutlineXCircle,
    HiOutlineX,
    HiOutlineZoomIn,
    HiOutlineZoomOut
 } from "react-icons/hi";

export const HeroIcons = {
    "HiAcademicCap": HiAcademicCap,
    "HiAdjustments": HiAdjustments,
    "HiAnnotation": HiAnnotation,
    "HiArchive": HiArchive,
    "HiArrowCircleDown": HiArrowCircleDown,
    "HiArrowCircleLeft": HiArrowCircleLeft,
    "HiArrowCircleRight": HiArrowCircleRight,
    "HiArrowCircleUp": HiArrowCircleUp,
    "HiArrowDown": HiArrowDown,
    "HiArrowLeft": HiArrowLeft,
    "HiArrowNarrowDown": HiArrowNarrowDown,
    "HiArrowNarrowLeft": HiArrowNarrowLeft,
    "HiArrowNarrowRight": HiArrowNarrowRight,
    "HiArrowNarrowUp": HiArrowNarrowUp,
    "HiArrowRight": HiArrowRight,
    "HiArrowSmDown": HiArrowSmDown,
    "HiArrowSmLeft": HiArrowSmLeft,
    "HiArrowSmRight": HiArrowSmRight,
    "HiArrowSmUp": HiArrowSmUp,
    "HiArrowUp": HiArrowUp,
    "HiArrowsExpand": HiArrowsExpand,
    "HiAtSymbol": HiAtSymbol,
    "HiBackspace": HiBackspace,
    "HiBadgeCheck": HiBadgeCheck,
    "HiBan": HiBan,
    "HiBeaker": HiBeaker,
    "HiBell": HiBell,
    "HiBookOpen": HiBookOpen,
    "HiBookmarkAlt": HiBookmarkAlt,
    "HiBookmark": HiBookmark,
    "HiBriefcase": HiBriefcase,
    "HiCake": HiCake,
    "HiCalculator": HiCalculator,
    "HiCalendar": HiCalendar,
    "HiCamera": HiCamera,
    "HiCash": HiCash,
    "HiChartBar": HiChartBar,
    "HiChartPie": HiChartPie,
    "HiChartSquareBar": HiChartSquareBar,
    "HiChatAlt2": HiChatAlt2,
    "HiChatAlt": HiChatAlt,
    "HiChat": HiChat,
    "HiCheckCircle": HiCheckCircle,
    "HiCheck": HiCheck,
    "HiChevronDoubleDown": HiChevronDoubleDown,
    "HiChevronDoubleLeft": HiChevronDoubleLeft,
    "HiChevronDoubleRight": HiChevronDoubleRight,
    "HiChevronDoubleUp": HiChevronDoubleUp,
    "HiChevronDown": HiChevronDown,
    "HiChevronLeft": HiChevronLeft,
    "HiChevronRight": HiChevronRight,
    "HiChevronUp": HiChevronUp,
    "HiChip": HiChip,
    "HiClipboardCheck": HiClipboardCheck,
    "HiClipboardCopy": HiClipboardCopy,
    "HiClipboardList": HiClipboardList,
    "HiClipboard": HiClipboard,
    "HiClock": HiClock,
    "HiCloudDownload": HiCloudDownload,
    "HiCloudUpload": HiCloudUpload,
    "HiCloud": HiCloud,
    "HiCode": HiCode,
    "HiCog": HiCog,
    "HiCollection": HiCollection,
    "HiColorSwatch": HiColorSwatch,
    "HiCreditCard": HiCreditCard,
    "HiCubeTransparent": HiCubeTransparent,
    "HiCube": HiCube,
    "HiCurrencyBangladeshi": HiCurrencyBangladeshi,
    "HiCurrencyDollar": HiCurrencyDollar,
    "HiCurrencyEuro": HiCurrencyEuro,
    "HiCurrencyPound": HiCurrencyPound,
    "HiCurrencyRupee": HiCurrencyRupee,
    "HiCurrencyYen": HiCurrencyYen,
    "HiCursorClick": HiCursorClick,
    "HiDatabase": HiDatabase,
    "HiDesktopComputer": HiDesktopComputer,
    "HiDeviceMobile": HiDeviceMobile,
    "HiDeviceTablet": HiDeviceTablet,
    "HiDocumentAdd": HiDocumentAdd,
    "HiDocumentDownload": HiDocumentDownload,
    "HiDocumentDuplicate": HiDocumentDuplicate,
    "HiDocumentRemove": HiDocumentRemove,
    "HiDocumentReport": HiDocumentReport,
    "HiDocumentSearch": HiDocumentSearch,
    "HiDocumentText": HiDocumentText,
    "HiDocument": HiDocument,
    "HiDotsCircleHorizontal": HiDotsCircleHorizontal,
    "HiDotsHorizontal": HiDotsHorizontal,
    "HiDotsVertical": HiDotsVertical,
    "HiDownload": HiDownload,
    "HiDuplicate": HiDuplicate,
    "HiEmojiHappy": HiEmojiHappy,
    "HiEmojiSad": HiEmojiSad,
    "HiExclamationCircle": HiExclamationCircle,
    "HiExclamation": HiExclamation,
    "HiExternalLink": HiExternalLink,
    "HiEyeOff": HiEyeOff,
    "HiEye": HiEye,
    "HiFastForward": HiFastForward,
    "HiFilm": HiFilm,
    "HiFilter": HiFilter,
    "HiFingerPrint": HiFingerPrint,
    "HiFire": HiFire,
    "HiFlag": HiFlag,
    "HiFolderAdd": HiFolderAdd,
    "HiFolderDownload": HiFolderDownload,
    "HiFolderOpen": HiFolderOpen,
    "HiFolderRemove": HiFolderRemove,
    "HiFolder": HiFolder,
    "HiGift": HiGift,
    "HiGlobeAlt": HiGlobeAlt,
    "HiGlobe": HiGlobe,
    "HiHand": HiHand,
    "HiHashtag": HiHashtag,
    "HiHeart": HiHeart,
    "HiHome": HiHome,
    "HiIdentification": HiIdentification,
    "HiInboxIn": HiInboxIn,
    "HiInbox": HiInbox,
    "HiInformationCircle": HiInformationCircle,
    "HiKey": HiKey,
    "HiLibrary": HiLibrary,
    "HiLightBulb": HiLightBulb,
    "HiLightningBolt": HiLightningBolt,
    "HiLink": HiLink,
    "HiLocationMarker": HiLocationMarker,
    "HiLockClosed": HiLockClosed,
    "HiLockOpen": HiLockOpen,
    "HiLogin": HiLogin,
    "HiLogout": HiLogout,
    "HiMailOpen": HiMailOpen,
    "HiMail": HiMail,
    "HiMap": HiMap,
    "HiMenuAlt1": HiMenuAlt1,
    "HiMenuAlt2": HiMenuAlt2,
    "HiMenuAlt3": HiMenuAlt3,
    "HiMenuAlt4": HiMenuAlt4,
    "HiMenu": HiMenu,
    "HiMicrophone": HiMicrophone,
    "HiMinusCircle": HiMinusCircle,
    "HiMinusSm": HiMinusSm,
    "HiMinus": HiMinus,
    "HiMoon": HiMoon,
    "HiMusicNote": HiMusicNote,
    "HiNewspaper": HiNewspaper,
    "HiOfficeBuilding": HiOfficeBuilding,
    "HiPaperAirplane": HiPaperAirplane,
    "HiPaperClip": HiPaperClip,
    "HiPause": HiPause,
    "HiPencilAlt": HiPencilAlt,
    "HiPencil": HiPencil,
    "HiPhoneIncoming": HiPhoneIncoming,
    "HiPhoneMissedCall": HiPhoneMissedCall,
    "HiPhoneOutgoing": HiPhoneOutgoing,
    "HiPhone": HiPhone,
    "HiPhotograph": HiPhotograph,
    "HiPlay": HiPlay,
    "HiPlusCircle": HiPlusCircle,
    "HiPlusSm": HiPlusSm,
    "HiPlus": HiPlus,
    "HiPresentationChartBar": HiPresentationChartBar,
    "HiPresentationChartLine": HiPresentationChartLine,
    "HiPrinter": HiPrinter,
    "HiPuzzle": HiPuzzle,
    "HiQrcode": HiQrcode,
    "HiQuestionMarkCircle": HiQuestionMarkCircle,
    "HiReceiptRefund": HiReceiptRefund,
    "HiReceiptTax": HiReceiptTax,
    "HiRefresh": HiRefresh,
    "HiReply": HiReply,
    "HiRewind": HiRewind,
    "HiRss": HiRss,
    "HiSaveAs": HiSaveAs,
    "HiSave": HiSave,
    "HiScale": HiScale,
    "HiScissors": HiScissors,
    "HiSearchCircle": HiSearchCircle,
    "HiSearch": HiSearch,
    "HiSelector": HiSelector,
    "HiServer": HiServer,
    "HiShare": HiShare,
    "HiShieldCheck": HiShieldCheck,
    "HiShieldExclamation": HiShieldExclamation,
    "HiShoppingBag": HiShoppingBag,
    "HiShoppingCart": HiShoppingCart,
    "HiSortAscending": HiSortAscending,
    "HiSortDescending": HiSortDescending,
    "HiSparkles": HiSparkles,
    "HiSpeakerphone": HiSpeakerphone,
    "HiStar": HiStar,
    "HiStatusOffline": HiStatusOffline,
    "HiStatusOnline": HiStatusOnline,
    "HiStop": HiStop,
    "HiSun": HiSun,
    "HiSupport": HiSupport,
    "HiSwitchHorizontal": HiSwitchHorizontal,
    "HiSwitchVertical": HiSwitchVertical,
    "HiTable": HiTable,
    "HiTag": HiTag,
    "HiTemplate": HiTemplate,
    "HiTerminal": HiTerminal,
    "HiThumbDown": HiThumbDown,
    "HiThumbUp": HiThumbUp,
    "HiTicket": HiTicket,
    "HiTranslate": HiTranslate,
    "HiTrash": HiTrash,
    "HiTrendingDown": HiTrendingDown,
    "HiTrendingUp": HiTrendingUp,
    "HiTruck": HiTruck,
    "HiUpload": HiUpload,
    "HiUserAdd": HiUserAdd,
    "HiUserCircle": HiUserCircle,
    "HiUserGroup": HiUserGroup,
    "HiUserRemove": HiUserRemove,
    "HiUser": HiUser,
    "HiUsers": HiUsers,
    "HiVariable": HiVariable,
    "HiVideoCamera": HiVideoCamera,
    "HiViewBoards": HiViewBoards,
    "HiViewGridAdd": HiViewGridAdd,
    "HiViewGrid": HiViewGrid,
    "HiViewList": HiViewList,
    "HiVolumeOff": HiVolumeOff,
    "HiVolumeUp": HiVolumeUp,
    "HiWifi": HiWifi,
    "HiXCircle": HiXCircle,
    "HiX": HiX,
    "HiZoomIn": HiZoomIn,
    "HiZoomOut": HiZoomOut,
    "HiOutlineAcademicCap": HiOutlineAcademicCap,
    "HiOutlineAdjustments": HiOutlineAdjustments,
    "HiOutlineAnnotation": HiOutlineAnnotation,
    "HiOutlineArchive": HiOutlineArchive,
    "HiOutlineArrowCircleDown": HiOutlineArrowCircleDown,
    "HiOutlineArrowCircleLeft": HiOutlineArrowCircleLeft,
    "HiOutlineArrowCircleRight": HiOutlineArrowCircleRight,
    "HiOutlineArrowCircleUp": HiOutlineArrowCircleUp,
    "HiOutlineArrowDown": HiOutlineArrowDown,
    "HiOutlineArrowLeft": HiOutlineArrowLeft,
    "HiOutlineArrowNarrowDown": HiOutlineArrowNarrowDown,
    "HiOutlineArrowNarrowLeft": HiOutlineArrowNarrowLeft,
    "HiOutlineArrowNarrowRight": HiOutlineArrowNarrowRight,
    "HiOutlineArrowNarrowUp": HiOutlineArrowNarrowUp,
    "HiOutlineArrowRight": HiOutlineArrowRight,
    "HiOutlineArrowSmDown": HiOutlineArrowSmDown,
    "HiOutlineArrowSmLeft": HiOutlineArrowSmLeft,
    "HiOutlineArrowSmRight": HiOutlineArrowSmRight,
    "HiOutlineArrowSmUp": HiOutlineArrowSmUp,
    "HiOutlineArrowUp": HiOutlineArrowUp,
    "HiOutlineArrowsExpand": HiOutlineArrowsExpand,
    "HiOutlineAtSymbol": HiOutlineAtSymbol,
    "HiOutlineBackspace": HiOutlineBackspace,
    "HiOutlineBadgeCheck": HiOutlineBadgeCheck,
    "HiOutlineBan": HiOutlineBan,
    "HiOutlineBeaker": HiOutlineBeaker,
    "HiOutlineBell": HiOutlineBell,
    "HiOutlineBookOpen": HiOutlineBookOpen,
    "HiOutlineBookmarkAlt": HiOutlineBookmarkAlt,
    "HiOutlineBookmark": HiOutlineBookmark,
    "HiOutlineBriefcase": HiOutlineBriefcase,
    "HiOutlineCake": HiOutlineCake,
    "HiOutlineCalculator": HiOutlineCalculator,
    "HiOutlineCalendar": HiOutlineCalendar,
    "HiOutlineCamera": HiOutlineCamera,
    "HiOutlineCash": HiOutlineCash,
    "HiOutlineChartBar": HiOutlineChartBar,
    "HiOutlineChartPie": HiOutlineChartPie,
    "HiOutlineChartSquareBar": HiOutlineChartSquareBar,
    "HiOutlineChatAlt2": HiOutlineChatAlt2,
    "HiOutlineChatAlt": HiOutlineChatAlt,
    "HiOutlineChat": HiOutlineChat,
    "HiOutlineCheckCircle": HiOutlineCheckCircle,
    "HiOutlineCheck": HiOutlineCheck,
    "HiOutlineChevronDoubleDown": HiOutlineChevronDoubleDown,
    "HiOutlineChevronDoubleLeft": HiOutlineChevronDoubleLeft,
    "HiOutlineChevronDoubleRight": HiOutlineChevronDoubleRight,
    "HiOutlineChevronDoubleUp": HiOutlineChevronDoubleUp,
    "HiOutlineChevronDown": HiOutlineChevronDown,
    "HiOutlineChevronLeft": HiOutlineChevronLeft,
    "HiOutlineChevronRight": HiOutlineChevronRight,
    "HiOutlineChevronUp": HiOutlineChevronUp,
    "HiOutlineChip": HiOutlineChip,
    "HiOutlineClipboardCheck": HiOutlineClipboardCheck,
    "HiOutlineClipboardCopy": HiOutlineClipboardCopy,
    "HiOutlineClipboardList": HiOutlineClipboardList,
    "HiOutlineClipboard": HiOutlineClipboard,
    "HiOutlineClock": HiOutlineClock,
    "HiOutlineCloudDownload": HiOutlineCloudDownload,
    "HiOutlineCloudUpload": HiOutlineCloudUpload,
    "HiOutlineCloud": HiOutlineCloud,
    "HiOutlineCode": HiOutlineCode,
    "HiOutlineCog": HiOutlineCog,
    "HiOutlineCollection": HiOutlineCollection,
    "HiOutlineColorSwatch": HiOutlineColorSwatch,
    "HiOutlineCreditCard": HiOutlineCreditCard,
    "HiOutlineCubeTransparent": HiOutlineCubeTransparent,
    "HiOutlineCube": HiOutlineCube,
    "HiOutlineCurrencyBangladeshi": HiOutlineCurrencyBangladeshi,
    "HiOutlineCurrencyDollar": HiOutlineCurrencyDollar,
    "HiOutlineCurrencyEuro": HiOutlineCurrencyEuro,
    "HiOutlineCurrencyPound": HiOutlineCurrencyPound,
    "HiOutlineCurrencyRupee": HiOutlineCurrencyRupee,
    "HiOutlineCurrencyYen": HiOutlineCurrencyYen,
    "HiOutlineCursorClick": HiOutlineCursorClick,
    "HiOutlineDatabase": HiOutlineDatabase,
    "HiOutlineDesktopComputer": HiOutlineDesktopComputer,
    "HiOutlineDeviceMobile": HiOutlineDeviceMobile,
    "HiOutlineDeviceTablet": HiOutlineDeviceTablet,
    "HiOutlineDocumentAdd": HiOutlineDocumentAdd,
    "HiOutlineDocumentDownload": HiOutlineDocumentDownload,
    "HiOutlineDocumentDuplicate": HiOutlineDocumentDuplicate,
    "HiOutlineDocumentRemove": HiOutlineDocumentRemove,
    "HiOutlineDocumentReport": HiOutlineDocumentReport,
    "HiOutlineDocumentSearch": HiOutlineDocumentSearch,
    "HiOutlineDocumentText": HiOutlineDocumentText,
    "HiOutlineDocument": HiOutlineDocument,
    "HiOutlineDotsCircleHorizontal": HiOutlineDotsCircleHorizontal,
    "HiOutlineDotsHorizontal": HiOutlineDotsHorizontal,
    "HiOutlineDotsVertical": HiOutlineDotsVertical,
    "HiOutlineDownload": HiOutlineDownload,
    "HiOutlineDuplicate": HiOutlineDuplicate,
    "HiOutlineEmojiHappy": HiOutlineEmojiHappy,
    "HiOutlineEmojiSad": HiOutlineEmojiSad,
    "HiOutlineExclamationCircle": HiOutlineExclamationCircle,
    "HiOutlineExclamation": HiOutlineExclamation,
    "HiOutlineExternalLink": HiOutlineExternalLink,
    "HiOutlineEyeOff": HiOutlineEyeOff,
    "HiOutlineEye": HiOutlineEye,
    "HiOutlineFastForward": HiOutlineFastForward,
    "HiOutlineFilm": HiOutlineFilm,
    "HiOutlineFilter": HiOutlineFilter,
    "HiOutlineFingerPrint": HiOutlineFingerPrint,
    "HiOutlineFire": HiOutlineFire,
    "HiOutlineFlag": HiOutlineFlag,
    "HiOutlineFolderAdd": HiOutlineFolderAdd,
    "HiOutlineFolderDownload": HiOutlineFolderDownload,
    "HiOutlineFolderOpen": HiOutlineFolderOpen,
    "HiOutlineFolderRemove": HiOutlineFolderRemove,
    "HiOutlineFolder": HiOutlineFolder,
    "HiOutlineGift": HiOutlineGift,
    "HiOutlineGlobeAlt": HiOutlineGlobeAlt,
    "HiOutlineGlobe": HiOutlineGlobe,
    "HiOutlineHand": HiOutlineHand,
    "HiOutlineHashtag": HiOutlineHashtag,
    "HiOutlineHeart": HiOutlineHeart,
    "HiOutlineHome": HiOutlineHome,
    "HiOutlineIdentification": HiOutlineIdentification,
    "HiOutlineInboxIn": HiOutlineInboxIn,
    "HiOutlineInbox": HiOutlineInbox,
    "HiOutlineInformationCircle": HiOutlineInformationCircle,
    "HiOutlineKey": HiOutlineKey,
    "HiOutlineLibrary": HiOutlineLibrary,
    "HiOutlineLightBulb": HiOutlineLightBulb,
    "HiOutlineLightningBolt": HiOutlineLightningBolt,
    "HiOutlineLink": HiOutlineLink,
    "HiOutlineLocationMarker": HiOutlineLocationMarker,
    "HiOutlineLockClosed": HiOutlineLockClosed,
    "HiOutlineLockOpen": HiOutlineLockOpen,
    "HiOutlineLogin": HiOutlineLogin,
    "HiOutlineLogout": HiOutlineLogout,
    "HiOutlineMailOpen": HiOutlineMailOpen,
    "HiOutlineMail": HiOutlineMail,
    "HiOutlineMap": HiOutlineMap,
    "HiOutlineMenuAlt1": HiOutlineMenuAlt1,
    "HiOutlineMenuAlt2": HiOutlineMenuAlt2,
    "HiOutlineMenuAlt3": HiOutlineMenuAlt3,
    "HiOutlineMenuAlt4": HiOutlineMenuAlt4,
    "HiOutlineMenu": HiOutlineMenu,
    "HiOutlineMicrophone": HiOutlineMicrophone,
    "HiOutlineMinusCircle": HiOutlineMinusCircle,
    "HiOutlineMinusSm": HiOutlineMinusSm,
    "HiOutlineMinus": HiOutlineMinus,
    "HiOutlineMoon": HiOutlineMoon,
    "HiOutlineMusicNote": HiOutlineMusicNote,
    "HiOutlineNewspaper": HiOutlineNewspaper,
    "HiOutlineOfficeBuilding": HiOutlineOfficeBuilding,
    "HiOutlinePaperAirplane": HiOutlinePaperAirplane,
    "HiOutlinePaperClip": HiOutlinePaperClip,
    "HiOutlinePause": HiOutlinePause,
    "HiOutlinePencilAlt": HiOutlinePencilAlt,
    "HiOutlinePencil": HiOutlinePencil,
    "HiOutlinePhoneIncoming": HiOutlinePhoneIncoming,
    "HiOutlinePhoneMissedCall": HiOutlinePhoneMissedCall,
    "HiOutlinePhoneOutgoing": HiOutlinePhoneOutgoing,
    "HiOutlinePhone": HiOutlinePhone,
    "HiOutlinePhotograph": HiOutlinePhotograph,
    "HiOutlinePlay": HiOutlinePlay,
    "HiOutlinePlusCircle": HiOutlinePlusCircle,
    "HiOutlinePlusSm": HiOutlinePlusSm,
    "HiOutlinePlus": HiOutlinePlus,
    "HiOutlinePresentationChartBar": HiOutlinePresentationChartBar,
    "HiOutlinePresentationChartLine": HiOutlinePresentationChartLine,
    "HiOutlinePrinter": HiOutlinePrinter,
    "HiOutlinePuzzle": HiOutlinePuzzle,
    "HiOutlineQrcode": HiOutlineQrcode,
    "HiOutlineQuestionMarkCircle": HiOutlineQuestionMarkCircle,
    "HiOutlineReceiptRefund": HiOutlineReceiptRefund,
    "HiOutlineReceiptTax": HiOutlineReceiptTax,
    "HiOutlineRefresh": HiOutlineRefresh,
    "HiOutlineReply": HiOutlineReply,
    "HiOutlineRewind": HiOutlineRewind,
    "HiOutlineRss": HiOutlineRss,
    "HiOutlineSaveAs": HiOutlineSaveAs,
    "HiOutlineSave": HiOutlineSave,
    "HiOutlineScale": HiOutlineScale,
    "HiOutlineScissors": HiOutlineScissors,
    "HiOutlineSearchCircle": HiOutlineSearchCircle,
    "HiOutlineSearch": HiOutlineSearch,
    "HiOutlineSelector": HiOutlineSelector,
    "HiOutlineServer": HiOutlineServer,
    "HiOutlineShare": HiOutlineShare,
    "HiOutlineShieldCheck": HiOutlineShieldCheck,
    "HiOutlineShieldExclamation": HiOutlineShieldExclamation,
    "HiOutlineShoppingBag": HiOutlineShoppingBag,
    "HiOutlineShoppingCart": HiOutlineShoppingCart,
    "HiOutlineSortAscending": HiOutlineSortAscending,
    "HiOutlineSortDescending": HiOutlineSortDescending,
    "HiOutlineSparkles": HiOutlineSparkles,
    "HiOutlineSpeakerphone": HiOutlineSpeakerphone,
    "HiOutlineStar": HiOutlineStar,
    "HiOutlineStatusOffline": HiOutlineStatusOffline,
    "HiOutlineStatusOnline": HiOutlineStatusOnline,
    "HiOutlineStop": HiOutlineStop,
    "HiOutlineSun": HiOutlineSun,
    "HiOutlineSupport": HiOutlineSupport,
    "HiOutlineSwitchHorizontal": HiOutlineSwitchHorizontal,
    "HiOutlineSwitchVertical": HiOutlineSwitchVertical,
    "HiOutlineTable": HiOutlineTable,
    "HiOutlineTag": HiOutlineTag,
    "HiOutlineTemplate": HiOutlineTemplate,
    "HiOutlineTerminal": HiOutlineTerminal,
    "HiOutlineThumbDown": HiOutlineThumbDown,
    "HiOutlineThumbUp": HiOutlineThumbUp,
    "HiOutlineTicket": HiOutlineTicket,
    "HiOutlineTranslate": HiOutlineTranslate,
    "HiOutlineTrash": HiOutlineTrash,
    "HiOutlineTrendingDown": HiOutlineTrendingDown,
    "HiOutlineTrendingUp": HiOutlineTrendingUp,
    "HiOutlineTruck": HiOutlineTruck,
    "HiOutlineUpload": HiOutlineUpload,
    "HiOutlineUserAdd": HiOutlineUserAdd,
    "HiOutlineUserCircle": HiOutlineUserCircle,
    "HiOutlineUserGroup": HiOutlineUserGroup,
    "HiOutlineUserRemove": HiOutlineUserRemove,
    "HiOutlineUser": HiOutlineUser,
    "HiOutlineUsers": HiOutlineUsers,
    "HiOutlineVariable": HiOutlineVariable,
    "HiOutlineVideoCamera": HiOutlineVideoCamera,
    "HiOutlineViewBoards": HiOutlineViewBoards,
    "HiOutlineViewGridAdd": HiOutlineViewGridAdd,
    "HiOutlineViewGrid": HiOutlineViewGrid,
    "HiOutlineViewList": HiOutlineViewList,
    "HiOutlineVolumeOff": HiOutlineVolumeOff,
    "HiOutlineVolumeUp": HiOutlineVolumeUp,
    "HiOutlineWifi": HiOutlineWifi,
    "HiOutlineXCircle": HiOutlineXCircle,
    "HiOutlineX": HiOutlineX,
    "HiOutlineZoomIn": HiOutlineZoomIn,
    "HiOutlineZoomOut": HiOutlineZoomOut
}