//import { 
//    HiAcademicCap,
//HiAdjustmentsHorizontal,
//HiAdjustmentsVertical,
//HiArchiveBoxArrowDown,
//HiArchiveBoxXMark,
//HiArchiveBox,
//HiArrowDownCircle,
//HiArrowDownLeft,
//HiArrowDownOnSquareStack,
//HiArrowDownOnSquare,
//HiArrowDownRight,
//HiArrowDownTray,
//HiArrowDown,
//HiArrowLeftCircle,
//HiArrowLeftOnRectangle,
//HiArrowLeft,
//HiArrowLongDown,
//HiArrowLongLeft,
//HiArrowLongRight,
//HiArrowLongUp,
//HiArrowPath,
//HiArrowRightCircle,
//HiArrowRightOnRectangle,
//HiArrowRight,
//HiArrowTopRightOnSquare,
//HiArrowTrendingDown,
//HiArrowTrendingUp,
//HiArrowUpCircle,
//HiArrowUpLeft,
//HiArrowUpOnSquareStack,
//HiArrowUpOnSquare,
//HiArrowUpRight,
//HiArrowUpTray,
//HiArrowUp,
//HiArrowUturnDown,
//HiArrowUturnLeft,
//HiArrowUturnRight,
//HiArrowUturnUp,
//HiArrowsPointingIn,
//HiArrowsPointingOut,
//HiArrowsRightLeft,
//HiArrowsUpDown,
//HiAtSymbol,
//HiBackspace,
//HiBackward,
//HiBanknotes,
//HiBars2,
//HiBars3BottomLeft,
//HiBars3BottomRight,
//HiBars3CenterLeft,
//HiBars3,
//HiBars4,
//HiBarsArrowDown,
//HiBarsArrowUp,
//HiBeaker,
//HiBellAlert,
//HiBellSlash,
//HiBellSnooze,
//HiBell,
//HiBoltSlash,
//HiBolt,
//HiBookOpen,
//HiBookmarkSlash,
//HiBookmarkSquare,
//HiBookmark,
//HiBriefcase,
//HiBuildingLibrary,
//HiBuildingOffice2,
//HiBuildingOffice,
//HiBuildingStorefront,
//HiCake,
//HiCalculator,
//HiCalendarDays,
//HiCalendar,
//HiCamera,
//HiChartBarSquare,
//HiChartBar,
//HiChartPie,
//HiChatBubbleBottomCenterText,
//HiChatBubbleBottomCenter,
//HiChatBubbleLeftEllipsis,
//HiChatBubbleLeftRight,
//HiChatBubbleLeft,
//HiChatBubbleOvalLeftEllipsis,
//HiChatBubbleOvalLeft,
//HiCheckBadge,
//HiCheckCircle,
//HiCheck,
//HiChevronDoubleDown,
//HiChevronDoubleLeft,
//HiChevronDoubleRight,
//HiChevronDoubleUp,
//HiChevronDown,
//HiChevronLeft,
//HiChevronRight,
//HiChevronUpDown,
//HiChevronUp,
//HiCircleStack,
//HiClipboardDocumentCheck,
//HiClipboardDocumentList,
//HiClipboardDocument,
//HiClipboard,
//HiClock,
//HiCloudArrowDown,
//HiCloudArrowUp,
//HiCloud,
//HiCodeBracketSquare,
//HiCodeBracket,
//HiCog6Tooth,
//HiCog8Tooth,
//HiCog,
//HiCommandLine,
//HiComputerDesktop,
//HiCpuChip,
//HiCreditCard,
//HiCube,
//HiCurrencyDollar,
//HiCurrencyEuro,
//HiCurrencyPound,
//HiCurrencyRupee,
//HiCurrencyYen,
//HiCursorArrowRays,
//HiCursorArrowRipple,
//HiDevicePhoneMobile,
//HiDeviceTablet,
//HiDocumentArrowDown,
//HiDocumentArrowUp,
//HiDocumentChartBar,
//HiDocumentCheck,
//HiDocumentDuplicate,
//HiDocumentMagnifyingGlass,
//HiDocumentMinus,
//HiDocumentPlus,
//HiDocumentText,
//HiDocument,
//HiEllipsisHorizontalCircle,
//HiEllipsisHorizontal,
//HiEllipsisVertical,
//HiEnvelopeOpen,
//HiEnvelope,
//HiExclamationCircle,
//HiExclamationTriangle,
//HiEyeSlash,
//HiEye,
//HiFaceFrown,
//HiFaceSmile,
//HiFilm,
//HiFingerPrint,
//HiFire,
//HiFlag,
//HiFolderArrowDown,
//HiFolderMinus,
//HiFolderOpen,
//HiFolderPlus,
//HiFolder,
//HiForward,
//HiFunnel,
//HiGif,
//HiGiftTop,
//HiGift,
//HiGlobeAlt,
//HiGlobeAmericas,
//HiGlobeAsiaAustralia,
//HiGlobeEuropeAfrica,
//HiHandRaised,
//HiHandThumbDown,
//HiHandThumbUp,
//HiHashtag,
//HiHeart,
//HiHomeModern,
//HiHome,
//HiIdentification,
//HiInboxArrowDown,
//HiInboxStack,
//HiInbox,
//HiInformationCircle,
//HiKey,
//HiLanguage,
//HiLifebuoy,
//HiLightBulb,
//HiLink,
//HiListBullet,
//HiLockClosed,
//HiLockOpen,
//HiMagnifyingGlassCircle,
//HiMagnifyingGlassMinus,
//HiMagnifyingGlassPlus,
//HiMagnifyingGlass,
//HiMapPin,
//HiMap,
//HiMegaphone,
//HiMicrophone,
//HiMinusCircle,
//HiMinus,
//HiMoon,
//HiMusicalNote,
//HiNewspaper,
//HiNoSymbol,
//HiPaperAirplane,
//HiPaperClip,
//HiPause,
//HiPencilSquare,
//HiPencil,
//HiPhoneArrowDownLeft,
//HiPhoneArrowUpRight,
//HiPhoneXMark,
//HiPhone,
//HiPhoto,
//HiPlayPause,
//HiPlay,
//HiPlusCircle,
//HiPlus,
//HiPresentationChartBar,
//HiPresentationChartLine,
//HiPrinter,
//HiPuzzlePiece,
//HiQrCode,
//HiQuestionMarkCircle,
//HiQueueList,
//HiRadio,
//HiReceiptPercent,
//HiReceiptRefund,
//HiRectangleGroup,
//HiRectangleStack,
//HiRss,
//HiScale,
//HiScissors,
//HiServerStack,
//HiServer,
//HiShare,
//HiShieldCheck,
//HiShieldExclamation,
//HiShoppingBag,
//HiShoppingCart,
//HiSignalSlash,
//HiSignal,
//HiSparkles,
//HiSpeakerWave,
//HiSpeakerXMark,
//HiSquare2Stack,
//HiSquares2X2,
//HiSquaresPlus,
//HiStar,
//HiStop,
//HiSun,
//HiSwatch,
//HiTableCells,
//HiTag,
//HiTicket,
//HiTrash,
//HiTruck,
//HiUserCircle,
//HiUserGroup,
//HiUserMinus,
//HiUserPlus,
//HiUser,
//HiUsers,
//HiVideoCameraSlash,
//HiVideoCamera,
//HiViewColumns,
//HiWifi,
//HiWrenchScrewdriver,
//HiWrench,
//HiXCircle,
//HiXMark,
//HiOutlineAcademicCap,
//HiOutlineAdjustmentsHorizontal,
//HiOutlineAdjustmentsVertical,
//HiOutlineArchiveBoxArrowDown,
//HiOutlineArchiveBoxXMark,
//HiOutlineArchiveBox,
//HiOutlineArrowDownCircle,
//HiOutlineArrowDownLeft,
//HiOutlineArrowDownOnSquareStack,
//HiOutlineArrowDownOnSquare,
//HiOutlineArrowDownRight,
//HiOutlineArrowDownTray,
//HiOutlineArrowDown,
//HiOutlineArrowLeftCircle,
//HiOutlineArrowLeftOnRectangle,
//HiOutlineArrowLeft,
//HiOutlineArrowLongDown,
//HiOutlineArrowLongLeft,
//HiOutlineArrowLongRight,
//HiOutlineArrowLongUp,
//HiOutlineArrowPath,
//HiOutlineArrowRightCircle,
//HiOutlineArrowRightOnRectangle,
//HiOutlineArrowRight,
//HiOutlineArrowTopRightOnSquare,
//HiOutlineArrowTrendingDown,
//HiOutlineArrowTrendingUp,
//HiOutlineArrowUpCircle,
//HiOutlineArrowUpLeft,
//HiOutlineArrowUpOnSquareStack,
//HiOutlineArrowUpOnSquare,
//HiOutlineArrowUpRight,
//HiOutlineArrowUpTray,
//HiOutlineArrowUp,
//HiOutlineArrowUturnDown,
//HiOutlineArrowUturnLeft,
//HiOutlineArrowUturnRight,
//HiOutlineArrowUturnUp,
//HiOutlineArrowsPointingIn,
//HiOutlineArrowsPointingOut,
//HiOutlineArrowsRightLeft,
//HiOutlineArrowsUpDown,
//HiOutlineAtSymbol,
//HiOutlineBackspace,
//HiOutlineBackward,
//HiOutlineBanknotes,
//HiOutlineBars2,
//HiOutlineBars3BottomLeft,
//HiOutlineBars3BottomRight,
//HiOutlineBars3CenterLeft,
//HiOutlineBars3,
//HiOutlineBars4,
//HiOutlineBarsArrowDown,
//HiOutlineBarsArrowUp,
//HiOutlineBeaker,
//HiOutlineBellAlert,
//HiOutlineBellSlash,
//HiOutlineBellSnooze,
//HiOutlineBell,
//HiOutlineBoltSlash,
//HiOutlineBolt,
//HiOutlineBookOpen,
//HiOutlineBookmarkSlash,
//HiOutlineBookmarkSquare,
//HiOutlineBookmark,
//HiOutlineBriefcase,
//HiOutlineBuildingLibrary,
//HiOutlineBuildingOffice2,
//HiOutlineBuildingOffice,
//HiOutlineBuildingStorefront,
//HiOutlineCake,
//HiOutlineCalculator,
//HiOutlineCalendarDays,
//HiOutlineCalendar,
//HiOutlineCamera,
//HiOutlineChartBarSquare,
//HiOutlineChartBar,
//HiOutlineChartPie,
//HiOutlineChatBubbleBottomCenterText,
//HiOutlineChatBubbleBottomCenter,
//HiOutlineChatBubbleLeftEllipsis,
//HiOutlineChatBubbleLeftRight,
//HiOutlineChatBubbleLeft,
//HiOutlineChatBubbleOvalLeftEllipsis,
//HiOutlineChatBubbleOvalLeft,
//HiOutlineCheckBadge,
//HiOutlineCheckCircle,
//HiOutlineCheck,
//HiOutlineChevronDoubleDown,
//HiOutlineChevronDoubleLeft,
//HiOutlineChevronDoubleRight,
//HiOutlineChevronDoubleUp,
//HiOutlineChevronDown,
//HiOutlineChevronLeft,
//HiOutlineChevronRight,
//HiOutlineChevronUpDown,
//HiOutlineChevronUp,
//HiOutlineCircleStack,
//HiOutlineClipboardDocumentCheck,
//HiOutlineClipboardDocumentList,
//HiOutlineClipboardDocument,
//HiOutlineClipboard,
//HiOutlineClock,
//HiOutlineCloudArrowDown,
//HiOutlineCloudArrowUp,
//HiOutlineCloud,
//HiOutlineCodeBracketSquare,
//HiOutlineCodeBracket,
//HiOutlineCog6Tooth,
//HiOutlineCog8Tooth,
//HiOutlineCog,
//HiOutlineCommandLine,
//HiOutlineComputerDesktop,
//HiOutlineCpuChip,
//HiOutlineCreditCard,
//HiOutlineCube,
//HiOutlineCurrencyDollar,
//HiOutlineCurrencyEuro,
//HiOutlineCurrencyPound,
//HiOutlineCurrencyRupee,
//HiOutlineCurrencyYen,
//HiOutlineCursorArrowRays,
//HiOutlineCursorArrowRipple,
//HiOutlineDevicePhoneMobile,
//HiOutlineDeviceTablet,
//HiOutlineDocumentArrowDown,
//HiOutlineDocumentArrowUp,
//HiOutlineDocumentChartBar,
//HiOutlineDocumentCheck,
//HiOutlineDocumentDuplicate,
//HiOutlineDocumentMagnifyingGlass,
//HiOutlineDocumentMinus,
//HiOutlineDocumentPlus,
//HiOutlineDocumentText,
//HiOutlineDocument,
//HiOutlineEllipsisHorizontalCircle,
//HiOutlineEllipsisHorizontal,
//HiOutlineEllipsisVertical,
//HiOutlineEnvelopeOpen,
//HiOutlineEnvelope,
//HiOutlineExclamationCircle,
//HiOutlineExclamationTriangle,
//HiOutlineEyeSlash,
//HiOutlineEye,
//HiOutlineFaceFrown,
//HiOutlineFaceSmile,
//HiOutlineFilm,
//HiOutlineFingerPrint,
//HiOutlineFire,
//HiOutlineFlag,
//HiOutlineFolderArrowDown,
//HiOutlineFolderMinus,
//HiOutlineFolderOpen,
//HiOutlineFolderPlus,
//HiOutlineFolder,
//HiOutlineForward,
//HiOutlineFunnel,
//HiOutlineGif,
//HiOutlineGiftTop,
//HiOutlineGift,
//HiOutlineGlobeAlt,
//HiOutlineGlobeAmericas,
//HiOutlineGlobeAsiaAustralia,
//HiOutlineGlobeEuropeAfrica,
//HiOutlineHandRaised,
//HiOutlineHandThumbDown,
//HiOutlineHandThumbUp,
//HiOutlineHashtag,
//HiOutlineHeart,
//HiOutlineHomeModern,
//HiOutlineHome,
//HiOutlineIdentification,
//HiOutlineInboxArrowDown,
//HiOutlineInboxStack,
//HiOutlineInbox,
//HiOutlineInformationCircle,
//HiOutlineKey,
//HiOutlineLanguage,
//HiOutlineLifebuoy,
//HiOutlineLightBulb,
//HiOutlineLink,
//HiOutlineListBullet,
//HiOutlineLockClosed,
//HiOutlineLockOpen,
//HiOutlineMagnifyingGlassCircle,
//HiOutlineMagnifyingGlassMinus,
//HiOutlineMagnifyingGlassPlus,
//HiOutlineMagnifyingGlass,
//HiOutlineMapPin,
//HiOutlineMap,
//HiOutlineMegaphone,
//HiOutlineMicrophone,
//HiOutlineMinusCircle,
//HiOutlineMinus,
//HiOutlineMoon,
//HiOutlineMusicalNote,
//HiOutlineNewspaper,
//HiOutlineNoSymbol,
//HiOutlinePaperAirplane,
//HiOutlinePaperClip,
//HiOutlinePause,
//HiOutlinePencilSquare,
//HiOutlinePencil,
//HiOutlinePhoneArrowDownLeft,
//HiOutlinePhoneArrowUpRight,
//HiOutlinePhoneXMark,
//HiOutlinePhone,
//HiOutlinePhoto,
//HiOutlinePlayPause,
//HiOutlinePlay,
//HiOutlinePlusCircle,
//HiOutlinePlus,
//HiOutlinePresentationChartBar,
//HiOutlinePresentationChartLine,
//HiOutlinePrinter,
//HiOutlinePuzzlePiece,
//HiOutlineQrCode,
//HiOutlineQuestionMarkCircle,
//HiOutlineQueueList,
//HiOutlineRadio,
//HiOutlineReceiptPercent,
//HiOutlineReceiptRefund,
//HiOutlineRectangleGroup,
//HiOutlineRectangleStack,
//HiOutlineRss,
//HiOutlineScale,
//HiOutlineScissors,
//HiOutlineServerStack,
//HiOutlineServer,
//HiOutlineShare,
//HiOutlineShieldCheck,
//HiOutlineShieldExclamation,
//HiOutlineShoppingBag,
//HiOutlineShoppingCart,
//HiOutlineSignalSlash,
//HiOutlineSignal,
//HiOutlineSparkles,
//HiOutlineSpeakerWave,
//HiOutlineSpeakerXMark,
//HiOutlineSquare2Stack,
//HiOutlineSquares2X2,
//HiOutlineSquaresPlus,
//HiOutlineStar,
//HiOutlineStop,
//HiOutlineSun,
//HiOutlineSwatch,
//HiOutlineTableCells,
//HiOutlineTag,
//HiOutlineTicket,
//HiOutlineTrash,
//HiOutlineTruck,
//HiOutlineUserCircle,
//HiOutlineUserGroup,
//HiOutlineUserMinus,
//HiOutlineUserPlus,
//HiOutlineUser,
//HiOutlineUsers,
//HiOutlineVideoCameraSlash,
//HiOutlineVideoCamera,
//HiOutlineViewColumns,
//HiOutlineWifi,
//HiOutlineWrenchScrewdriver,
//HiOutlineWrench,
//HiOutlineXCircle,
//HiOutlineXMark
// } from "react-icons/hi2";

//export const HeroIcons2 = {
//    "HiAcademicCap": HiAcademicCap,
//    "HiAdjustmentsHorizontal": HiAdjustmentsHorizontal,
//    "HiAdjustmentsVertical": HiAdjustmentsVertical,
//    "HiArchiveBoxArrowDown": HiArchiveBoxArrowDown,
//    "HiArchiveBoxXMark": HiArchiveBoxXMark,
//    "HiArchiveBox": HiArchiveBox,
//    "HiArrowDownCircle": HiArrowDownCircle,
//    "HiArrowDownLeft": HiArrowDownLeft,
//    "HiArrowDownOnSquareStack": HiArrowDownOnSquareStack,
//    "HiArrowDownOnSquare": HiArrowDownOnSquare,
//    "HiArrowDownRight": HiArrowDownRight,
//    "HiArrowDownTray": HiArrowDownTray,
//    "HiArrowDown": HiArrowDown,
//    "HiArrowLeftCircle": HiArrowLeftCircle,
//    "HiArrowLeftOnRectangle": HiArrowLeftOnRectangle,
//    "HiArrowLeft": HiArrowLeft,
//    "HiArrowLongDown": HiArrowLongDown,
//    "HiArrowLongLeft": HiArrowLongLeft,
//    "HiArrowLongRight": HiArrowLongRight,
//    "HiArrowLongUp": HiArrowLongUp,
//    "HiArrowPath": HiArrowPath,
//    "HiArrowRightCircle": HiArrowRightCircle,
//    "HiArrowRightOnRectangle": HiArrowRightOnRectangle,
//    "HiArrowRight": HiArrowRight,
//    "HiArrowTopRightOnSquare": HiArrowTopRightOnSquare,
//    "HiArrowTrendingDown": HiArrowTrendingDown,
//    "HiArrowTrendingUp": HiArrowTrendingUp,
//    "HiArrowUpCircle": HiArrowUpCircle,
//    "HiArrowUpLeft": HiArrowUpLeft,
//    "HiArrowUpOnSquareStack": HiArrowUpOnSquareStack,
//    "HiArrowUpOnSquare": HiArrowUpOnSquare,
//    "HiArrowUpRight": HiArrowUpRight,
//    "HiArrowUpTray": HiArrowUpTray,
//    "HiArrowUp": HiArrowUp,
//    "HiArrowUturnDown": HiArrowUturnDown,
//    "HiArrowUturnLeft": HiArrowUturnLeft,
//    "HiArrowUturnRight": HiArrowUturnRight,
//    "HiArrowUturnUp": HiArrowUturnUp,
//    "HiArrowsPointingIn": HiArrowsPointingIn,
//    "HiArrowsPointingOut": HiArrowsPointingOut,
//    "HiArrowsRightLeft": HiArrowsRightLeft,
//    "HiArrowsUpDown": HiArrowsUpDown,
//    "HiAtSymbol": HiAtSymbol,
//    "HiBackspace": HiBackspace,
//    "HiBackward": HiBackward,
//    "HiBanknotes": HiBanknotes,
//    "HiBars2": HiBars2,
//    "HiBars3BottomLeft": HiBars3BottomLeft,
//    "HiBars3BottomRight": HiBars3BottomRight,
//    "HiBars3CenterLeft": HiBars3CenterLeft,
//    "HiBars3": HiBars3,
//    "HiBars4": HiBars4,
//    "HiBarsArrowDown": HiBarsArrowDown,
//    "HiBarsArrowUp": HiBarsArrowUp,
//    "HiBeaker": HiBeaker,
//    "HiBellAlert": HiBellAlert,
//    "HiBellSlash": HiBellSlash,
//    "HiBellSnooze": HiBellSnooze,
//    "HiBell": HiBell,
//    "HiBoltSlash": HiBoltSlash,
//    "HiBolt": HiBolt,
//    "HiBookOpen": HiBookOpen,
//    "HiBookmarkSlash": HiBookmarkSlash,
//    "HiBookmarkSquare": HiBookmarkSquare,
//    "HiBookmark": HiBookmark,
//    "HiBriefcase": HiBriefcase,
//    "HiBuildingLibrary": HiBuildingLibrary,
//    "HiBuildingOffice2": HiBuildingOffice2,
//    "HiBuildingOffice": HiBuildingOffice,
//    "HiBuildingStorefront": HiBuildingStorefront,
//    "HiCake": HiCake,
//    "HiCalculator": HiCalculator,
//    "HiCalendarDays": HiCalendarDays,
//    "HiCalendar": HiCalendar,
//    "HiCamera": HiCamera,
//    "HiChartBarSquare": HiChartBarSquare,
//    "HiChartBar": HiChartBar,
//    "HiChartPie": HiChartPie,
//    "HiChatBubbleBottomCenterText": HiChatBubbleBottomCenterText,
//    "HiChatBubbleBottomCenter": HiChatBubbleBottomCenter,
//    "HiChatBubbleLeftEllipsis": HiChatBubbleLeftEllipsis,
//    "HiChatBubbleLeftRight": HiChatBubbleLeftRight,
//    "HiChatBubbleLeft": HiChatBubbleLeft,
//    "HiChatBubbleOvalLeftEllipsis": HiChatBubbleOvalLeftEllipsis,
//    "HiChatBubbleOvalLeft": HiChatBubbleOvalLeft,
//    "HiCheckBadge": HiCheckBadge,
//    "HiCheckCircle": HiCheckCircle,
//    "HiCheck": HiCheck,
//    "HiChevronDoubleDown": HiChevronDoubleDown,
//    "HiChevronDoubleLeft": HiChevronDoubleLeft,
//    "HiChevronDoubleRight": HiChevronDoubleRight,
//    "HiChevronDoubleUp": HiChevronDoubleUp,
//    "HiChevronDown": HiChevronDown,
//    "HiChevronLeft": HiChevronLeft,
//    "HiChevronRight": HiChevronRight,
//    "HiChevronUpDown": HiChevronUpDown,
//    "HiChevronUp": HiChevronUp,
//    "HiCircleStack": HiCircleStack,
//    "HiClipboardDocumentCheck": HiClipboardDocumentCheck,
//    "HiClipboardDocumentList": HiClipboardDocumentList,
//    "HiClipboardDocument": HiClipboardDocument,
//    "HiClipboard": HiClipboard,
//    "HiClock": HiClock,
//    "HiCloudArrowDown": HiCloudArrowDown,
//    "HiCloudArrowUp": HiCloudArrowUp,
//    "HiCloud": HiCloud,
//    "HiCodeBracketSquare": HiCodeBracketSquare,
//    "HiCodeBracket": HiCodeBracket,
//    "HiCog6Tooth": HiCog6Tooth,
//    "HiCog8Tooth": HiCog8Tooth,
//    "HiCog": HiCog,
//    "HiCommandLine": HiCommandLine,
//    "HiComputerDesktop": HiComputerDesktop,
//    "HiCpuChip": HiCpuChip,
//    "HiCreditCard": HiCreditCard,
//    "HiCube": HiCube,
//    "HiCurrencyDollar": HiCurrencyDollar,
//    "HiCurrencyEuro": HiCurrencyEuro,
//    "HiCurrencyPound": HiCurrencyPound,
//    "HiCurrencyRupee": HiCurrencyRupee,
//    "HiCurrencyYen": HiCurrencyYen,
//    "HiCursorArrowRays": HiCursorArrowRays,
//    "HiCursorArrowRipple": HiCursorArrowRipple,
//    "HiDevicePhoneMobile": HiDevicePhoneMobile,
//    "HiDeviceTablet": HiDeviceTablet,
//    "HiDocumentArrowDown": HiDocumentArrowDown,
//    "HiDocumentArrowUp": HiDocumentArrowUp,
//    "HiDocumentChartBar": HiDocumentChartBar,
//    "HiDocumentCheck": HiDocumentCheck,
//    "HiDocumentDuplicate": HiDocumentDuplicate,
//    "HiDocumentMagnifyingGlass": HiDocumentMagnifyingGlass,
//    "HiDocumentMinus": HiDocumentMinus,
//    "HiDocumentPlus": HiDocumentPlus,
//    "HiDocumentText": HiDocumentText,
//    "HiDocument": HiDocument,
//    "HiEllipsisHorizontalCircle": HiEllipsisHorizontalCircle,
//    "HiEllipsisHorizontal": HiEllipsisHorizontal,
//    "HiEllipsisVertical": HiEllipsisVertical,
//    "HiEnvelopeOpen": HiEnvelopeOpen,
//    "HiEnvelope": HiEnvelope,
//    "HiExclamationCircle": HiExclamationCircle,
//    "HiExclamationTriangle": HiExclamationTriangle,
//    "HiEyeSlash": HiEyeSlash,
//    "HiEye": HiEye,
//    "HiFaceFrown": HiFaceFrown,
//    "HiFaceSmile": HiFaceSmile,
//    "HiFilm": HiFilm,
//    "HiFingerPrint": HiFingerPrint,
//    "HiFire": HiFire,
//    "HiFlag": HiFlag,
//    "HiFolderArrowDown": HiFolderArrowDown,
//    "HiFolderMinus": HiFolderMinus,
//    "HiFolderOpen": HiFolderOpen,
//    "HiFolderPlus": HiFolderPlus,
//    "HiFolder": HiFolder,
//    "HiForward": HiForward,
//    "HiFunnel": HiFunnel,
//    "HiGif": HiGif,
//    "HiGiftTop": HiGiftTop,
//    "HiGift": HiGift,
//    "HiGlobeAlt": HiGlobeAlt,
//    "HiGlobeAmericas": HiGlobeAmericas,
//    "HiGlobeAsiaAustralia": HiGlobeAsiaAustralia,
//    "HiGlobeEuropeAfrica": HiGlobeEuropeAfrica,
//    "HiHandRaised": HiHandRaised,
//    "HiHandThumbDown": HiHandThumbDown,
//    "HiHandThumbUp": HiHandThumbUp,
//    "HiHashtag": HiHashtag,
//    "HiHeart": HiHeart,
//    "HiHomeModern": HiHomeModern,
//    "HiHome": HiHome,
//    "HiIdentification": HiIdentification,
//    "HiInboxArrowDown": HiInboxArrowDown,
//    "HiInboxStack": HiInboxStack,
//    "HiInbox": HiInbox,
//    "HiInformationCircle": HiInformationCircle,
//    "HiKey": HiKey,
//    "HiLanguage": HiLanguage,
//    "HiLifebuoy": HiLifebuoy,
//    "HiLightBulb": HiLightBulb,
//    "HiLink": HiLink,
//    "HiListBullet": HiListBullet,
//    "HiLockClosed": HiLockClosed,
//    "HiLockOpen": HiLockOpen,
//    "HiMagnifyingGlassCircle": HiMagnifyingGlassCircle,
//    "HiMagnifyingGlassMinus": HiMagnifyingGlassMinus,
//    "HiMagnifyingGlassPlus": HiMagnifyingGlassPlus,
//    "HiMagnifyingGlass": HiMagnifyingGlass,
//    "HiMapPin": HiMapPin,
//    "HiMap": HiMap,
//    "HiMegaphone": HiMegaphone,
//    "HiMicrophone": HiMicrophone,
//    "HiMinusCircle": HiMinusCircle,
//    "HiMinus": HiMinus,
//    "HiMoon": HiMoon,
//    "HiMusicalNote": HiMusicalNote,
//    "HiNewspaper": HiNewspaper,
//    "HiNoSymbol": HiNoSymbol,
//    "HiPaperAirplane": HiPaperAirplane,
//    "HiPaperClip": HiPaperClip,
//    "HiPause": HiPause,
//    "HiPencilSquare": HiPencilSquare,
//    "HiPencil": HiPencil,
//    "HiPhoneArrowDownLeft": HiPhoneArrowDownLeft,
//    "HiPhoneArrowUpRight": HiPhoneArrowUpRight,
//    "HiPhoneXMark": HiPhoneXMark,
//    "HiPhone": HiPhone,
//    "HiPhoto": HiPhoto,
//    "HiPlayPause": HiPlayPause,
//    "HiPlay": HiPlay,
//    "HiPlusCircle": HiPlusCircle,
//    "HiPlus": HiPlus,
//    "HiPresentationChartBar": HiPresentationChartBar,
//    "HiPresentationChartLine": HiPresentationChartLine,
//    "HiPrinter": HiPrinter,
//    "HiPuzzlePiece": HiPuzzlePiece,
//    "HiQrCode": HiQrCode,
//    "HiQuestionMarkCircle": HiQuestionMarkCircle,
//    "HiQueueList": HiQueueList,
//    "HiRadio": HiRadio,
//    "HiReceiptPercent": HiReceiptPercent,
//    "HiReceiptRefund": HiReceiptRefund,
//    "HiRectangleGroup": HiRectangleGroup,
//    "HiRectangleStack": HiRectangleStack,
//    "HiRss": HiRss,
//    "HiScale": HiScale,
//    "HiScissors": HiScissors,
//    "HiServerStack": HiServerStack,
//    "HiServer": HiServer,
//    "HiShare": HiShare,
//    "HiShieldCheck": HiShieldCheck,
//    "HiShieldExclamation": HiShieldExclamation,
//    "HiShoppingBag": HiShoppingBag,
//    "HiShoppingCart": HiShoppingCart,
//    "HiSignalSlash": HiSignalSlash,
//    "HiSignal": HiSignal,
//    "HiSparkles": HiSparkles,
//    "HiSpeakerWave": HiSpeakerWave,
//    "HiSpeakerXMark": HiSpeakerXMark,
//    "HiSquare2Stack": HiSquare2Stack,
//    "HiSquares2X2": HiSquares2X2,
//    "HiSquaresPlus": HiSquaresPlus,
//    "HiStar": HiStar,
//    "HiStop": HiStop,
//    "HiSun": HiSun,
//    "HiSwatch": HiSwatch,
//    "HiTableCells": HiTableCells,
//    "HiTag": HiTag,
//    "HiTicket": HiTicket,
//    "HiTrash": HiTrash,
//    "HiTruck": HiTruck,
//    "HiUserCircle": HiUserCircle,
//    "HiUserGroup": HiUserGroup,
//    "HiUserMinus": HiUserMinus,
//    "HiUserPlus": HiUserPlus,
//    "HiUser": HiUser,
//    "HiUsers": HiUsers,
//    "HiVideoCameraSlash": HiVideoCameraSlash,
//    "HiVideoCamera": HiVideoCamera,
//    "HiViewColumns": HiViewColumns,
//    "HiWifi": HiWifi,
//    "HiWrenchScrewdriver": HiWrenchScrewdriver,
//    "HiWrench": HiWrench,
//    "HiXCircle": HiXCircle,
//    "HiXMark": HiXMark,
//    "HiOutlineAcademicCap": HiOutlineAcademicCap,
//    "HiOutlineAdjustmentsHorizontal": HiOutlineAdjustmentsHorizontal,
//    "HiOutlineAdjustmentsVertical": HiOutlineAdjustmentsVertical,
//    "HiOutlineArchiveBoxArrowDown": HiOutlineArchiveBoxArrowDown,
//    "HiOutlineArchiveBoxXMark": HiOutlineArchiveBoxXMark,
//    "HiOutlineArchiveBox": HiOutlineArchiveBox,
//    "HiOutlineArrowDownCircle": HiOutlineArrowDownCircle,
//    "HiOutlineArrowDownLeft": HiOutlineArrowDownLeft,
//    "HiOutlineArrowDownOnSquareStack": HiOutlineArrowDownOnSquareStack,
//    "HiOutlineArrowDownOnSquare": HiOutlineArrowDownOnSquare,
//    "HiOutlineArrowDownRight": HiOutlineArrowDownRight,
//    "HiOutlineArrowDownTray": HiOutlineArrowDownTray,
//    "HiOutlineArrowDown": HiOutlineArrowDown,
//    "HiOutlineArrowLeftCircle": HiOutlineArrowLeftCircle,
//    "HiOutlineArrowLeftOnRectangle": HiOutlineArrowLeftOnRectangle,
//    "HiOutlineArrowLeft": HiOutlineArrowLeft,
//    "HiOutlineArrowLongDown": HiOutlineArrowLongDown,
//    "HiOutlineArrowLongLeft": HiOutlineArrowLongLeft,
//    "HiOutlineArrowLongRight": HiOutlineArrowLongRight,
//    "HiOutlineArrowLongUp": HiOutlineArrowLongUp,
//    "HiOutlineArrowPath": HiOutlineArrowPath,
//    "HiOutlineArrowRightCircle": HiOutlineArrowRightCircle,
//    "HiOutlineArrowRightOnRectangle": HiOutlineArrowRightOnRectangle,
//    "HiOutlineArrowRight": HiOutlineArrowRight,
//    "HiOutlineArrowTopRightOnSquare": HiOutlineArrowTopRightOnSquare,
//    "HiOutlineArrowTrendingDown": HiOutlineArrowTrendingDown,
//    "HiOutlineArrowTrendingUp": HiOutlineArrowTrendingUp,
//    "HiOutlineArrowUpCircle": HiOutlineArrowUpCircle,
//    "HiOutlineArrowUpLeft": HiOutlineArrowUpLeft,
//    "HiOutlineArrowUpOnSquareStack": HiOutlineArrowUpOnSquareStack,
//    "HiOutlineArrowUpOnSquare": HiOutlineArrowUpOnSquare,
//    "HiOutlineArrowUpRight": HiOutlineArrowUpRight,
//    "HiOutlineArrowUpTray": HiOutlineArrowUpTray,
//    "HiOutlineArrowUp": HiOutlineArrowUp,
//    "HiOutlineArrowUturnDown": HiOutlineArrowUturnDown,
//    "HiOutlineArrowUturnLeft": HiOutlineArrowUturnLeft,
//    "HiOutlineArrowUturnRight": HiOutlineArrowUturnRight,
//    "HiOutlineArrowUturnUp": HiOutlineArrowUturnUp,
//    "HiOutlineArrowsPointingIn": HiOutlineArrowsPointingIn,
//    "HiOutlineArrowsPointingOut": HiOutlineArrowsPointingOut,
//    "HiOutlineArrowsRightLeft": HiOutlineArrowsRightLeft,
//    "HiOutlineArrowsUpDown": HiOutlineArrowsUpDown,
//    "HiOutlineAtSymbol": HiOutlineAtSymbol,
//    "HiOutlineBackspace": HiOutlineBackspace,
//    "HiOutlineBackward": HiOutlineBackward,
//    "HiOutlineBanknotes": HiOutlineBanknotes,
//    "HiOutlineBars2": HiOutlineBars2,
//    "HiOutlineBars3BottomLeft": HiOutlineBars3BottomLeft,
//    "HiOutlineBars3BottomRight": HiOutlineBars3BottomRight,
//    "HiOutlineBars3CenterLeft": HiOutlineBars3CenterLeft,
//    "HiOutlineBars3": HiOutlineBars3,
//    "HiOutlineBars4": HiOutlineBars4,
//    "HiOutlineBarsArrowDown": HiOutlineBarsArrowDown,
//    "HiOutlineBarsArrowUp": HiOutlineBarsArrowUp,
//    "HiOutlineBeaker": HiOutlineBeaker,
//    "HiOutlineBellAlert": HiOutlineBellAlert,
//    "HiOutlineBellSlash": HiOutlineBellSlash,
//    "HiOutlineBellSnooze": HiOutlineBellSnooze,
//    "HiOutlineBell": HiOutlineBell,
//    "HiOutlineBoltSlash": HiOutlineBoltSlash,
//    "HiOutlineBolt": HiOutlineBolt,
//    "HiOutlineBookOpen": HiOutlineBookOpen,
//    "HiOutlineBookmarkSlash": HiOutlineBookmarkSlash,
//    "HiOutlineBookmarkSquare": HiOutlineBookmarkSquare,
//    "HiOutlineBookmark": HiOutlineBookmark,
//    "HiOutlineBriefcase": HiOutlineBriefcase,
//    "HiOutlineBuildingLibrary": HiOutlineBuildingLibrary,
//    "HiOutlineBuildingOffice2": HiOutlineBuildingOffice2,
//    "HiOutlineBuildingOffice": HiOutlineBuildingOffice,
//    "HiOutlineBuildingStorefront": HiOutlineBuildingStorefront,
//    "HiOutlineCake": HiOutlineCake,
//    "HiOutlineCalculator": HiOutlineCalculator,
//    "HiOutlineCalendarDays": HiOutlineCalendarDays,
//    "HiOutlineCalendar": HiOutlineCalendar,
//    "HiOutlineCamera": HiOutlineCamera,
//    "HiOutlineChartBarSquare": HiOutlineChartBarSquare,
//    "HiOutlineChartBar": HiOutlineChartBar,
//    "HiOutlineChartPie": HiOutlineChartPie,
//    "HiOutlineChatBubbleBottomCenterText": HiOutlineChatBubbleBottomCenterText,
//    "HiOutlineChatBubbleBottomCenter": HiOutlineChatBubbleBottomCenter,
//    "HiOutlineChatBubbleLeftEllipsis": HiOutlineChatBubbleLeftEllipsis,
//    "HiOutlineChatBubbleLeftRight": HiOutlineChatBubbleLeftRight,
//    "HiOutlineChatBubbleLeft": HiOutlineChatBubbleLeft,
//    "HiOutlineChatBubbleOvalLeftEllipsis": HiOutlineChatBubbleOvalLeftEllipsis,
//    "HiOutlineChatBubbleOvalLeft": HiOutlineChatBubbleOvalLeft,
//    "HiOutlineCheckBadge": HiOutlineCheckBadge,
//    "HiOutlineCheckCircle": HiOutlineCheckCircle,
//    "HiOutlineCheck": HiOutlineCheck,
//    "HiOutlineChevronDoubleDown": HiOutlineChevronDoubleDown,
//    "HiOutlineChevronDoubleLeft": HiOutlineChevronDoubleLeft,
//    "HiOutlineChevronDoubleRight": HiOutlineChevronDoubleRight,
//    "HiOutlineChevronDoubleUp": HiOutlineChevronDoubleUp,
//    "HiOutlineChevronDown": HiOutlineChevronDown,
//    "HiOutlineChevronLeft": HiOutlineChevronLeft,
//    "HiOutlineChevronRight": HiOutlineChevronRight,
//    "HiOutlineChevronUpDown": HiOutlineChevronUpDown,
//    "HiOutlineChevronUp": HiOutlineChevronUp,
//    "HiOutlineCircleStack": HiOutlineCircleStack,
//    "HiOutlineClipboardDocumentCheck": HiOutlineClipboardDocumentCheck,
//    "HiOutlineClipboardDocumentList": HiOutlineClipboardDocumentList,
//    "HiOutlineClipboardDocument": HiOutlineClipboardDocument,
//    "HiOutlineClipboard": HiOutlineClipboard,
//    "HiOutlineClock": HiOutlineClock,
//    "HiOutlineCloudArrowDown": HiOutlineCloudArrowDown,
//    "HiOutlineCloudArrowUp": HiOutlineCloudArrowUp,
//    "HiOutlineCloud": HiOutlineCloud,
//    "HiOutlineCodeBracketSquare": HiOutlineCodeBracketSquare,
//    "HiOutlineCodeBracket": HiOutlineCodeBracket,
//    "HiOutlineCog6Tooth": HiOutlineCog6Tooth,
//    "HiOutlineCog8Tooth": HiOutlineCog8Tooth,
//    "HiOutlineCog": HiOutlineCog,
//    "HiOutlineCommandLine": HiOutlineCommandLine,
//    "HiOutlineComputerDesktop": HiOutlineComputerDesktop,
//    "HiOutlineCpuChip": HiOutlineCpuChip,
//    "HiOutlineCreditCard": HiOutlineCreditCard,
//    "HiOutlineCube": HiOutlineCube,
//    "HiOutlineCurrencyDollar": HiOutlineCurrencyDollar,
//    "HiOutlineCurrencyEuro": HiOutlineCurrencyEuro,
//    "HiOutlineCurrencyPound": HiOutlineCurrencyPound,
//    "HiOutlineCurrencyRupee": HiOutlineCurrencyRupee,
//    "HiOutlineCurrencyYen": HiOutlineCurrencyYen,
//    "HiOutlineCursorArrowRays": HiOutlineCursorArrowRays,
//    "HiOutlineCursorArrowRipple": HiOutlineCursorArrowRipple,
//    "HiOutlineDevicePhoneMobile": HiOutlineDevicePhoneMobile,
//    "HiOutlineDeviceTablet": HiOutlineDeviceTablet,
//    "HiOutlineDocumentArrowDown": HiOutlineDocumentArrowDown,
//    "HiOutlineDocumentArrowUp": HiOutlineDocumentArrowUp,
//    "HiOutlineDocumentChartBar": HiOutlineDocumentChartBar,
//    "HiOutlineDocumentCheck": HiOutlineDocumentCheck,
//    "HiOutlineDocumentDuplicate": HiOutlineDocumentDuplicate,
//    "HiOutlineDocumentMagnifyingGlass": HiOutlineDocumentMagnifyingGlass,
//    "HiOutlineDocumentMinus": HiOutlineDocumentMinus,
//    "HiOutlineDocumentPlus": HiOutlineDocumentPlus,
//    "HiOutlineDocumentText": HiOutlineDocumentText,
//    "HiOutlineDocument": HiOutlineDocument,
//    "HiOutlineEllipsisHorizontalCircle": HiOutlineEllipsisHorizontalCircle,
//    "HiOutlineEllipsisHorizontal": HiOutlineEllipsisHorizontal,
//    "HiOutlineEllipsisVertical": HiOutlineEllipsisVertical,
//    "HiOutlineEnvelopeOpen": HiOutlineEnvelopeOpen,
//    "HiOutlineEnvelope": HiOutlineEnvelope,
//    "HiOutlineExclamationCircle": HiOutlineExclamationCircle,
//    "HiOutlineExclamationTriangle": HiOutlineExclamationTriangle,
//    "HiOutlineEyeSlash": HiOutlineEyeSlash,
//    "HiOutlineEye": HiOutlineEye,
//    "HiOutlineFaceFrown": HiOutlineFaceFrown,
//    "HiOutlineFaceSmile": HiOutlineFaceSmile,
//    "HiOutlineFilm": HiOutlineFilm,
//    "HiOutlineFingerPrint": HiOutlineFingerPrint,
//    "HiOutlineFire": HiOutlineFire,
//    "HiOutlineFlag": HiOutlineFlag,
//    "HiOutlineFolderArrowDown": HiOutlineFolderArrowDown,
//    "HiOutlineFolderMinus": HiOutlineFolderMinus,
//    "HiOutlineFolderOpen": HiOutlineFolderOpen,
//    "HiOutlineFolderPlus": HiOutlineFolderPlus,
//    "HiOutlineFolder": HiOutlineFolder,
//    "HiOutlineForward": HiOutlineForward,
//    "HiOutlineFunnel": HiOutlineFunnel,
//    "HiOutlineGif": HiOutlineGif,
//    "HiOutlineGiftTop": HiOutlineGiftTop,
//    "HiOutlineGift": HiOutlineGift,
//    "HiOutlineGlobeAlt": HiOutlineGlobeAlt,
//    "HiOutlineGlobeAmericas": HiOutlineGlobeAmericas,
//    "HiOutlineGlobeAsiaAustralia": HiOutlineGlobeAsiaAustralia,
//    "HiOutlineGlobeEuropeAfrica": HiOutlineGlobeEuropeAfrica,
//    "HiOutlineHandRaised": HiOutlineHandRaised,
//    "HiOutlineHandThumbDown": HiOutlineHandThumbDown,
//    "HiOutlineHandThumbUp": HiOutlineHandThumbUp,
//    "HiOutlineHashtag": HiOutlineHashtag,
//    "HiOutlineHeart": HiOutlineHeart,
//    "HiOutlineHomeModern": HiOutlineHomeModern,
//    "HiOutlineHome": HiOutlineHome,
//    "HiOutlineIdentification": HiOutlineIdentification,
//    "HiOutlineInboxArrowDown": HiOutlineInboxArrowDown,
//    "HiOutlineInboxStack": HiOutlineInboxStack,
//    "HiOutlineInbox": HiOutlineInbox,
//    "HiOutlineInformationCircle": HiOutlineInformationCircle,
//    "HiOutlineKey": HiOutlineKey,
//    "HiOutlineLanguage": HiOutlineLanguage,
//    "HiOutlineLifebuoy": HiOutlineLifebuoy,
//    "HiOutlineLightBulb": HiOutlineLightBulb,
//    "HiOutlineLink": HiOutlineLink,
//    "HiOutlineListBullet": HiOutlineListBullet,
//    "HiOutlineLockClosed": HiOutlineLockClosed,
//    "HiOutlineLockOpen": HiOutlineLockOpen,
//    "HiOutlineMagnifyingGlassCircle": HiOutlineMagnifyingGlassCircle,
//    "HiOutlineMagnifyingGlassMinus": HiOutlineMagnifyingGlassMinus,
//    "HiOutlineMagnifyingGlassPlus": HiOutlineMagnifyingGlassPlus,
//    "HiOutlineMagnifyingGlass": HiOutlineMagnifyingGlass,
//    "HiOutlineMapPin": HiOutlineMapPin,
//    "HiOutlineMap": HiOutlineMap,
//    "HiOutlineMegaphone": HiOutlineMegaphone,
//    "HiOutlineMicrophone": HiOutlineMicrophone,
//    "HiOutlineMinusCircle": HiOutlineMinusCircle,
//    "HiOutlineMinus": HiOutlineMinus,
//    "HiOutlineMoon": HiOutlineMoon,
//    "HiOutlineMusicalNote": HiOutlineMusicalNote,
//    "HiOutlineNewspaper": HiOutlineNewspaper,
//    "HiOutlineNoSymbol": HiOutlineNoSymbol,
//    "HiOutlinePaperAirplane": HiOutlinePaperAirplane,
//    "HiOutlinePaperClip": HiOutlinePaperClip,
//    "HiOutlinePause": HiOutlinePause,
//    "HiOutlinePencilSquare": HiOutlinePencilSquare,
//    "HiOutlinePencil": HiOutlinePencil,
//    "HiOutlinePhoneArrowDownLeft": HiOutlinePhoneArrowDownLeft,
//    "HiOutlinePhoneArrowUpRight": HiOutlinePhoneArrowUpRight,
//    "HiOutlinePhoneXMark": HiOutlinePhoneXMark,
//    "HiOutlinePhone": HiOutlinePhone,
//    "HiOutlinePhoto": HiOutlinePhoto,
//    "HiOutlinePlayPause": HiOutlinePlayPause,
//    "HiOutlinePlay": HiOutlinePlay,
//    "HiOutlinePlusCircle": HiOutlinePlusCircle,
//    "HiOutlinePlus": HiOutlinePlus,
//    "HiOutlinePresentationChartBar": HiOutlinePresentationChartBar,
//    "HiOutlinePresentationChartLine": HiOutlinePresentationChartLine,
//    "HiOutlinePrinter": HiOutlinePrinter,
//    "HiOutlinePuzzlePiece": HiOutlinePuzzlePiece,
//    "HiOutlineQrCode": HiOutlineQrCode,
//    "HiOutlineQuestionMarkCircle": HiOutlineQuestionMarkCircle,
//    "HiOutlineQueueList": HiOutlineQueueList,
//    "HiOutlineRadio": HiOutlineRadio,
//    "HiOutlineReceiptPercent": HiOutlineReceiptPercent,
//    "HiOutlineReceiptRefund": HiOutlineReceiptRefund,
//    "HiOutlineRectangleGroup": HiOutlineRectangleGroup,
//    "HiOutlineRectangleStack": HiOutlineRectangleStack,
//    "HiOutlineRss": HiOutlineRss,
//    "HiOutlineScale": HiOutlineScale,
//    "HiOutlineScissors": HiOutlineScissors,
//    "HiOutlineServerStack": HiOutlineServerStack,
//    "HiOutlineServer": HiOutlineServer,
//    "HiOutlineShare": HiOutlineShare,
//    "HiOutlineShieldCheck": HiOutlineShieldCheck,
//    "HiOutlineShieldExclamation": HiOutlineShieldExclamation,
//    "HiOutlineShoppingBag": HiOutlineShoppingBag,
//    "HiOutlineShoppingCart": HiOutlineShoppingCart,
//    "HiOutlineSignalSlash": HiOutlineSignalSlash,
//    "HiOutlineSignal": HiOutlineSignal,
//    "HiOutlineSparkles": HiOutlineSparkles,
//    "HiOutlineSpeakerWave": HiOutlineSpeakerWave,
//    "HiOutlineSpeakerXMark": HiOutlineSpeakerXMark,
//    "HiOutlineSquare2Stack": HiOutlineSquare2Stack,
//    "HiOutlineSquares2X2": HiOutlineSquares2X2,
//    "HiOutlineSquaresPlus": HiOutlineSquaresPlus,
//    "HiOutlineStar": HiOutlineStar,
//    "HiOutlineStop": HiOutlineStop,
//    "HiOutlineSun": HiOutlineSun,
//    "HiOutlineSwatch": HiOutlineSwatch,
//    "HiOutlineTableCells": HiOutlineTableCells,
//    "HiOutlineTag": HiOutlineTag,
//    "HiOutlineTicket": HiOutlineTicket,
//    "HiOutlineTrash": HiOutlineTrash,
//    "HiOutlineTruck": HiOutlineTruck,
//    "HiOutlineUserCircle": HiOutlineUserCircle,
//    "HiOutlineUserGroup": HiOutlineUserGroup,
//    "HiOutlineUserMinus": HiOutlineUserMinus,
//    "HiOutlineUserPlus": HiOutlineUserPlus,
//    "HiOutlineUser": HiOutlineUser,
//    "HiOutlineUsers": HiOutlineUsers,
//    "HiOutlineVideoCameraSlash": HiOutlineVideoCameraSlash,
//    "HiOutlineVideoCamera": HiOutlineVideoCamera,
//    "HiOutlineViewColumns": HiOutlineViewColumns,
//    "HiOutlineWifi": HiOutlineWifi,
//    "HiOutlineWrenchScrewdriver": HiOutlineWrenchScrewdriver,
//    "HiOutlineWrench": HiOutlineWrench,
//    "HiOutlineXCircle": HiOutlineXCircle,
//    "HiOutlineXMark": HiOutlineXMark,
//}