import { 
    ImHome,
ImHome2,
ImHome3,
ImOffice,
ImNewspaper,
ImPencil,
ImPencil2,
ImQuill,
ImPen,
ImBlog,
ImEyedropper,
ImDroplet,
ImPaintFormat,
ImImage,
ImImages,
ImCamera,
ImHeadphones,
ImMusic,
ImPlay,
ImFilm,
ImVideoCamera,
ImDice,
ImPacman,
ImSpades,
ImClubs,
ImDiamonds,
ImBullhorn,
ImConnection,
ImPodcast,
ImFeed,
ImMic,
ImBook,
ImBooks,
ImLibrary,
ImFileText,
ImProfile,
ImFileEmpty,
ImFilesEmpty,
ImFileText2,
ImFilePicture,
ImFileMusic,
ImFilePlay,
ImFileVideo,
ImFileZip,
ImCopy,
ImPaste,
ImStack,
ImFolder,
ImFolderOpen,
ImFolderPlus,
ImFolderMinus,
ImFolderDownload,
ImFolderUpload,
ImPriceTag,
ImPriceTags,
ImBarcode,
ImQrcode,
ImTicket,
ImCart,
ImCoinDollar,
ImCoinEuro,
ImCoinPound,
ImCoinYen,
ImCreditCard,
ImCalculator,
ImLifebuoy,
ImPhone,
ImPhoneHangUp,
ImAddressBook,
ImEnvelop,
ImPushpin,
ImLocation,
ImLocation2,
ImCompass,
ImCompass2,
ImMap,
ImMap2,
ImHistory,
ImClock,
ImClock2,
ImAlarm,
ImBell,
ImStopwatch,
ImCalendar,
ImPrinter,
ImKeyboard,
ImDisplay,
ImLaptop,
ImMobile,
ImMobile2,
ImTablet,
ImTv,
ImDrawer,
ImDrawer2,
ImBoxAdd,
ImBoxRemove,
ImDownload,
ImUpload,
ImFloppyDisk,
ImDrive,
ImDatabase,
ImUndo,
ImRedo,
ImUndo2,
ImRedo2,
ImForward,
ImReply,
ImBubble,
ImBubbles,
ImBubbles2,
ImBubble2,
ImBubbles3,
ImBubbles4,
ImUser,
ImUsers,
ImUserPlus,
ImUserMinus,
ImUserCheck,
ImUserTie,
ImQuotesLeft,
ImQuotesRight,
ImHourGlass,
ImSpinner,
ImSpinner2,
ImSpinner3,
ImSpinner4,
ImSpinner5,
ImSpinner6,
ImSpinner7,
ImSpinner8,
ImSpinner9,
ImSpinner10,
ImSpinner11,
ImBinoculars,
ImSearch,
ImZoomIn,
ImZoomOut,
ImEnlarge,
ImShrink,
ImEnlarge2,
ImShrink2,
ImKey,
ImKey2,
ImLock,
ImUnlocked,
ImWrench,
ImEqualizer,
ImEqualizer2,
ImCog,
ImCogs,
ImHammer,
ImMagicWand,
ImAidKit,
ImBug,
ImPieChart,
ImStatsDots,
ImStatsBars,
ImStatsBars2,
ImTrophy,
ImGift,
ImGlass,
ImGlass2,
ImMug,
ImSpoonKnife,
ImLeaf,
ImRocket,
ImMeter,
ImMeter2,
ImHammer2,
ImFire,
ImLab,
ImMagnet,
ImBin,
ImBin2,
ImBriefcase,
ImAirplane,
ImTruck,
ImRoad,
ImAccessibility,
ImTarget,
ImShield,
ImPower,
ImSwitch,
ImPowerCord,
ImClipboard,
ImListNumbered,
ImList,
ImList2,
ImTree,
ImMenu,
ImMenu2,
ImMenu3,
ImMenu4,
ImCloud,
ImCloudDownload,
ImCloudUpload,
ImCloudCheck,
ImDownload2,
ImUpload2,
ImDownload3,
ImUpload3,
ImSphere,
ImEarth,
ImLink,
ImFlag,
ImAttachment,
ImEye,
ImEyePlus,
ImEyeMinus,
ImEyeBlocked,
ImBookmark,
ImBookmarks,
ImSun,
ImContrast,
ImBrightnessContrast,
ImStarEmpty,
ImStarHalf,
ImStarFull,
ImHeart,
ImHeartBroken,
ImMan,
ImWoman,
ImManWoman,
ImHappy,
ImHappy2,
ImSmile,
ImSmile2,
ImTongue,
ImTongue2,
ImSad,
ImSad2,
ImWink,
ImWink2,
ImGrin,
ImGrin2,
ImCool,
ImCool2,
ImAngry,
ImAngry2,
ImEvil,
ImEvil2,
ImShocked,
ImShocked2,
ImBaffled,
ImBaffled2,
ImConfused,
ImConfused2,
ImNeutral,
ImNeutral2,
ImHipster,
ImHipster2,
ImWondering,
ImWondering2,
ImSleepy,
ImSleepy2,
ImFrustrated,
ImFrustrated2,
ImCrying,
ImCrying2,
ImPointUp,
ImPointRight,
ImPointDown,
ImPointLeft,
ImWarning,
ImNotification,
ImQuestion,
ImPlus,
ImMinus,
ImInfo,
ImCancelCircle,
ImBlocked,
ImCross,
ImCheckmark,
ImCheckmark2,
ImSpellCheck,
ImEnter,
ImExit,
ImPlay2,
ImPause,
ImStop,
ImPrevious,
ImNext,
ImBackward,
ImForward2,
ImPlay3,
ImPause2,
ImStop2,
ImBackward2,
ImForward3,
ImFirst,
ImLast,
ImPrevious2,
ImNext2,
ImEject,
ImVolumeHigh,
ImVolumeMedium,
ImVolumeLow,
ImVolumeMute,
ImVolumeMute2,
ImVolumeIncrease,
ImVolumeDecrease,
ImLoop,
ImLoop2,
ImInfinite,
ImShuffle,
ImArrowUpLeft,
ImArrowUp,
ImArrowUpRight,
ImArrowRight,
ImArrowDownRight,
ImArrowDown,
ImArrowDownLeft,
ImArrowLeft,
ImArrowUpLeft2,
ImArrowUp2,
ImArrowUpRight2,
ImArrowRight2,
ImArrowDownRight2,
ImArrowDown2,
ImArrowDownLeft2,
ImArrowLeft2,
ImCircleUp,
ImCircleRight,
ImCircleDown,
ImCircleLeft,
ImTab,
ImMoveUp,
ImMoveDown,
ImSortAlphaAsc,
ImSortAlphaDesc,
ImSortNumericAsc,
ImSortNumbericDesc,
ImSortAmountAsc,
ImSortAmountDesc,
ImCommand,
ImShift,
ImCtrl,
ImOpt,
ImCheckboxChecked,
ImCheckboxUnchecked,
ImRadioChecked,
ImRadioChecked2,
ImRadioUnchecked,
ImCrop,
ImMakeGroup,
ImUngroup,
ImScissors,
ImFilter,
ImFont,
ImLigature,
ImLigature2,
ImTextHeight,
ImTextWidth,
ImFontSize,
ImBold,
ImUnderline,
ImItalic,
ImStrikethrough,
ImOmega,
ImSigma,
ImPageBreak,
ImSuperscript,
ImSubscript,
ImSuperscript2,
ImSubscript2,
ImTextColor,
ImPagebreak,
ImClearFormatting,
ImTable,
ImTable2,
ImInsertTemplate,
ImPilcrow,
ImLtr,
ImRtl,
ImSection,
ImParagraphLeft,
ImParagraphCenter,
ImParagraphRight,
ImParagraphJustify,
ImIndentIncrease,
ImIndentDecrease,
ImShare,
ImNewTab,
ImEmbed,
ImEmbed2,
ImTerminal,
ImShare2,
ImMail,
ImMail2,
ImMail3,
ImMail4,
ImAmazon,
ImGoogle,
ImGoogle2,
ImGoogle3,
ImGooglePlus,
ImGooglePlus2,
ImGooglePlus3,
ImHangouts,
ImGoogleDrive,
ImFacebook,
ImFacebook2,
ImInstagram,
ImWhatsapp,
ImSpotify,
ImTelegram,
ImTwitter,
ImVine,
ImVk,
ImRenren,
ImSinaWeibo,
ImRss,
ImRss2,
ImYoutube,
ImYoutube2,
ImTwitch,
ImVimeo,
ImVimeo2,
ImLanyrd,
ImFlickr,
ImFlickr2,
ImFlickr3,
ImFlickr4,
ImDribbble,
ImBehance,
ImBehance2,
ImDeviantart,
Im500Px,
ImSteam,
ImSteam2,
ImDropbox,
ImOnedrive,
ImGithub,
ImNpm,
ImBasecamp,
ImTrello,
ImWordpress,
ImJoomla,
ImEllo,
ImBlogger,
ImBlogger2,
ImTumblr,
ImTumblr2,
ImYahoo,
ImYahoo2,
ImTux,
ImAppleinc,
ImFinder,
ImAndroid,
ImWindows,
ImWindows8,
ImSoundcloud,
ImSoundcloud2,
ImSkype,
ImReddit,
ImHackernews,
ImWikipedia,
ImLinkedin,
ImLinkedin2,
ImLastfm,
ImLastfm2,
ImDelicious,
ImStumbleupon,
ImStumbleupon2,
ImStackoverflow,
ImPinterest,
ImPinterest2,
ImXing,
ImXing2,
ImFlattr,
ImFoursquare,
ImYelp,
ImPaypal,
ImChrome,
ImFirefox,
ImIe,
ImEdge,
ImSafari,
ImOpera,
ImFilePdf,
ImFileOpenoffice,
ImFileWord,
ImFileExcel,
ImLibreoffice,
ImHtmlFive,
ImHtmlFive2,
ImCss3,
ImGit,
ImCodepen,
ImSvg,
ImIcoMoon
 } from "react-icons/im";

export const IcoMoonIcons = {
    "ImHome": ImHome,
    "ImHome2": ImHome2,
    "ImHome3": ImHome3,
    "ImOffice": ImOffice,
    "ImNewspaper": ImNewspaper,
    "ImPencil": ImPencil,
    "ImPencil2": ImPencil2,
    "ImQuill": ImQuill,
    "ImPen": ImPen,
    "ImBlog": ImBlog,
    "ImEyedropper": ImEyedropper,
    "ImDroplet": ImDroplet,
    "ImPaintFormat": ImPaintFormat,
    "ImImage": ImImage,
    "ImImages": ImImages,
    "ImCamera": ImCamera,
    "ImHeadphones": ImHeadphones,
    "ImMusic": ImMusic,
    "ImPlay": ImPlay,
    "ImFilm": ImFilm,
    "ImVideoCamera": ImVideoCamera,
    "ImDice": ImDice,
    "ImPacman": ImPacman,
    "ImSpades": ImSpades,
    "ImClubs": ImClubs,
    "ImDiamonds": ImDiamonds,
    "ImBullhorn": ImBullhorn,
    "ImConnection": ImConnection,
    "ImPodcast": ImPodcast,
    "ImFeed": ImFeed,
    "ImMic": ImMic,
    "ImBook": ImBook,
    "ImBooks": ImBooks,
    "ImLibrary": ImLibrary,
    "ImFileText": ImFileText,
    "ImProfile": ImProfile,
    "ImFileEmpty": ImFileEmpty,
    "ImFilesEmpty": ImFilesEmpty,
    "ImFileText2": ImFileText2,
    "ImFilePicture": ImFilePicture,
    "ImFileMusic": ImFileMusic,
    "ImFilePlay": ImFilePlay,
    "ImFileVideo": ImFileVideo,
    "ImFileZip": ImFileZip,
    "ImCopy": ImCopy,
    "ImPaste": ImPaste,
    "ImStack": ImStack,
    "ImFolder": ImFolder,
    "ImFolderOpen": ImFolderOpen,
    "ImFolderPlus": ImFolderPlus,
    "ImFolderMinus": ImFolderMinus,
    "ImFolderDownload": ImFolderDownload,
    "ImFolderUpload": ImFolderUpload,
    "ImPriceTag": ImPriceTag,
    "ImPriceTags": ImPriceTags,
    "ImBarcode": ImBarcode,
    "ImQrcode": ImQrcode,
    "ImTicket": ImTicket,
    "ImCart": ImCart,
    "ImCoinDollar": ImCoinDollar,
    "ImCoinEuro": ImCoinEuro,
    "ImCoinPound": ImCoinPound,
    "ImCoinYen": ImCoinYen,
    "ImCreditCard": ImCreditCard,
    "ImCalculator": ImCalculator,
    "ImLifebuoy": ImLifebuoy,
    "ImPhone": ImPhone,
    "ImPhoneHangUp": ImPhoneHangUp,
    "ImAddressBook": ImAddressBook,
    "ImEnvelop": ImEnvelop,
    "ImPushpin": ImPushpin,
    "ImLocation": ImLocation,
    "ImLocation2": ImLocation2,
    "ImCompass": ImCompass,
    "ImCompass2": ImCompass2,
    "ImMap": ImMap,
    "ImMap2": ImMap2,
    "ImHistory": ImHistory,
    "ImClock": ImClock,
    "ImClock2": ImClock2,
    "ImAlarm": ImAlarm,
    "ImBell": ImBell,
    "ImStopwatch": ImStopwatch,
    "ImCalendar": ImCalendar,
    "ImPrinter": ImPrinter,
    "ImKeyboard": ImKeyboard,
    "ImDisplay": ImDisplay,
    "ImLaptop": ImLaptop,
    "ImMobile": ImMobile,
    "ImMobile2": ImMobile2,
    "ImTablet": ImTablet,
    "ImTv": ImTv,
    "ImDrawer": ImDrawer,
    "ImDrawer2": ImDrawer2,
    "ImBoxAdd": ImBoxAdd,
    "ImBoxRemove": ImBoxRemove,
    "ImDownload": ImDownload,
    "ImUpload": ImUpload,
    "ImFloppyDisk": ImFloppyDisk,
    "ImDrive": ImDrive,
    "ImDatabase": ImDatabase,
    "ImUndo": ImUndo,
    "ImRedo": ImRedo,
    "ImUndo2": ImUndo2,
    "ImRedo2": ImRedo2,
    "ImForward": ImForward,
    "ImReply": ImReply,
    "ImBubble": ImBubble,
    "ImBubbles": ImBubbles,
    "ImBubbles2": ImBubbles2,
    "ImBubble2": ImBubble2,
    "ImBubbles3": ImBubbles3,
    "ImBubbles4": ImBubbles4,
    "ImUser": ImUser,
    "ImUsers": ImUsers,
    "ImUserPlus": ImUserPlus,
    "ImUserMinus": ImUserMinus,
    "ImUserCheck": ImUserCheck,
    "ImUserTie": ImUserTie,
    "ImQuotesLeft": ImQuotesLeft,
    "ImQuotesRight": ImQuotesRight,
    "ImHourGlass": ImHourGlass,
    "ImSpinner": ImSpinner,
    "ImSpinner2": ImSpinner2,
    "ImSpinner3": ImSpinner3,
    "ImSpinner4": ImSpinner4,
    "ImSpinner5": ImSpinner5,
    "ImSpinner6": ImSpinner6,
    "ImSpinner7": ImSpinner7,
    "ImSpinner8": ImSpinner8,
    "ImSpinner9": ImSpinner9,
    "ImSpinner10": ImSpinner10,
    "ImSpinner11": ImSpinner11,
    "ImBinoculars": ImBinoculars,
    "ImSearch": ImSearch,
    "ImZoomIn": ImZoomIn,
    "ImZoomOut": ImZoomOut,
    "ImEnlarge": ImEnlarge,
    "ImShrink": ImShrink,
    "ImEnlarge2": ImEnlarge2,
    "ImShrink2": ImShrink2,
    "ImKey": ImKey,
    "ImKey2": ImKey2,
    "ImLock": ImLock,
    "ImUnlocked": ImUnlocked,
    "ImWrench": ImWrench,
    "ImEqualizer": ImEqualizer,
    "ImEqualizer2": ImEqualizer2,
    "ImCog": ImCog,
    "ImCogs": ImCogs,
    "ImHammer": ImHammer,
    "ImMagicWand": ImMagicWand,
    "ImAidKit": ImAidKit,
    "ImBug": ImBug,
    "ImPieChart": ImPieChart,
    "ImStatsDots": ImStatsDots,
    "ImStatsBars": ImStatsBars,
    "ImStatsBars2": ImStatsBars2,
    "ImTrophy": ImTrophy,
    "ImGift": ImGift,
    "ImGlass": ImGlass,
    "ImGlass2": ImGlass2,
    "ImMug": ImMug,
    "ImSpoonKnife": ImSpoonKnife,
    "ImLeaf": ImLeaf,
    "ImRocket": ImRocket,
    "ImMeter": ImMeter,
    "ImMeter2": ImMeter2,
    "ImHammer2": ImHammer2,
    "ImFire": ImFire,
    "ImLab": ImLab,
    "ImMagnet": ImMagnet,
    "ImBin": ImBin,
    "ImBin2": ImBin2,
    "ImBriefcase": ImBriefcase,
    "ImAirplane": ImAirplane,
    "ImTruck": ImTruck,
    "ImRoad": ImRoad,
    "ImAccessibility": ImAccessibility,
    "ImTarget": ImTarget,
    "ImShield": ImShield,
    "ImPower": ImPower,
    "ImSwitch": ImSwitch,
    "ImPowerCord": ImPowerCord,
    "ImClipboard": ImClipboard,
    "ImListNumbered": ImListNumbered,
    "ImList": ImList,
    "ImList2": ImList2,
    "ImTree": ImTree,
    "ImMenu": ImMenu,
    "ImMenu2": ImMenu2,
    "ImMenu3": ImMenu3,
    "ImMenu4": ImMenu4,
    "ImCloud": ImCloud,
    "ImCloudDownload": ImCloudDownload,
    "ImCloudUpload": ImCloudUpload,
    "ImCloudCheck": ImCloudCheck,
    "ImDownload2": ImDownload2,
    "ImUpload2": ImUpload2,
    "ImDownload3": ImDownload3,
    "ImUpload3": ImUpload3,
    "ImSphere": ImSphere,
    "ImEarth": ImEarth,
    "ImLink": ImLink,
    "ImFlag": ImFlag,
    "ImAttachment": ImAttachment,
    "ImEye": ImEye,
    "ImEyePlus": ImEyePlus,
    "ImEyeMinus": ImEyeMinus,
    "ImEyeBlocked": ImEyeBlocked,
    "ImBookmark": ImBookmark,
    "ImBookmarks": ImBookmarks,
    "ImSun": ImSun,
    "ImContrast": ImContrast,
    "ImBrightnessContrast": ImBrightnessContrast,
    "ImStarEmpty": ImStarEmpty,
    "ImStarHalf": ImStarHalf,
    "ImStarFull": ImStarFull,
    "ImHeart": ImHeart,
    "ImHeartBroken": ImHeartBroken,
    "ImMan": ImMan,
    "ImWoman": ImWoman,
    "ImManWoman": ImManWoman,
    "ImHappy": ImHappy,
    "ImHappy2": ImHappy2,
    "ImSmile": ImSmile,
    "ImSmile2": ImSmile2,
    "ImTongue": ImTongue,
    "ImTongue2": ImTongue2,
    "ImSad": ImSad,
    "ImSad2": ImSad2,
    "ImWink": ImWink,
    "ImWink2": ImWink2,
    "ImGrin": ImGrin,
    "ImGrin2": ImGrin2,
    "ImCool": ImCool,
    "ImCool2": ImCool2,
    "ImAngry": ImAngry,
    "ImAngry2": ImAngry2,
    "ImEvil": ImEvil,
    "ImEvil2": ImEvil2,
    "ImShocked": ImShocked,
    "ImShocked2": ImShocked2,
    "ImBaffled": ImBaffled,
    "ImBaffled2": ImBaffled2,
    "ImConfused": ImConfused,
    "ImConfused2": ImConfused2,
    "ImNeutral": ImNeutral,
    "ImNeutral2": ImNeutral2,
    "ImHipster": ImHipster,
    "ImHipster2": ImHipster2,
    "ImWondering": ImWondering,
    "ImWondering2": ImWondering2,
    "ImSleepy": ImSleepy,
    "ImSleepy2": ImSleepy2,
    "ImFrustrated": ImFrustrated,
    "ImFrustrated2": ImFrustrated2,
    "ImCrying": ImCrying,
    "ImCrying2": ImCrying2,
    "ImPointUp": ImPointUp,
    "ImPointRight": ImPointRight,
    "ImPointDown": ImPointDown,
    "ImPointLeft": ImPointLeft,
    "ImWarning": ImWarning,
    "ImNotification": ImNotification,
    "ImQuestion": ImQuestion,
    "ImPlus": ImPlus,
    "ImMinus": ImMinus,
    "ImInfo": ImInfo,
    "ImCancelCircle": ImCancelCircle,
    "ImBlocked": ImBlocked,
    "ImCross": ImCross,
    "ImCheckmark": ImCheckmark,
    "ImCheckmark2": ImCheckmark2,
    "ImSpellCheck": ImSpellCheck,
    "ImEnter": ImEnter,
    "ImExit": ImExit,
    "ImPlay2": ImPlay2,
    "ImPause": ImPause,
    "ImStop": ImStop,
    "ImPrevious": ImPrevious,
    "ImNext": ImNext,
    "ImBackward": ImBackward,
    "ImForward2": ImForward2,
    "ImPlay3": ImPlay3,
    "ImPause2": ImPause2,
    "ImStop2": ImStop2,
    "ImBackward2": ImBackward2,
    "ImForward3": ImForward3,
    "ImFirst": ImFirst,
    "ImLast": ImLast,
    "ImPrevious2": ImPrevious2,
    "ImNext2": ImNext2,
    "ImEject": ImEject,
    "ImVolumeHigh": ImVolumeHigh,
    "ImVolumeMedium": ImVolumeMedium,
    "ImVolumeLow": ImVolumeLow,
    "ImVolumeMute": ImVolumeMute,
    "ImVolumeMute2": ImVolumeMute2,
    "ImVolumeIncrease": ImVolumeIncrease,
    "ImVolumeDecrease": ImVolumeDecrease,
    "ImLoop": ImLoop,
    "ImLoop2": ImLoop2,
    "ImInfinite": ImInfinite,
    "ImShuffle": ImShuffle,
    "ImArrowUpLeft": ImArrowUpLeft,
    "ImArrowUp": ImArrowUp,
    "ImArrowUpRight": ImArrowUpRight,
    "ImArrowRight": ImArrowRight,
    "ImArrowDownRight": ImArrowDownRight,
    "ImArrowDown": ImArrowDown,
    "ImArrowDownLeft": ImArrowDownLeft,
    "ImArrowLeft": ImArrowLeft,
    "ImArrowUpLeft2": ImArrowUpLeft2,
    "ImArrowUp2": ImArrowUp2,
    "ImArrowUpRight2": ImArrowUpRight2,
    "ImArrowRight2": ImArrowRight2,
    "ImArrowDownRight2": ImArrowDownRight2,
    "ImArrowDown2": ImArrowDown2,
    "ImArrowDownLeft2": ImArrowDownLeft2,
    "ImArrowLeft2": ImArrowLeft2,
    "ImCircleUp": ImCircleUp,
    "ImCircleRight": ImCircleRight,
    "ImCircleDown": ImCircleDown,
    "ImCircleLeft": ImCircleLeft,
    "ImTab": ImTab,
    "ImMoveUp": ImMoveUp,
    "ImMoveDown": ImMoveDown,
    "ImSortAlphaAsc": ImSortAlphaAsc,
    "ImSortAlphaDesc": ImSortAlphaDesc,
    "ImSortNumericAsc": ImSortNumericAsc,
    "ImSortNumbericDesc": ImSortNumbericDesc,
    "ImSortAmountAsc": ImSortAmountAsc,
    "ImSortAmountDesc": ImSortAmountDesc,
    "ImCommand": ImCommand,
    "ImShift": ImShift,
    "ImCtrl": ImCtrl,
    "ImOpt": ImOpt,
    "ImCheckboxChecked": ImCheckboxChecked,
    "ImCheckboxUnchecked": ImCheckboxUnchecked,
    "ImRadioChecked": ImRadioChecked,
    "ImRadioChecked2": ImRadioChecked2,
    "ImRadioUnchecked": ImRadioUnchecked,
    "ImCrop": ImCrop,
    "ImMakeGroup": ImMakeGroup,
    "ImUngroup": ImUngroup,
    "ImScissors": ImScissors,
    "ImFilter": ImFilter,
    "ImFont": ImFont,
    "ImLigature": ImLigature,
    "ImLigature2": ImLigature2,
    "ImTextHeight": ImTextHeight,
    "ImTextWidth": ImTextWidth,
    "ImFontSize": ImFontSize,
    "ImBold": ImBold,
    "ImUnderline": ImUnderline,
    "ImItalic": ImItalic,
    "ImStrikethrough": ImStrikethrough,
    "ImOmega": ImOmega,
    "ImSigma": ImSigma,
    "ImPageBreak": ImPageBreak,
    "ImSuperscript": ImSuperscript,
    "ImSubscript": ImSubscript,
    "ImSuperscript2": ImSuperscript2,
    "ImSubscript2": ImSubscript2,
    "ImTextColor": ImTextColor,
    "ImPagebreak": ImPagebreak,
    "ImClearFormatting": ImClearFormatting,
    "ImTable": ImTable,
    "ImTable2": ImTable2,
    "ImInsertTemplate": ImInsertTemplate,
    "ImPilcrow": ImPilcrow,
    "ImLtr": ImLtr,
    "ImRtl": ImRtl,
    "ImSection": ImSection,
    "ImParagraphLeft": ImParagraphLeft,
    "ImParagraphCenter": ImParagraphCenter,
    "ImParagraphRight": ImParagraphRight,
    "ImParagraphJustify": ImParagraphJustify,
    "ImIndentIncrease": ImIndentIncrease,
    "ImIndentDecrease": ImIndentDecrease,
    "ImShare": ImShare,
    "ImNewTab": ImNewTab,
    "ImEmbed": ImEmbed,
    "ImEmbed2": ImEmbed2,
    "ImTerminal": ImTerminal,
    "ImShare2": ImShare2,
    "ImMail": ImMail,
    "ImMail2": ImMail2,
    "ImMail3": ImMail3,
    "ImMail4": ImMail4,
    "ImAmazon": ImAmazon,
    "ImGoogle": ImGoogle,
    "ImGoogle2": ImGoogle2,
    "ImGoogle3": ImGoogle3,
    "ImGooglePlus": ImGooglePlus,
    "ImGooglePlus2": ImGooglePlus2,
    "ImGooglePlus3": ImGooglePlus3,
    "ImHangouts": ImHangouts,
    "ImGoogleDrive": ImGoogleDrive,
    "ImFacebook": ImFacebook,
    "ImFacebook2": ImFacebook2,
    "ImInstagram": ImInstagram,
    "ImWhatsapp": ImWhatsapp,
    "ImSpotify": ImSpotify,
    "ImTelegram": ImTelegram,
    "ImTwitter": ImTwitter,
    "ImVine": ImVine,
    "ImVk": ImVk,
    "ImRenren": ImRenren,
    "ImSinaWeibo": ImSinaWeibo,
    "ImRss": ImRss,
    "ImRss2": ImRss2,
    "ImYoutube": ImYoutube,
    "ImYoutube2": ImYoutube2,
    "ImTwitch": ImTwitch,
    "ImVimeo": ImVimeo,
    "ImVimeo2": ImVimeo2,
    "ImLanyrd": ImLanyrd,
    "ImFlickr": ImFlickr,
    "ImFlickr2": ImFlickr2,
    "ImFlickr3": ImFlickr3,
    "ImFlickr4": ImFlickr4,
    "ImDribbble": ImDribbble,
    "ImBehance": ImBehance,
    "ImBehance2": ImBehance2,
    "ImDeviantart": ImDeviantart,
    "Im500Px": Im500Px,
    "ImSteam": ImSteam,
    "ImSteam2": ImSteam2,
    "ImDropbox": ImDropbox,
    "ImOnedrive": ImOnedrive,
    "ImGithub": ImGithub,
    "ImNpm": ImNpm,
    "ImBasecamp": ImBasecamp,
    "ImTrello": ImTrello,
    "ImWordpress": ImWordpress,
    "ImJoomla": ImJoomla,
    "ImEllo": ImEllo,
    "ImBlogger": ImBlogger,
    "ImBlogger2": ImBlogger2,
    "ImTumblr": ImTumblr,
    "ImTumblr2": ImTumblr2,
    "ImYahoo": ImYahoo,
    "ImYahoo2": ImYahoo2,
    "ImTux": ImTux,
    "ImAppleinc": ImAppleinc,
    "ImFinder": ImFinder,
    "ImAndroid": ImAndroid,
    "ImWindows": ImWindows,
    "ImWindows8": ImWindows8,
    "ImSoundcloud": ImSoundcloud,
    "ImSoundcloud2": ImSoundcloud2,
    "ImSkype": ImSkype,
    "ImReddit": ImReddit,
    "ImHackernews": ImHackernews,
    "ImWikipedia": ImWikipedia,
    "ImLinkedin": ImLinkedin,
    "ImLinkedin2": ImLinkedin2,
    "ImLastfm": ImLastfm,
    "ImLastfm2": ImLastfm2,
    "ImDelicious": ImDelicious,
    "ImStumbleupon": ImStumbleupon,
    "ImStumbleupon2": ImStumbleupon2,
    "ImStackoverflow": ImStackoverflow,
    "ImPinterest": ImPinterest,
    "ImPinterest2": ImPinterest2,
    "ImXing": ImXing,
    "ImXing2": ImXing2,
    "ImFlattr": ImFlattr,
    "ImFoursquare": ImFoursquare,
    "ImYelp": ImYelp,
    "ImPaypal": ImPaypal,
    "ImChrome": ImChrome,
    "ImFirefox": ImFirefox,
    "ImIe": ImIe,
    "ImEdge": ImEdge,
    "ImSafari": ImSafari,
    "ImOpera": ImOpera,
    "ImFilePdf": ImFilePdf,
    "ImFileOpenoffice": ImFileOpenoffice,
    "ImFileWord": ImFileWord,
    "ImFileExcel": ImFileExcel,
    "ImLibreoffice": ImLibreoffice,
    "ImHtmlFive": ImHtmlFive,
    "ImHtmlFive2": ImHtmlFive2,
    "ImCss3": ImCss3,
    "ImGit": ImGit,
    "ImCodepen": ImCodepen,
    "ImSvg": ImSvg,
    "ImIcoMoon": ImIcoMoon
}