import { 
    IoIosAddCircleOutline,
IoIosAddCircle,
IoIosAdd,
IoIosAirplane,
IoIosAlarm,
IoIosAlbums,
IoIosAlert,
IoIosAmericanFootball,
IoIosAnalytics,
IoIosAperture,
IoIosApps,
IoIosAppstore,
IoIosArchive,
IoIosArrowBack,
IoIosArrowDown,
IoIosArrowDropdownCircle,
IoIosArrowDropdown,
IoIosArrowDropleftCircle,
IoIosArrowDropleft,
IoIosArrowDroprightCircle,
IoIosArrowDropright,
IoIosArrowDropupCircle,
IoIosArrowDropup,
IoIosArrowForward,
IoIosArrowRoundBack,
IoIosArrowRoundDown,
IoIosArrowRoundForward,
IoIosArrowRoundUp,
IoIosArrowUp,
IoIosAt,
IoIosAttach,
IoIosBackspace,
IoIosBarcode,
IoIosBaseball,
IoIosBasket,
IoIosBasketball,
IoIosBatteryCharging,
IoIosBatteryDead,
IoIosBatteryFull,
IoIosBeaker,
IoIosBed,
IoIosBeer,
IoIosBicycle,
IoIosBluetooth,
IoIosBoat,
IoIosBody,
IoIosBonfire,
IoIosBook,
IoIosBookmark,
IoIosBookmarks,
IoIosBowtie,
IoIosBriefcase,
IoIosBrowsers,
IoIosBrush,
IoIosBug,
IoIosBuild,
IoIosBulb,
IoIosBus,
IoIosBusiness,
IoIosCafe,
IoIosCalculator,
IoIosCalendar,
IoIosCall,
IoIosCamera,
IoIosCar,
IoIosCard,
IoIosCart,
IoIosCash,
IoIosCellular,
IoIosChatboxes,
IoIosChatbubbles,
IoIosCheckboxOutline,
IoIosCheckbox,
IoIosCheckmarkCircleOutline,
IoIosCheckmarkCircle,
IoIosCheckmark,
IoIosClipboard,
IoIosClock,
IoIosCloseCircleOutline,
IoIosCloseCircle,
IoIosClose,
IoIosCloudCircle,
IoIosCloudDone,
IoIosCloudDownload,
IoIosCloudOutline,
IoIosCloudUpload,
IoIosCloud,
IoIosCloudyNight,
IoIosCloudy,
IoIosCodeDownload,
IoIosCodeWorking,
IoIosCode,
IoIosCog,
IoIosColorFill,
IoIosColorFilter,
IoIosColorPalette,
IoIosColorWand,
IoIosCompass,
IoIosConstruct,
IoIosContact,
IoIosContacts,
IoIosContract,
IoIosContrast,
IoIosCopy,
IoIosCreate,
IoIosCrop,
IoIosCube,
IoIosCut,
IoIosDesktop,
IoIosDisc,
IoIosDocument,
IoIosDoneAll,
IoIosDownload,
IoIosEasel,
IoIosEgg,
IoIosExit,
IoIosExpand,
IoIosEyeOff,
IoIosEye,
IoIosFastforward,
IoIosFemale,
IoIosFiling,
IoIosFilm,
IoIosFingerPrint,
IoIosFitness,
IoIosFlag,
IoIosFlame,
IoIosFlashOff,
IoIosFlash,
IoIosFlashlight,
IoIosFlask,
IoIosFlower,
IoIosFolderOpen,
IoIosFolder,
IoIosFootball,
IoIosFunnel,
IoIosGift,
IoIosGitBranch,
IoIosGitCommit,
IoIosGitCompare,
IoIosGitMerge,
IoIosGitNetwork,
IoIosGitPullRequest,
IoIosGlasses,
IoIosGlobe,
IoIosGrid,
IoIosHammer,
IoIosHand,
IoIosHappy,
IoIosHeadset,
IoIosHeartDislike,
IoIosHeartEmpty,
IoIosHeartHalf,
IoIosHeart,
IoIosHelpBuoy,
IoIosHelpCircleOutline,
IoIosHelpCircle,
IoIosHelp,
IoIosHome,
IoIosHourglass,
IoIosIceCream,
IoIosImage,
IoIosImages,
IoIosInfinite,
IoIosInformationCircleOutline,
IoIosInformationCircle,
IoIosInformation,
IoIosJet,
IoIosJournal,
IoIosKey,
IoIosKeypad,
IoIosLaptop,
IoIosLeaf,
IoIosLink,
IoIosListBox,
IoIosList,
IoIosLocate,
IoIosLock,
IoIosLogIn,
IoIosLogOut,
IoIosMagnet,
IoIosMailOpen,
IoIosMailUnread,
IoIosMail,
IoIosMale,
IoIosMan,
IoIosMap,
IoIosMedal,
IoIosMedical,
IoIosMedkit,
IoIosMegaphone,
IoIosMenu,
IoIosMicOff,
IoIosMic,
IoIosMicrophone,
IoIosMoon,
IoIosMore,
IoIosMove,
IoIosMusicalNote,
IoIosMusicalNotes,
IoIosNavigate,
IoIosNotificationsOff,
IoIosNotificationsOutline,
IoIosNotifications,
IoIosNuclear,
IoIosNutrition,
IoIosOpen,
IoIosOptions,
IoIosOutlet,
IoIosPaperPlane,
IoIosPaper,
IoIosPartlySunny,
IoIosPause,
IoIosPaw,
IoIosPeople,
IoIosPersonAdd,
IoIosPerson,
IoIosPhoneLandscape,
IoIosPhonePortrait,
IoIosPhotos,
IoIosPie,
IoIosPin,
IoIosPint,
IoIosPizza,
IoIosPlanet,
IoIosPlayCircle,
IoIosPlay,
IoIosPodium,
IoIosPower,
IoIosPricetag,
IoIosPricetags,
IoIosPrint,
IoIosPulse,
IoIosQrScanner,
IoIosQuote,
IoIosRadioButtonOff,
IoIosRadioButtonOn,
IoIosRadio,
IoIosRainy,
IoIosRecording,
IoIosRedo,
IoIosRefreshCircle,
IoIosRefresh,
IoIosRemoveCircleOutline,
IoIosRemoveCircle,
IoIosRemove,
IoIosReorder,
IoIosRepeat,
IoIosResize,
IoIosRestaurant,
IoIosReturnLeft,
IoIosReturnRight,
IoIosReverseCamera,
IoIosRewind,
IoIosRibbon,
IoIosRocket,
IoIosRose,
IoIosSad,
IoIosSave,
IoIosSchool,
IoIosSearch,
IoIosSend,
IoIosSettings,
IoIosShareAlt,
IoIosShare,
IoIosShirt,
IoIosShuffle,
IoIosSkipBackward,
IoIosSkipForward,
IoIosSnow,
IoIosSpeedometer,
IoIosSquareOutline,
IoIosSquare,
IoIosStarHalf,
IoIosStarOutline,
IoIosStar,
IoIosStats,
IoIosStopwatch,
IoIosSubway,
IoIosSunny,
IoIosSwap,
IoIosSwitch,
IoIosSync,
IoIosTabletLandscape,
IoIosTabletPortrait,
IoIosTennisball,
IoIosText,
IoIosThermometer,
IoIosThumbsDown,
IoIosThumbsUp,
IoIosThunderstorm,
IoIosTime,
IoIosTimer,
IoIosToday,
IoIosTrain,
IoIosTransgender,
IoIosTrash,
IoIosTrendingDown,
IoIosTrendingUp,
IoIosTrophy,
IoIosTv,
IoIosUmbrella,
IoIosUndo,
IoIosUnlock,
IoIosVideocam,
IoIosVolumeHigh,
IoIosVolumeLow,
IoIosVolumeMute,
IoIosVolumeOff,
IoIosWalk,
IoIosWallet,
IoIosWarning,
IoIosWatch,
IoIosWater,
IoIosWifi,
IoIosWine,
IoIosWoman,
IoLogoAndroid,
IoLogoAngular,
IoLogoApple,
IoLogoBitbucket,
IoLogoBitcoin,
IoLogoBuffer,
IoLogoChrome,
IoLogoClosedCaptioning,
IoLogoCodepen,
IoLogoCss3,
IoLogoDesignernews,
IoLogoDribbble,
IoLogoDropbox,
IoLogoEuro,
IoLogoFacebook,
IoLogoFlickr,
IoLogoFoursquare,
IoLogoFreebsdDevil,
IoLogoGameControllerA,
IoLogoGameControllerB,
IoLogoGithub,
IoLogoGoogle,
IoLogoGoogleplus,
IoLogoHackernews,
IoLogoHtml5,
IoLogoInstagram,
IoLogoIonic,
IoLogoIonitron,
IoLogoJavascript,
IoLogoLinkedin,
IoLogoMarkdown,
IoLogoModelS,
IoLogoNoSmoking,
IoLogoNodejs,
IoLogoNpm,
IoLogoOctocat,
IoLogoPinterest,
IoLogoPlaystation,
IoLogoPolymer,
IoLogoPython,
IoLogoReddit,
IoLogoRss,
IoLogoSass,
IoLogoSkype,
IoLogoSlack,
IoLogoSnapchat,
IoLogoSteam,
IoLogoTumblr,
IoLogoTux,
IoLogoTwitch,
IoLogoTwitter,
IoLogoUsd,
IoLogoVimeo,
IoLogoVk,
IoLogoWhatsapp,
IoLogoWindows,
IoLogoWordpress,
IoLogoXbox,
IoLogoXing,
IoLogoYahoo,
IoLogoYen,
IoLogoYoutube,
IoMdAddCircleOutline,
IoMdAddCircle,
IoMdAdd,
IoMdAirplane,
IoMdAlarm,
IoMdAlbums,
IoMdAlert,
IoMdAmericanFootball,
IoMdAnalytics,
IoMdAperture,
IoMdApps,
IoMdAppstore,
IoMdArchive,
IoMdArrowBack,
IoMdArrowDown,
IoMdArrowDropdownCircle,
IoMdArrowDropdown,
IoMdArrowDropleftCircle,
IoMdArrowDropleft,
IoMdArrowDroprightCircle,
IoMdArrowDropright,
IoMdArrowDropupCircle,
IoMdArrowDropup,
IoMdArrowForward,
IoMdArrowRoundBack,
IoMdArrowRoundDown,
IoMdArrowRoundForward,
IoMdArrowRoundUp,
IoMdArrowUp,
IoMdAt,
IoMdAttach,
IoMdBackspace,
IoMdBarcode,
IoMdBaseball,
IoMdBasket,
IoMdBasketball,
IoMdBatteryCharging,
IoMdBatteryDead,
IoMdBatteryFull,
IoMdBeaker,
IoMdBed,
IoMdBeer,
IoMdBicycle,
IoMdBluetooth,
IoMdBoat,
IoMdBody,
IoMdBonfire,
IoMdBook,
IoMdBookmark,
IoMdBookmarks,
IoMdBowtie,
IoMdBriefcase,
IoMdBrowsers,
IoMdBrush,
IoMdBug,
IoMdBuild,
IoMdBulb,
IoMdBus,
IoMdBusiness,
IoMdCafe,
IoMdCalculator,
IoMdCalendar,
IoMdCall,
IoMdCamera,
IoMdCar,
IoMdCard,
IoMdCart,
IoMdCash,
IoMdCellular,
IoMdChatboxes,
IoMdChatbubbles,
IoMdCheckboxOutline,
IoMdCheckbox,
IoMdCheckmarkCircleOutline,
IoMdCheckmarkCircle,
IoMdCheckmark,
IoMdClipboard,
IoMdClock,
IoMdCloseCircleOutline,
IoMdCloseCircle,
IoMdClose,
IoMdCloudCircle,
IoMdCloudDone,
IoMdCloudDownload,
IoMdCloudOutline,
IoMdCloudUpload,
IoMdCloud,
IoMdCloudyNight,
IoMdCloudy,
IoMdCodeDownload,
IoMdCodeWorking,
IoMdCode,
IoMdCog,
IoMdColorFill,
IoMdColorFilter,
IoMdColorPalette,
IoMdColorWand,
IoMdCompass,
IoMdConstruct,
IoMdContact,
IoMdContacts,
IoMdContract,
IoMdContrast,
IoMdCopy,
IoMdCreate,
IoMdCrop,
IoMdCube,
IoMdCut,
IoMdDesktop,
IoMdDisc,
IoMdDocument,
IoMdDoneAll,
IoMdDownload,
IoMdEasel,
IoMdEgg,
IoMdExit,
IoMdExpand,
IoMdEyeOff,
IoMdEye,
IoMdFastforward,
IoMdFemale,
IoMdFiling,
IoMdFilm,
IoMdFingerPrint,
IoMdFitness,
IoMdFlag,
IoMdFlame,
IoMdFlashOff,
IoMdFlash,
IoMdFlashlight,
IoMdFlask,
IoMdFlower,
IoMdFolderOpen,
IoMdFolder,
IoMdFootball,
IoMdFunnel,
IoMdGift,
IoMdGitBranch,
IoMdGitCommit,
IoMdGitCompare,
IoMdGitMerge,
IoMdGitNetwork,
IoMdGitPullRequest,
IoMdGlasses,
IoMdGlobe,
IoMdGrid,
IoMdHammer,
IoMdHand,
IoMdHappy,
IoMdHeadset,
IoMdHeartDislike,
IoMdHeartEmpty,
IoMdHeartHalf,
IoMdHeart,
IoMdHelpBuoy,
IoMdHelpCircleOutline,
IoMdHelpCircle,
IoMdHelp,
IoMdHome,
IoMdHourglass,
IoMdIceCream,
IoMdImage,
IoMdImages,
IoMdInfinite,
IoMdInformationCircleOutline,
IoMdInformationCircle,
IoMdInformation,
IoMdJet,
IoMdJournal,
IoMdKey,
IoMdKeypad,
IoMdLaptop,
IoMdLeaf,
IoMdLink,
IoMdListBox,
IoMdList,
IoMdLocate,
IoMdLock,
IoMdLogIn,
IoMdLogOut,
IoMdMagnet,
IoMdMailOpen,
IoMdMailUnread,
IoMdMail,
IoMdMale,
IoMdMan,
IoMdMap,
IoMdMedal,
IoMdMedical,
IoMdMedkit,
IoMdMegaphone,
IoMdMenu,
IoMdMicOff,
IoMdMic,
IoMdMicrophone,
IoMdMoon,
IoMdMore,
IoMdMove,
IoMdMusicalNote,
IoMdMusicalNotes,
IoMdNavigate,
IoMdNotificationsOff,
IoMdNotificationsOutline,
IoMdNotifications,
IoMdNuclear,
IoMdNutrition,
IoMdOpen,
IoMdOptions,
IoMdOutlet,
IoMdPaperPlane,
IoMdPaper,
IoMdPartlySunny,
IoMdPause,
IoMdPaw,
IoMdPeople,
IoMdPersonAdd,
IoMdPerson,
IoMdPhoneLandscape,
IoMdPhonePortrait,
IoMdPhotos,
IoMdPie,
IoMdPin,
IoMdPint,
IoMdPizza,
IoMdPlanet,
IoMdPlayCircle,
IoMdPlay,
IoMdPodium,
IoMdPower,
IoMdPricetag,
IoMdPricetags,
IoMdPrint,
IoMdPulse,
IoMdQrScanner,
IoMdQuote,
IoMdRadioButtonOff,
IoMdRadioButtonOn,
IoMdRadio,
IoMdRainy,
IoMdRecording,
IoMdRedo,
IoMdRefreshCircle,
IoMdRefresh,
IoMdRemoveCircleOutline,
IoMdRemoveCircle,
IoMdRemove,
IoMdReorder,
IoMdRepeat,
IoMdResize,
IoMdRestaurant,
IoMdReturnLeft,
IoMdReturnRight,
IoMdReverseCamera,
IoMdRewind,
IoMdRibbon,
IoMdRocket,
IoMdRose,
IoMdSad,
IoMdSave,
IoMdSchool,
IoMdSearch,
IoMdSend,
IoMdSettings,
IoMdShareAlt,
IoMdShare,
IoMdShirt,
IoMdShuffle,
IoMdSkipBackward,
IoMdSkipForward,
IoMdSnow,
IoMdSpeedometer,
IoMdSquareOutline,
IoMdSquare,
IoMdStarHalf,
IoMdStarOutline,
IoMdStar,
IoMdStats,
IoMdStopwatch,
IoMdSubway,
IoMdSunny,
IoMdSwap,
IoMdSwitch,
IoMdSync,
IoMdTabletLandscape,
IoMdTabletPortrait,
IoMdTennisball,
IoMdText,
IoMdThermometer,
IoMdThumbsDown,
IoMdThumbsUp,
IoMdThunderstorm,
IoMdTime,
IoMdTimer,
IoMdToday,
IoMdTrain,
IoMdTransgender,
IoMdTrash,
IoMdTrendingDown,
IoMdTrendingUp,
IoMdTrophy,
IoMdTv,
IoMdUmbrella,
IoMdUndo,
IoMdUnlock,
IoMdVideocam,
IoMdVolumeHigh,
IoMdVolumeLow,
IoMdVolumeMute,
IoMdVolumeOff,
IoMdWalk,
IoMdWallet,
IoMdWarning,
IoMdWatch,
IoMdWater,
IoMdWifi,
IoMdWine,
IoMdWoman
 } from "react-icons/io";

export const IonIcons4 = {
    "IoIosAddCircleOutline": IoIosAddCircleOutline,
    "IoIosAddCircle": IoIosAddCircle,
    "IoIosAdd": IoIosAdd,
    "IoIosAirplane": IoIosAirplane,
    "IoIosAlarm": IoIosAlarm,
    "IoIosAlbums": IoIosAlbums,
    "IoIosAlert": IoIosAlert,
    "IoIosAmericanFootball": IoIosAmericanFootball,
    "IoIosAnalytics": IoIosAnalytics,
    "IoIosAperture": IoIosAperture,
    "IoIosApps": IoIosApps,
    "IoIosAppstore": IoIosAppstore,
    "IoIosArchive": IoIosArchive,
    "IoIosArrowBack": IoIosArrowBack,
    "IoIosArrowDown": IoIosArrowDown,
    "IoIosArrowDropdownCircle": IoIosArrowDropdownCircle,
    "IoIosArrowDropdown": IoIosArrowDropdown,
    "IoIosArrowDropleftCircle": IoIosArrowDropleftCircle,
    "IoIosArrowDropleft": IoIosArrowDropleft,
    "IoIosArrowDroprightCircle": IoIosArrowDroprightCircle,
    "IoIosArrowDropright": IoIosArrowDropright,
    "IoIosArrowDropupCircle": IoIosArrowDropupCircle,
    "IoIosArrowDropup": IoIosArrowDropup,
    "IoIosArrowForward": IoIosArrowForward,
    "IoIosArrowRoundBack": IoIosArrowRoundBack,
    "IoIosArrowRoundDown": IoIosArrowRoundDown,
    "IoIosArrowRoundForward": IoIosArrowRoundForward,
    "IoIosArrowRoundUp": IoIosArrowRoundUp,
    "IoIosArrowUp": IoIosArrowUp,
    "IoIosAt": IoIosAt,
    "IoIosAttach": IoIosAttach,
    "IoIosBackspace": IoIosBackspace,
    "IoIosBarcode": IoIosBarcode,
    "IoIosBaseball": IoIosBaseball,
    "IoIosBasket": IoIosBasket,
    "IoIosBasketball": IoIosBasketball,
    "IoIosBatteryCharging": IoIosBatteryCharging,
    "IoIosBatteryDead": IoIosBatteryDead,
    "IoIosBatteryFull": IoIosBatteryFull,
    "IoIosBeaker": IoIosBeaker,
    "IoIosBed": IoIosBed,
    "IoIosBeer": IoIosBeer,
    "IoIosBicycle": IoIosBicycle,
    "IoIosBluetooth": IoIosBluetooth,
    "IoIosBoat": IoIosBoat,
    "IoIosBody": IoIosBody,
    "IoIosBonfire": IoIosBonfire,
    "IoIosBook": IoIosBook,
    "IoIosBookmark": IoIosBookmark,
    "IoIosBookmarks": IoIosBookmarks,
    "IoIosBowtie": IoIosBowtie,
    "IoIosBriefcase": IoIosBriefcase,
    "IoIosBrowsers": IoIosBrowsers,
    "IoIosBrush": IoIosBrush,
    "IoIosBug": IoIosBug,
    "IoIosBuild": IoIosBuild,
    "IoIosBulb": IoIosBulb,
    "IoIosBus": IoIosBus,
    "IoIosBusiness": IoIosBusiness,
    "IoIosCafe": IoIosCafe,
    "IoIosCalculator": IoIosCalculator,
    "IoIosCalendar": IoIosCalendar,
    "IoIosCall": IoIosCall,
    "IoIosCamera": IoIosCamera,
    "IoIosCar": IoIosCar,
    "IoIosCard": IoIosCard,
    "IoIosCart": IoIosCart,
    "IoIosCash": IoIosCash,
    "IoIosCellular": IoIosCellular,
    "IoIosChatboxes": IoIosChatboxes,
    "IoIosChatbubbles": IoIosChatbubbles,
    "IoIosCheckboxOutline": IoIosCheckboxOutline,
    "IoIosCheckbox": IoIosCheckbox,
    "IoIosCheckmarkCircleOutline": IoIosCheckmarkCircleOutline,
    "IoIosCheckmarkCircle": IoIosCheckmarkCircle,
    "IoIosCheckmark": IoIosCheckmark,
    "IoIosClipboard": IoIosClipboard,
    "IoIosClock": IoIosClock,
    "IoIosCloseCircleOutline": IoIosCloseCircleOutline,
    "IoIosCloseCircle": IoIosCloseCircle,
    "IoIosClose": IoIosClose,
    "IoIosCloudCircle": IoIosCloudCircle,
    "IoIosCloudDone": IoIosCloudDone,
    "IoIosCloudDownload": IoIosCloudDownload,
    "IoIosCloudOutline": IoIosCloudOutline,
    "IoIosCloudUpload": IoIosCloudUpload,
    "IoIosCloud": IoIosCloud,
    "IoIosCloudyNight": IoIosCloudyNight,
    "IoIosCloudy": IoIosCloudy,
    "IoIosCodeDownload": IoIosCodeDownload,
    "IoIosCodeWorking": IoIosCodeWorking,
    "IoIosCode": IoIosCode,
    "IoIosCog": IoIosCog,
    "IoIosColorFill": IoIosColorFill,
    "IoIosColorFilter": IoIosColorFilter,
    "IoIosColorPalette": IoIosColorPalette,
    "IoIosColorWand": IoIosColorWand,
    "IoIosCompass": IoIosCompass,
    "IoIosConstruct": IoIosConstruct,
    "IoIosContact": IoIosContact,
    "IoIosContacts": IoIosContacts,
    "IoIosContract": IoIosContract,
    "IoIosContrast": IoIosContrast,
    "IoIosCopy": IoIosCopy,
    "IoIosCreate": IoIosCreate,
    "IoIosCrop": IoIosCrop,
    "IoIosCube": IoIosCube,
    "IoIosCut": IoIosCut,
    "IoIosDesktop": IoIosDesktop,
    "IoIosDisc": IoIosDisc,
    "IoIosDocument": IoIosDocument,
    "IoIosDoneAll": IoIosDoneAll,
    "IoIosDownload": IoIosDownload,
    "IoIosEasel": IoIosEasel,
    "IoIosEgg": IoIosEgg,
    "IoIosExit": IoIosExit,
    "IoIosExpand": IoIosExpand,
    "IoIosEyeOff": IoIosEyeOff,
    "IoIosEye": IoIosEye,
    "IoIosFastforward": IoIosFastforward,
    "IoIosFemale": IoIosFemale,
    "IoIosFiling": IoIosFiling,
    "IoIosFilm": IoIosFilm,
    "IoIosFingerPrint": IoIosFingerPrint,
    "IoIosFitness": IoIosFitness,
    "IoIosFlag": IoIosFlag,
    "IoIosFlame": IoIosFlame,
    "IoIosFlashOff": IoIosFlashOff,
    "IoIosFlash": IoIosFlash,
    "IoIosFlashlight": IoIosFlashlight,
    "IoIosFlask": IoIosFlask,
    "IoIosFlower": IoIosFlower,
    "IoIosFolderOpen": IoIosFolderOpen,
    "IoIosFolder": IoIosFolder,
    "IoIosFootball": IoIosFootball,
    "IoIosFunnel": IoIosFunnel,
    "IoIosGift": IoIosGift,
    "IoIosGitBranch": IoIosGitBranch,
    "IoIosGitCommit": IoIosGitCommit,
    "IoIosGitCompare": IoIosGitCompare,
    "IoIosGitMerge": IoIosGitMerge,
    "IoIosGitNetwork": IoIosGitNetwork,
    "IoIosGitPullRequest": IoIosGitPullRequest,
    "IoIosGlasses": IoIosGlasses,
    "IoIosGlobe": IoIosGlobe,
    "IoIosGrid": IoIosGrid,
    "IoIosHammer": IoIosHammer,
    "IoIosHand": IoIosHand,
    "IoIosHappy": IoIosHappy,
    "IoIosHeadset": IoIosHeadset,
    "IoIosHeartDislike": IoIosHeartDislike,
    "IoIosHeartEmpty": IoIosHeartEmpty,
    "IoIosHeartHalf": IoIosHeartHalf,
    "IoIosHeart": IoIosHeart,
    "IoIosHelpBuoy": IoIosHelpBuoy,
    "IoIosHelpCircleOutline": IoIosHelpCircleOutline,
    "IoIosHelpCircle": IoIosHelpCircle,
    "IoIosHelp": IoIosHelp,
    "IoIosHome": IoIosHome,
    "IoIosHourglass": IoIosHourglass,
    "IoIosIceCream": IoIosIceCream,
    "IoIosImage": IoIosImage,
    "IoIosImages": IoIosImages,
    "IoIosInfinite": IoIosInfinite,
    "IoIosInformationCircleOutline": IoIosInformationCircleOutline,
    "IoIosInformationCircle": IoIosInformationCircle,
    "IoIosInformation": IoIosInformation,
    "IoIosJet": IoIosJet,
    "IoIosJournal": IoIosJournal,
    "IoIosKey": IoIosKey,
    "IoIosKeypad": IoIosKeypad,
    "IoIosLaptop": IoIosLaptop,
    "IoIosLeaf": IoIosLeaf,
    "IoIosLink": IoIosLink,
    "IoIosListBox": IoIosListBox,
    "IoIosList": IoIosList,
    "IoIosLocate": IoIosLocate,
    "IoIosLock": IoIosLock,
    "IoIosLogIn": IoIosLogIn,
    "IoIosLogOut": IoIosLogOut,
    "IoIosMagnet": IoIosMagnet,
    "IoIosMailOpen": IoIosMailOpen,
    "IoIosMailUnread": IoIosMailUnread,
    "IoIosMail": IoIosMail,
    "IoIosMale": IoIosMale,
    "IoIosMan": IoIosMan,
    "IoIosMap": IoIosMap,
    "IoIosMedal": IoIosMedal,
    "IoIosMedical": IoIosMedical,
    "IoIosMedkit": IoIosMedkit,
    "IoIosMegaphone": IoIosMegaphone,
    "IoIosMenu": IoIosMenu,
    "IoIosMicOff": IoIosMicOff,
    "IoIosMic": IoIosMic,
    "IoIosMicrophone": IoIosMicrophone,
    "IoIosMoon": IoIosMoon,
    "IoIosMore": IoIosMore,
    "IoIosMove": IoIosMove,
    "IoIosMusicalNote": IoIosMusicalNote,
    "IoIosMusicalNotes": IoIosMusicalNotes,
    "IoIosNavigate": IoIosNavigate,
    "IoIosNotificationsOff": IoIosNotificationsOff,
    "IoIosNotificationsOutline": IoIosNotificationsOutline,
    "IoIosNotifications": IoIosNotifications,
    "IoIosNuclear": IoIosNuclear,
    "IoIosNutrition": IoIosNutrition,
    "IoIosOpen": IoIosOpen,
    "IoIosOptions": IoIosOptions,
    "IoIosOutlet": IoIosOutlet,
    "IoIosPaperPlane": IoIosPaperPlane,
    "IoIosPaper": IoIosPaper,
    "IoIosPartlySunny": IoIosPartlySunny,
    "IoIosPause": IoIosPause,
    "IoIosPaw": IoIosPaw,
    "IoIosPeople": IoIosPeople,
    "IoIosPersonAdd": IoIosPersonAdd,
    "IoIosPerson": IoIosPerson,
    "IoIosPhoneLandscape": IoIosPhoneLandscape,
    "IoIosPhonePortrait": IoIosPhonePortrait,
    "IoIosPhotos": IoIosPhotos,
    "IoIosPie": IoIosPie,
    "IoIosPin": IoIosPin,
    "IoIosPint": IoIosPint,
    "IoIosPizza": IoIosPizza,
    "IoIosPlanet": IoIosPlanet,
    "IoIosPlayCircle": IoIosPlayCircle,
    "IoIosPlay": IoIosPlay,
    "IoIosPodium": IoIosPodium,
    "IoIosPower": IoIosPower,
    "IoIosPricetag": IoIosPricetag,
    "IoIosPricetags": IoIosPricetags,
    "IoIosPrint": IoIosPrint,
    "IoIosPulse": IoIosPulse,
    "IoIosQrScanner": IoIosQrScanner,
    "IoIosQuote": IoIosQuote,
    "IoIosRadioButtonOff": IoIosRadioButtonOff,
    "IoIosRadioButtonOn": IoIosRadioButtonOn,
    "IoIosRadio": IoIosRadio,
    "IoIosRainy": IoIosRainy,
    "IoIosRecording": IoIosRecording,
    "IoIosRedo": IoIosRedo,
    "IoIosRefreshCircle": IoIosRefreshCircle,
    "IoIosRefresh": IoIosRefresh,
    "IoIosRemoveCircleOutline": IoIosRemoveCircleOutline,
    "IoIosRemoveCircle": IoIosRemoveCircle,
    "IoIosRemove": IoIosRemove,
    "IoIosReorder": IoIosReorder,
    "IoIosRepeat": IoIosRepeat,
    "IoIosResize": IoIosResize,
    "IoIosRestaurant": IoIosRestaurant,
    "IoIosReturnLeft": IoIosReturnLeft,
    "IoIosReturnRight": IoIosReturnRight,
    "IoIosReverseCamera": IoIosReverseCamera,
    "IoIosRewind": IoIosRewind,
    "IoIosRibbon": IoIosRibbon,
    "IoIosRocket": IoIosRocket,
    "IoIosRose": IoIosRose,
    "IoIosSad": IoIosSad,
    "IoIosSave": IoIosSave,
    "IoIosSchool": IoIosSchool,
    "IoIosSearch": IoIosSearch,
    "IoIosSend": IoIosSend,
    "IoIosSettings": IoIosSettings,
    "IoIosShareAlt": IoIosShareAlt,
    "IoIosShare": IoIosShare,
    "IoIosShirt": IoIosShirt,
    "IoIosShuffle": IoIosShuffle,
    "IoIosSkipBackward": IoIosSkipBackward,
    "IoIosSkipForward": IoIosSkipForward,
    "IoIosSnow": IoIosSnow,
    "IoIosSpeedometer": IoIosSpeedometer,
    "IoIosSquareOutline": IoIosSquareOutline,
    "IoIosSquare": IoIosSquare,
    "IoIosStarHalf": IoIosStarHalf,
    "IoIosStarOutline": IoIosStarOutline,
    "IoIosStar": IoIosStar,
    "IoIosStats": IoIosStats,
    "IoIosStopwatch": IoIosStopwatch,
    "IoIosSubway": IoIosSubway,
    "IoIosSunny": IoIosSunny,
    "IoIosSwap": IoIosSwap,
    "IoIosSwitch": IoIosSwitch,
    "IoIosSync": IoIosSync,
    "IoIosTabletLandscape": IoIosTabletLandscape,
    "IoIosTabletPortrait": IoIosTabletPortrait,
    "IoIosTennisball": IoIosTennisball,
    "IoIosText": IoIosText,
    "IoIosThermometer": IoIosThermometer,
    "IoIosThumbsDown": IoIosThumbsDown,
    "IoIosThumbsUp": IoIosThumbsUp,
    "IoIosThunderstorm": IoIosThunderstorm,
    "IoIosTime": IoIosTime,
    "IoIosTimer": IoIosTimer,
    "IoIosToday": IoIosToday,
    "IoIosTrain": IoIosTrain,
    "IoIosTransgender": IoIosTransgender,
    "IoIosTrash": IoIosTrash,
    "IoIosTrendingDown": IoIosTrendingDown,
    "IoIosTrendingUp": IoIosTrendingUp,
    "IoIosTrophy": IoIosTrophy,
    "IoIosTv": IoIosTv,
    "IoIosUmbrella": IoIosUmbrella,
    "IoIosUndo": IoIosUndo,
    "IoIosUnlock": IoIosUnlock,
    "IoIosVideocam": IoIosVideocam,
    "IoIosVolumeHigh": IoIosVolumeHigh,
    "IoIosVolumeLow": IoIosVolumeLow,
    "IoIosVolumeMute": IoIosVolumeMute,
    "IoIosVolumeOff": IoIosVolumeOff,
    "IoIosWalk": IoIosWalk,
    "IoIosWallet": IoIosWallet,
    "IoIosWarning": IoIosWarning,
    "IoIosWatch": IoIosWatch,
    "IoIosWater": IoIosWater,
    "IoIosWifi": IoIosWifi,
    "IoIosWine": IoIosWine,
    "IoIosWoman": IoIosWoman,
    "IoLogoAndroid": IoLogoAndroid,
    "IoLogoAngular": IoLogoAngular,
    "IoLogoApple": IoLogoApple,
    "IoLogoBitbucket": IoLogoBitbucket,
    "IoLogoBitcoin": IoLogoBitcoin,
    "IoLogoBuffer": IoLogoBuffer,
    "IoLogoChrome": IoLogoChrome,
    "IoLogoClosedCaptioning": IoLogoClosedCaptioning,
    "IoLogoCodepen": IoLogoCodepen,
    "IoLogoCss3": IoLogoCss3,
    "IoLogoDesignernews": IoLogoDesignernews,
    "IoLogoDribbble": IoLogoDribbble,
    "IoLogoDropbox": IoLogoDropbox,
    "IoLogoEuro": IoLogoEuro,
    "IoLogoFacebook": IoLogoFacebook,
    "IoLogoFlickr": IoLogoFlickr,
    "IoLogoFoursquare": IoLogoFoursquare,
    "IoLogoFreebsdDevil": IoLogoFreebsdDevil,
    "IoLogoGameControllerA": IoLogoGameControllerA,
    "IoLogoGameControllerB": IoLogoGameControllerB,
    "IoLogoGithub": IoLogoGithub,
    "IoLogoGoogle": IoLogoGoogle,
    "IoLogoGoogleplus": IoLogoGoogleplus,
    "IoLogoHackernews": IoLogoHackernews,
    "IoLogoHtml5": IoLogoHtml5,
    "IoLogoInstagram": IoLogoInstagram,
    "IoLogoIonic": IoLogoIonic,
    "IoLogoIonitron": IoLogoIonitron,
    "IoLogoJavascript": IoLogoJavascript,
    "IoLogoLinkedin": IoLogoLinkedin,
    "IoLogoMarkdown": IoLogoMarkdown,
    "IoLogoModelS": IoLogoModelS,
    "IoLogoNoSmoking": IoLogoNoSmoking,
    "IoLogoNodejs": IoLogoNodejs,
    "IoLogoNpm": IoLogoNpm,
    "IoLogoOctocat": IoLogoOctocat,
    "IoLogoPinterest": IoLogoPinterest,
    "IoLogoPlaystation": IoLogoPlaystation,
    "IoLogoPolymer": IoLogoPolymer,
    "IoLogoPython": IoLogoPython,
    "IoLogoReddit": IoLogoReddit,
    "IoLogoRss": IoLogoRss,
    "IoLogoSass": IoLogoSass,
    "IoLogoSkype": IoLogoSkype,
    "IoLogoSlack": IoLogoSlack,
    "IoLogoSnapchat": IoLogoSnapchat,
    "IoLogoSteam": IoLogoSteam,
    "IoLogoTumblr": IoLogoTumblr,
    "IoLogoTux": IoLogoTux,
    "IoLogoTwitch": IoLogoTwitch,
    "IoLogoTwitter": IoLogoTwitter,
    "IoLogoUsd": IoLogoUsd,
    "IoLogoVimeo": IoLogoVimeo,
    "IoLogoVk": IoLogoVk,
    "IoLogoWhatsapp": IoLogoWhatsapp,
    "IoLogoWindows": IoLogoWindows,
    "IoLogoWordpress": IoLogoWordpress,
    "IoLogoXbox": IoLogoXbox,
    "IoLogoXing": IoLogoXing,
    "IoLogoYahoo": IoLogoYahoo,
    "IoLogoYen": IoLogoYen,
    "IoLogoYoutube": IoLogoYoutube,
    "IoMdAddCircleOutline": IoMdAddCircleOutline,
    "IoMdAddCircle": IoMdAddCircle,
    "IoMdAdd": IoMdAdd,
    "IoMdAirplane": IoMdAirplane,
    "IoMdAlarm": IoMdAlarm,
    "IoMdAlbums": IoMdAlbums,
    "IoMdAlert": IoMdAlert,
    "IoMdAmericanFootball": IoMdAmericanFootball,
    "IoMdAnalytics": IoMdAnalytics,
    "IoMdAperture": IoMdAperture,
    "IoMdApps": IoMdApps,
    "IoMdAppstore": IoMdAppstore,
    "IoMdArchive": IoMdArchive,
    "IoMdArrowBack": IoMdArrowBack,
    "IoMdArrowDown": IoMdArrowDown,
    "IoMdArrowDropdownCircle": IoMdArrowDropdownCircle,
    "IoMdArrowDropdown": IoMdArrowDropdown,
    "IoMdArrowDropleftCircle": IoMdArrowDropleftCircle,
    "IoMdArrowDropleft": IoMdArrowDropleft,
    "IoMdArrowDroprightCircle": IoMdArrowDroprightCircle,
    "IoMdArrowDropright": IoMdArrowDropright,
    "IoMdArrowDropupCircle": IoMdArrowDropupCircle,
    "IoMdArrowDropup": IoMdArrowDropup,
    "IoMdArrowForward": IoMdArrowForward,
    "IoMdArrowRoundBack": IoMdArrowRoundBack,
    "IoMdArrowRoundDown": IoMdArrowRoundDown,
    "IoMdArrowRoundForward": IoMdArrowRoundForward,
    "IoMdArrowRoundUp": IoMdArrowRoundUp,
    "IoMdArrowUp": IoMdArrowUp,
    "IoMdAt": IoMdAt,
    "IoMdAttach": IoMdAttach,
    "IoMdBackspace": IoMdBackspace,
    "IoMdBarcode": IoMdBarcode,
    "IoMdBaseball": IoMdBaseball,
    "IoMdBasket": IoMdBasket,
    "IoMdBasketball": IoMdBasketball,
    "IoMdBatteryCharging": IoMdBatteryCharging,
    "IoMdBatteryDead": IoMdBatteryDead,
    "IoMdBatteryFull": IoMdBatteryFull,
    "IoMdBeaker": IoMdBeaker,
    "IoMdBed": IoMdBed,
    "IoMdBeer": IoMdBeer,
    "IoMdBicycle": IoMdBicycle,
    "IoMdBluetooth": IoMdBluetooth,
    "IoMdBoat": IoMdBoat,
    "IoMdBody": IoMdBody,
    "IoMdBonfire": IoMdBonfire,
    "IoMdBook": IoMdBook,
    "IoMdBookmark": IoMdBookmark,
    "IoMdBookmarks": IoMdBookmarks,
    "IoMdBowtie": IoMdBowtie,
    "IoMdBriefcase": IoMdBriefcase,
    "IoMdBrowsers": IoMdBrowsers,
    "IoMdBrush": IoMdBrush,
    "IoMdBug": IoMdBug,
    "IoMdBuild": IoMdBuild,
    "IoMdBulb": IoMdBulb,
    "IoMdBus": IoMdBus,
    "IoMdBusiness": IoMdBusiness,
    "IoMdCafe": IoMdCafe,
    "IoMdCalculator": IoMdCalculator,
    "IoMdCalendar": IoMdCalendar,
    "IoMdCall": IoMdCall,
    "IoMdCamera": IoMdCamera,
    "IoMdCar": IoMdCar,
    "IoMdCard": IoMdCard,
    "IoMdCart": IoMdCart,
    "IoMdCash": IoMdCash,
    "IoMdCellular": IoMdCellular,
    "IoMdChatboxes": IoMdChatboxes,
    "IoMdChatbubbles": IoMdChatbubbles,
    "IoMdCheckboxOutline": IoMdCheckboxOutline,
    "IoMdCheckbox": IoMdCheckbox,
    "IoMdCheckmarkCircleOutline": IoMdCheckmarkCircleOutline,
    "IoMdCheckmarkCircle": IoMdCheckmarkCircle,
    "IoMdCheckmark": IoMdCheckmark,
    "IoMdClipboard": IoMdClipboard,
    "IoMdClock": IoMdClock,
    "IoMdCloseCircleOutline": IoMdCloseCircleOutline,
    "IoMdCloseCircle": IoMdCloseCircle,
    "IoMdClose": IoMdClose,
    "IoMdCloudCircle": IoMdCloudCircle,
    "IoMdCloudDone": IoMdCloudDone,
    "IoMdCloudDownload": IoMdCloudDownload,
    "IoMdCloudOutline": IoMdCloudOutline,
    "IoMdCloudUpload": IoMdCloudUpload,
    "IoMdCloud": IoMdCloud,
    "IoMdCloudyNight": IoMdCloudyNight,
    "IoMdCloudy": IoMdCloudy,
    "IoMdCodeDownload": IoMdCodeDownload,
    "IoMdCodeWorking": IoMdCodeWorking,
    "IoMdCode": IoMdCode,
    "IoMdCog": IoMdCog,
    "IoMdColorFill": IoMdColorFill,
    "IoMdColorFilter": IoMdColorFilter,
    "IoMdColorPalette": IoMdColorPalette,
    "IoMdColorWand": IoMdColorWand,
    "IoMdCompass": IoMdCompass,
    "IoMdConstruct": IoMdConstruct,
    "IoMdContact": IoMdContact,
    "IoMdContacts": IoMdContacts,
    "IoMdContract": IoMdContract,
    "IoMdContrast": IoMdContrast,
    "IoMdCopy": IoMdCopy,
    "IoMdCreate": IoMdCreate,
    "IoMdCrop": IoMdCrop,
    "IoMdCube": IoMdCube,
    "IoMdCut": IoMdCut,
    "IoMdDesktop": IoMdDesktop,
    "IoMdDisc": IoMdDisc,
    "IoMdDocument": IoMdDocument,
    "IoMdDoneAll": IoMdDoneAll,
    "IoMdDownload": IoMdDownload,
    "IoMdEasel": IoMdEasel,
    "IoMdEgg": IoMdEgg,
    "IoMdExit": IoMdExit,
    "IoMdExpand": IoMdExpand,
    "IoMdEyeOff": IoMdEyeOff,
    "IoMdEye": IoMdEye,
    "IoMdFastforward": IoMdFastforward,
    "IoMdFemale": IoMdFemale,
    "IoMdFiling": IoMdFiling,
    "IoMdFilm": IoMdFilm,
    "IoMdFingerPrint": IoMdFingerPrint,
    "IoMdFitness": IoMdFitness,
    "IoMdFlag": IoMdFlag,
    "IoMdFlame": IoMdFlame,
    "IoMdFlashOff": IoMdFlashOff,
    "IoMdFlash": IoMdFlash,
    "IoMdFlashlight": IoMdFlashlight,
    "IoMdFlask": IoMdFlask,
    "IoMdFlower": IoMdFlower,
    "IoMdFolderOpen": IoMdFolderOpen,
    "IoMdFolder": IoMdFolder,
    "IoMdFootball": IoMdFootball,
    "IoMdFunnel": IoMdFunnel,
    "IoMdGift": IoMdGift,
    "IoMdGitBranch": IoMdGitBranch,
    "IoMdGitCommit": IoMdGitCommit,
    "IoMdGitCompare": IoMdGitCompare,
    "IoMdGitMerge": IoMdGitMerge,
    "IoMdGitNetwork": IoMdGitNetwork,
    "IoMdGitPullRequest": IoMdGitPullRequest,
    "IoMdGlasses": IoMdGlasses,
    "IoMdGlobe": IoMdGlobe,
    "IoMdGrid": IoMdGrid,
    "IoMdHammer": IoMdHammer,
    "IoMdHand": IoMdHand,
    "IoMdHappy": IoMdHappy,
    "IoMdHeadset": IoMdHeadset,
    "IoMdHeartDislike": IoMdHeartDislike,
    "IoMdHeartEmpty": IoMdHeartEmpty,
    "IoMdHeartHalf": IoMdHeartHalf,
    "IoMdHeart": IoMdHeart,
    "IoMdHelpBuoy": IoMdHelpBuoy,
    "IoMdHelpCircleOutline": IoMdHelpCircleOutline,
    "IoMdHelpCircle": IoMdHelpCircle,
    "IoMdHelp": IoMdHelp,
    "IoMdHome": IoMdHome,
    "IoMdHourglass": IoMdHourglass,
    "IoMdIceCream": IoMdIceCream,
    "IoMdImage": IoMdImage,
    "IoMdImages": IoMdImages,
    "IoMdInfinite": IoMdInfinite,
    "IoMdInformationCircleOutline": IoMdInformationCircleOutline,
    "IoMdInformationCircle": IoMdInformationCircle,
    "IoMdInformation": IoMdInformation,
    "IoMdJet": IoMdJet,
    "IoMdJournal": IoMdJournal,
    "IoMdKey": IoMdKey,
    "IoMdKeypad": IoMdKeypad,
    "IoMdLaptop": IoMdLaptop,
    "IoMdLeaf": IoMdLeaf,
    "IoMdLink": IoMdLink,
    "IoMdListBox": IoMdListBox,
    "IoMdList": IoMdList,
    "IoMdLocate": IoMdLocate,
    "IoMdLock": IoMdLock,
    "IoMdLogIn": IoMdLogIn,
    "IoMdLogOut": IoMdLogOut,
    "IoMdMagnet": IoMdMagnet,
    "IoMdMailOpen": IoMdMailOpen,
    "IoMdMailUnread": IoMdMailUnread,
    "IoMdMail": IoMdMail,
    "IoMdMale": IoMdMale,
    "IoMdMan": IoMdMan,
    "IoMdMap": IoMdMap,
    "IoMdMedal": IoMdMedal,
    "IoMdMedical": IoMdMedical,
    "IoMdMedkit": IoMdMedkit,
    "IoMdMegaphone": IoMdMegaphone,
    "IoMdMenu": IoMdMenu,
    "IoMdMicOff": IoMdMicOff,
    "IoMdMic": IoMdMic,
    "IoMdMicrophone": IoMdMicrophone,
    "IoMdMoon": IoMdMoon,
    "IoMdMore": IoMdMore,
    "IoMdMove": IoMdMove,
    "IoMdMusicalNote": IoMdMusicalNote,
    "IoMdMusicalNotes": IoMdMusicalNotes,
    "IoMdNavigate": IoMdNavigate,
    "IoMdNotificationsOff": IoMdNotificationsOff,
    "IoMdNotificationsOutline": IoMdNotificationsOutline,
    "IoMdNotifications": IoMdNotifications,
    "IoMdNuclear": IoMdNuclear,
    "IoMdNutrition": IoMdNutrition,
    "IoMdOpen": IoMdOpen,
    "IoMdOptions": IoMdOptions,
    "IoMdOutlet": IoMdOutlet,
    "IoMdPaperPlane": IoMdPaperPlane,
    "IoMdPaper": IoMdPaper,
    "IoMdPartlySunny": IoMdPartlySunny,
    "IoMdPause": IoMdPause,
    "IoMdPaw": IoMdPaw,
    "IoMdPeople": IoMdPeople,
    "IoMdPersonAdd": IoMdPersonAdd,
    "IoMdPerson": IoMdPerson,
    "IoMdPhoneLandscape": IoMdPhoneLandscape,
    "IoMdPhonePortrait": IoMdPhonePortrait,
    "IoMdPhotos": IoMdPhotos,
    "IoMdPie": IoMdPie,
    "IoMdPin": IoMdPin,
    "IoMdPint": IoMdPint,
    "IoMdPizza": IoMdPizza,
    "IoMdPlanet": IoMdPlanet,
    "IoMdPlayCircle": IoMdPlayCircle,
    "IoMdPlay": IoMdPlay,
    "IoMdPodium": IoMdPodium,
    "IoMdPower": IoMdPower,
    "IoMdPricetag": IoMdPricetag,
    "IoMdPricetags": IoMdPricetags,
    "IoMdPrint": IoMdPrint,
    "IoMdPulse": IoMdPulse,
    "IoMdQrScanner": IoMdQrScanner,
    "IoMdQuote": IoMdQuote,
    "IoMdRadioButtonOff": IoMdRadioButtonOff,
    "IoMdRadioButtonOn": IoMdRadioButtonOn,
    "IoMdRadio": IoMdRadio,
    "IoMdRainy": IoMdRainy,
    "IoMdRecording": IoMdRecording,
    "IoMdRedo": IoMdRedo,
    "IoMdRefreshCircle": IoMdRefreshCircle,
    "IoMdRefresh": IoMdRefresh,
    "IoMdRemoveCircleOutline": IoMdRemoveCircleOutline,
    "IoMdRemoveCircle": IoMdRemoveCircle,
    "IoMdRemove": IoMdRemove,
    "IoMdReorder": IoMdReorder,
    "IoMdRepeat": IoMdRepeat,
    "IoMdResize": IoMdResize,
    "IoMdRestaurant": IoMdRestaurant,
    "IoMdReturnLeft": IoMdReturnLeft,
    "IoMdReturnRight": IoMdReturnRight,
    "IoMdReverseCamera": IoMdReverseCamera,
    "IoMdRewind": IoMdRewind,
    "IoMdRibbon": IoMdRibbon,
    "IoMdRocket": IoMdRocket,
    "IoMdRose": IoMdRose,
    "IoMdSad": IoMdSad,
    "IoMdSave": IoMdSave,
    "IoMdSchool": IoMdSchool,
    "IoMdSearch": IoMdSearch,
    "IoMdSend": IoMdSend,
    "IoMdSettings": IoMdSettings,
    "IoMdShareAlt": IoMdShareAlt,
    "IoMdShare": IoMdShare,
    "IoMdShirt": IoMdShirt,
    "IoMdShuffle": IoMdShuffle,
    "IoMdSkipBackward": IoMdSkipBackward,
    "IoMdSkipForward": IoMdSkipForward,
    "IoMdSnow": IoMdSnow,
    "IoMdSpeedometer": IoMdSpeedometer,
    "IoMdSquareOutline": IoMdSquareOutline,
    "IoMdSquare": IoMdSquare,
    "IoMdStarHalf": IoMdStarHalf,
    "IoMdStarOutline": IoMdStarOutline,
    "IoMdStar": IoMdStar,
    "IoMdStats": IoMdStats,
    "IoMdStopwatch": IoMdStopwatch,
    "IoMdSubway": IoMdSubway,
    "IoMdSunny": IoMdSunny,
    "IoMdSwap": IoMdSwap,
    "IoMdSwitch": IoMdSwitch,
    "IoMdSync": IoMdSync,
    "IoMdTabletLandscape": IoMdTabletLandscape,
    "IoMdTabletPortrait": IoMdTabletPortrait,
    "IoMdTennisball": IoMdTennisball,
    "IoMdText": IoMdText,
    "IoMdThermometer": IoMdThermometer,
    "IoMdThumbsDown": IoMdThumbsDown,
    "IoMdThumbsUp": IoMdThumbsUp,
    "IoMdThunderstorm": IoMdThunderstorm,
    "IoMdTime": IoMdTime,
    "IoMdTimer": IoMdTimer,
    "IoMdToday": IoMdToday,
    "IoMdTrain": IoMdTrain,
    "IoMdTransgender": IoMdTransgender,
    "IoMdTrash": IoMdTrash,
    "IoMdTrendingDown": IoMdTrendingDown,
    "IoMdTrendingUp": IoMdTrendingUp,
    "IoMdTrophy": IoMdTrophy,
    "IoMdTv": IoMdTv,
    "IoMdUmbrella": IoMdUmbrella,
    "IoMdUndo": IoMdUndo,
    "IoMdUnlock": IoMdUnlock,
    "IoMdVideocam": IoMdVideocam,
    "IoMdVolumeHigh": IoMdVolumeHigh,
    "IoMdVolumeLow": IoMdVolumeLow,
    "IoMdVolumeMute": IoMdVolumeMute,
    "IoMdVolumeOff": IoMdVolumeOff,
    "IoMdWalk": IoMdWalk,
    "IoMdWallet": IoMdWallet,
    "IoMdWarning": IoMdWarning,
    "IoMdWatch": IoMdWatch,
    "IoMdWater": IoMdWater,
    "IoMdWifi": IoMdWifi,
    "IoMdWine": IoMdWine,
    "IoMdWoman": IoMdWoman
}