import { 
  IoAccessibilityOutline,
  IoAccessibilitySharp,
  IoAccessibility,
  IoAddCircleOutline,
  IoAddCircleSharp,
  IoAddCircle,
  IoAddOutline,
  IoAddSharp,
  IoAdd,
  IoAirplaneOutline,
  IoAirplaneSharp,
  IoAirplane,
  IoAlarmOutline,
  IoAlarmSharp,
  IoAlarm,
  IoAlbumsOutline,
  IoAlbumsSharp,
  IoAlbums,
  IoAlertCircleOutline,
  IoAlertCircleSharp,
  IoAlertCircle,
  IoAlertOutline,
  IoAlertSharp,
  IoAlert,
  IoAmericanFootballOutline,
  IoAmericanFootballSharp,
  IoAmericanFootball,
  IoAnalyticsOutline,
  IoAnalyticsSharp,
  IoAnalytics,
  IoApertureOutline,
  IoApertureSharp,
  IoAperture,
  IoAppsOutline,
  IoAppsSharp,
  IoApps,
  IoArchiveOutline,
  IoArchiveSharp,
  IoArchive,
  IoArrowBackCircleOutline,
  IoArrowBackCircleSharp,
  IoArrowBackCircle,
  IoArrowBackOutline,
  IoArrowBackSharp,
  IoArrowBack,
  IoArrowDownCircleOutline,
  IoArrowDownCircleSharp,
  IoArrowDownCircle,
  IoArrowDownOutline,
  IoArrowDownSharp,
  IoArrowDown,
  IoArrowForwardCircleOutline,
  IoArrowForwardCircleSharp,
  IoArrowForwardCircle,
  IoArrowForwardOutline,
  IoArrowForwardSharp,
  IoArrowForward,
  IoArrowRedoCircleOutline,
  IoArrowRedoCircleSharp,
  IoArrowRedoCircle,
  IoArrowRedoOutline,
  IoArrowRedoSharp,
  IoArrowRedo,
  IoArrowUndoCircleOutline,
  IoArrowUndoCircleSharp,
  IoArrowUndoCircle,
  IoArrowUndoOutline,
  IoArrowUndoSharp,
  IoArrowUndo,
  IoArrowUpCircleOutline,
  IoArrowUpCircleSharp,
  IoArrowUpCircle,
  IoArrowUpOutline,
  IoArrowUpSharp,
  IoArrowUp,
  IoAtCircleOutline,
  IoAtCircleSharp,
  IoAtCircle,
  IoAtOutline,
  IoAtSharp,
  IoAt,
  IoAttachOutline,
  IoAttachSharp,
  IoAttach,
  IoBackspaceOutline,
  IoBackspaceSharp,
  IoBackspace,
  IoBagAddOutline,
  IoBagAddSharp,
  IoBagAdd,
  IoBagCheckOutline,
  IoBagCheckSharp,
  IoBagCheck,
  IoBagHandleOutline,
  IoBagHandleSharp,
  IoBagHandle,
  IoBagOutline,
  IoBagRemoveOutline,
  IoBagRemoveSharp,
  IoBagRemove,
  IoBagSharp,
  IoBag,
  IoBalloonOutline,
  IoBalloonSharp,
  IoBalloon,
  IoBanOutline,
  IoBanSharp,
  IoBan,
  IoBandageOutline,
  IoBandageSharp,
  IoBandage,
  IoBarChartOutline,
  IoBarChartSharp,
  IoBarChart,
  IoBarbellOutline,
  IoBarbellSharp,
  IoBarbell,
  IoBarcodeOutline,
  IoBarcodeSharp,
  IoBarcode,
  IoBaseballOutline,
  IoBaseballSharp,
  IoBaseball,
  IoBasketOutline,
  IoBasketSharp,
  IoBasket,
  IoBasketballOutline,
  IoBasketballSharp,
  IoBasketball,
  IoBatteryChargingOutline,
  IoBatteryChargingSharp,
  IoBatteryCharging,
  IoBatteryDeadOutline,
  IoBatteryDeadSharp,
  IoBatteryDead,
  IoBatteryFullOutline,
  IoBatteryFullSharp,
  IoBatteryFull,
  IoBatteryHalfOutline,
  IoBatteryHalfSharp,
  IoBatteryHalf,
  IoBeakerOutline,
  IoBeakerSharp,
  IoBeaker,
  IoBedOutline,
  IoBedSharp,
  IoBed,
  IoBeerOutline,
  IoBeerSharp,
  IoBeer,
  IoBicycleOutline,
  IoBicycleSharp,
  IoBicycle,
  IoBluetoothOutline,
  IoBluetoothSharp,
  IoBluetooth,
  IoBoatOutline,
  IoBoatSharp,
  IoBoat,
  IoBodyOutline,
  IoBodySharp,
  IoBody,
  IoBonfireOutline,
  IoBonfireSharp,
  IoBonfire,
  IoBookOutline,
  IoBookSharp,
  IoBook,
  IoBookmarkOutline,
  IoBookmarkSharp,
  IoBookmark,
  IoBookmarksOutline,
  IoBookmarksSharp,
  IoBookmarks,
  IoBowlingBallOutline,
  IoBowlingBallSharp,
  IoBowlingBall,
  IoBriefcaseOutline,
  IoBriefcaseSharp,
  IoBriefcase,
  IoBrowsersOutline,
  IoBrowsersSharp,
  IoBrowsers,
  IoBrushOutline,
  IoBrushSharp,
  IoBrush,
  IoBugOutline,
  IoBugSharp,
  IoBug,
  IoBuildOutline,
  IoBuildSharp,
  IoBuild,
  IoBulbOutline,
  IoBulbSharp,
  IoBulb,
  IoBusOutline,
  IoBusSharp,
  IoBus,
  IoBusinessOutline,
  IoBusinessSharp,
  IoBusiness,
  IoCafeOutline,
  IoCafeSharp,
  IoCafe,
  IoCalculatorOutline,
  IoCalculatorSharp,
  IoCalculator,
  IoCalendarClearOutline,
  IoCalendarClearSharp,
  IoCalendarClear,
  IoCalendarNumberOutline,
  IoCalendarNumberSharp,
  IoCalendarNumber,
  IoCalendarOutline,
  IoCalendarSharp,
  IoCalendar,
  IoCallOutline,
  IoCallSharp,
  IoCall,
  IoCameraOutline,
  IoCameraReverseOutline,
  IoCameraReverseSharp,
  IoCameraReverse,
  IoCameraSharp,
  IoCamera,
  IoCarOutline,
  IoCarSharp,
  IoCarSportOutline,
  IoCarSportSharp,
  IoCarSport,
  IoCar,
  IoCardOutline,
  IoCardSharp,
  IoCard,
  IoCaretBackCircleOutline,
  IoCaretBackCircleSharp,
  IoCaretBackCircle,
  IoCaretBackOutline,
  IoCaretBackSharp,
  IoCaretBack,
  IoCaretDownCircleOutline,
  IoCaretDownCircleSharp,
  IoCaretDownCircle,
  IoCaretDownOutline,
  IoCaretDownSharp,
  IoCaretDown,
  IoCaretForwardCircleOutline,
  IoCaretForwardCircleSharp,
  IoCaretForwardCircle,
  IoCaretForwardOutline,
  IoCaretForwardSharp,
  IoCaretForward,
  IoCaretUpCircleOutline,
  IoCaretUpCircleSharp,
  IoCaretUpCircle,
  IoCaretUpOutline,
  IoCaretUpSharp,
  IoCaretUp,
  IoCartOutline,
  IoCartSharp,
  IoCart,
  IoCashOutline,
  IoCashSharp,
  IoCash,
  IoCellularOutline,
  IoCellularSharp,
  IoCellular,
  IoChatboxEllipsesOutline,
  IoChatboxEllipsesSharp,
  IoChatboxEllipses,
  IoChatboxOutline,
  IoChatboxSharp,
  IoChatbox,
  IoChatbubbleEllipsesOutline,
  IoChatbubbleEllipsesSharp,
  IoChatbubbleEllipses,
  IoChatbubbleOutline,
  IoChatbubbleSharp,
  IoChatbubble,
  IoChatbubblesOutline,
  IoChatbubblesSharp,
  IoChatbubbles,
  IoCheckboxOutline,
  IoCheckboxSharp,
  IoCheckbox,
  IoCheckmarkCircleOutline,
  IoCheckmarkCircleSharp,
  IoCheckmarkCircle,
  IoCheckmarkDoneCircleOutline,
  IoCheckmarkDoneCircleSharp,
  IoCheckmarkDoneCircle,
  IoCheckmarkDoneOutline,
  IoCheckmarkDoneSharp,
  IoCheckmarkDone,
  IoCheckmarkOutline,
  IoCheckmarkSharp,
  IoCheckmark,
  IoChevronBackCircleOutline,
  IoChevronBackCircleSharp,
  IoChevronBackCircle,
  IoChevronBackOutline,
  IoChevronBackSharp,
  IoChevronBack,
  IoChevronDownCircleOutline,
  IoChevronDownCircleSharp,
  IoChevronDownCircle,
  IoChevronDownOutline,
  IoChevronDownSharp,
  IoChevronDown,
  IoChevronForwardCircleOutline,
  IoChevronForwardCircleSharp,
  IoChevronForwardCircle,
  IoChevronForwardOutline,
  IoChevronForwardSharp,
  IoChevronForward,
  IoChevronUpCircleOutline,
  IoChevronUpCircleSharp,
  IoChevronUpCircle,
  IoChevronUpOutline,
  IoChevronUpSharp,
  IoChevronUp,
  IoClipboardOutline,
  IoClipboardSharp,
  IoClipboard,
  IoCloseCircleOutline,
  IoCloseCircleSharp,
  IoCloseCircle,
  IoCloseOutline,
  IoCloseSharp,
  IoClose,
  IoCloudCircleOutline,
  IoCloudCircleSharp,
  IoCloudCircle,
  IoCloudDoneOutline,
  IoCloudDoneSharp,
  IoCloudDone,
  IoCloudDownloadOutline,
  IoCloudDownloadSharp,
  IoCloudDownload,
  IoCloudOfflineOutline,
  IoCloudOfflineSharp,
  IoCloudOffline,
  IoCloudOutline,
  IoCloudSharp,
  IoCloudUploadOutline,
  IoCloudUploadSharp,
  IoCloudUpload,
  IoCloud,
  IoCloudyNightOutline,
  IoCloudyNightSharp,
  IoCloudyNight,
  IoCloudyOutline,
  IoCloudySharp,
  IoCloudy,
  IoCodeDownloadOutline,
  IoCodeDownloadSharp,
  IoCodeDownload,
  IoCodeOutline,
  IoCodeSharp,
  IoCodeSlashOutline,
  IoCodeSlashSharp,
  IoCodeSlash,
  IoCodeWorkingOutline,
  IoCodeWorkingSharp,
  IoCodeWorking,
  IoCode,
  IoCogOutline,
  IoCogSharp,
  IoCog,
  IoColorFillOutline,
  IoColorFillSharp,
  IoColorFill,
  IoColorFilterOutline,
  IoColorFilterSharp,
  IoColorFilter,
  IoColorPaletteOutline,
  IoColorPaletteSharp,
  IoColorPalette,
  IoColorWandOutline,
  IoColorWandSharp,
  IoColorWand,
  IoCompassOutline,
  IoCompassSharp,
  IoCompass,
  IoConstructOutline,
  IoConstructSharp,
  IoConstruct,
  IoContractOutline,
  IoContractSharp,
  IoContract,
  IoContrastOutline,
  IoContrastSharp,
  IoContrast,
  IoCopyOutline,
  IoCopySharp,
  IoCopy,
  IoCreateOutline,
  IoCreateSharp,
  IoCreate,
  IoCropOutline,
  IoCropSharp,
  IoCrop,
  IoCubeOutline,
  IoCubeSharp,
  IoCube,
  IoCutOutline,
  IoCutSharp,
  IoCut,
  IoDesktopOutline,
  IoDesktopSharp,
  IoDesktop,
  IoDiamondOutline,
  IoDiamondSharp,
  IoDiamond,
  IoDiceOutline,
  IoDiceSharp,
  IoDice,
  IoDiscOutline,
  IoDiscSharp,
  IoDisc,
  IoDocumentAttachOutline,
  IoDocumentAttachSharp,
  IoDocumentAttach,
  IoDocumentLockOutline,
  IoDocumentLockSharp,
  IoDocumentLock,
  IoDocumentOutline,
  IoDocumentSharp,
  IoDocumentTextOutline,
  IoDocumentTextSharp,
  IoDocumentText,
  IoDocument,
  IoDocumentsOutline,
  IoDocumentsSharp,
  IoDocuments,
  IoDownloadOutline,
  IoDownloadSharp,
  IoDownload,
  IoDuplicateOutline,
  IoDuplicateSharp,
  IoDuplicate,
  IoEarOutline,
  IoEarSharp,
  IoEar,
  IoEarthOutline,
  IoEarthSharp,
  IoEarth,
  IoEaselOutline,
  IoEaselSharp,
  IoEasel,
  IoEggOutline,
  IoEggSharp,
  IoEgg,
  IoEllipseOutline,
  IoEllipseSharp,
  IoEllipse,
  IoEllipsisHorizontalCircleOutline,
  IoEllipsisHorizontalCircleSharp,
  IoEllipsisHorizontalCircle,
  IoEllipsisHorizontalOutline,
  IoEllipsisHorizontalSharp,
  IoEllipsisHorizontal,
  IoEllipsisVerticalCircleOutline,
  IoEllipsisVerticalCircleSharp,
  IoEllipsisVerticalCircle,
  IoEllipsisVerticalOutline,
  IoEllipsisVerticalSharp,
  IoEllipsisVertical,
  IoEnterOutline,
  IoEnterSharp,
  IoEnter,
  IoExitOutline,
  IoExitSharp,
  IoExit,
  IoExpandOutline,
  IoExpandSharp,
  IoExpand,
  IoExtensionPuzzleOutline,
  IoExtensionPuzzleSharp,
  IoExtensionPuzzle,
  IoEyeOffOutline,
  IoEyeOffSharp,
  IoEyeOff,
  IoEyeOutline,
  IoEyeSharp,
  IoEye,
  IoEyedropOutline,
  IoEyedropSharp,
  IoEyedrop,
  IoFastFoodOutline,
  IoFastFoodSharp,
  IoFastFood,
  IoFemaleOutline,
  IoFemaleSharp,
  IoFemale,
  IoFileTrayFullOutline,
  IoFileTrayFullSharp,
  IoFileTrayFull,
  IoFileTrayOutline,
  IoFileTraySharp,
  IoFileTrayStackedOutline,
  IoFileTrayStackedSharp,
  IoFileTrayStacked,
  IoFileTray,
  IoFilmOutline,
  IoFilmSharp,
  IoFilm,
  IoFilterCircleOutline,
  IoFilterCircleSharp,
  IoFilterCircle,
  IoFilterOutline,
  IoFilterSharp,
  IoFilter,
  IoFingerPrintOutline,
  IoFingerPrintSharp,
  IoFingerPrint,
  IoFishOutline,
  IoFishSharp,
  IoFish,
  IoFitnessOutline,
  IoFitnessSharp,
  IoFitness,
  IoFlagOutline,
  IoFlagSharp,
  IoFlag,
  IoFlameOutline,
  IoFlameSharp,
  IoFlame,
  IoFlashOffOutline,
  IoFlashOffSharp,
  IoFlashOff,
  IoFlashOutline,
  IoFlashSharp,
  IoFlash,
  IoFlashlightOutline,
  IoFlashlightSharp,
  IoFlashlight,
  IoFlaskOutline,
  IoFlaskSharp,
  IoFlask,
  IoFlowerOutline,
  IoFlowerSharp,
  IoFlower,
  IoFolderOpenOutline,
  IoFolderOpenSharp,
  IoFolderOpen,
  IoFolderOutline,
  IoFolderSharp,
  IoFolder,
  IoFootballOutline,
  IoFootballSharp,
  IoFootball,
  IoFootstepsOutline,
  IoFootstepsSharp,
  IoFootsteps,
  IoFunnelOutline,
  IoFunnelSharp,
  IoFunnel,
  IoGameControllerOutline,
  IoGameControllerSharp,
  IoGameController,
  IoGiftOutline,
  IoGiftSharp,
  IoGift,
  IoGitBranchOutline,
  IoGitBranchSharp,
  IoGitBranch,
  IoGitCommitOutline,
  IoGitCommitSharp,
  IoGitCommit,
  IoGitCompareOutline,
  IoGitCompareSharp,
  IoGitCompare,
  IoGitMergeOutline,
  IoGitMergeSharp,
  IoGitMerge,
  IoGitNetworkOutline,
  IoGitNetworkSharp,
  IoGitNetwork,
  IoGitPullRequestOutline,
  IoGitPullRequestSharp,
  IoGitPullRequest,
  IoGlassesOutline,
  IoGlassesSharp,
  IoGlasses,
  IoGlobeOutline,
  IoGlobeSharp,
  IoGlobe,
  IoGolfOutline,
  IoGolfSharp,
  IoGolf,
  IoGridOutline,
  IoGridSharp,
  IoGrid,
  IoHammerOutline,
  IoHammerSharp,
  IoHammer,
  IoHandLeftOutline,
  IoHandLeftSharp,
  IoHandLeft,
  IoHandRightOutline,
  IoHandRightSharp,
  IoHandRight,
  IoHappyOutline,
  IoHappySharp,
  IoHappy,
  IoHardwareChipOutline,
  IoHardwareChipSharp,
  IoHardwareChip,
  IoHeadsetOutline,
  IoHeadsetSharp,
  IoHeadset,
  IoHeartCircleOutline,
  IoHeartCircleSharp,
  IoHeartCircle,
  IoHeartDislikeCircleOutline,
  IoHeartDislikeCircleSharp,
  IoHeartDislikeCircle,
  IoHeartDislikeOutline,
  IoHeartDislikeSharp,
  IoHeartDislike,
  IoHeartHalfOutline,
  IoHeartHalfSharp,
  IoHeartHalf,
  IoHeartOutline,
  IoHeartSharp,
  IoHeart,
  IoHelpBuoyOutline,
  IoHelpBuoySharp,
  IoHelpBuoy,
  IoHelpCircleOutline,
  IoHelpCircleSharp,
  IoHelpCircle,
  IoHelpOutline,
  IoHelpSharp,
  IoHelp,
  IoHomeOutline,
  IoHomeSharp,
  IoHome,
  IoHourglassOutline,
  IoHourglassSharp,
  IoHourglass,
  IoIceCreamOutline,
  IoIceCreamSharp,
  IoIceCream,
  IoIdCardOutline,
  IoIdCardSharp,
  IoIdCard,
  IoImageOutline,
  IoImageSharp,
  IoImage,
  IoImagesOutline,
  IoImagesSharp,
  IoImages,
  IoInfiniteOutline,
  IoInfiniteSharp,
  IoInfinite,
  IoInformationCircleOutline,
  IoInformationCircleSharp,
  IoInformationCircle,
  IoInformationOutline,
  IoInformationSharp,
  IoInformation,
  IoInvertModeOutline,
  IoInvertModeSharp,
  IoInvertMode,
  IoJournalOutline,
  IoJournalSharp,
  IoJournal,
  IoKeyOutline,
  IoKeySharp,
  IoKey,
  IoKeypadOutline,
  IoKeypadSharp,
  IoKeypad,
  IoLanguageOutline,
  IoLanguageSharp,
  IoLanguage,
  IoLaptopOutline,
  IoLaptopSharp,
  IoLaptop,
  IoLayersOutline,
  IoLayersSharp,
  IoLayers,
  IoLeafOutline,
  IoLeafSharp,
  IoLeaf,
  IoLibraryOutline,
  IoLibrarySharp,
  IoLibrary,
  IoLinkOutline,
  IoLinkSharp,
  IoLink,
  IoListCircleOutline,
  IoListCircleSharp,
  IoListCircle,
  IoListOutline,
  IoListSharp,
  IoList,
  IoLocateOutline,
  IoLocateSharp,
  IoLocate,
  IoLocationOutline,
  IoLocationSharp,
  IoLocation,
  IoLockClosedOutline,
  IoLockClosedSharp,
  IoLockClosed,
  IoLockOpenOutline,
  IoLockOpenSharp,
  IoLockOpen,
  IoLogInOutline,
  IoLogInSharp,
  IoLogIn,
  IoLogOutOutline,
  IoLogOutSharp,
  IoLogOut,
  IoLogoAlipay,
  IoLogoAmazon,
  IoLogoAmplify,
  IoLogoAndroid,
  IoLogoAngular,
  IoLogoAppleAppstore,
  IoLogoAppleAr,
  IoLogoApple,
  IoLogoBehance,
  IoLogoBitbucket,
  IoLogoBitcoin,
  IoLogoBuffer,
  IoLogoCapacitor,
  IoLogoChrome,
  IoLogoClosedCaptioning,
  IoLogoCodepen,
  IoLogoCss3,
  IoLogoDesignernews,
  IoLogoDeviantart,
  IoLogoDiscord,
  IoLogoDocker,
  IoLogoDribbble,
  IoLogoDropbox,
  IoLogoEdge,
  IoLogoElectron,
  IoLogoEuro,
  IoLogoFacebook,
  IoLogoFigma,
  IoLogoFirebase,
  IoLogoFirefox,
  IoLogoFlickr,
  IoLogoFoursquare,
  IoLogoGithub,
  IoLogoGitlab,
  IoLogoGooglePlaystore,
  IoLogoGoogle,
  IoLogoHackernews,
  IoLogoHtml5,
  IoLogoInstagram,
  IoLogoIonic,
  IoLogoIonitron,
  IoLogoJavascript,
  IoLogoLaravel,
  IoLogoLinkedin,
  IoLogoMarkdown,
  IoLogoMastodon,
  IoLogoMedium,
  IoLogoMicrosoft,
  IoLogoNoSmoking,
  IoLogoNodejs,
  IoLogoNpm,
  IoLogoOctocat,
  IoLogoPaypal,
  IoLogoPinterest,
  IoLogoPlaystation,
  IoLogoPwa,
  IoLogoPython,
  IoLogoReact,
  IoLogoReddit,
  IoLogoRss,
  IoLogoSass,
  IoLogoSkype,
  IoLogoSlack,
  IoLogoSnapchat,
  IoLogoSoundcloud,
  IoLogoStackoverflow,
  IoLogoSteam,
  IoLogoStencil,
  IoLogoTableau,
  IoLogoTiktok,
  IoLogoTumblr,
  IoLogoTux,
  IoLogoTwitch,
  IoLogoTwitter,
  IoLogoUsd,
  IoLogoVenmo,
  IoLogoVercel,
  IoLogoVimeo,
  IoLogoVk,
  IoLogoVue,
  IoLogoWebComponent,
  IoLogoWechat,
  IoLogoWhatsapp,
  IoLogoWindows,
  IoLogoWordpress,
  IoLogoXbox,
  IoLogoXing,
  IoLogoYahoo,
  IoLogoYen,
  IoLogoYoutube,
  IoMagnetOutline,
  IoMagnetSharp,
  IoMagnet,
  IoMailOpenOutline,
  IoMailOpenSharp,
  IoMailOpen,
  IoMailOutline,
  IoMailSharp,
  IoMailUnreadOutline,
  IoMailUnreadSharp,
  IoMailUnread,
  IoMail,
  IoMaleFemaleOutline,
  IoMaleFemaleSharp,
  IoMaleFemale,
  IoMaleOutline,
  IoMaleSharp,
  IoMale,
  IoManOutline,
  IoManSharp,
  IoMan,
  IoMapOutline,
  IoMapSharp,
  IoMap,
  IoMedalOutline,
  IoMedalSharp,
  IoMedal,
  IoMedicalOutline,
  IoMedicalSharp,
  IoMedical,
  IoMedkitOutline,
  IoMedkitSharp,
  IoMedkit,
  IoMegaphoneOutline,
  IoMegaphoneSharp,
  IoMegaphone,
  IoMenuOutline,
  IoMenuSharp,
  IoMenu,
  IoMicCircleOutline,
  IoMicCircleSharp,
  IoMicCircle,
  IoMicOffCircleOutline,
  IoMicOffCircleSharp,
  IoMicOffCircle,
  IoMicOffOutline,
  IoMicOffSharp,
  IoMicOff,
  IoMicOutline,
  IoMicSharp,
  IoMic,
  IoMoonOutline,
  IoMoonSharp,
  IoMoon,
  IoMoveOutline,
  IoMoveSharp,
  IoMove,
  IoMusicalNoteOutline,
  IoMusicalNoteSharp,
  IoMusicalNote,
  IoMusicalNotesOutline,
  IoMusicalNotesSharp,
  IoMusicalNotes,
  IoNavigateCircleOutline,
  IoNavigateCircleSharp,
  IoNavigateCircle,
  IoNavigateOutline,
  IoNavigateSharp,
  IoNavigate,
  IoNewspaperOutline,
  IoNewspaperSharp,
  IoNewspaper,
  IoNotificationsCircleOutline,
  IoNotificationsCircleSharp,
  IoNotificationsCircle,
  IoNotificationsOffCircleOutline,
  IoNotificationsOffCircleSharp,
  IoNotificationsOffCircle,
  IoNotificationsOffOutline,
  IoNotificationsOffSharp,
  IoNotificationsOff,
  IoNotificationsOutline,
  IoNotificationsSharp,
  IoNotifications,
  IoNuclearOutline,
  IoNuclearSharp,
  IoNuclear,
  IoNutritionOutline,
  IoNutritionSharp,
  IoNutrition,
  IoOpenOutline,
  IoOpenSharp,
  IoOpen,
  IoOptionsOutline,
  IoOptionsSharp,
  IoOptions,
  IoPaperPlaneOutline,
  IoPaperPlaneSharp,
  IoPaperPlane,
  IoPartlySunnyOutline,
  IoPartlySunnySharp,
  IoPartlySunny,
  IoPauseCircleOutline,
  IoPauseCircleSharp,
  IoPauseCircle,
  IoPauseOutline,
  IoPauseSharp,
  IoPause,
  IoPawOutline,
  IoPawSharp,
  IoPaw,
  IoPencilOutline,
  IoPencilSharp,
  IoPencil,
  IoPeopleCircleOutline,
  IoPeopleCircleSharp,
  IoPeopleCircle,
  IoPeopleOutline,
  IoPeopleSharp,
  IoPeople,
  IoPersonAddOutline,
  IoPersonAddSharp,
  IoPersonAdd,
  IoPersonCircleOutline,
  IoPersonCircleSharp,
  IoPersonCircle,
  IoPersonOutline,
  IoPersonRemoveOutline,
  IoPersonRemoveSharp,
  IoPersonRemove,
  IoPersonSharp,
  IoPerson,
  IoPhoneLandscapeOutline,
  IoPhoneLandscapeSharp,
  IoPhoneLandscape,
  IoPhonePortraitOutline,
  IoPhonePortraitSharp,
  IoPhonePortrait,
  IoPieChartOutline,
  IoPieChartSharp,
  IoPieChart,
  IoPinOutline,
  IoPinSharp,
  IoPin,
  IoPintOutline,
  IoPintSharp,
  IoPint,
  IoPizzaOutline,
  IoPizzaSharp,
  IoPizza,
  IoPlanetOutline,
  IoPlanetSharp,
  IoPlanet,
  IoPlayBackCircleOutline,
  IoPlayBackCircleSharp,
  IoPlayBackCircle,
  IoPlayBackOutline,
  IoPlayBackSharp,
  IoPlayBack,
  IoPlayCircleOutline,
  IoPlayCircleSharp,
  IoPlayCircle,
  IoPlayForwardCircleOutline,
  IoPlayForwardCircleSharp,
  IoPlayForwardCircle,
  IoPlayForwardOutline,
  IoPlayForwardSharp,
  IoPlayForward,
  IoPlayOutline,
  IoPlaySharp,
  IoPlaySkipBackCircleOutline,
  IoPlaySkipBackCircleSharp,
  IoPlaySkipBackCircle,
  IoPlaySkipBackOutline,
  IoPlaySkipBackSharp,
  IoPlaySkipBack,
  IoPlaySkipForwardCircleOutline,
  IoPlaySkipForwardCircleSharp,
  IoPlaySkipForwardCircle,
  IoPlaySkipForwardOutline,
  IoPlaySkipForwardSharp,
  IoPlaySkipForward,
  IoPlay,
  IoPodiumOutline,
  IoPodiumSharp,
  IoPodium,
  IoPowerOutline,
  IoPowerSharp,
  IoPower,
  IoPricetagOutline,
  IoPricetagSharp,
  IoPricetag,
  IoPricetagsOutline,
  IoPricetagsSharp,
  IoPricetags,
  IoPrintOutline,
  IoPrintSharp,
  IoPrint,
  IoPrismOutline,
  IoPrismSharp,
  IoPrism,
  IoPulseOutline,
  IoPulseSharp,
  IoPulse,
  IoPushOutline,
  IoPushSharp,
  IoPush,
  IoQrCodeOutline,
  IoQrCodeSharp,
  IoQrCode,
  IoRadioButtonOffOutline,
  IoRadioButtonOffSharp,
  IoRadioButtonOff,
  IoRadioButtonOnOutline,
  IoRadioButtonOnSharp,
  IoRadioButtonOn,
  IoRadioOutline,
  IoRadioSharp,
  IoRadio,
  IoRainyOutline,
  IoRainySharp,
  IoRainy,
  IoReaderOutline,
  IoReaderSharp,
  IoReader,
  IoReceiptOutline,
  IoReceiptSharp,
  IoReceipt,
  IoRecordingOutline,
  IoRecordingSharp,
  IoRecording,
  IoRefreshCircleOutline,
  IoRefreshCircleSharp,
  IoRefreshCircle,
  IoRefreshOutline,
  IoRefreshSharp,
  IoRefresh,
  IoReloadCircleOutline,
  IoReloadCircleSharp,
  IoReloadCircle,
  IoReloadOutline,
  IoReloadSharp,
  IoReload,
  IoRemoveCircleOutline,
  IoRemoveCircleSharp,
  IoRemoveCircle,
  IoRemoveOutline,
  IoRemoveSharp,
  IoRemove,
  IoReorderFourOutline,
  IoReorderFourSharp,
  IoReorderFour,
  IoReorderThreeOutline,
  IoReorderThreeSharp,
  IoReorderThree,
  IoReorderTwoOutline,
  IoReorderTwoSharp,
  IoReorderTwo,
  IoRepeatOutline,
  IoRepeatSharp,
  IoRepeat,
  IoResizeOutline,
  IoResizeSharp,
  IoResize,
  IoRestaurantOutline,
  IoRestaurantSharp,
  IoRestaurant,
  IoReturnDownBackOutline,
  IoReturnDownBackSharp,
  IoReturnDownBack,
  IoReturnDownForwardOutline,
  IoReturnDownForwardSharp,
  IoReturnDownForward,
  IoReturnUpBackOutline,
  IoReturnUpBackSharp,
  IoReturnUpBack,
  IoReturnUpForwardOutline,
  IoReturnUpForwardSharp,
  IoReturnUpForward,
  IoRibbonOutline,
  IoRibbonSharp,
  IoRibbon,
  IoRocketOutline,
  IoRocketSharp,
  IoRocket,
  IoRoseOutline,
  IoRoseSharp,
  IoRose,
  IoSadOutline,
  IoSadSharp,
  IoSad,
  IoSaveOutline,
  IoSaveSharp,
  IoSave,
  IoScaleOutline,
  IoScaleSharp,
  IoScale,
  IoScanCircleOutline,
  IoScanCircleSharp,
  IoScanCircle,
  IoScanOutline,
  IoScanSharp,
  IoScan,
  IoSchoolOutline,
  IoSchoolSharp,
  IoSchool,
  IoSearchCircleOutline,
  IoSearchCircleSharp,
  IoSearchCircle,
  IoSearchOutline,
  IoSearchSharp,
  IoSearch,
  IoSendOutline,
  IoSendSharp,
  IoSend,
  IoServerOutline,
  IoServerSharp,
  IoServer,
  IoSettingsOutline,
  IoSettingsSharp,
  IoSettings,
  IoShapesOutline,
  IoShapesSharp,
  IoShapes,
  IoShareOutline,
  IoShareSharp,
  IoShareSocialOutline,
  IoShareSocialSharp,
  IoShareSocial,
  IoShare,
  IoShieldCheckmarkOutline,
  IoShieldCheckmarkSharp,
  IoShieldCheckmark,
  IoShieldHalfOutline,
  IoShieldHalfSharp,
  IoShieldHalf,
  IoShieldOutline,
  IoShieldSharp,
  IoShield,
  IoShirtOutline,
  IoShirtSharp,
  IoShirt,
  IoShuffleOutline,
  IoShuffleSharp,
  IoShuffle,
  IoSkullOutline,
  IoSkullSharp,
  IoSkull,
  IoSnowOutline,
  IoSnowSharp,
  IoSnow,
  IoSparklesOutline,
  IoSparklesSharp,
  IoSparkles,
  IoSpeedometerOutline,
  IoSpeedometerSharp,
  IoSpeedometer,
  IoSquareOutline,
  IoSquareSharp,
  IoSquare,
  IoStarHalfOutline,
  IoStarHalfSharp,
  IoStarHalf,
  IoStarOutline,
  IoStarSharp,
  IoStar,
  IoStatsChartOutline,
  IoStatsChartSharp,
  IoStatsChart,
  IoStopCircleOutline,
  IoStopCircleSharp,
  IoStopCircle,
  IoStopOutline,
  IoStopSharp,
  IoStop,
  IoStopwatchOutline,
  IoStopwatchSharp,
  IoStopwatch,
  IoStorefrontOutline,
  IoStorefrontSharp,
  IoStorefront,
  IoSubwayOutline,
  IoSubwaySharp,
  IoSubway,
  IoSunnyOutline,
  IoSunnySharp,
  IoSunny,
  IoSwapHorizontalOutline,
  IoSwapHorizontalSharp,
  IoSwapHorizontal,
  IoSwapVerticalOutline,
  IoSwapVerticalSharp,
  IoSwapVertical,
  IoSyncCircleOutline,
  IoSyncCircleSharp,
  IoSyncCircle,
  IoSyncOutline,
  IoSyncSharp,
  IoSync,
  IoTabletLandscapeOutline,
  IoTabletLandscapeSharp,
  IoTabletLandscape,
  IoTabletPortraitOutline,
  IoTabletPortraitSharp,
  IoTabletPortrait,
  IoTelescopeOutline,
  IoTelescopeSharp,
  IoTelescope,
  IoTennisballOutline,
  IoTennisballSharp,
  IoTennisball,
  IoTerminalOutline,
  IoTerminalSharp,
  IoTerminal,
  IoTextOutline,
  IoTextSharp,
  IoText,
  IoThermometerOutline,
  IoThermometerSharp,
  IoThermometer,
  IoThumbsDownOutline,
  IoThumbsDownSharp,
  IoThumbsDown,
  IoThumbsUpOutline,
  IoThumbsUpSharp,
  IoThumbsUp,
  IoThunderstormOutline,
  IoThunderstormSharp,
  IoThunderstorm,
  IoTicketOutline,
  IoTicketSharp,
  IoTicket,
  IoTimeOutline,
  IoTimeSharp,
  IoTime,
  IoTimerOutline,
  IoTimerSharp,
  IoTimer,
  IoTodayOutline,
  IoTodaySharp,
  IoToday,
  IoToggleOutline,
  IoToggleSharp,
  IoToggle,
  IoTrailSignOutline,
  IoTrailSignSharp,
  IoTrailSign,
  IoTrainOutline,
  IoTrainSharp,
  IoTrain,
  IoTransgenderOutline,
  IoTransgenderSharp,
  IoTransgender,
  IoTrashBinOutline,
  IoTrashBinSharp,
  IoTrashBin,
  IoTrashOutline,
  IoTrashSharp,
  IoTrash,
  IoTrendingDownOutline,
  IoTrendingDownSharp,
  IoTrendingDown,
  IoTrendingUpOutline,
  IoTrendingUpSharp,
  IoTrendingUp,
  IoTriangleOutline,
  IoTriangleSharp,
  IoTriangle,
  IoTrophyOutline,
  IoTrophySharp,
  IoTrophy,
  IoTvOutline,
  IoTvSharp,
  IoTv,
  IoUmbrellaOutline,
  IoUmbrellaSharp,
  IoUmbrella,
  IoUnlinkOutline,
  IoUnlinkSharp,
  IoUnlink,
  IoVideocamOffOutline,
  IoVideocamOffSharp,
  IoVideocamOff,
  IoVideocamOutline,
  IoVideocamSharp,
  IoVideocam,
  IoVolumeHighOutline,
  IoVolumeHighSharp,
  IoVolumeHigh,
  IoVolumeLowOutline,
  IoVolumeLowSharp,
  IoVolumeLow,
  IoVolumeMediumOutline,
  IoVolumeMediumSharp,
  IoVolumeMedium,
  IoVolumeMuteOutline,
  IoVolumeMuteSharp,
  IoVolumeMute,
  IoVolumeOffOutline,
  IoVolumeOffSharp,
  IoVolumeOff,
  IoWalkOutline,
  IoWalkSharp,
  IoWalk,
  IoWalletOutline,
  IoWalletSharp,
  IoWallet,
  IoWarningOutline,
  IoWarningSharp,
  IoWarning,
  IoWatchOutline,
  IoWatchSharp,
  IoWatch,
  IoWaterOutline,
  IoWaterSharp,
  IoWater,
  IoWifiOutline,
  IoWifiSharp,
  IoWifi,
  IoWineOutline,
  IoWineSharp,
  IoWine,
  IoWomanOutline,
  IoWomanSharp,
  IoWoman
} from "react-icons/io5";

export const IonIcons5 = {
  "IoAccessibilityOutline": IoAccessibilityOutline,
  "IoAccessibilitySharp": IoAccessibilitySharp,
  "IoAccessibility": IoAccessibility,
  "IoAddCircleOutline": IoAddCircleOutline,
  "IoAddCircleSharp": IoAddCircleSharp,
  "IoAddCircle": IoAddCircle,
  "IoAddOutline": IoAddOutline,
  "IoAddSharp": IoAddSharp,
  "IoAdd": IoAdd,
  "IoAirplaneOutline": IoAirplaneOutline,
  "IoAirplaneSharp": IoAirplaneSharp,
  "IoAirplane": IoAirplane,
  "IoAlarmOutline": IoAlarmOutline,
  "IoAlarmSharp": IoAlarmSharp,
  "IoAlarm": IoAlarm,
  "IoAlbumsOutline": IoAlbumsOutline,
  "IoAlbumsSharp": IoAlbumsSharp,
  "IoAlbums": IoAlbums,
  "IoAlertCircleOutline": IoAlertCircleOutline,
  "IoAlertCircleSharp": IoAlertCircleSharp,
  "IoAlertCircle": IoAlertCircle,
  "IoAlertOutline": IoAlertOutline,
  "IoAlertSharp": IoAlertSharp,
  "IoAlert": IoAlert,
  "IoAmericanFootballOutline": IoAmericanFootballOutline,
  "IoAmericanFootballSharp": IoAmericanFootballSharp,
  "IoAmericanFootball": IoAmericanFootball,
  "IoAnalyticsOutline": IoAnalyticsOutline,
  "IoAnalyticsSharp": IoAnalyticsSharp,
  "IoAnalytics": IoAnalytics,
  "IoApertureOutline": IoApertureOutline,
  "IoApertureSharp": IoApertureSharp,
  "IoAperture": IoAperture,
  "IoAppsOutline": IoAppsOutline,
  "IoAppsSharp": IoAppsSharp,
  "IoApps": IoApps,
  "IoArchiveOutline": IoArchiveOutline,
  "IoArchiveSharp": IoArchiveSharp,
  "IoArchive": IoArchive,
  "IoArrowBackCircleOutline": IoArrowBackCircleOutline,
  "IoArrowBackCircleSharp": IoArrowBackCircleSharp,
  "IoArrowBackCircle": IoArrowBackCircle,
  "IoArrowBackOutline": IoArrowBackOutline,
  "IoArrowBackSharp": IoArrowBackSharp,
  "IoArrowBack": IoArrowBack,
  "IoArrowDownCircleOutline": IoArrowDownCircleOutline,
  "IoArrowDownCircleSharp": IoArrowDownCircleSharp,
  "IoArrowDownCircle": IoArrowDownCircle,
  "IoArrowDownOutline": IoArrowDownOutline,
  "IoArrowDownSharp": IoArrowDownSharp,
  "IoArrowDown": IoArrowDown,
  "IoArrowForwardCircleOutline": IoArrowForwardCircleOutline,
  "IoArrowForwardCircleSharp": IoArrowForwardCircleSharp,
  "IoArrowForwardCircle": IoArrowForwardCircle,
  "IoArrowForwardOutline": IoArrowForwardOutline,
  "IoArrowForwardSharp": IoArrowForwardSharp,
  "IoArrowForward": IoArrowForward,
  "IoArrowRedoCircleOutline": IoArrowRedoCircleOutline,
  "IoArrowRedoCircleSharp": IoArrowRedoCircleSharp,
  "IoArrowRedoCircle": IoArrowRedoCircle,
  "IoArrowRedoOutline": IoArrowRedoOutline,
  "IoArrowRedoSharp": IoArrowRedoSharp,
  "IoArrowRedo": IoArrowRedo,
  "IoArrowUndoCircleOutline": IoArrowUndoCircleOutline,
  "IoArrowUndoCircleSharp": IoArrowUndoCircleSharp,
  "IoArrowUndoCircle": IoArrowUndoCircle,
  "IoArrowUndoOutline": IoArrowUndoOutline,
  "IoArrowUndoSharp": IoArrowUndoSharp,
  "IoArrowUndo": IoArrowUndo,
  "IoArrowUpCircleOutline": IoArrowUpCircleOutline,
  "IoArrowUpCircleSharp": IoArrowUpCircleSharp,
  "IoArrowUpCircle": IoArrowUpCircle,
  "IoArrowUpOutline": IoArrowUpOutline,
  "IoArrowUpSharp": IoArrowUpSharp,
  "IoArrowUp": IoArrowUp,
  "IoAtCircleOutline": IoAtCircleOutline,
  "IoAtCircleSharp": IoAtCircleSharp,
  "IoAtCircle": IoAtCircle,
  "IoAtOutline": IoAtOutline,
  "IoAtSharp": IoAtSharp,
  "IoAt": IoAt,
  "IoAttachOutline": IoAttachOutline,
  "IoAttachSharp": IoAttachSharp,
  "IoAttach": IoAttach,
  "IoBackspaceOutline": IoBackspaceOutline,
  "IoBackspaceSharp": IoBackspaceSharp,
  "IoBackspace": IoBackspace,
  "IoBagAddOutline": IoBagAddOutline,
  "IoBagAddSharp": IoBagAddSharp,
  "IoBagAdd": IoBagAdd,
  "IoBagCheckOutline": IoBagCheckOutline,
  "IoBagCheckSharp": IoBagCheckSharp,
  "IoBagCheck": IoBagCheck,
  "IoBagHandleOutline": IoBagHandleOutline,
  "IoBagHandleSharp": IoBagHandleSharp,
  "IoBagHandle": IoBagHandle,
  "IoBagOutline": IoBagOutline,
  "IoBagRemoveOutline": IoBagRemoveOutline,
  "IoBagRemoveSharp": IoBagRemoveSharp,
  "IoBagRemove": IoBagRemove,
  "IoBagSharp": IoBagSharp,
  "IoBag": IoBag,
  "IoBalloonOutline": IoBalloonOutline,
  "IoBalloonSharp": IoBalloonSharp,
  "IoBalloon": IoBalloon,
  "IoBanOutline": IoBanOutline,
  "IoBanSharp": IoBanSharp,
  "IoBan": IoBan,
  "IoBandageOutline": IoBandageOutline,
  "IoBandageSharp": IoBandageSharp,
  "IoBandage": IoBandage,
  "IoBarChartOutline": IoBarChartOutline,
  "IoBarChartSharp": IoBarChartSharp,
  "IoBarChart": IoBarChart,
  "IoBarbellOutline": IoBarbellOutline,
  "IoBarbellSharp": IoBarbellSharp,
  "IoBarbell": IoBarbell,
  "IoBarcodeOutline": IoBarcodeOutline,
  "IoBarcodeSharp": IoBarcodeSharp,
  "IoBarcode": IoBarcode,
  "IoBaseballOutline": IoBaseballOutline,
  "IoBaseballSharp": IoBaseballSharp,
  "IoBaseball": IoBaseball,
  "IoBasketOutline": IoBasketOutline,
  "IoBasketSharp": IoBasketSharp,
  "IoBasket": IoBasket,
  "IoBasketballOutline": IoBasketballOutline,
  "IoBasketballSharp": IoBasketballSharp,
  "IoBasketball": IoBasketball,
  "IoBatteryChargingOutline": IoBatteryChargingOutline,
  "IoBatteryChargingSharp": IoBatteryChargingSharp,
  "IoBatteryCharging": IoBatteryCharging,
  "IoBatteryDeadOutline": IoBatteryDeadOutline,
  "IoBatteryDeadSharp": IoBatteryDeadSharp,
  "IoBatteryDead": IoBatteryDead,
  "IoBatteryFullOutline": IoBatteryFullOutline,
  "IoBatteryFullSharp": IoBatteryFullSharp,
  "IoBatteryFull": IoBatteryFull,
  "IoBatteryHalfOutline": IoBatteryHalfOutline,
  "IoBatteryHalfSharp": IoBatteryHalfSharp,
  "IoBatteryHalf": IoBatteryHalf,
  "IoBeakerOutline": IoBeakerOutline,
  "IoBeakerSharp": IoBeakerSharp,
  "IoBeaker": IoBeaker,
  "IoBedOutline": IoBedOutline,
  "IoBedSharp": IoBedSharp,
  "IoBed": IoBed,
  "IoBeerOutline": IoBeerOutline,
  "IoBeerSharp": IoBeerSharp,
  "IoBeer": IoBeer,
  "IoBicycleOutline": IoBicycleOutline,
  "IoBicycleSharp": IoBicycleSharp,
  "IoBicycle": IoBicycle,
  "IoBluetoothOutline": IoBluetoothOutline,
  "IoBluetoothSharp": IoBluetoothSharp,
  "IoBluetooth": IoBluetooth,
  "IoBoatOutline": IoBoatOutline,
  "IoBoatSharp": IoBoatSharp,
  "IoBoat": IoBoat,
  "IoBodyOutline": IoBodyOutline,
  "IoBodySharp": IoBodySharp,
  "IoBody": IoBody,
  "IoBonfireOutline": IoBonfireOutline,
  "IoBonfireSharp": IoBonfireSharp,
  "IoBonfire": IoBonfire,
  "IoBookOutline": IoBookOutline,
  "IoBookSharp": IoBookSharp,
  "IoBook": IoBook,
  "IoBookmarkOutline": IoBookmarkOutline,
  "IoBookmarkSharp": IoBookmarkSharp,
  "IoBookmark": IoBookmark,
  "IoBookmarksOutline": IoBookmarksOutline,
  "IoBookmarksSharp": IoBookmarksSharp,
  "IoBookmarks": IoBookmarks,
  "IoBowlingBallOutline": IoBowlingBallOutline,
  "IoBowlingBallSharp": IoBowlingBallSharp,
  "IoBowlingBall": IoBowlingBall,
  "IoBriefcaseOutline": IoBriefcaseOutline,
  "IoBriefcaseSharp": IoBriefcaseSharp,
  "IoBriefcase": IoBriefcase,
  "IoBrowsersOutline": IoBrowsersOutline,
  "IoBrowsersSharp": IoBrowsersSharp,
  "IoBrowsers": IoBrowsers,
  "IoBrushOutline": IoBrushOutline,
  "IoBrushSharp": IoBrushSharp,
  "IoBrush": IoBrush,
  "IoBugOutline": IoBugOutline,
  "IoBugSharp": IoBugSharp,
  "IoBug": IoBug,
  "IoBuildOutline": IoBuildOutline,
  "IoBuildSharp": IoBuildSharp,
  "IoBuild": IoBuild,
  "IoBulbOutline": IoBulbOutline,
  "IoBulbSharp": IoBulbSharp,
  "IoBulb": IoBulb,
  "IoBusOutline": IoBusOutline,
  "IoBusSharp": IoBusSharp,
  "IoBus": IoBus,
  "IoBusinessOutline": IoBusinessOutline,
  "IoBusinessSharp": IoBusinessSharp,
  "IoBusiness": IoBusiness,
  "IoCafeOutline": IoCafeOutline,
  "IoCafeSharp": IoCafeSharp,
  "IoCafe": IoCafe,
  "IoCalculatorOutline": IoCalculatorOutline,
  "IoCalculatorSharp": IoCalculatorSharp,
  "IoCalculator": IoCalculator,
  "IoCalendarClearOutline": IoCalendarClearOutline,
  "IoCalendarClearSharp": IoCalendarClearSharp,
  "IoCalendarClear": IoCalendarClear,
  "IoCalendarNumberOutline": IoCalendarNumberOutline,
  "IoCalendarNumberSharp": IoCalendarNumberSharp,
  "IoCalendarNumber": IoCalendarNumber,
  "IoCalendarOutline": IoCalendarOutline,
  "IoCalendarSharp": IoCalendarSharp,
  "IoCalendar": IoCalendar,
  "IoCallOutline": IoCallOutline,
  "IoCallSharp": IoCallSharp,
  "IoCall": IoCall,
  "IoCameraOutline": IoCameraOutline,
  "IoCameraReverseOutline": IoCameraReverseOutline,
  "IoCameraReverseSharp": IoCameraReverseSharp,
  "IoCameraReverse": IoCameraReverse,
  "IoCameraSharp": IoCameraSharp,
  "IoCamera": IoCamera,
  "IoCarOutline": IoCarOutline,
  "IoCarSharp": IoCarSharp,
  "IoCarSportOutline": IoCarSportOutline,
  "IoCarSportSharp": IoCarSportSharp,
  "IoCarSport": IoCarSport,
  "IoCar": IoCar,
  "IoCardOutline": IoCardOutline,
  "IoCardSharp": IoCardSharp,
  "IoCard": IoCard,
  "IoCaretBackCircleOutline": IoCaretBackCircleOutline,
  "IoCaretBackCircleSharp": IoCaretBackCircleSharp,
  "IoCaretBackCircle": IoCaretBackCircle,
  "IoCaretBackOutline": IoCaretBackOutline,
  "IoCaretBackSharp": IoCaretBackSharp,
  "IoCaretBack": IoCaretBack,
  "IoCaretDownCircleOutline": IoCaretDownCircleOutline,
  "IoCaretDownCircleSharp": IoCaretDownCircleSharp,
  "IoCaretDownCircle": IoCaretDownCircle,
  "IoCaretDownOutline": IoCaretDownOutline,
  "IoCaretDownSharp": IoCaretDownSharp,
  "IoCaretDown": IoCaretDown,
  "IoCaretForwardCircleOutline": IoCaretForwardCircleOutline,
  "IoCaretForwardCircleSharp": IoCaretForwardCircleSharp,
  "IoCaretForwardCircle": IoCaretForwardCircle,
  "IoCaretForwardOutline": IoCaretForwardOutline,
  "IoCaretForwardSharp": IoCaretForwardSharp,
  "IoCaretForward": IoCaretForward,
  "IoCaretUpCircleOutline": IoCaretUpCircleOutline,
  "IoCaretUpCircleSharp": IoCaretUpCircleSharp,
  "IoCaretUpCircle": IoCaretUpCircle,
  "IoCaretUpOutline": IoCaretUpOutline,
  "IoCaretUpSharp": IoCaretUpSharp,
  "IoCaretUp": IoCaretUp,
  "IoCartOutline": IoCartOutline,
  "IoCartSharp": IoCartSharp,
  "IoCart": IoCart,
  "IoCashOutline": IoCashOutline,
  "IoCashSharp": IoCashSharp,
  "IoCash": IoCash,
  "IoCellularOutline": IoCellularOutline,
  "IoCellularSharp": IoCellularSharp,
  "IoCellular": IoCellular,
  "IoChatboxEllipsesOutline": IoChatboxEllipsesOutline,
  "IoChatboxEllipsesSharp": IoChatboxEllipsesSharp,
  "IoChatboxEllipses": IoChatboxEllipses,
  "IoChatboxOutline": IoChatboxOutline,
  "IoChatboxSharp": IoChatboxSharp,
  "IoChatbox": IoChatbox,
  "IoChatbubbleEllipsesOutline": IoChatbubbleEllipsesOutline,
  "IoChatbubbleEllipsesSharp": IoChatbubbleEllipsesSharp,
  "IoChatbubbleEllipses": IoChatbubbleEllipses,
  "IoChatbubbleOutline": IoChatbubbleOutline,
  "IoChatbubbleSharp": IoChatbubbleSharp,
  "IoChatbubble": IoChatbubble,
  "IoChatbubblesOutline": IoChatbubblesOutline,
  "IoChatbubblesSharp": IoChatbubblesSharp,
  "IoChatbubbles": IoChatbubbles,
  "IoCheckboxOutline": IoCheckboxOutline,
  "IoCheckboxSharp": IoCheckboxSharp,
  "IoCheckbox": IoCheckbox,
  "IoCheckmarkCircleOutline": IoCheckmarkCircleOutline,
  "IoCheckmarkCircleSharp": IoCheckmarkCircleSharp,
  "IoCheckmarkCircle": IoCheckmarkCircle,
  "IoCheckmarkDoneCircleOutline": IoCheckmarkDoneCircleOutline,
  "IoCheckmarkDoneCircleSharp": IoCheckmarkDoneCircleSharp,
  "IoCheckmarkDoneCircle": IoCheckmarkDoneCircle,
  "IoCheckmarkDoneOutline": IoCheckmarkDoneOutline,
  "IoCheckmarkDoneSharp": IoCheckmarkDoneSharp,
  "IoCheckmarkDone": IoCheckmarkDone,
  "IoCheckmarkOutline": IoCheckmarkOutline,
  "IoCheckmarkSharp": IoCheckmarkSharp,
  "IoCheckmark": IoCheckmark,
  "IoChevronBackCircleOutline": IoChevronBackCircleOutline,
  "IoChevronBackCircleSharp": IoChevronBackCircleSharp,
  "IoChevronBackCircle": IoChevronBackCircle,
  "IoChevronBackOutline": IoChevronBackOutline,
  "IoChevronBackSharp": IoChevronBackSharp,
  "IoChevronBack": IoChevronBack,
  "IoChevronDownCircleOutline": IoChevronDownCircleOutline,
  "IoChevronDownCircleSharp": IoChevronDownCircleSharp,
  "IoChevronDownCircle": IoChevronDownCircle,
  "IoChevronDownOutline": IoChevronDownOutline,
  "IoChevronDownSharp": IoChevronDownSharp,
  "IoChevronDown": IoChevronDown,
  "IoChevronForwardCircleOutline": IoChevronForwardCircleOutline,
  "IoChevronForwardCircleSharp": IoChevronForwardCircleSharp,
  "IoChevronForwardCircle": IoChevronForwardCircle,
  "IoChevronForwardOutline": IoChevronForwardOutline,
  "IoChevronForwardSharp": IoChevronForwardSharp,
  "IoChevronForward": IoChevronForward,
  "IoChevronUpCircleOutline": IoChevronUpCircleOutline,
  "IoChevronUpCircleSharp": IoChevronUpCircleSharp,
  "IoChevronUpCircle": IoChevronUpCircle,
  "IoChevronUpOutline": IoChevronUpOutline,
  "IoChevronUpSharp": IoChevronUpSharp,
  "IoChevronUp": IoChevronUp,
  "IoClipboardOutline": IoClipboardOutline,
  "IoClipboardSharp": IoClipboardSharp,
  "IoClipboard": IoClipboard,
  "IoCloseCircleOutline": IoCloseCircleOutline,
  "IoCloseCircleSharp": IoCloseCircleSharp,
  "IoCloseCircle": IoCloseCircle,
  "IoCloseOutline": IoCloseOutline,
  "IoCloseSharp": IoCloseSharp,
  "IoClose": IoClose,
  "IoCloudCircleOutline": IoCloudCircleOutline,
  "IoCloudCircleSharp": IoCloudCircleSharp,
  "IoCloudCircle": IoCloudCircle,
  "IoCloudDoneOutline": IoCloudDoneOutline,
  "IoCloudDoneSharp": IoCloudDoneSharp,
  "IoCloudDone": IoCloudDone,
  "IoCloudDownloadOutline": IoCloudDownloadOutline,
  "IoCloudDownloadSharp": IoCloudDownloadSharp,
  "IoCloudDownload": IoCloudDownload,
  "IoCloudOfflineOutline": IoCloudOfflineOutline,
  "IoCloudOfflineSharp": IoCloudOfflineSharp,
  "IoCloudOffline": IoCloudOffline,
  "IoCloudOutline": IoCloudOutline,
  "IoCloudSharp": IoCloudSharp,
  "IoCloudUploadOutline": IoCloudUploadOutline,
  "IoCloudUploadSharp": IoCloudUploadSharp,
  "IoCloudUpload": IoCloudUpload,
  "IoCloud": IoCloud,
  "IoCloudyNightOutline": IoCloudyNightOutline,
  "IoCloudyNightSharp": IoCloudyNightSharp,
  "IoCloudyNight": IoCloudyNight,
  "IoCloudyOutline": IoCloudyOutline,
  "IoCloudySharp": IoCloudySharp,
  "IoCloudy": IoCloudy,
  "IoCodeDownloadOutline": IoCodeDownloadOutline,
  "IoCodeDownloadSharp": IoCodeDownloadSharp,
  "IoCodeDownload": IoCodeDownload,
  "IoCodeOutline": IoCodeOutline,
  "IoCodeSharp": IoCodeSharp,
  "IoCodeSlashOutline": IoCodeSlashOutline,
  "IoCodeSlashSharp": IoCodeSlashSharp,
  "IoCodeSlash": IoCodeSlash,
  "IoCodeWorkingOutline": IoCodeWorkingOutline,
  "IoCodeWorkingSharp": IoCodeWorkingSharp,
  "IoCodeWorking": IoCodeWorking,
  "IoCode": IoCode,
  "IoCogOutline": IoCogOutline,
  "IoCogSharp": IoCogSharp,
  "IoCog": IoCog,
  "IoColorFillOutline": IoColorFillOutline,
  "IoColorFillSharp": IoColorFillSharp,
  "IoColorFill": IoColorFill,
  "IoColorFilterOutline": IoColorFilterOutline,
  "IoColorFilterSharp": IoColorFilterSharp,
  "IoColorFilter": IoColorFilter,
  "IoColorPaletteOutline": IoColorPaletteOutline,
  "IoColorPaletteSharp": IoColorPaletteSharp,
  "IoColorPalette": IoColorPalette,
  "IoColorWandOutline": IoColorWandOutline,
  "IoColorWandSharp": IoColorWandSharp,
  "IoColorWand": IoColorWand,
  "IoCompassOutline": IoCompassOutline,
  "IoCompassSharp": IoCompassSharp,
  "IoCompass": IoCompass,
  "IoConstructOutline": IoConstructOutline,
  "IoConstructSharp": IoConstructSharp,
  "IoConstruct": IoConstruct,
  "IoContractOutline": IoContractOutline,
  "IoContractSharp": IoContractSharp,
  "IoContract": IoContract,
  "IoContrastOutline": IoContrastOutline,
  "IoContrastSharp": IoContrastSharp,
  "IoContrast": IoContrast,
  "IoCopyOutline": IoCopyOutline,
  "IoCopySharp": IoCopySharp,
  "IoCopy": IoCopy,
  "IoCreateOutline": IoCreateOutline,
  "IoCreateSharp": IoCreateSharp,
  "IoCreate": IoCreate,
  "IoCropOutline": IoCropOutline,
  "IoCropSharp": IoCropSharp,
  "IoCrop": IoCrop,
  "IoCubeOutline": IoCubeOutline,
  "IoCubeSharp": IoCubeSharp,
  "IoCube": IoCube,
  "IoCutOutline": IoCutOutline,
  "IoCutSharp": IoCutSharp,
  "IoCut": IoCut,
  "IoDesktopOutline": IoDesktopOutline,
  "IoDesktopSharp": IoDesktopSharp,
  "IoDesktop": IoDesktop,
  "IoDiamondOutline": IoDiamondOutline,
  "IoDiamondSharp": IoDiamondSharp,
  "IoDiamond": IoDiamond,
  "IoDiceOutline": IoDiceOutline,
  "IoDiceSharp": IoDiceSharp,
  "IoDice": IoDice,
  "IoDiscOutline": IoDiscOutline,
  "IoDiscSharp": IoDiscSharp,
  "IoDisc": IoDisc,
  "IoDocumentAttachOutline": IoDocumentAttachOutline,
  "IoDocumentAttachSharp": IoDocumentAttachSharp,
  "IoDocumentAttach": IoDocumentAttach,
  "IoDocumentLockOutline": IoDocumentLockOutline,
  "IoDocumentLockSharp": IoDocumentLockSharp,
  "IoDocumentLock": IoDocumentLock,
  "IoDocumentOutline": IoDocumentOutline,
  "IoDocumentSharp": IoDocumentSharp,
  "IoDocumentTextOutline": IoDocumentTextOutline,
  "IoDocumentTextSharp": IoDocumentTextSharp,
  "IoDocumentText": IoDocumentText,
  "IoDocument": IoDocument,
  "IoDocumentsOutline": IoDocumentsOutline,
  "IoDocumentsSharp": IoDocumentsSharp,
  "IoDocuments": IoDocuments,
  "IoDownloadOutline": IoDownloadOutline,
  "IoDownloadSharp": IoDownloadSharp,
  "IoDownload": IoDownload,
  "IoDuplicateOutline": IoDuplicateOutline,
  "IoDuplicateSharp": IoDuplicateSharp,
  "IoDuplicate": IoDuplicate,
  "IoEarOutline": IoEarOutline,
  "IoEarSharp": IoEarSharp,
  "IoEar": IoEar,
  "IoEarthOutline": IoEarthOutline,
  "IoEarthSharp": IoEarthSharp,
  "IoEarth": IoEarth,
  "IoEaselOutline": IoEaselOutline,
  "IoEaselSharp": IoEaselSharp,
  "IoEasel": IoEasel,
  "IoEggOutline": IoEggOutline,
  "IoEggSharp": IoEggSharp,
  "IoEgg": IoEgg,
  "IoEllipseOutline": IoEllipseOutline,
  "IoEllipseSharp": IoEllipseSharp,
  "IoEllipse": IoEllipse,
  "IoEllipsisHorizontalCircleOutline": IoEllipsisHorizontalCircleOutline,
  "IoEllipsisHorizontalCircleSharp": IoEllipsisHorizontalCircleSharp,
  "IoEllipsisHorizontalCircle": IoEllipsisHorizontalCircle,
  "IoEllipsisHorizontalOutline": IoEllipsisHorizontalOutline,
  "IoEllipsisHorizontalSharp": IoEllipsisHorizontalSharp,
  "IoEllipsisHorizontal": IoEllipsisHorizontal,
  "IoEllipsisVerticalCircleOutline": IoEllipsisVerticalCircleOutline,
  "IoEllipsisVerticalCircleSharp": IoEllipsisVerticalCircleSharp,
  "IoEllipsisVerticalCircle": IoEllipsisVerticalCircle,
  "IoEllipsisVerticalOutline": IoEllipsisVerticalOutline,
  "IoEllipsisVerticalSharp": IoEllipsisVerticalSharp,
  "IoEllipsisVertical": IoEllipsisVertical,
  "IoEnterOutline": IoEnterOutline,
  "IoEnterSharp": IoEnterSharp,
  "IoEnter": IoEnter,
  "IoExitOutline": IoExitOutline,
  "IoExitSharp": IoExitSharp,
  "IoExit": IoExit,
  "IoExpandOutline": IoExpandOutline,
  "IoExpandSharp": IoExpandSharp,
  "IoExpand": IoExpand,
  "IoExtensionPuzzleOutline": IoExtensionPuzzleOutline,
  "IoExtensionPuzzleSharp": IoExtensionPuzzleSharp,
  "IoExtensionPuzzle": IoExtensionPuzzle,
  "IoEyeOffOutline": IoEyeOffOutline,
  "IoEyeOffSharp": IoEyeOffSharp,
  "IoEyeOff": IoEyeOff,
  "IoEyeOutline": IoEyeOutline,
  "IoEyeSharp": IoEyeSharp,
  "IoEye": IoEye,
  "IoEyedropOutline": IoEyedropOutline,
  "IoEyedropSharp": IoEyedropSharp,
  "IoEyedrop": IoEyedrop,
  "IoFastFoodOutline": IoFastFoodOutline,
  "IoFastFoodSharp": IoFastFoodSharp,
  "IoFastFood": IoFastFood,
  "IoFemaleOutline": IoFemaleOutline,
  "IoFemaleSharp": IoFemaleSharp,
  "IoFemale": IoFemale,
  "IoFileTrayFullOutline": IoFileTrayFullOutline,
  "IoFileTrayFullSharp": IoFileTrayFullSharp,
  "IoFileTrayFull": IoFileTrayFull,
  "IoFileTrayOutline": IoFileTrayOutline,
  "IoFileTraySharp": IoFileTraySharp,
  "IoFileTrayStackedOutline": IoFileTrayStackedOutline,
  "IoFileTrayStackedSharp": IoFileTrayStackedSharp,
  "IoFileTrayStacked": IoFileTrayStacked,
  "IoFileTray": IoFileTray,
  "IoFilmOutline": IoFilmOutline,
  "IoFilmSharp": IoFilmSharp,
  "IoFilm": IoFilm,
  "IoFilterCircleOutline": IoFilterCircleOutline,
  "IoFilterCircleSharp": IoFilterCircleSharp,
  "IoFilterCircle": IoFilterCircle,
  "IoFilterOutline": IoFilterOutline,
  "IoFilterSharp": IoFilterSharp,
  "IoFilter": IoFilter,
  "IoFingerPrintOutline": IoFingerPrintOutline,
  "IoFingerPrintSharp": IoFingerPrintSharp,
  "IoFingerPrint": IoFingerPrint,
  "IoFishOutline": IoFishOutline,
  "IoFishSharp": IoFishSharp,
  "IoFish": IoFish,
  "IoFitnessOutline": IoFitnessOutline,
  "IoFitnessSharp": IoFitnessSharp,
  "IoFitness": IoFitness,
  "IoFlagOutline": IoFlagOutline,
  "IoFlagSharp": IoFlagSharp,
  "IoFlag": IoFlag,
  "IoFlameOutline": IoFlameOutline,
  "IoFlameSharp": IoFlameSharp,
  "IoFlame": IoFlame,
  "IoFlashOffOutline": IoFlashOffOutline,
  "IoFlashOffSharp": IoFlashOffSharp,
  "IoFlashOff": IoFlashOff,
  "IoFlashOutline": IoFlashOutline,
  "IoFlashSharp": IoFlashSharp,
  "IoFlash": IoFlash,
  "IoFlashlightOutline": IoFlashlightOutline,
  "IoFlashlightSharp": IoFlashlightSharp,
  "IoFlashlight": IoFlashlight,
  "IoFlaskOutline": IoFlaskOutline,
  "IoFlaskSharp": IoFlaskSharp,
  "IoFlask": IoFlask,
  "IoFlowerOutline": IoFlowerOutline,
  "IoFlowerSharp": IoFlowerSharp,
  "IoFlower": IoFlower,
  "IoFolderOpenOutline": IoFolderOpenOutline,
  "IoFolderOpenSharp": IoFolderOpenSharp,
  "IoFolderOpen": IoFolderOpen,
  "IoFolderOutline": IoFolderOutline,
  "IoFolderSharp": IoFolderSharp,
  "IoFolder": IoFolder,
  "IoFootballOutline": IoFootballOutline,
  "IoFootballSharp": IoFootballSharp,
  "IoFootball": IoFootball,
  "IoFootstepsOutline": IoFootstepsOutline,
  "IoFootstepsSharp": IoFootstepsSharp,
  "IoFootsteps": IoFootsteps,
  "IoFunnelOutline": IoFunnelOutline,
  "IoFunnelSharp": IoFunnelSharp,
  "IoFunnel": IoFunnel,
  "IoGameControllerOutline": IoGameControllerOutline,
  "IoGameControllerSharp": IoGameControllerSharp,
  "IoGameController": IoGameController,
  "IoGiftOutline": IoGiftOutline,
  "IoGiftSharp": IoGiftSharp,
  "IoGift": IoGift,
  "IoGitBranchOutline": IoGitBranchOutline,
  "IoGitBranchSharp": IoGitBranchSharp,
  "IoGitBranch": IoGitBranch,
  "IoGitCommitOutline": IoGitCommitOutline,
  "IoGitCommitSharp": IoGitCommitSharp,
  "IoGitCommit": IoGitCommit,
  "IoGitCompareOutline": IoGitCompareOutline,
  "IoGitCompareSharp": IoGitCompareSharp,
  "IoGitCompare": IoGitCompare,
  "IoGitMergeOutline": IoGitMergeOutline,
  "IoGitMergeSharp": IoGitMergeSharp,
  "IoGitMerge": IoGitMerge,
  "IoGitNetworkOutline": IoGitNetworkOutline,
  "IoGitNetworkSharp": IoGitNetworkSharp,
  "IoGitNetwork": IoGitNetwork,
  "IoGitPullRequestOutline": IoGitPullRequestOutline,
  "IoGitPullRequestSharp": IoGitPullRequestSharp,
  "IoGitPullRequest": IoGitPullRequest,
  "IoGlassesOutline": IoGlassesOutline,
  "IoGlassesSharp": IoGlassesSharp,
  "IoGlasses": IoGlasses,
  "IoGlobeOutline": IoGlobeOutline,
  "IoGlobeSharp": IoGlobeSharp,
  "IoGlobe": IoGlobe,
  "IoGolfOutline": IoGolfOutline,
  "IoGolfSharp": IoGolfSharp,
  "IoGolf": IoGolf,
  "IoGridOutline": IoGridOutline,
  "IoGridSharp": IoGridSharp,
  "IoGrid": IoGrid,
  "IoHammerOutline": IoHammerOutline,
  "IoHammerSharp": IoHammerSharp,
  "IoHammer": IoHammer,
  "IoHandLeftOutline": IoHandLeftOutline,
  "IoHandLeftSharp": IoHandLeftSharp,
  "IoHandLeft": IoHandLeft,
  "IoHandRightOutline": IoHandRightOutline,
  "IoHandRightSharp": IoHandRightSharp,
  "IoHandRight": IoHandRight,
  "IoHappyOutline": IoHappyOutline,
  "IoHappySharp": IoHappySharp,
  "IoHappy": IoHappy,
  "IoHardwareChipOutline": IoHardwareChipOutline,
  "IoHardwareChipSharp": IoHardwareChipSharp,
  "IoHardwareChip": IoHardwareChip,
  "IoHeadsetOutline": IoHeadsetOutline,
  "IoHeadsetSharp": IoHeadsetSharp,
  "IoHeadset": IoHeadset,
  "IoHeartCircleOutline": IoHeartCircleOutline,
  "IoHeartCircleSharp": IoHeartCircleSharp,
  "IoHeartCircle": IoHeartCircle,
  "IoHeartDislikeCircleOutline": IoHeartDislikeCircleOutline,
  "IoHeartDislikeCircleSharp": IoHeartDislikeCircleSharp,
  "IoHeartDislikeCircle": IoHeartDislikeCircle,
  "IoHeartDislikeOutline": IoHeartDislikeOutline,
  "IoHeartDislikeSharp": IoHeartDislikeSharp,
  "IoHeartDislike": IoHeartDislike,
  "IoHeartHalfOutline": IoHeartHalfOutline,
  "IoHeartHalfSharp": IoHeartHalfSharp,
  "IoHeartHalf": IoHeartHalf,
  "IoHeartOutline": IoHeartOutline,
  "IoHeartSharp": IoHeartSharp,
  "IoHeart": IoHeart,
  "IoHelpBuoyOutline": IoHelpBuoyOutline,
  "IoHelpBuoySharp": IoHelpBuoySharp,
  "IoHelpBuoy": IoHelpBuoy,
  "IoHelpCircleOutline": IoHelpCircleOutline,
  "IoHelpCircleSharp": IoHelpCircleSharp,
  "IoHelpCircle": IoHelpCircle,
  "IoHelpOutline": IoHelpOutline,
  "IoHelpSharp": IoHelpSharp,
  "IoHelp": IoHelp,
  "IoHomeOutline": IoHomeOutline,
  "IoHomeSharp": IoHomeSharp,
  "IoHome": IoHome,
  "IoHourglassOutline": IoHourglassOutline,
  "IoHourglassSharp": IoHourglassSharp,
  "IoHourglass": IoHourglass,
  "IoIceCreamOutline": IoIceCreamOutline,
  "IoIceCreamSharp": IoIceCreamSharp,
  "IoIceCream": IoIceCream,
  "IoIdCardOutline": IoIdCardOutline,
  "IoIdCardSharp": IoIdCardSharp,
  "IoIdCard": IoIdCard,
  "IoImageOutline": IoImageOutline,
  "IoImageSharp": IoImageSharp,
  "IoImage": IoImage,
  "IoImagesOutline": IoImagesOutline,
  "IoImagesSharp": IoImagesSharp,
  "IoImages": IoImages,
  "IoInfiniteOutline": IoInfiniteOutline,
  "IoInfiniteSharp": IoInfiniteSharp,
  "IoInfinite": IoInfinite,
  "IoInformationCircleOutline": IoInformationCircleOutline,
  "IoInformationCircleSharp": IoInformationCircleSharp,
  "IoInformationCircle": IoInformationCircle,
  "IoInformationOutline": IoInformationOutline,
  "IoInformationSharp": IoInformationSharp,
  "IoInformation": IoInformation,
  "IoInvertModeOutline": IoInvertModeOutline,
  "IoInvertModeSharp": IoInvertModeSharp,
  "IoInvertMode": IoInvertMode,
  "IoJournalOutline": IoJournalOutline,
  "IoJournalSharp": IoJournalSharp,
  "IoJournal": IoJournal,
  "IoKeyOutline": IoKeyOutline,
  "IoKeySharp": IoKeySharp,
  "IoKey": IoKey,
  "IoKeypadOutline": IoKeypadOutline,
  "IoKeypadSharp": IoKeypadSharp,
  "IoKeypad": IoKeypad,
  "IoLanguageOutline": IoLanguageOutline,
  "IoLanguageSharp": IoLanguageSharp,
  "IoLanguage": IoLanguage,
  "IoLaptopOutline": IoLaptopOutline,
  "IoLaptopSharp": IoLaptopSharp,
  "IoLaptop": IoLaptop,
  "IoLayersOutline": IoLayersOutline,
  "IoLayersSharp": IoLayersSharp,
  "IoLayers": IoLayers,
  "IoLeafOutline": IoLeafOutline,
  "IoLeafSharp": IoLeafSharp,
  "IoLeaf": IoLeaf,
  "IoLibraryOutline": IoLibraryOutline,
  "IoLibrarySharp": IoLibrarySharp,
  "IoLibrary": IoLibrary,
  "IoLinkOutline": IoLinkOutline,
  "IoLinkSharp": IoLinkSharp,
  "IoLink": IoLink,
  "IoListCircleOutline": IoListCircleOutline,
  "IoListCircleSharp": IoListCircleSharp,
  "IoListCircle": IoListCircle,
  "IoListOutline": IoListOutline,
  "IoListSharp": IoListSharp,
  "IoList": IoList,
  "IoLocateOutline": IoLocateOutline,
  "IoLocateSharp": IoLocateSharp,
  "IoLocate": IoLocate,
  "IoLocationOutline": IoLocationOutline,
  "IoLocationSharp": IoLocationSharp,
  "IoLocation": IoLocation,
  "IoLockClosedOutline": IoLockClosedOutline,
  "IoLockClosedSharp": IoLockClosedSharp,
  "IoLockClosed": IoLockClosed,
  "IoLockOpenOutline": IoLockOpenOutline,
  "IoLockOpenSharp": IoLockOpenSharp,
  "IoLockOpen": IoLockOpen,
  "IoLogInOutline": IoLogInOutline,
  "IoLogInSharp": IoLogInSharp,
  "IoLogIn": IoLogIn,
  "IoLogOutOutline": IoLogOutOutline,
  "IoLogOutSharp": IoLogOutSharp,
  "IoLogOut": IoLogOut,
  "IoLogoAlipay": IoLogoAlipay,
  "IoLogoAmazon": IoLogoAmazon,
  "IoLogoAmplify": IoLogoAmplify,
  "IoLogoAndroid": IoLogoAndroid,
  "IoLogoAngular": IoLogoAngular,
  "IoLogoAppleAppstore": IoLogoAppleAppstore,
  "IoLogoAppleAr": IoLogoAppleAr,
  "IoLogoApple": IoLogoApple,
  "IoLogoBehance": IoLogoBehance,
  "IoLogoBitbucket": IoLogoBitbucket,
  "IoLogoBitcoin": IoLogoBitcoin,
  "IoLogoBuffer": IoLogoBuffer,
  "IoLogoCapacitor": IoLogoCapacitor,
  "IoLogoChrome": IoLogoChrome,
  "IoLogoClosedCaptioning": IoLogoClosedCaptioning,
  "IoLogoCodepen": IoLogoCodepen,
  "IoLogoCss3": IoLogoCss3,
  "IoLogoDesignernews": IoLogoDesignernews,
  "IoLogoDeviantart": IoLogoDeviantart,
  "IoLogoDiscord": IoLogoDiscord,
  "IoLogoDocker": IoLogoDocker,
  "IoLogoDribbble": IoLogoDribbble,
  "IoLogoDropbox": IoLogoDropbox,
  "IoLogoEdge": IoLogoEdge,
  "IoLogoElectron": IoLogoElectron,
  "IoLogoEuro": IoLogoEuro,
  "IoLogoFacebook": IoLogoFacebook,
  "IoLogoFigma": IoLogoFigma,
  "IoLogoFirebase": IoLogoFirebase,
  "IoLogoFirefox": IoLogoFirefox,
  "IoLogoFlickr": IoLogoFlickr,
  "IoLogoFoursquare": IoLogoFoursquare,
  "IoLogoGithub": IoLogoGithub,
  "IoLogoGitlab": IoLogoGitlab,
  "IoLogoGooglePlaystore": IoLogoGooglePlaystore,
  "IoLogoGoogle": IoLogoGoogle,
  "IoLogoHackernews": IoLogoHackernews,
  "IoLogoHtml5": IoLogoHtml5,
  "IoLogoInstagram": IoLogoInstagram,
  "IoLogoIonic": IoLogoIonic,
  "IoLogoIonitron": IoLogoIonitron,
  "IoLogoJavascript": IoLogoJavascript,
  "IoLogoLaravel": IoLogoLaravel,
  "IoLogoLinkedin": IoLogoLinkedin,
  "IoLogoMarkdown": IoLogoMarkdown,
  "IoLogoMastodon": IoLogoMastodon,
  "IoLogoMedium": IoLogoMedium,
  "IoLogoMicrosoft": IoLogoMicrosoft,
  "IoLogoNoSmoking": IoLogoNoSmoking,
  "IoLogoNodejs": IoLogoNodejs,
  "IoLogoNpm": IoLogoNpm,
  "IoLogoOctocat": IoLogoOctocat,
  "IoLogoPaypal": IoLogoPaypal,
  "IoLogoPinterest": IoLogoPinterest,
  "IoLogoPlaystation": IoLogoPlaystation,
  "IoLogoPwa": IoLogoPwa,
  "IoLogoPython": IoLogoPython,
  "IoLogoReact": IoLogoReact,
  "IoLogoReddit": IoLogoReddit,
  "IoLogoRss": IoLogoRss,
  "IoLogoSass": IoLogoSass,
  "IoLogoSkype": IoLogoSkype,
  "IoLogoSlack": IoLogoSlack,
  "IoLogoSnapchat": IoLogoSnapchat,
  "IoLogoSoundcloud": IoLogoSoundcloud,
  "IoLogoStackoverflow": IoLogoStackoverflow,
  "IoLogoSteam": IoLogoSteam,
  "IoLogoStencil": IoLogoStencil,
  "IoLogoTableau": IoLogoTableau,
  "IoLogoTiktok": IoLogoTiktok,
  "IoLogoTumblr": IoLogoTumblr,
  "IoLogoTux": IoLogoTux,
  "IoLogoTwitch": IoLogoTwitch,
  "IoLogoTwitter": IoLogoTwitter,
  "IoLogoUsd": IoLogoUsd,
  "IoLogoVenmo": IoLogoVenmo,
  "IoLogoVercel": IoLogoVercel,
  "IoLogoVimeo": IoLogoVimeo,
  "IoLogoVk": IoLogoVk,
  "IoLogoVue": IoLogoVue,
  "IoLogoWebComponent": IoLogoWebComponent,
  "IoLogoWechat": IoLogoWechat,
  "IoLogoWhatsapp": IoLogoWhatsapp,
  "IoLogoWindows": IoLogoWindows,
  "IoLogoWordpress": IoLogoWordpress,
  "IoLogoXbox": IoLogoXbox,
  "IoLogoXing": IoLogoXing,
  "IoLogoYahoo": IoLogoYahoo,
  "IoLogoYen": IoLogoYen,
  "IoLogoYoutube": IoLogoYoutube,
  "IoMagnetOutline": IoMagnetOutline,
  "IoMagnetSharp": IoMagnetSharp,
  "IoMagnet": IoMagnet,
  "IoMailOpenOutline": IoMailOpenOutline,
  "IoMailOpenSharp": IoMailOpenSharp,
  "IoMailOpen": IoMailOpen,
  "IoMailOutline": IoMailOutline,
  "IoMailSharp": IoMailSharp,
  "IoMailUnreadOutline": IoMailUnreadOutline,
  "IoMailUnreadSharp": IoMailUnreadSharp,
  "IoMailUnread": IoMailUnread,
  "IoMail": IoMail,
  "IoMaleFemaleOutline": IoMaleFemaleOutline,
  "IoMaleFemaleSharp": IoMaleFemaleSharp,
  "IoMaleFemale": IoMaleFemale,
  "IoMaleOutline": IoMaleOutline,
  "IoMaleSharp": IoMaleSharp,
  "IoMale": IoMale,
  "IoManOutline": IoManOutline,
  "IoManSharp": IoManSharp,
  "IoMan": IoMan,
  "IoMapOutline": IoMapOutline,
  "IoMapSharp": IoMapSharp,
  "IoMap": IoMap,
  "IoMedalOutline": IoMedalOutline,
  "IoMedalSharp": IoMedalSharp,
  "IoMedal": IoMedal,
  "IoMedicalOutline": IoMedicalOutline,
  "IoMedicalSharp": IoMedicalSharp,
  "IoMedical": IoMedical,
  "IoMedkitOutline": IoMedkitOutline,
  "IoMedkitSharp": IoMedkitSharp,
  "IoMedkit": IoMedkit,
  "IoMegaphoneOutline": IoMegaphoneOutline,
  "IoMegaphoneSharp": IoMegaphoneSharp,
  "IoMegaphone": IoMegaphone,
  "IoMenuOutline": IoMenuOutline,
  "IoMenuSharp": IoMenuSharp,
  "IoMenu": IoMenu,
  "IoMicCircleOutline": IoMicCircleOutline,
  "IoMicCircleSharp": IoMicCircleSharp,
  "IoMicCircle": IoMicCircle,
  "IoMicOffCircleOutline": IoMicOffCircleOutline,
  "IoMicOffCircleSharp": IoMicOffCircleSharp,
  "IoMicOffCircle": IoMicOffCircle,
  "IoMicOffOutline": IoMicOffOutline,
  "IoMicOffSharp": IoMicOffSharp,
  "IoMicOff": IoMicOff,
  "IoMicOutline": IoMicOutline,
  "IoMicSharp": IoMicSharp,
  "IoMic": IoMic,
  "IoMoonOutline": IoMoonOutline,
  "IoMoonSharp": IoMoonSharp,
  "IoMoon": IoMoon,
  "IoMoveOutline": IoMoveOutline,
  "IoMoveSharp": IoMoveSharp,
  "IoMove": IoMove,
  "IoMusicalNoteOutline": IoMusicalNoteOutline,
  "IoMusicalNoteSharp": IoMusicalNoteSharp,
  "IoMusicalNote": IoMusicalNote,
  "IoMusicalNotesOutline": IoMusicalNotesOutline,
  "IoMusicalNotesSharp": IoMusicalNotesSharp,
  "IoMusicalNotes": IoMusicalNotes,
  "IoNavigateCircleOutline": IoNavigateCircleOutline,
  "IoNavigateCircleSharp": IoNavigateCircleSharp,
  "IoNavigateCircle": IoNavigateCircle,
  "IoNavigateOutline": IoNavigateOutline,
  "IoNavigateSharp": IoNavigateSharp,
  "IoNavigate": IoNavigate,
  "IoNewspaperOutline": IoNewspaperOutline,
  "IoNewspaperSharp": IoNewspaperSharp,
  "IoNewspaper": IoNewspaper,
  "IoNotificationsCircleOutline": IoNotificationsCircleOutline,
  "IoNotificationsCircleSharp": IoNotificationsCircleSharp,
  "IoNotificationsCircle": IoNotificationsCircle,
  "IoNotificationsOffCircleOutline": IoNotificationsOffCircleOutline,
  "IoNotificationsOffCircleSharp": IoNotificationsOffCircleSharp,
  "IoNotificationsOffCircle": IoNotificationsOffCircle,
  "IoNotificationsOffOutline": IoNotificationsOffOutline,
  "IoNotificationsOffSharp": IoNotificationsOffSharp,
  "IoNotificationsOff": IoNotificationsOff,
  "IoNotificationsOutline": IoNotificationsOutline,
  "IoNotificationsSharp": IoNotificationsSharp,
  "IoNotifications": IoNotifications,
  "IoNuclearOutline": IoNuclearOutline,
  "IoNuclearSharp": IoNuclearSharp,
  "IoNuclear": IoNuclear,
  "IoNutritionOutline": IoNutritionOutline,
  "IoNutritionSharp": IoNutritionSharp,
  "IoNutrition": IoNutrition,
  "IoOpenOutline": IoOpenOutline,
  "IoOpenSharp": IoOpenSharp,
  "IoOpen": IoOpen,
  "IoOptionsOutline": IoOptionsOutline,
  "IoOptionsSharp": IoOptionsSharp,
  "IoOptions": IoOptions,
  "IoPaperPlaneOutline": IoPaperPlaneOutline,
  "IoPaperPlaneSharp": IoPaperPlaneSharp,
  "IoPaperPlane": IoPaperPlane,
  "IoPartlySunnyOutline": IoPartlySunnyOutline,
  "IoPartlySunnySharp": IoPartlySunnySharp,
  "IoPartlySunny": IoPartlySunny,
  "IoPauseCircleOutline": IoPauseCircleOutline,
  "IoPauseCircleSharp": IoPauseCircleSharp,
  "IoPauseCircle": IoPauseCircle,
  "IoPauseOutline": IoPauseOutline,
  "IoPauseSharp": IoPauseSharp,
  "IoPause": IoPause,
  "IoPawOutline": IoPawOutline,
  "IoPawSharp": IoPawSharp,
  "IoPaw": IoPaw,
  "IoPencilOutline": IoPencilOutline,
  "IoPencilSharp": IoPencilSharp,
  "IoPencil": IoPencil,
  "IoPeopleCircleOutline": IoPeopleCircleOutline,
  "IoPeopleCircleSharp": IoPeopleCircleSharp,
  "IoPeopleCircle": IoPeopleCircle,
  "IoPeopleOutline": IoPeopleOutline,
  "IoPeopleSharp": IoPeopleSharp,
  "IoPeople": IoPeople,
  "IoPersonAddOutline": IoPersonAddOutline,
  "IoPersonAddSharp": IoPersonAddSharp,
  "IoPersonAdd": IoPersonAdd,
  "IoPersonCircleOutline": IoPersonCircleOutline,
  "IoPersonCircleSharp": IoPersonCircleSharp,
  "IoPersonCircle": IoPersonCircle,
  "IoPersonOutline": IoPersonOutline,
  "IoPersonRemoveOutline": IoPersonRemoveOutline,
  "IoPersonRemoveSharp": IoPersonRemoveSharp,
  "IoPersonRemove": IoPersonRemove,
  "IoPersonSharp": IoPersonSharp,
  "IoPerson": IoPerson,
  "IoPhoneLandscapeOutline": IoPhoneLandscapeOutline,
  "IoPhoneLandscapeSharp": IoPhoneLandscapeSharp,
  "IoPhoneLandscape": IoPhoneLandscape,
  "IoPhonePortraitOutline": IoPhonePortraitOutline,
  "IoPhonePortraitSharp": IoPhonePortraitSharp,
  "IoPhonePortrait": IoPhonePortrait,
  "IoPieChartOutline": IoPieChartOutline,
  "IoPieChartSharp": IoPieChartSharp,
  "IoPieChart": IoPieChart,
  "IoPinOutline": IoPinOutline,
  "IoPinSharp": IoPinSharp,
  "IoPin": IoPin,
  "IoPintOutline": IoPintOutline,
  "IoPintSharp": IoPintSharp,
  "IoPint": IoPint,
  "IoPizzaOutline": IoPizzaOutline,
  "IoPizzaSharp": IoPizzaSharp,
  "IoPizza": IoPizza,
  "IoPlanetOutline": IoPlanetOutline,
  "IoPlanetSharp": IoPlanetSharp,
  "IoPlanet": IoPlanet,
  "IoPlayBackCircleOutline": IoPlayBackCircleOutline,
  "IoPlayBackCircleSharp": IoPlayBackCircleSharp,
  "IoPlayBackCircle": IoPlayBackCircle,
  "IoPlayBackOutline": IoPlayBackOutline,
  "IoPlayBackSharp": IoPlayBackSharp,
  "IoPlayBack": IoPlayBack,
  "IoPlayCircleOutline": IoPlayCircleOutline,
  "IoPlayCircleSharp": IoPlayCircleSharp,
  "IoPlayCircle": IoPlayCircle,
  "IoPlayForwardCircleOutline": IoPlayForwardCircleOutline,
  "IoPlayForwardCircleSharp": IoPlayForwardCircleSharp,
  "IoPlayForwardCircle": IoPlayForwardCircle,
  "IoPlayForwardOutline": IoPlayForwardOutline,
  "IoPlayForwardSharp": IoPlayForwardSharp,
  "IoPlayForward": IoPlayForward,
  "IoPlayOutline": IoPlayOutline,
  "IoPlaySharp": IoPlaySharp,
  "IoPlaySkipBackCircleOutline": IoPlaySkipBackCircleOutline,
  "IoPlaySkipBackCircleSharp": IoPlaySkipBackCircleSharp,
  "IoPlaySkipBackCircle": IoPlaySkipBackCircle,
  "IoPlaySkipBackOutline": IoPlaySkipBackOutline,
  "IoPlaySkipBackSharp": IoPlaySkipBackSharp,
  "IoPlaySkipBack": IoPlaySkipBack,
  "IoPlaySkipForwardCircleOutline": IoPlaySkipForwardCircleOutline,
  "IoPlaySkipForwardCircleSharp": IoPlaySkipForwardCircleSharp,
  "IoPlaySkipForwardCircle": IoPlaySkipForwardCircle,
  "IoPlaySkipForwardOutline": IoPlaySkipForwardOutline,
  "IoPlaySkipForwardSharp": IoPlaySkipForwardSharp,
  "IoPlaySkipForward": IoPlaySkipForward,
  "IoPlay": IoPlay,
  "IoPodiumOutline": IoPodiumOutline,
  "IoPodiumSharp": IoPodiumSharp,
  "IoPodium": IoPodium,
  "IoPowerOutline": IoPowerOutline,
  "IoPowerSharp": IoPowerSharp,
  "IoPower": IoPower,
  "IoPricetagOutline": IoPricetagOutline,
  "IoPricetagSharp": IoPricetagSharp,
  "IoPricetag": IoPricetag,
  "IoPricetagsOutline": IoPricetagsOutline,
  "IoPricetagsSharp": IoPricetagsSharp,
  "IoPricetags": IoPricetags,
  "IoPrintOutline": IoPrintOutline,
  "IoPrintSharp": IoPrintSharp,
  "IoPrint": IoPrint,
  "IoPrismOutline": IoPrismOutline,
  "IoPrismSharp": IoPrismSharp,
  "IoPrism": IoPrism,
  "IoPulseOutline": IoPulseOutline,
  "IoPulseSharp": IoPulseSharp,
  "IoPulse": IoPulse,
  "IoPushOutline": IoPushOutline,
  "IoPushSharp": IoPushSharp,
  "IoPush": IoPush,
  "IoQrCodeOutline": IoQrCodeOutline,
  "IoQrCodeSharp": IoQrCodeSharp,
  "IoQrCode": IoQrCode,
  "IoRadioButtonOffOutline": IoRadioButtonOffOutline,
  "IoRadioButtonOffSharp": IoRadioButtonOffSharp,
  "IoRadioButtonOff": IoRadioButtonOff,
  "IoRadioButtonOnOutline": IoRadioButtonOnOutline,
  "IoRadioButtonOnSharp": IoRadioButtonOnSharp,
  "IoRadioButtonOn": IoRadioButtonOn,
  "IoRadioOutline": IoRadioOutline,
  "IoRadioSharp": IoRadioSharp,
  "IoRadio": IoRadio,
  "IoRainyOutline": IoRainyOutline,
  "IoRainySharp": IoRainySharp,
  "IoRainy": IoRainy,
  "IoReaderOutline": IoReaderOutline,
  "IoReaderSharp": IoReaderSharp,
  "IoReader": IoReader,
  "IoReceiptOutline": IoReceiptOutline,
  "IoReceiptSharp": IoReceiptSharp,
  "IoReceipt": IoReceipt,
  "IoRecordingOutline": IoRecordingOutline,
  "IoRecordingSharp": IoRecordingSharp,
  "IoRecording": IoRecording,
  "IoRefreshCircleOutline": IoRefreshCircleOutline,
  "IoRefreshCircleSharp": IoRefreshCircleSharp,
  "IoRefreshCircle": IoRefreshCircle,
  "IoRefreshOutline": IoRefreshOutline,
  "IoRefreshSharp": IoRefreshSharp,
  "IoRefresh": IoRefresh,
  "IoReloadCircleOutline": IoReloadCircleOutline,
  "IoReloadCircleSharp": IoReloadCircleSharp,
  "IoReloadCircle": IoReloadCircle,
  "IoReloadOutline": IoReloadOutline,
  "IoReloadSharp": IoReloadSharp,
  "IoReload": IoReload,
  "IoRemoveCircleOutline": IoRemoveCircleOutline,
  "IoRemoveCircleSharp": IoRemoveCircleSharp,
  "IoRemoveCircle": IoRemoveCircle,
  "IoRemoveOutline": IoRemoveOutline,
  "IoRemoveSharp": IoRemoveSharp,
  "IoRemove": IoRemove,
  "IoReorderFourOutline": IoReorderFourOutline,
  "IoReorderFourSharp": IoReorderFourSharp,
  "IoReorderFour": IoReorderFour,
  "IoReorderThreeOutline": IoReorderThreeOutline,
  "IoReorderThreeSharp": IoReorderThreeSharp,
  "IoReorderThree": IoReorderThree,
  "IoReorderTwoOutline": IoReorderTwoOutline,
  "IoReorderTwoSharp": IoReorderTwoSharp,
  "IoReorderTwo": IoReorderTwo,
  "IoRepeatOutline": IoRepeatOutline,
  "IoRepeatSharp": IoRepeatSharp,
  "IoRepeat": IoRepeat,
  "IoResizeOutline": IoResizeOutline,
  "IoResizeSharp": IoResizeSharp,
  "IoResize": IoResize,
  "IoRestaurantOutline": IoRestaurantOutline,
  "IoRestaurantSharp": IoRestaurantSharp,
  "IoRestaurant": IoRestaurant,
  "IoReturnDownBackOutline": IoReturnDownBackOutline,
  "IoReturnDownBackSharp": IoReturnDownBackSharp,
  "IoReturnDownBack": IoReturnDownBack,
  "IoReturnDownForwardOutline": IoReturnDownForwardOutline,
  "IoReturnDownForwardSharp": IoReturnDownForwardSharp,
  "IoReturnDownForward": IoReturnDownForward,
  "IoReturnUpBackOutline": IoReturnUpBackOutline,
  "IoReturnUpBackSharp": IoReturnUpBackSharp,
  "IoReturnUpBack": IoReturnUpBack,
  "IoReturnUpForwardOutline": IoReturnUpForwardOutline,
  "IoReturnUpForwardSharp": IoReturnUpForwardSharp,
  "IoReturnUpForward": IoReturnUpForward,
  "IoRibbonOutline": IoRibbonOutline,
  "IoRibbonSharp": IoRibbonSharp,
  "IoRibbon": IoRibbon,
  "IoRocketOutline": IoRocketOutline,
  "IoRocketSharp": IoRocketSharp,
  "IoRocket": IoRocket,
  "IoRoseOutline": IoRoseOutline,
  "IoRoseSharp": IoRoseSharp,
  "IoRose": IoRose,
  "IoSadOutline": IoSadOutline,
  "IoSadSharp": IoSadSharp,
  "IoSad": IoSad,
  "IoSaveOutline": IoSaveOutline,
  "IoSaveSharp": IoSaveSharp,
  "IoSave": IoSave,
  "IoScaleOutline": IoScaleOutline,
  "IoScaleSharp": IoScaleSharp,
  "IoScale": IoScale,
  "IoScanCircleOutline": IoScanCircleOutline,
  "IoScanCircleSharp": IoScanCircleSharp,
  "IoScanCircle": IoScanCircle,
  "IoScanOutline": IoScanOutline,
  "IoScanSharp": IoScanSharp,
  "IoScan": IoScan,
  "IoSchoolOutline": IoSchoolOutline,
  "IoSchoolSharp": IoSchoolSharp,
  "IoSchool": IoSchool,
  "IoSearchCircleOutline": IoSearchCircleOutline,
  "IoSearchCircleSharp": IoSearchCircleSharp,
  "IoSearchCircle": IoSearchCircle,
  "IoSearchOutline": IoSearchOutline,
  "IoSearchSharp": IoSearchSharp,
  "IoSearch": IoSearch,
  "IoSendOutline": IoSendOutline,
  "IoSendSharp": IoSendSharp,
  "IoSend": IoSend,
  "IoServerOutline": IoServerOutline,
  "IoServerSharp": IoServerSharp,
  "IoServer": IoServer,
  "IoSettingsOutline": IoSettingsOutline,
  "IoSettingsSharp": IoSettingsSharp,
  "IoSettings": IoSettings,
  "IoShapesOutline": IoShapesOutline,
  "IoShapesSharp": IoShapesSharp,
  "IoShapes": IoShapes,
  "IoShareOutline": IoShareOutline,
  "IoShareSharp": IoShareSharp,
  "IoShareSocialOutline": IoShareSocialOutline,
  "IoShareSocialSharp": IoShareSocialSharp,
  "IoShareSocial": IoShareSocial,
  "IoShare": IoShare,
  "IoShieldCheckmarkOutline": IoShieldCheckmarkOutline,
  "IoShieldCheckmarkSharp": IoShieldCheckmarkSharp,
  "IoShieldCheckmark": IoShieldCheckmark,
  "IoShieldHalfOutline": IoShieldHalfOutline,
  "IoShieldHalfSharp": IoShieldHalfSharp,
  "IoShieldHalf": IoShieldHalf,
  "IoShieldOutline": IoShieldOutline,
  "IoShieldSharp": IoShieldSharp,
  "IoShield": IoShield,
  "IoShirtOutline": IoShirtOutline,
  "IoShirtSharp": IoShirtSharp,
  "IoShirt": IoShirt,
  "IoShuffleOutline": IoShuffleOutline,
  "IoShuffleSharp": IoShuffleSharp,
  "IoShuffle": IoShuffle,
  "IoSkullOutline": IoSkullOutline,
  "IoSkullSharp": IoSkullSharp,
  "IoSkull": IoSkull,
  "IoSnowOutline": IoSnowOutline,
  "IoSnowSharp": IoSnowSharp,
  "IoSnow": IoSnow,
  "IoSparklesOutline": IoSparklesOutline,
  "IoSparklesSharp": IoSparklesSharp,
  "IoSparkles": IoSparkles,
  "IoSpeedometerOutline": IoSpeedometerOutline,
  "IoSpeedometerSharp": IoSpeedometerSharp,
  "IoSpeedometer": IoSpeedometer,
  "IoSquareOutline": IoSquareOutline,
  "IoSquareSharp": IoSquareSharp,
  "IoSquare": IoSquare,
  "IoStarHalfOutline": IoStarHalfOutline,
  "IoStarHalfSharp": IoStarHalfSharp,
  "IoStarHalf": IoStarHalf,
  "IoStarOutline": IoStarOutline,
  "IoStarSharp": IoStarSharp,
  "IoStar": IoStar,
  "IoStatsChartOutline": IoStatsChartOutline,
  "IoStatsChartSharp": IoStatsChartSharp,
  "IoStatsChart": IoStatsChart,
  "IoStopCircleOutline": IoStopCircleOutline,
  "IoStopCircleSharp": IoStopCircleSharp,
  "IoStopCircle": IoStopCircle,
  "IoStopOutline": IoStopOutline,
  "IoStopSharp": IoStopSharp,
  "IoStop": IoStop,
  "IoStopwatchOutline": IoStopwatchOutline,
  "IoStopwatchSharp": IoStopwatchSharp,
  "IoStopwatch": IoStopwatch,
  "IoStorefrontOutline": IoStorefrontOutline,
  "IoStorefrontSharp": IoStorefrontSharp,
  "IoStorefront": IoStorefront,
  "IoSubwayOutline": IoSubwayOutline,
  "IoSubwaySharp": IoSubwaySharp,
  "IoSubway": IoSubway,
  "IoSunnyOutline": IoSunnyOutline,
  "IoSunnySharp": IoSunnySharp,
  "IoSunny": IoSunny,
  "IoSwapHorizontalOutline": IoSwapHorizontalOutline,
  "IoSwapHorizontalSharp": IoSwapHorizontalSharp,
  "IoSwapHorizontal": IoSwapHorizontal,
  "IoSwapVerticalOutline": IoSwapVerticalOutline,
  "IoSwapVerticalSharp": IoSwapVerticalSharp,
  "IoSwapVertical": IoSwapVertical,
  "IoSyncCircleOutline": IoSyncCircleOutline,
  "IoSyncCircleSharp": IoSyncCircleSharp,
  "IoSyncCircle": IoSyncCircle,
  "IoSyncOutline": IoSyncOutline,
  "IoSyncSharp": IoSyncSharp,
  "IoSync": IoSync,
  "IoTabletLandscapeOutline": IoTabletLandscapeOutline,
  "IoTabletLandscapeSharp": IoTabletLandscapeSharp,
  "IoTabletLandscape": IoTabletLandscape,
  "IoTabletPortraitOutline": IoTabletPortraitOutline,
  "IoTabletPortraitSharp": IoTabletPortraitSharp,
  "IoTabletPortrait": IoTabletPortrait,
  "IoTelescopeOutline": IoTelescopeOutline,
  "IoTelescopeSharp": IoTelescopeSharp,
  "IoTelescope": IoTelescope,
  "IoTennisballOutline": IoTennisballOutline,
  "IoTennisballSharp": IoTennisballSharp,
  "IoTennisball": IoTennisball,
  "IoTerminalOutline": IoTerminalOutline,
  "IoTerminalSharp": IoTerminalSharp,
  "IoTerminal": IoTerminal,
  "IoTextOutline": IoTextOutline,
  "IoTextSharp": IoTextSharp,
  "IoText": IoText,
  "IoThermometerOutline": IoThermometerOutline,
  "IoThermometerSharp": IoThermometerSharp,
  "IoThermometer": IoThermometer,
  "IoThumbsDownOutline": IoThumbsDownOutline,
  "IoThumbsDownSharp": IoThumbsDownSharp,
  "IoThumbsDown": IoThumbsDown,
  "IoThumbsUpOutline": IoThumbsUpOutline,
  "IoThumbsUpSharp": IoThumbsUpSharp,
  "IoThumbsUp": IoThumbsUp,
  "IoThunderstormOutline": IoThunderstormOutline,
  "IoThunderstormSharp": IoThunderstormSharp,
  "IoThunderstorm": IoThunderstorm,
  "IoTicketOutline": IoTicketOutline,
  "IoTicketSharp": IoTicketSharp,
  "IoTicket": IoTicket,
  "IoTimeOutline": IoTimeOutline,
  "IoTimeSharp": IoTimeSharp,
  "IoTime": IoTime,
  "IoTimerOutline": IoTimerOutline,
  "IoTimerSharp": IoTimerSharp,
  "IoTimer": IoTimer,
  "IoTodayOutline": IoTodayOutline,
  "IoTodaySharp": IoTodaySharp,
  "IoToday": IoToday,
  "IoToggleOutline": IoToggleOutline,
  "IoToggleSharp": IoToggleSharp,
  "IoToggle": IoToggle,
  "IoTrailSignOutline": IoTrailSignOutline,
  "IoTrailSignSharp": IoTrailSignSharp,
  "IoTrailSign": IoTrailSign,
  "IoTrainOutline": IoTrainOutline,
  "IoTrainSharp": IoTrainSharp,
  "IoTrain": IoTrain,
  "IoTransgenderOutline": IoTransgenderOutline,
  "IoTransgenderSharp": IoTransgenderSharp,
  "IoTransgender": IoTransgender,
  "IoTrashBinOutline": IoTrashBinOutline,
  "IoTrashBinSharp": IoTrashBinSharp,
  "IoTrashBin": IoTrashBin,
  "IoTrashOutline": IoTrashOutline,
  "IoTrashSharp": IoTrashSharp,
  "IoTrash": IoTrash,
  "IoTrendingDownOutline": IoTrendingDownOutline,
  "IoTrendingDownSharp": IoTrendingDownSharp,
  "IoTrendingDown": IoTrendingDown,
  "IoTrendingUpOutline": IoTrendingUpOutline,
  "IoTrendingUpSharp": IoTrendingUpSharp,
  "IoTrendingUp": IoTrendingUp,
  "IoTriangleOutline": IoTriangleOutline,
  "IoTriangleSharp": IoTriangleSharp,
  "IoTriangle": IoTriangle,
  "IoTrophyOutline": IoTrophyOutline,
  "IoTrophySharp": IoTrophySharp,
  "IoTrophy": IoTrophy,
  "IoTvOutline": IoTvOutline,
  "IoTvSharp": IoTvSharp,
  "IoTv": IoTv,
  "IoUmbrellaOutline": IoUmbrellaOutline,
  "IoUmbrellaSharp": IoUmbrellaSharp,
  "IoUmbrella": IoUmbrella,
  "IoUnlinkOutline": IoUnlinkOutline,
  "IoUnlinkSharp": IoUnlinkSharp,
  "IoUnlink": IoUnlink,
  "IoVideocamOffOutline": IoVideocamOffOutline,
  "IoVideocamOffSharp": IoVideocamOffSharp,
  "IoVideocamOff": IoVideocamOff,
  "IoVideocamOutline": IoVideocamOutline,
  "IoVideocamSharp": IoVideocamSharp,
  "IoVideocam": IoVideocam,
  "IoVolumeHighOutline": IoVolumeHighOutline,
  "IoVolumeHighSharp": IoVolumeHighSharp,
  "IoVolumeHigh": IoVolumeHigh,
  "IoVolumeLowOutline": IoVolumeLowOutline,
  "IoVolumeLowSharp": IoVolumeLowSharp,
  "IoVolumeLow": IoVolumeLow,
  "IoVolumeMediumOutline": IoVolumeMediumOutline,
  "IoVolumeMediumSharp": IoVolumeMediumSharp,
  "IoVolumeMedium": IoVolumeMedium,
  "IoVolumeMuteOutline": IoVolumeMuteOutline,
  "IoVolumeMuteSharp": IoVolumeMuteSharp,
  "IoVolumeMute": IoVolumeMute,
  "IoVolumeOffOutline": IoVolumeOffOutline,
  "IoVolumeOffSharp": IoVolumeOffSharp,
  "IoVolumeOff": IoVolumeOff,
  "IoWalkOutline": IoWalkOutline,
  "IoWalkSharp": IoWalkSharp,
  "IoWalk": IoWalk,
  "IoWalletOutline": IoWalletOutline,
  "IoWalletSharp": IoWalletSharp,
  "IoWallet": IoWallet,
  "IoWarningOutline": IoWarningOutline,
  "IoWarningSharp": IoWarningSharp,
  "IoWarning": IoWarning,
  "IoWatchOutline": IoWatchOutline,
  "IoWatchSharp": IoWatchSharp,
  "IoWatch": IoWatch,
  "IoWaterOutline": IoWaterOutline,
  "IoWaterSharp": IoWaterSharp,
  "IoWater": IoWater,
  "IoWifiOutline": IoWifiOutline,
  "IoWifiSharp": IoWifiSharp,
  "IoWifi": IoWifi,
  "IoWineOutline": IoWineOutline,
  "IoWineSharp": IoWineSharp,
  "IoWine": IoWine,
  "IoWomanOutline": IoWomanOutline,
  "IoWomanSharp": IoWomanSharp,
  "IoWoman": IoWoman,
};