//import { 
//    SlActionRedo,
//SlActionUndo,
//SlAnchor,
//SlArrowDownCircle,
//SlArrowDown,
//SlArrowLeftCircle,
//SlArrowLeft,
//SlArrowRightCircle,
//SlArrowRight,
//SlArrowUpCircle,
//SlArrowUp,
//SlBadge,
//SlBag,
//SlBan,
//SlBasketLoaded,
//SlBasket,
//SlBell,
//SlBookOpen,
//SlBriefcase,
//SlBubble,
//SlBubbles,
//SlBulb,
//SlCalculator,
//SlCalender,
//SlCallEnd,
//SlCallIn,
//SlCallOut,
//SlCamera,
//SlCamrecorder,
//SlChart,
//SlCheck,
//SlChemistry,
//SlClock,
//SlClose,
//SlCloudDownload,
//SlCloudUpload,
//SlCompass,
//SlControlEnd,
//SlControlForward,
//SlControlPause,
//SlControlPlay,
//SlControlRewind,
//SlControlStart,
//SlCreditCard,
//SlCrop,
//SlCup,
//SlCursorMove,
//SlCursor,
//SlDiamond,
//SlDirection,
//SlDirections,
//SlDisc,
//SlDislike,
//SlDoc,
//SlDocs,
//SlDrawer,
//SlDrop,
//SlEarphonesAlt,
//SlEarphones,
//SlEmotsmile,
//SlEnergy,
//SlEnvelopeOpen,
//SlEnvolopeLetter,
//SlEnvolope,
//SlEqualizer,
//SlEvent,
//SlExclamation,
//SlEye,
//SlEyeglass,
//SlFeed,
//SlFilm,
//SlFire,
//SlFlag,
//SlFolderAlt,
//SlFolder,
//SlFrame,
//SlGameController,
//SlGhost,
//SlGlobeAlt,
//SlGlobe,
//SlGraduation,
//SlGraph,
//SlGrid,
//SlHandbag,
//SlHeart,
//SlHome,
//SlHourglass,
//SlInfo,
//SlKey,
//SlLayers,
//SlLike,
//SlLink,
//SlList,
//SlLocationPin,
//SlLockOpen,
//SlLock,
//SlLogin,
//SlLogout,
//SlLoop,
//SlMagicWand,
//SlMagnet,
//SlMagnifierAdd,
//SlMagnifierRemove,
//SlMagnifier,
//SlMap,
//SlMenu,
//SlMicrophone,
//SlMinus,
//SlMouse,
//SlMusicToneAlt,
//SlMusicTone,
//SlMustache,
//SlNote,
//SlNotebook,
//SlOptionsVertical,
//SlOptions,
//SlOrganization,
//SlPaperClip,
//SlPaperPlane,
//SlPaypal,
//SlPencil,
//SlPeople,
//SlPhone,
//SlPicture,
//SlPieChart,
//SlPin,
//SlPlane,
//SlPlaylist,
//SlPlus,
//SlPower,
//SlPresent,
//SlPrinter,
//SlPuzzle,
//SlQuestion,
//SlRefresh,
//SlReload,
//SlRocket,
//SlScreenDesktop,
//SlScreenSmartphone,
//SlScreenTablet,
//SlSettings,
//SlShareAlt,
//SlShare,
//SlShield,
//SlShuffle,
//SlSizeActual,
//SlSizeFullscreen,
//SlSocialBehance,
//SlSocialDribbble,
//SlSocialDropbox,
//SlSocialFacebook,
//SlSocialFoursqare,
//SlSocialGithub,
//SlSocialGoogle,
//SlSocialInstagram,
//SlSocialLinkedin,
//SlSocialPintarest,
//SlSocialReddit,
//SlSocialSkype,
//SlSocialSoundcloud,
//SlSocialSpotify,
//SlSocialSteam,
//SlSocialStumbleupon,
//SlSocialTumblr,
//SlSocialTwitter,
//SlSocialVkontakte,
//SlSocialYoutube,
//SlSpeech,
//SlSpeedometer,
//SlStar,
//SlSupport,
//SlSymbleFemale,
//SlSymbolMale,
//SlTag,
//SlTarget,
//SlTrash,
//SlTrophy,
//SlUmbrella,
//SlUserFemale,
//SlUserFollow,
//SlUserFollowing,
//SlUserUnfollow,
//SlUser,
//SlVector,
//SlVolume1,
//SlVolume2,
//SlVolumeOff,
//SlWallet,
//SlWrench
// } from "react-icons/sl";

//export const SimpleLineIcons = {
//    "SlActionRedo": SlActionRedo,
//    "SlActionUndo": SlActionUndo,
//    "SlAnchor": SlAnchor,
//    "SlArrowDownCircle": SlArrowDownCircle,
//    "SlArrowDown": SlArrowDown,
//    "SlArrowLeftCircle": SlArrowLeftCircle,
//    "SlArrowLeft": SlArrowLeft,
//    "SlArrowRightCircle": SlArrowRightCircle,
//    "SlArrowRight": SlArrowRight,
//    "SlArrowUpCircle": SlArrowUpCircle,
//    "SlArrowUp": SlArrowUp,
//    "SlBadge": SlBadge,
//    "SlBag": SlBag,
//    "SlBan": SlBan,
//    "SlBasketLoaded": SlBasketLoaded,
//    "SlBasket": SlBasket,
//    "SlBell": SlBell,
//    "SlBookOpen": SlBookOpen,
//    "SlBriefcase": SlBriefcase,
//    "SlBubble": SlBubble,
//    "SlBubbles": SlBubbles,
//    "SlBulb": SlBulb,
//    "SlCalculator": SlCalculator,
//    "SlCalender": SlCalender,
//    "SlCallEnd": SlCallEnd,
//    "SlCallIn": SlCallIn,
//    "SlCallOut": SlCallOut,
//    "SlCamera": SlCamera,
//    "SlCamrecorder": SlCamrecorder,
//    "SlChart": SlChart,
//    "SlCheck": SlCheck,
//    "SlChemistry": SlChemistry,
//    "SlClock": SlClock,
//    "SlClose": SlClose,
//    "SlCloudDownload": SlCloudDownload,
//    "SlCloudUpload": SlCloudUpload,
//    "SlCompass": SlCompass,
//    "SlControlEnd": SlControlEnd,
//    "SlControlForward": SlControlForward,
//    "SlControlPause": SlControlPause,
//    "SlControlPlay": SlControlPlay,
//    "SlControlRewind": SlControlRewind,
//    "SlControlStart": SlControlStart,
//    "SlCreditCard": SlCreditCard,
//    "SlCrop": SlCrop,
//    "SlCup": SlCup,
//    "SlCursorMove": SlCursorMove,
//    "SlCursor": SlCursor,
//    "SlDiamond": SlDiamond,
//    "SlDirection": SlDirection,
//    "SlDirections": SlDirections,
//    "SlDisc": SlDisc,
//    "SlDislike": SlDislike,
//    "SlDoc": SlDoc,
//    "SlDocs": SlDocs,
//    "SlDrawer": SlDrawer,
//    "SlDrop": SlDrop,
//    "SlEarphonesAlt": SlEarphonesAlt,
//    "SlEarphones": SlEarphones,
//    "SlEmotsmile": SlEmotsmile,
//    "SlEnergy": SlEnergy,
//    "SlEnvelopeOpen": SlEnvelopeOpen,
//    "SlEnvolopeLetter": SlEnvolopeLetter,
//    "SlEnvolope": SlEnvolope,
//    "SlEqualizer": SlEqualizer,
//    "SlEvent": SlEvent,
//    "SlExclamation": SlExclamation,
//    "SlEye": SlEye,
//    "SlEyeglass": SlEyeglass,
//    "SlFeed": SlFeed,
//    "SlFilm": SlFilm,
//    "SlFire": SlFire,
//    "SlFlag": SlFlag,
//    "SlFolderAlt": SlFolderAlt,
//    "SlFolder": SlFolder,
//    "SlFrame": SlFrame,
//    "SlGameController": SlGameController,
//    "SlGhost": SlGhost,
//    "SlGlobeAlt": SlGlobeAlt,
//    "SlGlobe": SlGlobe,
//    "SlGraduation": SlGraduation,
//    "SlGraph": SlGraph,
//    "SlGrid": SlGrid,
//    "SlHandbag": SlHandbag,
//    "SlHeart": SlHeart,
//    "SlHome": SlHome,
//    "SlHourglass": SlHourglass,
//    "SlInfo": SlInfo,
//    "SlKey": SlKey,
//    "SlLayers": SlLayers,
//    "SlLike": SlLike,
//    "SlLink": SlLink,
//    "SlList": SlList,
//    "SlLocationPin": SlLocationPin,
//    "SlLockOpen": SlLockOpen,
//    "SlLock": SlLock,
//    "SlLogin": SlLogin,
//    "SlLogout": SlLogout,
//    "SlLoop": SlLoop,
//    "SlMagicWand": SlMagicWand,
//    "SlMagnet": SlMagnet,
//    "SlMagnifierAdd": SlMagnifierAdd,
//    "SlMagnifierRemove": SlMagnifierRemove,
//    "SlMagnifier": SlMagnifier,
//    "SlMap": SlMap,
//    "SlMenu": SlMenu,
//    "SlMicrophone": SlMicrophone,
//    "SlMinus": SlMinus,
//    "SlMouse": SlMouse,
//    "SlMusicToneAlt": SlMusicToneAlt,
//    "SlMusicTone": SlMusicTone,
//    "SlMustache": SlMustache,
//    "SlNote": SlNote,
//    "SlNotebook": SlNotebook,
//    "SlOptionsVertical": SlOptionsVertical,
//    "SlOptions": SlOptions,
//    "SlOrganization": SlOrganization,
//    "SlPaperClip": SlPaperClip,
//    "SlPaperPlane": SlPaperPlane,
//    "SlPaypal": SlPaypal,
//    "SlPencil": SlPencil,
//    "SlPeople": SlPeople,
//    "SlPhone": SlPhone,
//    "SlPicture": SlPicture,
//    "SlPieChart": SlPieChart,
//    "SlPin": SlPin,
//    "SlPlane": SlPlane,
//    "SlPlaylist": SlPlaylist,
//    "SlPlus": SlPlus,
//    "SlPower": SlPower,
//    "SlPresent": SlPresent,
//    "SlPrinter": SlPrinter,
//    "SlPuzzle": SlPuzzle,
//    "SlQuestion": SlQuestion,
//    "SlRefresh": SlRefresh,
//    "SlReload": SlReload,
//    "SlRocket": SlRocket,
//    "SlScreenDesktop": SlScreenDesktop,
//    "SlScreenSmartphone": SlScreenSmartphone,
//    "SlScreenTablet": SlScreenTablet,
//    "SlSettings": SlSettings,
//    "SlShareAlt": SlShareAlt,
//    "SlShare": SlShare,
//    "SlShield": SlShield,
//    "SlShuffle": SlShuffle,
//    "SlSizeActual": SlSizeActual,
//    "SlSizeFullscreen": SlSizeFullscreen,
//    "SlSocialBehance": SlSocialBehance,
//    "SlSocialDribbble": SlSocialDribbble,
//    "SlSocialDropbox": SlSocialDropbox,
//    "SlSocialFacebook": SlSocialFacebook,
//    "SlSocialFoursqare": SlSocialFoursqare,
//    "SlSocialGithub": SlSocialGithub,
//    "SlSocialGoogle": SlSocialGoogle,
//    "SlSocialInstagram": SlSocialInstagram,
//    "SlSocialLinkedin": SlSocialLinkedin,
//    "SlSocialPintarest": SlSocialPintarest,
//    "SlSocialReddit": SlSocialReddit,
//    "SlSocialSkype": SlSocialSkype,
//    "SlSocialSoundcloud": SlSocialSoundcloud,
//    "SlSocialSpotify": SlSocialSpotify,
//    "SlSocialSteam": SlSocialSteam,
//    "SlSocialStumbleupon": SlSocialStumbleupon,
//    "SlSocialTumblr": SlSocialTumblr,
//    "SlSocialTwitter": SlSocialTwitter,
//    "SlSocialVkontakte": SlSocialVkontakte,
//    "SlSocialYoutube": SlSocialYoutube,
//    "SlSpeech": SlSpeech,
//    "SlSpeedometer": SlSpeedometer,
//    "SlStar": SlStar,
//    "SlSupport": SlSupport,
//    "SlSymbleFemale": SlSymbleFemale,
//    "SlSymbolMale": SlSymbolMale,
//    "SlTag": SlTag,
//    "SlTarget": SlTarget,
//    "SlTrash": SlTrash,
//    "SlTrophy": SlTrophy,
//    "SlUmbrella": SlUmbrella,
//    "SlUserFemale": SlUserFemale,
//    "SlUserFollow": SlUserFollow,
//    "SlUserFollowing": SlUserFollowing,
//    "SlUserUnfollow": SlUserUnfollow,
//    "SlUser": SlUser,
//    "SlVector": SlVector,
//    "SlVolume1": SlVolume1,
//    "SlVolume2": SlVolume2,
//    "SlVolumeOff": SlVolumeOff,
//    "SlWallet": SlWallet,
//    "SlWrench": SlWrench,
//}