//import { TfiAgenda,
//    TfiAlarmClock,
//    TfiAlert,
//    TfiAlignCenter,
//    TfiAlignJustify,
//    TfiAlignLeft,
//    TfiAlignRight,
//    TfiAnchor,
//    TfiAndroid,
//    TfiAngleDoubleDown,
//    TfiAngleDoubleLeft,
//    TfiAngleDoubleRight,
//    TfiAngleDoubleUp,
//    TfiAngleDown,
//    TfiAngleLeft,
//    TfiAngleRight,
//    TfiAngleUp,
//    TfiAnnouncement,
//    TfiApple,
//    TfiArchive,
//    TfiArrowCircleDown,
//    TfiArrowCircleLeft,
//    TfiArrowCircleRight,
//    TfiArrowCircleUp,
//    TfiArrowDown,
//    TfiArrowLeft,
//    TfiArrowRight,
//    TfiArrowTopLeft,
//    TfiArrowTopRight,
//    TfiArrowUp,
//    TfiArrow,
//    TfiArrowsCorner,
//    TfiArrowsHorizontal,
//    TfiArrowsVertical,
//    TfiBackLeft,
//    TfiBackRight,
//    TfiBag,
//    TfiBarChartAlt,
//    TfiBarChart,
//    TfiBasketball,
//    TfiBell,
//    TfiBlackboard,
//    TfiBoltAlt,
//    TfiBolt,
//    TfiBook,
//    TfiBookmarkAlt,
//    TfiBookmark,
//    TfiBriefcase,
//    TfiBrushAlt,
//    TfiBrush,
//    TfiCalendar,
//    TfiCamera,
//    TfiCar,
//    TfiCheckBox,
//    TfiCheck,
//    TfiClip,
//    TfiClipboard,
//    TfiClose,
//    TfiCloudDown,
//    TfiCloudUp,
//    TfiCloud,
//    TfiCommentAlt,
//    TfiComment,
//    TfiCommentsSmiley,
//    TfiComments,
//    TfiControlBackward,
//    TfiControlEject,
//    TfiControlForward,
//    TfiControlPause,
//    TfiControlPlay,
//    TfiControlRecord,
//    TfiControlShuffle,
//    TfiControlSkipBackward,
//    TfiControlSkipForward,
//    TfiControlStop,
//    TfiCreditCard,
//    TfiCrown,
//    TfiCss3,
//    TfiCup,
//    TfiCut,
//    TfiDashboard,
//    TfiDesktop,
//    TfiDirectionAlt,
//    TfiDirection,
//    TfiDownload,
//    TfiDribbble,
//    TfiDropboxAlt,
//    TfiDropbox,
//    TfiDrupal,
//    TfiEmail,
//    TfiEnvelope,
//    TfiEraser,
//    TfiExchangeVertical,
//    TfiExport,
//    TfiEye,
//    TfiFaceSad,
//    TfiFaceSmile,
//    TfiFacebook,
//    TfiFile,
//    TfiFiles,
//    TfiFilter,
//    TfiFlagAlt2,
//    TfiFlagAlt,
//    TfiFlag,
//    TfiFlickrAlt,
//    TfiFlickr,
//    TfiFolder,
//    TfiFullscreen,
//    TfiGallery,
//    TfiGame,
//    TfiGift,
//    TfiGithub,
//    TfiGoogle,
//    TfiHandDrag,
//    TfiHandOpen,
//    TfiHandPointDown,
//    TfiHandPointLeft,
//    TfiHandPointRight,
//    TfiHandPointUp,
//    TfiHandStop,
//    TfiHarddrive,
//    TfiHarddrives,
//    TfiHeadphoneAlt,
//    TfiHeadphone,
//    TfiHeartBroken,
//    TfiHeart,
//    TfiHelpAlt,
//    TfiHelp,
//    TfiHome,
//    TfiHtml5,
//    TfiHummer,
//    TfiIdBadge,
//    TfiImage,
//    TfiImport,
//    TfiInfinite,
//    TfiInfoAlt,
//    TfiInfo,
//    TfiInkPen,
//    TfiInstagram,
//    TfiItalic,
//    TfiJoomla,
//    TfiJsfiddle,
//    TfiKey,
//    TfiLayersAlt,
//    TfiLayers,
//    TfiLayoutAccordionList,
//    TfiLayoutAccordionMerged,
//    TfiLayoutAccordionSeparated,
//    TfiLayoutColumn2Alt,
//    TfiLayoutColumn2,
//    TfiLayoutColumn3Alt,
//    TfiLayoutColumn3,
//    TfiLayoutColumn4Alt,
//    TfiLayoutColumn4,
//    TfiLayoutCtaBtnLeft,
//    TfiLayoutCtaBtnRight,
//    TfiLayoutCtaCenter,
//    TfiLayoutCtaLeft,
//    TfiLayoutCtaRight,
//    TfiLayoutGrid2Alt,
//    TfiLayoutGrid2Thumb,
//    TfiLayoutGrid2,
//    TfiLayoutGrid3Alt,
//    TfiLayoutGrid3,
//    TfiLayoutGrid4Alt,
//    TfiLayoutGrid4,
//    TfiLayoutLineSolid,
//    TfiLayoutListLargeImage,
//    TfiLayoutListPost,
//    TfiLayoutListThumbAlt,
//    TfiLayoutListThumb,
//    TfiLayoutMediaCenterAlt,
//    TfiLayoutMediaCenter,
//    TfiLayoutMediaLeftAlt,
//    TfiLayoutMediaLeft,
//    TfiLayoutMediaOverlayAlt2,
//    TfiLayoutMediaOverlayAlt,
//    TfiLayoutMediaOverlay,
//    TfiLayoutMediaRightAlt,
//    TfiLayoutMediaRight,
//    TfiLayoutMenuFull,
//    TfiLayoutMenuSeparated,
//    TfiLayoutMenuV,
//    TfiLayoutMenu,
//    TfiLayoutPlaceholder,
//    TfiLayoutSidebar2,
//    TfiLayoutSidebarLeft,
//    TfiLayoutSidebarNone,
//    TfiLayoutSidebarRight,
//    TfiLayoutSliderAlt,
//    TfiLayoutSlider,
//    TfiLayoutTabMin,
//    TfiLayoutTabV,
//    TfiLayoutTabWindow,
//    TfiLayoutTab,
//    TfiLayoutWidthDefaultAlt,
//    TfiLayoutWidthDefault,
//    TfiLayoutWidthFull,
//    TfiLayout,
//    TfiLightBulb,
//    TfiLineDashed,
//    TfiLineDotted,
//    TfiLineDouble,
//    TfiLink,
//    TfiLinkedin,
//    TfiLinux,
//    TfiListOl,
//    TfiList,
//    TfiLocationArrow,
//    TfiLocationPin,
//    TfiLock,
//    TfiLoop,
//    TfiMagnet,
//    TfiMapAlt,
//    TfiMap,
//    TfiMarkerAlt,
//    TfiMarker,
//    TfiMedallAlt,
//    TfiMedall,
//    TfiMenuAlt,
//    TfiMenu,
//    TfiMicrophoneAlt,
//    TfiMicrophone,
//    TfiMicrosoftAlt,
//    TfiMicrosoft,
//    TfiMinus,
//    TfiMobile,
//    TfiMoney,
//    TfiMoreAlt,
//    TfiMore,
//    TfiMouseAlt,
//    TfiMouse,
//    TfiMusicAlt,
//    TfiMusic,
//    TfiNa,
//    TfiNewWindow,
//    TfiNotepad,
//    TfiPackage,
//    TfiPaintBucket,
//    TfiPaintRoller,
//    TfiPalette,
//    TfiPanel,
//    TfiParagraph,
//    TfiPencilAlt,
//    TfiPencilAlt2,
//    TfiPencil,
//    TfiPieChart,
//    TfiPinAlt,
//    TfiPin,
//    TfiPin2,
//    TfiPinterestAlt,
//    TfiPinterest,
//    TfiPlug,
//    TfiPlus,
//    TfiPowerOff,
//    TfiPrinter,
//    TfiPulse,
//    TfiQuoteLeft,
//    TfiQuoteRight,
//    TfiReceipt,
//    TfiReddit,
//    TfiReload,
//    TfiRocket,
//    TfiRssAlt,
//    TfiRss,
//    TfiRulerAlt2,
//    TfiRulerAlt,
//    TfiRulerPencil,
//    TfiRuler,
//    TfiSaveAlt,
//    TfiSave,
//    TfiSearch,
//    TfiServer,
//    TfiSettings,
//    TfiShareAlt,
//    TfiShare,
//    TfiSharethisAlt,
//    TfiSharethis,
//    TfiShield,
//    TfiShiftLeftAlt,
//    TfiShiftLeft,
//    TfiShiftRightAlt,
//    TfiShiftRight,
//    TfiShine,
//    TfiShoppingCartFull,
//    TfiShoppingCart,
//    TfiShortcode,
//    TfiSignal,
//    TfiSkype,
//    TfiSlice,
//    TfiSmallcap,
//    TfiSoundcloud,
//    TfiSplitH,
//    TfiSplitVAlt,
//    TfiSplitV,
//    TfiSpray,
//    TfiStackOverflow,
//    TfiStamp,
//    TfiStar,
//    TfiStatsDown,
//    TfiStatsUp,
//    TfiSupport,
//    TfiTablet,
//    TfiTag,
//    TfiTarget,
//    TfiText,
//    TfiThemifyFaviconAlt,
//    TfiThemifyFavicon,
//    TfiThemifyLogo,
//    TfiThought,
//    TfiThumbDown,
//    TfiThumbUp,
//    TfiTicket,
//    TfiTime,
//    TfiTimer,
//    TfiTrash,
//    TfiTrello,
//    TfiTruck,
//    TfiTumblrAlt,
//    TfiTumblr,
//    TfiTwitterAlt,
//    TfiTwitter,
//    TfiUnderline,
//    TfiUnlink,
//    TfiUnlock,
//    TfiUpload,
//    TfiUppercase,
//    TfiUser,
//    TfiVector,
//    TfiVideoCamera,
//    TfiVideoClapper,
//    TfiViewGrid,
//    TfiViewListAlt,
//    TfiViewList,
//    TfiVimeoAlt,
//    TfiVimeo,
//    TfiVolume,
//    TfiWallet,
//    TfiWand,
//    TfiWheelchair,
//    TfiWidgetAlt,
//    TfiWidget,
//    TfiWidgetized,
//    TfiWindow,
//    TfiWordpress,
//    TfiWorld,
//    TfiWrite,
//    TfiYahoo,
//    TfiYoutube,
//    TfiZip,
//    TfiZoomIn,
//    TfiZoomOut
// } from "react-icons/tfi";

//export const ThemifyIcons = {
//    "TfiAgenda": TfiAgenda,
//    "TfiAlarmClock": TfiAlarmClock,
//    "TfiAlert": TfiAlert,
//    "TfiAlignCenter": TfiAlignCenter,
//    "TfiAlignJustify": TfiAlignJustify,
//    "TfiAlignLeft": TfiAlignLeft,
//    "TfiAlignRight": TfiAlignRight,
//    "TfiAnchor": TfiAnchor,
//    "TfiAndroid": TfiAndroid,
//    "TfiAngleDoubleDown": TfiAngleDoubleDown,
//    "TfiAngleDoubleLeft": TfiAngleDoubleLeft,
//    "TfiAngleDoubleRight": TfiAngleDoubleRight,
//    "TfiAngleDoubleUp": TfiAngleDoubleUp,
//    "TfiAngleDown": TfiAngleDown,
//    "TfiAngleLeft": TfiAngleLeft,
//    "TfiAngleRight": TfiAngleRight,
//    "TfiAngleUp": TfiAngleUp,
//    "TfiAnnouncement": TfiAnnouncement,
//    "TfiApple": TfiApple,
//    "TfiArchive": TfiArchive,
//    "TfiArrowCircleDown": TfiArrowCircleDown,
//    "TfiArrowCircleLeft": TfiArrowCircleLeft,
//    "TfiArrowCircleRight": TfiArrowCircleRight,
//    "TfiArrowCircleUp": TfiArrowCircleUp,
//    "TfiArrowDown": TfiArrowDown,
//    "TfiArrowLeft": TfiArrowLeft,
//    "TfiArrowRight": TfiArrowRight,
//    "TfiArrowTopLeft": TfiArrowTopLeft,
//    "TfiArrowTopRight": TfiArrowTopRight,
//    "TfiArrowUp": TfiArrowUp,
//    "TfiArrow": TfiArrow,
//    "TfiArrowsCorner": TfiArrowsCorner,
//    "TfiArrowsHorizontal": TfiArrowsHorizontal,
//    "TfiArrowsVertical": TfiArrowsVertical,
//    "TfiBackLeft": TfiBackLeft,
//    "TfiBackRight": TfiBackRight,
//    "TfiBag": TfiBag,
//    "TfiBarChartAlt": TfiBarChartAlt,
//    "TfiBarChart": TfiBarChart,
//    "TfiBasketball": TfiBasketball,
//    "TfiBell": TfiBell,
//    "TfiBlackboard": TfiBlackboard,
//    "TfiBoltAlt": TfiBoltAlt,
//    "TfiBolt": TfiBolt,
//    "TfiBook": TfiBook,
//    "TfiBookmarkAlt": TfiBookmarkAlt,
//    "TfiBookmark": TfiBookmark,
//    "TfiBriefcase": TfiBriefcase,
//    "TfiBrushAlt": TfiBrushAlt,
//    "TfiBrush": TfiBrush,
//    "TfiCalendar": TfiCalendar,
//    "TfiCamera": TfiCamera,
//    "TfiCar": TfiCar,
//    "TfiCheckBox": TfiCheckBox,
//    "TfiCheck": TfiCheck,
//    "TfiClip": TfiClip,
//    "TfiClipboard": TfiClipboard,
//    "TfiClose": TfiClose,
//    "TfiCloudDown": TfiCloudDown,
//    "TfiCloudUp": TfiCloudUp,
//    "TfiCloud": TfiCloud,
//    "TfiCommentAlt": TfiCommentAlt,
//    "TfiComment": TfiComment,
//    "TfiCommentsSmiley": TfiCommentsSmiley,
//    "TfiComments": TfiComments,
//    "TfiControlBackward": TfiControlBackward,
//    "TfiControlEject": TfiControlEject,
//    "TfiControlForward": TfiControlForward,
//    "TfiControlPause": TfiControlPause,
//    "TfiControlPlay": TfiControlPlay,
//    "TfiControlRecord": TfiControlRecord,
//    "TfiControlShuffle": TfiControlShuffle,
//    "TfiControlSkipBackward": TfiControlSkipBackward,
//    "TfiControlSkipForward": TfiControlSkipForward,
//    "TfiControlStop": TfiControlStop,
//    "TfiCreditCard": TfiCreditCard,
//    "TfiCrown": TfiCrown,
//    "TfiCss3": TfiCss3,
//    "TfiCup": TfiCup,
//    "TfiCut": TfiCut,
//    "TfiDashboard": TfiDashboard,
//    "TfiDesktop": TfiDesktop,
//    "TfiDirectionAlt": TfiDirectionAlt,
//    "TfiDirection": TfiDirection,
//    "TfiDownload": TfiDownload,
//    "TfiDribbble": TfiDribbble,
//    "TfiDropboxAlt": TfiDropboxAlt,
//    "TfiDropbox": TfiDropbox,
//    "TfiDrupal": TfiDrupal,
//    "TfiEmail": TfiEmail,
//    "TfiEnvelope": TfiEnvelope,
//    "TfiEraser": TfiEraser,
//    "TfiExchangeVertical": TfiExchangeVertical,
//    "TfiExport": TfiExport,
//    "TfiEye": TfiEye,
//    "TfiFaceSad": TfiFaceSad,
//    "TfiFaceSmile": TfiFaceSmile,
//    "TfiFacebook": TfiFacebook,
//    "TfiFile": TfiFile,
//    "TfiFiles": TfiFiles,
//    "TfiFilter": TfiFilter,
//    "TfiFlagAlt2": TfiFlagAlt2,
//    "TfiFlagAlt": TfiFlagAlt,
//    "TfiFlag": TfiFlag,
//    "TfiFlickrAlt": TfiFlickrAlt,
//    "TfiFlickr": TfiFlickr,
//    "TfiFolder": TfiFolder,
//    "TfiFullscreen": TfiFullscreen,
//    "TfiGallery": TfiGallery,
//    "TfiGame": TfiGame,
//    "TfiGift": TfiGift,
//    "TfiGithub": TfiGithub,
//    "TfiGoogle": TfiGoogle,
//    "TfiHandDrag": TfiHandDrag,
//    "TfiHandOpen": TfiHandOpen,
//    "TfiHandPointDown": TfiHandPointDown,
//    "TfiHandPointLeft": TfiHandPointLeft,
//    "TfiHandPointRight": TfiHandPointRight,
//    "TfiHandPointUp": TfiHandPointUp,
//    "TfiHandStop": TfiHandStop,
//    "TfiHarddrive": TfiHarddrive,
//    "TfiHarddrives": TfiHarddrives,
//    "TfiHeadphoneAlt": TfiHeadphoneAlt,
//    "TfiHeadphone": TfiHeadphone,
//    "TfiHeartBroken": TfiHeartBroken,
//    "TfiHeart": TfiHeart,
//    "TfiHelpAlt": TfiHelpAlt,
//    "TfiHelp": TfiHelp,
//    "TfiHome": TfiHome,
//    "TfiHtml5": TfiHtml5,
//    "TfiHummer": TfiHummer,
//    "TfiIdBadge": TfiIdBadge,
//    "TfiImage": TfiImage,
//    "TfiImport": TfiImport,
//    "TfiInfinite": TfiInfinite,
//    "TfiInfoAlt": TfiInfoAlt,
//    "TfiInfo": TfiInfo,
//    "TfiInkPen": TfiInkPen,
//    "TfiInstagram": TfiInstagram,
//    "TfiItalic": TfiItalic,
//    "TfiJoomla": TfiJoomla,
//    "TfiJsfiddle": TfiJsfiddle,
//    "TfiKey": TfiKey,
//    "TfiLayersAlt": TfiLayersAlt,
//    "TfiLayers": TfiLayers,
//    "TfiLayoutAccordionList": TfiLayoutAccordionList,
//    "TfiLayoutAccordionMerged": TfiLayoutAccordionMerged,
//    "TfiLayoutAccordionSeparated": TfiLayoutAccordionSeparated,
//    "TfiLayoutColumn2Alt": TfiLayoutColumn2Alt,
//    "TfiLayoutColumn2": TfiLayoutColumn2,
//    "TfiLayoutColumn3Alt": TfiLayoutColumn3Alt,
//    "TfiLayoutColumn3": TfiLayoutColumn3,
//    "TfiLayoutColumn4Alt": TfiLayoutColumn4Alt,
//    "TfiLayoutColumn4": TfiLayoutColumn4,
//    "TfiLayoutCtaBtnLeft": TfiLayoutCtaBtnLeft,
//    "TfiLayoutCtaBtnRight": TfiLayoutCtaBtnRight,
//    "TfiLayoutCtaCenter": TfiLayoutCtaCenter,
//    "TfiLayoutCtaLeft": TfiLayoutCtaLeft,
//    "TfiLayoutCtaRight": TfiLayoutCtaRight,
//    "TfiLayoutGrid2Alt": TfiLayoutGrid2Alt,
//    "TfiLayoutGrid2Thumb": TfiLayoutGrid2Thumb,
//    "TfiLayoutGrid2": TfiLayoutGrid2,
//    "TfiLayoutGrid3Alt": TfiLayoutGrid3Alt,
//    "TfiLayoutGrid3": TfiLayoutGrid3,
//    "TfiLayoutGrid4Alt": TfiLayoutGrid4Alt,
//    "TfiLayoutGrid4": TfiLayoutGrid4,
//    "TfiLayoutLineSolid": TfiLayoutLineSolid,
//    "TfiLayoutListLargeImage": TfiLayoutListLargeImage,
//    "TfiLayoutListPost": TfiLayoutListPost,
//    "TfiLayoutListThumbAlt": TfiLayoutListThumbAlt,
//    "TfiLayoutListThumb": TfiLayoutListThumb,
//    "TfiLayoutMediaCenterAlt": TfiLayoutMediaCenterAlt,
//    "TfiLayoutMediaCenter": TfiLayoutMediaCenter,
//    "TfiLayoutMediaLeftAlt": TfiLayoutMediaLeftAlt,
//    "TfiLayoutMediaLeft": TfiLayoutMediaLeft,
//    "TfiLayoutMediaOverlayAlt2": TfiLayoutMediaOverlayAlt2,
//    "TfiLayoutMediaOverlayAlt": TfiLayoutMediaOverlayAlt,
//    "TfiLayoutMediaOverlay": TfiLayoutMediaOverlay,
//    "TfiLayoutMediaRightAlt": TfiLayoutMediaRightAlt,
//    "TfiLayoutMediaRight": TfiLayoutMediaRight,
//    "TfiLayoutMenuFull": TfiLayoutMenuFull,
//    "TfiLayoutMenuSeparated": TfiLayoutMenuSeparated,
//    "TfiLayoutMenuV": TfiLayoutMenuV,
//    "TfiLayoutMenu": TfiLayoutMenu,
//    "TfiLayoutPlaceholder": TfiLayoutPlaceholder,
//    "TfiLayoutSidebar2": TfiLayoutSidebar2,
//    "TfiLayoutSidebarLeft": TfiLayoutSidebarLeft,
//    "TfiLayoutSidebarNone": TfiLayoutSidebarNone,
//    "TfiLayoutSidebarRight": TfiLayoutSidebarRight,
//    "TfiLayoutSliderAlt": TfiLayoutSliderAlt,
//    "TfiLayoutSlider": TfiLayoutSlider,
//    "TfiLayoutTabMin": TfiLayoutTabMin,
//    "TfiLayoutTabV": TfiLayoutTabV,
//    "TfiLayoutTabWindow": TfiLayoutTabWindow,
//    "TfiLayoutTab": TfiLayoutTab,
//    "TfiLayoutWidthDefaultAlt": TfiLayoutWidthDefaultAlt,
//    "TfiLayoutWidthDefault": TfiLayoutWidthDefault,
//    "TfiLayoutWidthFull": TfiLayoutWidthFull,
//    "TfiLayout": TfiLayout,
//    "TfiLightBulb": TfiLightBulb,
//    "TfiLineDashed": TfiLineDashed,
//    "TfiLineDotted": TfiLineDotted,
//    "TfiLineDouble": TfiLineDouble,
//    "TfiLink": TfiLink,
//    "TfiLinkedin": TfiLinkedin,
//    "TfiLinux": TfiLinux,
//    "TfiListOl": TfiListOl,
//    "TfiList": TfiList,
//    "TfiLocationArrow": TfiLocationArrow,
//    "TfiLocationPin": TfiLocationPin,
//    "TfiLock": TfiLock,
//    "TfiLoop": TfiLoop,
//    "TfiMagnet": TfiMagnet,
//    "TfiMapAlt": TfiMapAlt,
//    "TfiMap": TfiMap,
//    "TfiMarkerAlt": TfiMarkerAlt,
//    "TfiMarker": TfiMarker,
//    "TfiMedallAlt": TfiMedallAlt,
//    "TfiMedall": TfiMedall,
//    "TfiMenuAlt": TfiMenuAlt,
//    "TfiMenu": TfiMenu,
//    "TfiMicrophoneAlt": TfiMicrophoneAlt,
//    "TfiMicrophone": TfiMicrophone,
//    "TfiMicrosoftAlt": TfiMicrosoftAlt,
//    "TfiMicrosoft": TfiMicrosoft,
//    "TfiMinus": TfiMinus,
//    "TfiMobile": TfiMobile,
//    "TfiMoney": TfiMoney,
//    "TfiMoreAlt": TfiMoreAlt,
//    "TfiMore": TfiMore,
//    "TfiMouseAlt": TfiMouseAlt,
//    "TfiMouse": TfiMouse,
//    "TfiMusicAlt": TfiMusicAlt,
//    "TfiMusic": TfiMusic,
//    "TfiNa": TfiNa,
//    "TfiNewWindow": TfiNewWindow,
//    "TfiNotepad": TfiNotepad,
//    "TfiPackage": TfiPackage,
//    "TfiPaintBucket": TfiPaintBucket,
//    "TfiPaintRoller": TfiPaintRoller,
//    "TfiPalette": TfiPalette,
//    "TfiPanel": TfiPanel,
//    "TfiParagraph": TfiParagraph,
//    "TfiPencilAlt": TfiPencilAlt,
//    "TfiPencilAlt2": TfiPencilAlt2,
//    "TfiPencil": TfiPencil,
//    "TfiPieChart": TfiPieChart,
//    "TfiPinAlt": TfiPinAlt,
//    "TfiPin": TfiPin,
//    "TfiPin2": TfiPin2,
//    "TfiPinterestAlt": TfiPinterestAlt,
//    "TfiPinterest": TfiPinterest,
//    "TfiPlug": TfiPlug,
//    "TfiPlus": TfiPlus,
//    "TfiPowerOff": TfiPowerOff,
//    "TfiPrinter": TfiPrinter,
//    "TfiPulse": TfiPulse,
//    "TfiQuoteLeft": TfiQuoteLeft,
//    "TfiQuoteRight": TfiQuoteRight,
//    "TfiReceipt": TfiReceipt,
//    "TfiReddit": TfiReddit,
//    "TfiReload": TfiReload,
//    "TfiRocket": TfiRocket,
//    "TfiRssAlt": TfiRssAlt,
//    "TfiRss": TfiRss,
//    "TfiRulerAlt2": TfiRulerAlt2,
//    "TfiRulerAlt": TfiRulerAlt,
//    "TfiRulerPencil": TfiRulerPencil,
//    "TfiRuler": TfiRuler,
//    "TfiSaveAlt": TfiSaveAlt,
//    "TfiSave": TfiSave,
//    "TfiSearch": TfiSearch,
//    "TfiServer": TfiServer,
//    "TfiSettings": TfiSettings,
//    "TfiShareAlt": TfiShareAlt,
//    "TfiShare": TfiShare,
//    "TfiSharethisAlt": TfiSharethisAlt,
//    "TfiSharethis": TfiSharethis,
//    "TfiShield": TfiShield,
//    "TfiShiftLeftAlt": TfiShiftLeftAlt,
//    "TfiShiftLeft": TfiShiftLeft,
//    "TfiShiftRightAlt": TfiShiftRightAlt,
//    "TfiShiftRight": TfiShiftRight,
//    "TfiShine": TfiShine,
//    "TfiShoppingCartFull": TfiShoppingCartFull,
//    "TfiShoppingCart": TfiShoppingCart,
//    "TfiShortcode": TfiShortcode,
//    "TfiSignal": TfiSignal,
//    "TfiSkype": TfiSkype,
//    "TfiSlice": TfiSlice,
//    "TfiSmallcap": TfiSmallcap,
//    "TfiSoundcloud": TfiSoundcloud,
//    "TfiSplitH": TfiSplitH,
//    "TfiSplitVAlt": TfiSplitVAlt,
//    "TfiSplitV": TfiSplitV,
//    "TfiSpray": TfiSpray,
//    "TfiStackOverflow": TfiStackOverflow,
//    "TfiStamp": TfiStamp,
//    "TfiStar": TfiStar,
//    "TfiStatsDown": TfiStatsDown,
//    "TfiStatsUp": TfiStatsUp,
//    "TfiSupport": TfiSupport,
//    "TfiTablet": TfiTablet,
//    "TfiTag": TfiTag,
//    "TfiTarget": TfiTarget,
//    "TfiText": TfiText,
//    "TfiThemifyFaviconAlt": TfiThemifyFaviconAlt,
//    "TfiThemifyFavicon": TfiThemifyFavicon,
//    "TfiThemifyLogo": TfiThemifyLogo,
//    "TfiThought": TfiThought,
//    "TfiThumbDown": TfiThumbDown,
//    "TfiThumbUp": TfiThumbUp,
//    "TfiTicket": TfiTicket,
//    "TfiTime": TfiTime,
//    "TfiTimer": TfiTimer,
//    "TfiTrash": TfiTrash,
//    "TfiTrello": TfiTrello,
//    "TfiTruck": TfiTruck,
//    "TfiTumblrAlt": TfiTumblrAlt,
//    "TfiTumblr": TfiTumblr,
//    "TfiTwitterAlt": TfiTwitterAlt,
//    "TfiTwitter": TfiTwitter,
//    "TfiUnderline": TfiUnderline,
//    "TfiUnlink": TfiUnlink,
//    "TfiUnlock": TfiUnlock,
//    "TfiUpload": TfiUpload,
//    "TfiUppercase": TfiUppercase,
//    "TfiUser": TfiUser,
//    "TfiVector": TfiVector,
//    "TfiVideoCamera": TfiVideoCamera,
//    "TfiVideoClapper": TfiVideoClapper,
//    "TfiViewGrid": TfiViewGrid,
//    "TfiViewListAlt": TfiViewListAlt,
//    "TfiViewList": TfiViewList,
//    "TfiVimeoAlt": TfiVimeoAlt,
//    "TfiVimeo": TfiVimeo,
//    "TfiVolume": TfiVolume,
//    "TfiWallet": TfiWallet,
//    "TfiWand": TfiWand,
//    "TfiWheelchair": TfiWheelchair,
//    "TfiWidgetAlt": TfiWidgetAlt,
//    "TfiWidget": TfiWidget,
//    "TfiWidgetized": TfiWidgetized,
//    "TfiWindow": TfiWindow,
//    "TfiWordpress": TfiWordpress,
//    "TfiWorld": TfiWorld,
//    "TfiWrite": TfiWrite,
//    "TfiYahoo": TfiYahoo,
//    "TfiYoutube": TfiYoutube,
//    "TfiZip": TfiZip,
//    "TfiZoomIn": TfiZoomIn,
//    "TfiZoomOut": TfiZoomOut
//}