import { TiAdjustBrightness,
    TiAdjustContrast,
    TiAnchorOutline,
    TiAnchor,
    TiArchive,
    TiArrowBackOutline,
    TiArrowBack,
    TiArrowDownOutline,
    TiArrowDownThick,
    TiArrowDown,
    TiArrowForwardOutline,
    TiArrowForward,
    TiArrowLeftOutline,
    TiArrowLeftThick,
    TiArrowLeft,
    TiArrowLoopOutline,
    TiArrowLoop,
    TiArrowMaximiseOutline,
    TiArrowMaximise,
    TiArrowMinimiseOutline,
    TiArrowMinimise,
    TiArrowMoveOutline,
    TiArrowMove,
    TiArrowRepeatOutline,
    TiArrowRepeat,
    TiArrowRightOutline,
    TiArrowRightThick,
    TiArrowRight,
    TiArrowShuffle,
    TiArrowSortedDown,
    TiArrowSortedUp,
    TiArrowSyncOutline,
    TiArrowSync,
    TiArrowUnsorted,
    TiArrowUpOutline,
    TiArrowUpThick,
    TiArrowUp,
    TiAt,
    TiAttachmentOutline,
    TiAttachment,
    TiBackspaceOutline,
    TiBackspace,
    TiBatteryCharge,
    TiBatteryFull,
    TiBatteryHigh,
    TiBatteryLow,
    TiBatteryMid,
    TiBeaker,
    TiBeer,
    TiBell,
    TiBook,
    TiBookmark,
    TiBriefcase,
    TiBrush,
    TiBusinessCard,
    TiCalculator,
    TiCalendarOutline,
    TiCalendar,
    TiCameraOutline,
    TiCamera,
    TiCancelOutline,
    TiCancel,
    TiChartAreaOutline,
    TiChartArea,
    TiChartBarOutline,
    TiChartBar,
    TiChartLineOutline,
    TiChartLine,
    TiChartPieOutline,
    TiChartPie,
    TiChevronLeftOutline,
    TiChevronLeft,
    TiChevronRightOutline,
    TiChevronRight,
    TiClipboard,
    TiCloudStorageOutline,
    TiCloudStorage,
    TiCodeOutline,
    TiCode,
    TiCoffee,
    TiCogOutline,
    TiCog,
    TiCompass,
    TiContacts,
    TiCreditCard,
    TiCss3,
    TiDatabase,
    TiDeleteOutline,
    TiDelete,
    TiDeviceDesktop,
    TiDeviceLaptop,
    TiDevicePhone,
    TiDeviceTablet,
    TiDirections,
    TiDivideOutline,
    TiDivide,
    TiDocumentAdd,
    TiDocumentDelete,
    TiDocumentText,
    TiDocument,
    TiDownloadOutline,
    TiDownload,
    TiDropbox,
    TiEdit,
    TiEjectOutline,
    TiEject,
    TiEqualsOutline,
    TiEquals,
    TiExportOutline,
    TiExport,
    TiEyeOutline,
    TiEye,
    TiFeather,
    TiFilm,
    TiFilter,
    TiFlagOutline,
    TiFlag,
    TiFlashOutline,
    TiFlash,
    TiFlowChildren,
    TiFlowMerge,
    TiFlowParallel,
    TiFlowSwitch,
    TiFolderAdd,
    TiFolderDelete,
    TiFolderOpen,
    TiFolder,
    TiGift,
    TiGlobeOutline,
    TiGlobe,
    TiGroupOutline,
    TiGroup,
    TiHeadphones,
    TiHeartFullOutline,
    TiHeartHalfOutline,
    TiHeartOutline,
    TiHeart,
    TiHomeOutline,
    TiHome,
    TiHtml5,
    TiImageOutline,
    TiImage,
    TiInfinityOutline,
    TiInfinity,
    TiInfoLargeOutline,
    TiInfoLarge,
    TiInfoOutline,
    TiInfo,
    TiInputCheckedOutline,
    TiInputChecked,
    TiKeyOutline,
    TiKey,
    TiKeyboard,
    TiLeaf,
    TiLightbulb,
    TiLinkOutline,
    TiLink,
    TiLocationArrowOutline,
    TiLocationArrow,
    TiLocationOutline,
    TiLocation,
    TiLockClosedOutline,
    TiLockClosed,
    TiLockOpenOutline,
    TiLockOpen,
    TiMail,
    TiMap,
    TiMediaEjectOutline,
    TiMediaEject,
    TiMediaFastForwardOutline,
    TiMediaFastForward,
    TiMediaPauseOutline,
    TiMediaPause,
    TiMediaPlayOutline,
    TiMediaPlayReverseOutline,
    TiMediaPlayReverse,
    TiMediaPlay,
    TiMediaRecordOutline,
    TiMediaRecord,
    TiMediaRewindOutline,
    TiMediaRewind,
    TiMediaStopOutline,
    TiMediaStop,
    TiMessageTyping,
    TiMessage,
    TiMessages,
    TiMicrophoneOutline,
    TiMicrophone,
    TiMinusOutline,
    TiMinus,
    TiMortarBoard,
    TiNews,
    TiNotesOutline,
    TiNotes,
    TiPen,
    TiPencil,
    TiPhoneOutline,
    TiPhone,
    TiPiOutline,
    TiPi,
    TiPinOutline,
    TiPin,
    TiPipette,
    TiPlaneOutline,
    TiPlane,
    TiPlug,
    TiPlusOutline,
    TiPlus,
    TiPointOfInterestOutline,
    TiPointOfInterest,
    TiPowerOutline,
    TiPower,
    TiPrinter,
    TiPuzzleOutline,
    TiPuzzle,
    TiRadarOutline,
    TiRadar,
    TiRefreshOutline,
    TiRefresh,
    TiRssOutline,
    TiRss,
    TiScissorsOutline,
    TiScissors,
    TiShoppingBag,
    TiShoppingCart,
    TiSocialAtCircular,
    TiSocialDribbbleCircular,
    TiSocialDribbble,
    TiSocialFacebookCircular,
    TiSocialFacebook,
    TiSocialFlickrCircular,
    TiSocialFlickr,
    TiSocialGithubCircular,
    TiSocialGithub,
    TiSocialGooglePlusCircular,
    TiSocialGooglePlus,
    TiSocialInstagramCircular,
    TiSocialInstagram,
    TiSocialLastFmCircular,
    TiSocialLastFm,
    TiSocialLinkedinCircular,
    TiSocialLinkedin,
    TiSocialPinterestCircular,
    TiSocialPinterest,
    TiSocialSkypeOutline,
    TiSocialSkype,
    TiSocialTumblerCircular,
    TiSocialTumbler,
    TiSocialTwitterCircular,
    TiSocialTwitter,
    TiSocialVimeoCircular,
    TiSocialVimeo,
    TiSocialYoutubeCircular,
    TiSocialYoutube,
    TiSortAlphabeticallyOutline,
    TiSortAlphabetically,
    TiSortNumericallyOutline,
    TiSortNumerically,
    TiSpannerOutline,
    TiSpanner,
    TiSpiral,
    TiStarFullOutline,
    TiStarHalfOutline,
    TiStarHalf,
    TiStarOutline,
    TiStar,
    TiStarburstOutline,
    TiStarburst,
    TiStopwatch,
    TiSupport,
    TiTabsOutline,
    TiTag,
    TiTags,
    TiThLargeOutline,
    TiThLarge,
    TiThListOutline,
    TiThList,
    TiThMenuOutline,
    TiThMenu,
    TiThSmallOutline,
    TiThSmall,
    TiThermometer,
    TiThumbsDown,
    TiThumbsOk,
    TiThumbsUp,
    TiTickOutline,
    TiTick,
    TiTicket,
    TiTime,
    TiTimesOutline,
    TiTimes,
    TiTrash,
    TiTree,
    TiUploadOutline,
    TiUpload,
    TiUserAddOutline,
    TiUserAdd,
    TiUserDeleteOutline,
    TiUserDelete,
    TiUserOutline,
    TiUser,
    TiVendorAndroid,
    TiVendorApple,
    TiVendorMicrosoft,
    TiVideoOutline,
    TiVideo,
    TiVolumeDown,
    TiVolumeMute,
    TiVolumeUp,
    TiVolume,
    TiWarningOutline,
    TiWarning,
    TiWatch,
    TiWavesOutline,
    TiWaves,
    TiWeatherCloudy,
    TiWeatherDownpour,
    TiWeatherNight,
    TiWeatherPartlySunny,
    TiWeatherShower,
    TiWeatherSnow,
    TiWeatherStormy,
    TiWeatherSunny,
    TiWeatherWindyCloudy,
    TiWeatherWindy,
    TiWiFiOutline,
    TiWiFi,
    TiWine,
    TiWorldOutline,
    TiWorld,
    TiZoomInOutline,
    TiZoomIn,
    TiZoomOutOutline,
    TiZoomOut,
    TiZoomOutline,
    TiZoom
 } from "react-icons/ti";

export const TypiIcons = {
    "TiAdjustBrightness": TiAdjustBrightness,
    "TiAdjustContrast": TiAdjustContrast,
    "TiAnchorOutline": TiAnchorOutline,
    "TiAnchor": TiAnchor,
    "TiArchive": TiArchive,
    "TiArrowBackOutline": TiArrowBackOutline,
    "TiArrowBack": TiArrowBack,
    "TiArrowDownOutline": TiArrowDownOutline,
    "TiArrowDownThick": TiArrowDownThick,
    "TiArrowDown": TiArrowDown,
    "TiArrowForwardOutline": TiArrowForwardOutline,
    "TiArrowForward": TiArrowForward,
    "TiArrowLeftOutline": TiArrowLeftOutline,
    "TiArrowLeftThick": TiArrowLeftThick,
    "TiArrowLeft": TiArrowLeft,
    "TiArrowLoopOutline": TiArrowLoopOutline,
    "TiArrowLoop": TiArrowLoop,
    "TiArrowMaximiseOutline": TiArrowMaximiseOutline,
    "TiArrowMaximise": TiArrowMaximise,
    "TiArrowMinimiseOutline": TiArrowMinimiseOutline,
    "TiArrowMinimise": TiArrowMinimise,
    "TiArrowMoveOutline": TiArrowMoveOutline,
    "TiArrowMove": TiArrowMove,
    "TiArrowRepeatOutline": TiArrowRepeatOutline,
    "TiArrowRepeat": TiArrowRepeat,
    "TiArrowRightOutline": TiArrowRightOutline,
    "TiArrowRightThick": TiArrowRightThick,
    "TiArrowRight": TiArrowRight,
    "TiArrowShuffle": TiArrowShuffle,
    "TiArrowSortedDown": TiArrowSortedDown,
    "TiArrowSortedUp": TiArrowSortedUp,
    "TiArrowSyncOutline": TiArrowSyncOutline,
    "TiArrowSync": TiArrowSync,
    "TiArrowUnsorted": TiArrowUnsorted,
    "TiArrowUpOutline": TiArrowUpOutline,
    "TiArrowUpThick": TiArrowUpThick,
    "TiArrowUp": TiArrowUp,
    "TiAt": TiAt,
    "TiAttachmentOutline": TiAttachmentOutline,
    "TiAttachment": TiAttachment,
    "TiBackspaceOutline": TiBackspaceOutline,
    "TiBackspace": TiBackspace,
    "TiBatteryCharge": TiBatteryCharge,
    "TiBatteryFull": TiBatteryFull,
    "TiBatteryHigh": TiBatteryHigh,
    "TiBatteryLow": TiBatteryLow,
    "TiBatteryMid": TiBatteryMid,
    "TiBeaker": TiBeaker,
    "TiBeer": TiBeer,
    "TiBell": TiBell,
    "TiBook": TiBook,
    "TiBookmark": TiBookmark,
    "TiBriefcase": TiBriefcase,
    "TiBrush": TiBrush,
    "TiBusinessCard": TiBusinessCard,
    "TiCalculator": TiCalculator,
    "TiCalendarOutline": TiCalendarOutline,
    "TiCalendar": TiCalendar,
    "TiCameraOutline": TiCameraOutline,
    "TiCamera": TiCamera,
    "TiCancelOutline": TiCancelOutline,
    "TiCancel": TiCancel,
    "TiChartAreaOutline": TiChartAreaOutline,
    "TiChartArea": TiChartArea,
    "TiChartBarOutline": TiChartBarOutline,
    "TiChartBar": TiChartBar,
    "TiChartLineOutline": TiChartLineOutline,
    "TiChartLine": TiChartLine,
    "TiChartPieOutline": TiChartPieOutline,
    "TiChartPie": TiChartPie,
    "TiChevronLeftOutline": TiChevronLeftOutline,
    "TiChevronLeft": TiChevronLeft,
    "TiChevronRightOutline": TiChevronRightOutline,
    "TiChevronRight": TiChevronRight,
    "TiClipboard": TiClipboard,
    "TiCloudStorageOutline": TiCloudStorageOutline,
    "TiCloudStorage": TiCloudStorage,
    "TiCodeOutline": TiCodeOutline,
    "TiCode": TiCode,
    "TiCoffee": TiCoffee,
    "TiCogOutline": TiCogOutline,
    "TiCog": TiCog,
    "TiCompass": TiCompass,
    "TiContacts": TiContacts,
    "TiCreditCard": TiCreditCard,
    "TiCss3": TiCss3,
    "TiDatabase": TiDatabase,
    "TiDeleteOutline": TiDeleteOutline,
    "TiDelete": TiDelete,
    "TiDeviceDesktop": TiDeviceDesktop,
    "TiDeviceLaptop": TiDeviceLaptop,
    "TiDevicePhone": TiDevicePhone,
    "TiDeviceTablet": TiDeviceTablet,
    "TiDirections": TiDirections,
    "TiDivideOutline": TiDivideOutline,
    "TiDivide": TiDivide,
    "TiDocumentAdd": TiDocumentAdd,
    "TiDocumentDelete": TiDocumentDelete,
    "TiDocumentText": TiDocumentText,
    "TiDocument": TiDocument,
    "TiDownloadOutline": TiDownloadOutline,
    "TiDownload": TiDownload,
    "TiDropbox": TiDropbox,
    "TiEdit": TiEdit,
    "TiEjectOutline": TiEjectOutline,
    "TiEject": TiEject,
    "TiEqualsOutline": TiEqualsOutline,
    "TiEquals": TiEquals,
    "TiExportOutline": TiExportOutline,
    "TiExport": TiExport,
    "TiEyeOutline": TiEyeOutline,
    "TiEye": TiEye,
    "TiFeather": TiFeather,
    "TiFilm": TiFilm,
    "TiFilter": TiFilter,
    "TiFlagOutline": TiFlagOutline,
    "TiFlag": TiFlag,
    "TiFlashOutline": TiFlashOutline,
    "TiFlash": TiFlash,
    "TiFlowChildren": TiFlowChildren,
    "TiFlowMerge": TiFlowMerge,
    "TiFlowParallel": TiFlowParallel,
    "TiFlowSwitch": TiFlowSwitch,
    "TiFolderAdd": TiFolderAdd,
    "TiFolderDelete": TiFolderDelete,
    "TiFolderOpen": TiFolderOpen,
    "TiFolder": TiFolder,
    "TiGift": TiGift,
    "TiGlobeOutline": TiGlobeOutline,
    "TiGlobe": TiGlobe,
    "TiGroupOutline": TiGroupOutline,
    "TiGroup": TiGroup,
    "TiHeadphones": TiHeadphones,
    "TiHeartFullOutline": TiHeartFullOutline,
    "TiHeartHalfOutline": TiHeartHalfOutline,
    "TiHeartOutline": TiHeartOutline,
    "TiHeart": TiHeart,
    "TiHomeOutline": TiHomeOutline,
    "TiHome": TiHome,
    "TiHtml5": TiHtml5,
    "TiImageOutline": TiImageOutline,
    "TiImage": TiImage,
    "TiInfinityOutline": TiInfinityOutline,
    "TiInfinity": TiInfinity,
    "TiInfoLargeOutline": TiInfoLargeOutline,
    "TiInfoLarge": TiInfoLarge,
    "TiInfoOutline": TiInfoOutline,
    "TiInfo": TiInfo,
    "TiInputCheckedOutline": TiInputCheckedOutline,
    "TiInputChecked": TiInputChecked,
    "TiKeyOutline": TiKeyOutline,
    "TiKey": TiKey,
    "TiKeyboard": TiKeyboard,
    "TiLeaf": TiLeaf,
    "TiLightbulb": TiLightbulb,
    "TiLinkOutline": TiLinkOutline,
    "TiLink": TiLink,
    "TiLocationArrowOutline": TiLocationArrowOutline,
    "TiLocationArrow": TiLocationArrow,
    "TiLocationOutline": TiLocationOutline,
    "TiLocation": TiLocation,
    "TiLockClosedOutline": TiLockClosedOutline,
    "TiLockClosed": TiLockClosed,
    "TiLockOpenOutline": TiLockOpenOutline,
    "TiLockOpen": TiLockOpen,
    "TiMail": TiMail,
    "TiMap": TiMap,
    "TiMediaEjectOutline": TiMediaEjectOutline,
    "TiMediaEject": TiMediaEject,
    "TiMediaFastForwardOutline": TiMediaFastForwardOutline,
    "TiMediaFastForward": TiMediaFastForward,
    "TiMediaPauseOutline": TiMediaPauseOutline,
    "TiMediaPause": TiMediaPause,
    "TiMediaPlayOutline": TiMediaPlayOutline,
    "TiMediaPlayReverseOutline": TiMediaPlayReverseOutline,
    "TiMediaPlayReverse": TiMediaPlayReverse,
    "TiMediaPlay": TiMediaPlay,
    "TiMediaRecordOutline": TiMediaRecordOutline,
    "TiMediaRecord": TiMediaRecord,
    "TiMediaRewindOutline": TiMediaRewindOutline,
    "TiMediaRewind": TiMediaRewind,
    "TiMediaStopOutline": TiMediaStopOutline,
    "TiMediaStop": TiMediaStop,
    "TiMessageTyping": TiMessageTyping,
    "TiMessage": TiMessage,
    "TiMessages": TiMessages,
    "TiMicrophoneOutline": TiMicrophoneOutline,
    "TiMicrophone": TiMicrophone,
    "TiMinusOutline": TiMinusOutline,
    "TiMinus": TiMinus,
    "TiMortarBoard": TiMortarBoard,
    "TiNews": TiNews,
    "TiNotesOutline": TiNotesOutline,
    "TiNotes": TiNotes,
    "TiPen": TiPen,
    "TiPencil": TiPencil,
    "TiPhoneOutline": TiPhoneOutline,
    "TiPhone": TiPhone,
    "TiPiOutline": TiPiOutline,
    "TiPi": TiPi,
    "TiPinOutline": TiPinOutline,
    "TiPin": TiPin,
    "TiPipette": TiPipette,
    "TiPlaneOutline": TiPlaneOutline,
    "TiPlane": TiPlane,
    "TiPlug": TiPlug,
    "TiPlusOutline": TiPlusOutline,
    "TiPlus": TiPlus,
    "TiPointOfInterestOutline": TiPointOfInterestOutline,
    "TiPointOfInterest": TiPointOfInterest,
    "TiPowerOutline": TiPowerOutline,
    "TiPower": TiPower,
    "TiPrinter": TiPrinter,
    "TiPuzzleOutline": TiPuzzleOutline,
    "TiPuzzle": TiPuzzle,
    "TiRadarOutline": TiRadarOutline,
    "TiRadar": TiRadar,
    "TiRefreshOutline": TiRefreshOutline,
    "TiRefresh": TiRefresh,
    "TiRssOutline": TiRssOutline,
    "TiRss": TiRss,
    "TiScissorsOutline": TiScissorsOutline,
    "TiScissors": TiScissors,
    "TiShoppingBag": TiShoppingBag,
    "TiShoppingCart": TiShoppingCart,
    "TiSocialAtCircular": TiSocialAtCircular,
    "TiSocialDribbbleCircular": TiSocialDribbbleCircular,
    "TiSocialDribbble": TiSocialDribbble,
    "TiSocialFacebookCircular": TiSocialFacebookCircular,
    "TiSocialFacebook": TiSocialFacebook,
    "TiSocialFlickrCircular": TiSocialFlickrCircular,
    "TiSocialFlickr": TiSocialFlickr,
    "TiSocialGithubCircular": TiSocialGithubCircular,
    "TiSocialGithub": TiSocialGithub,
    "TiSocialGooglePlusCircular": TiSocialGooglePlusCircular,
    "TiSocialGooglePlus": TiSocialGooglePlus,
    "TiSocialInstagramCircular": TiSocialInstagramCircular,
    "TiSocialInstagram": TiSocialInstagram,
    "TiSocialLastFmCircular": TiSocialLastFmCircular,
    "TiSocialLastFm": TiSocialLastFm,
    "TiSocialLinkedinCircular": TiSocialLinkedinCircular,
    "TiSocialLinkedin": TiSocialLinkedin,
    "TiSocialPinterestCircular": TiSocialPinterestCircular,
    "TiSocialPinterest": TiSocialPinterest,
    "TiSocialSkypeOutline": TiSocialSkypeOutline,
    "TiSocialSkype": TiSocialSkype,
    "TiSocialTumblerCircular": TiSocialTumblerCircular,
    "TiSocialTumbler": TiSocialTumbler,
    "TiSocialTwitterCircular": TiSocialTwitterCircular,
    "TiSocialTwitter": TiSocialTwitter,
    "TiSocialVimeoCircular": TiSocialVimeoCircular,
    "TiSocialVimeo": TiSocialVimeo,
    "TiSocialYoutubeCircular": TiSocialYoutubeCircular,
    "TiSocialYoutube": TiSocialYoutube,
    "TiSortAlphabeticallyOutline": TiSortAlphabeticallyOutline,
    "TiSortAlphabetically": TiSortAlphabetically,
    "TiSortNumericallyOutline": TiSortNumericallyOutline,
    "TiSortNumerically": TiSortNumerically,
    "TiSpannerOutline": TiSpannerOutline,
    "TiSpanner": TiSpanner,
    "TiSpiral": TiSpiral,
    "TiStarFullOutline": TiStarFullOutline,
    "TiStarHalfOutline": TiStarHalfOutline,
    "TiStarHalf": TiStarHalf,
    "TiStarOutline": TiStarOutline,
    "TiStar": TiStar,
    "TiStarburstOutline": TiStarburstOutline,
    "TiStarburst": TiStarburst,
    "TiStopwatch": TiStopwatch,
    "TiSupport": TiSupport,
    "TiTabsOutline": TiTabsOutline,
    "TiTag": TiTag,
    "TiTags": TiTags,
    "TiThLargeOutline": TiThLargeOutline,
    "TiThLarge": TiThLarge,
    "TiThListOutline": TiThListOutline,
    "TiThList": TiThList,
    "TiThMenuOutline": TiThMenuOutline,
    "TiThMenu": TiThMenu,
    "TiThSmallOutline": TiThSmallOutline,
    "TiThSmall": TiThSmall,
    "TiThermometer": TiThermometer,
    "TiThumbsDown": TiThumbsDown,
    "TiThumbsOk": TiThumbsOk,
    "TiThumbsUp": TiThumbsUp,
    "TiTickOutline": TiTickOutline,
    "TiTick": TiTick,
    "TiTicket": TiTicket,
    "TiTime": TiTime,
    "TiTimesOutline": TiTimesOutline,
    "TiTimes": TiTimes,
    "TiTrash": TiTrash,
    "TiTree": TiTree,
    "TiUploadOutline": TiUploadOutline,
    "TiUpload": TiUpload,
    "TiUserAddOutline": TiUserAddOutline,
    "TiUserAdd": TiUserAdd,
    "TiUserDeleteOutline": TiUserDeleteOutline,
    "TiUserDelete": TiUserDelete,
    "TiUserOutline": TiUserOutline,
    "TiUser": TiUser,
    "TiVendorAndroid": TiVendorAndroid,
    "TiVendorApple": TiVendorApple,
    "TiVendorMicrosoft": TiVendorMicrosoft,
    "TiVideoOutline": TiVideoOutline,
    "TiVideo": TiVideo,
    "TiVolumeDown": TiVolumeDown,
    "TiVolumeMute": TiVolumeMute,
    "TiVolumeUp": TiVolumeUp,
    "TiVolume": TiVolume,
    "TiWarningOutline": TiWarningOutline,
    "TiWarning": TiWarning,
    "TiWatch": TiWatch,
    "TiWavesOutline": TiWavesOutline,
    "TiWaves": TiWaves,
    "TiWeatherCloudy": TiWeatherCloudy,
    "TiWeatherDownpour": TiWeatherDownpour,
    "TiWeatherNight": TiWeatherNight,
    "TiWeatherPartlySunny": TiWeatherPartlySunny,
    "TiWeatherShower": TiWeatherShower,
    "TiWeatherSnow": TiWeatherSnow,
    "TiWeatherStormy": TiWeatherStormy,
    "TiWeatherSunny": TiWeatherSunny,
    "TiWeatherWindyCloudy": TiWeatherWindyCloudy,
    "TiWeatherWindy": TiWeatherWindy,
    "TiWiFiOutline": TiWiFiOutline,
    "TiWiFi": TiWiFi,
    "TiWine": TiWine,
    "TiWorldOutline": TiWorldOutline,
    "TiWorld": TiWorld,
    "TiZoomInOutline": TiZoomInOutline,
    "TiZoomIn": TiZoomIn,
    "TiZoomOutOutline": TiZoomOutOutline,
    "TiZoomOut": TiZoomOut,
    "TiZoomOutline": TiZoomOutline,
    "TiZoom": TiZoom
}