import { 
    VscAccount,
VscActivateBreakpoints,
VscAdd,
VscArchive,
VscArrowBoth,
VscArrowDown,
VscArrowLeft,
VscArrowRight,
VscArrowSmallDown,
VscArrowSmallLeft,
VscArrowSmallRight,
VscArrowSmallUp,
VscArrowSwap,
VscArrowUp,
VscAzure,
VscBeakerStop,
VscBeaker,
VscBellDot,
VscBell,
VscBold,
VscBook,
VscBookmark,
VscBracketDot,
VscBracketError,
VscBriefcase,
VscBroadcast,
VscBrowser,
VscBug,
VscCalendar,
VscCallIncoming,
VscCallOutgoing,
VscCaseSensitive,
VscCheckAll,
VscCheck,
VscChecklist,
VscChevronDown,
VscChevronLeft,
VscChevronRight,
VscChevronUp,
VscChromeClose,
VscChromeMaximize,
VscChromeMinimize,
VscChromeRestore,
VscCircleFilled,
VscCircleLargeFilled,
VscCircleLargeOutline,
VscCircleOutline,
VscCircleSlash,
VscCircuitBoard,
VscClearAll,
VscClippy,
VscCloseAll,
VscClose,
VscCloudDownload,
VscCloudUpload,
VscCloud,
VscCode,
VscCollapseAll,
VscColorMode,
VscCombine,
VscCommentDiscussion,
VscComment,
VscCompassActive,
VscCompassDot,
VscCompass,
VscCopy,
VscCreditCard,
VscDash,
VscDashboard,
VscDatabase,
VscDebugAll,
VscDebugAltSmall,
VscDebugAlt,
VscDebugBreakpointConditionalUnverified,
VscDebugBreakpointConditional,
VscDebugBreakpointDataUnverified,
VscDebugBreakpointData,
VscDebugBreakpointFunctionUnverified,
VscDebugBreakpointFunction,
VscDebugBreakpointLogUnverified,
VscDebugBreakpointLog,
VscDebugBreakpointUnsupported,
VscDebugConsole,
VscDebugContinueSmall,
VscDebugContinue,
VscDebugCoverage,
VscDebugDisconnect,
VscDebugLineByLine,
VscDebugPause,
VscDebugRerun,
VscDebugRestartFrame,
VscDebugRestart,
VscDebugReverseContinue,
VscDebugStackframeActive,
VscDebugStackframeDot,
VscDebugStackframe,
VscDebugStart,
VscDebugStepBack,
VscDebugStepInto,
VscDebugStepOut,
VscDebugStepOver,
VscDebugStop,
VscDebug,
VscDesktopDownload,
VscDeviceCameraVideo,
VscDeviceCamera,
VscDeviceMobile,
VscDiffAdded,
VscDiffIgnored,
VscDiffModified,
VscDiffRemoved,
VscDiffRenamed,
VscDiff,
VscDiscard,
VscEdit,
VscEditorLayout,
VscEllipsis,
VscEmptyWindow,
VscError,
VscExclude,
VscExpandAll,
VscExport,
VscExtensions,
VscEyeClosed,
VscEye,
VscFeedback,
VscFileBinary,
VscFileCode,
VscFileMedia,
VscFilePdf,
VscFileSubmodule,
VscFileSymlinkDirectory,
VscFileSymlinkFile,
VscFileZip,
VscFile,
VscFiles,
VscFilterFilled,
VscFilter,
VscFlame,
VscFoldDown,
VscFoldUp,
VscFold,
VscFolderActive,
VscFolderLibrary,
VscFolderOpened,
VscFolder,
VscGear,
VscGift,
VscGistSecret,
VscGist,
VscGitCommit,
VscGitCompare,
VscGitMerge,
VscGitPullRequestClosed,
VscGitPullRequestCreate,
VscGitPullRequestDraft,
VscGitPullRequest,
VscGithubAction,
VscGithubAlt,
VscGithubInverted,
VscGithub,
VscGlobe,
VscGoToFile,
VscGrabber,
VscGraphLeft,
VscGraphLine,
VscGraphScatter,
VscGraph,
VscGripper,
VscGroupByRefType,
VscHeart,
VscHistory,
VscHome,
VscHorizontalRule,
VscHubot,
VscInbox,
VscInfo,
VscInspect,
VscIssueDraft,
VscIssueReopened,
VscIssues,
VscItalic,
VscJersey,
VscJson,
VscKebabVertical,
VscKey,
VscLaw,
VscLayersActive,
VscLayersDot,
VscLayers,
VscLibrary,
VscLightbulbAutofix,
VscLightbulb,
VscLinkExternal,
VscLink,
VscListFilter,
VscListFlat,
VscListOrdered,
VscListSelection,
VscListTree,
VscListUnordered,
VscLiveShare,
VscLoading,
VscLocation,
VscLock,
VscMagnet,
VscMailRead,
VscMail,
VscMarkdown,
VscMegaphone,
VscMention,
VscMenu,
VscMerge,
VscMilestone,
VscMirror,
VscMortarBoard,
VscMove,
VscMultipleWindows,
VscMute,
VscNewFile,
VscNewFolder,
VscNoNewline,
VscNote,
VscNotebookTemplate,
VscNotebook,
VscOctoface,
VscOpenPreview,
VscOrganization,
VscOutput,
VscPackage,
VscPaintcan,
VscPassFilled,
VscPass,
VscPersonAdd,
VscPerson,
VscPieChart,
VscPin,
VscPinnedDirty,
VscPinned,
VscPlayCircle,
VscPlay,
VscPlug,
VscPreserveCase,
VscPreview,
VscPrimitiveSquare,
VscProject,
VscPulse,
VscQuestion,
VscQuote,
VscRadioTower,
VscReactions,
VscRecordKeys,
VscRecord,
VscRedo,
VscReferences,
VscRefresh,
VscRegex,
VscRemoteExplorer,
VscRemote,
VscRemove,
VscReplaceAll,
VscReplace,
VscReply,
VscRepoClone,
VscRepoForcePush,
VscRepoForked,
VscRepoPull,
VscRepoPush,
VscRepo,
VscReport,
VscRequestChanges,
VscRocket,
VscRootFolderOpened,
VscRootFolder,
VscRss,
VscRuby,
VscRunAbove,
VscRunAll,
VscRunBelow,
VscRunErrors,
VscSaveAll,
VscSaveAs,
VscSave,
VscScreenFull,
VscScreenNormal,
VscSearchStop,
VscSearch,
VscServerEnvironment,
VscServerProcess,
VscServer,
VscSettingsGear,
VscSettings,
VscShield,
VscSignIn,
VscSignOut,
VscSmiley,
VscSortPrecedence,
VscSourceControl,
VscSplitHorizontal,
VscSplitVertical,
VscSquirrel,
VscStarEmpty,
VscStarFull,
VscStarHalf,
VscStopCircle,
VscSymbolArray,
VscSymbolBoolean,
VscSymbolClass,
VscSymbolColor,
VscSymbolConstant,
VscSymbolEnumMember,
VscSymbolEnum,
VscSymbolEvent,
VscSymbolField,
VscSymbolFile,
VscSymbolInterface,
VscSymbolKey,
VscSymbolKeyword,
VscSymbolMethod,
VscSymbolMisc,
VscSymbolNamespace,
VscSymbolNumeric,
VscSymbolOperator,
VscSymbolParameter,
VscSymbolProperty,
VscSymbolRuler,
VscSymbolSnippet,
VscSymbolString,
VscSymbolStructure,
VscSymbolVariable,
VscSyncIgnored,
VscSync,
VscTable,
VscTag,
VscTasklist,
VscTelescope,
VscTerminalBash,
VscTerminalCmd,
VscTerminalDebian,
VscTerminalLinux,
VscTerminalPowershell,
VscTerminalTmux,
VscTerminalUbuntu,
VscTerminal,
VscTextSize,
VscThreeBars,
VscThumbsdown,
VscThumbsup,
VscTools,
VscTrash,
VscTriangleDown,
VscTriangleLeft,
VscTriangleRight,
VscTriangleUp,
VscTwitter,
VscTypeHierarchySub,
VscTypeHierarchySuper,
VscTypeHierarchy,
VscUnfold,
VscUngroupByRefType,
VscUnlock,
VscUnmute,
VscUnverified,
VscVariableGroup,
VscVerified,
VscVersions,
VscVmActive,
VscVmConnect,
VscVmOutline,
VscVmRunning,
VscVm,
VscWand,
VscWarning,
VscWatch,
VscWhitespace,
VscWholeWord,
VscWindow,
VscWordWrap,
VscWorkspaceTrusted,
VscWorkspaceUnknown,
VscWorkspaceUntrusted,
VscZoomIn,
VscZoomOut
 } from "react-icons/vsc";

export const VsCodeIcons = {
    "VscAccount": VscAccount,
    "VscActivateBreakpoints": VscActivateBreakpoints,
    "VscAdd": VscAdd,
    "VscArchive": VscArchive,
    "VscArrowBoth": VscArrowBoth,
    "VscArrowDown": VscArrowDown,
    "VscArrowLeft": VscArrowLeft,
    "VscArrowRight": VscArrowRight,
    "VscArrowSmallDown": VscArrowSmallDown,
    "VscArrowSmallLeft": VscArrowSmallLeft,
    "VscArrowSmallRight": VscArrowSmallRight,
    "VscArrowSmallUp": VscArrowSmallUp,
    "VscArrowSwap": VscArrowSwap,
    "VscArrowUp": VscArrowUp,
    "VscAzure": VscAzure,
    "VscBeakerStop": VscBeakerStop,
    "VscBeaker": VscBeaker,
    "VscBellDot": VscBellDot,
    "VscBell": VscBell,
    "VscBold": VscBold,
    "VscBook": VscBook,
    "VscBookmark": VscBookmark,
    "VscBracketDot": VscBracketDot,
    "VscBracketError": VscBracketError,
    "VscBriefcase": VscBriefcase,
    "VscBroadcast": VscBroadcast,
    "VscBrowser": VscBrowser,
    "VscBug": VscBug,
    "VscCalendar": VscCalendar,
    "VscCallIncoming": VscCallIncoming,
    "VscCallOutgoing": VscCallOutgoing,
    "VscCaseSensitive": VscCaseSensitive,
    "VscCheckAll": VscCheckAll,
    "VscCheck": VscCheck,
    "VscChecklist": VscChecklist,
    "VscChevronDown": VscChevronDown,
    "VscChevronLeft": VscChevronLeft,
    "VscChevronRight": VscChevronRight,
    "VscChevronUp": VscChevronUp,
    "VscChromeClose": VscChromeClose,
    "VscChromeMaximize": VscChromeMaximize,
    "VscChromeMinimize": VscChromeMinimize,
    "VscChromeRestore": VscChromeRestore,
    "VscCircleFilled": VscCircleFilled,
    "VscCircleLargeFilled": VscCircleLargeFilled,
    "VscCircleLargeOutline": VscCircleLargeOutline,
    "VscCircleOutline": VscCircleOutline,
    "VscCircleSlash": VscCircleSlash,
    "VscCircuitBoard": VscCircuitBoard,
    "VscClearAll": VscClearAll,
    "VscClippy": VscClippy,
    "VscCloseAll": VscCloseAll,
    "VscClose": VscClose,
    "VscCloudDownload": VscCloudDownload,
    "VscCloudUpload": VscCloudUpload,
    "VscCloud": VscCloud,
    "VscCode": VscCode,
    "VscCollapseAll": VscCollapseAll,
    "VscColorMode": VscColorMode,
    "VscCombine": VscCombine,
    "VscCommentDiscussion": VscCommentDiscussion,
    "VscComment": VscComment,
    "VscCompassActive": VscCompassActive,
    "VscCompassDot": VscCompassDot,
    "VscCompass": VscCompass,
    "VscCopy": VscCopy,
    "VscCreditCard": VscCreditCard,
    "VscDash": VscDash,
    "VscDashboard": VscDashboard,
    "VscDatabase": VscDatabase,
    "VscDebugAll": VscDebugAll,
    "VscDebugAltSmall": VscDebugAltSmall,
    "VscDebugAlt": VscDebugAlt,
    "VscDebugBreakpointConditionalUnverified": VscDebugBreakpointConditionalUnverified,
    "VscDebugBreakpointConditional": VscDebugBreakpointConditional,
    "VscDebugBreakpointDataUnverified": VscDebugBreakpointDataUnverified,
    "VscDebugBreakpointData": VscDebugBreakpointData,
    "VscDebugBreakpointFunctionUnverified": VscDebugBreakpointFunctionUnverified,
    "VscDebugBreakpointFunction": VscDebugBreakpointFunction,
    "VscDebugBreakpointLogUnverified": VscDebugBreakpointLogUnverified,
    "VscDebugBreakpointLog": VscDebugBreakpointLog,
    "VscDebugBreakpointUnsupported": VscDebugBreakpointUnsupported,
    "VscDebugConsole": VscDebugConsole,
    "VscDebugContinueSmall": VscDebugContinueSmall,
    "VscDebugContinue": VscDebugContinue,
    "VscDebugCoverage": VscDebugCoverage,
    "VscDebugDisconnect": VscDebugDisconnect,
    "VscDebugLineByLine": VscDebugLineByLine,
    "VscDebugPause": VscDebugPause,
    "VscDebugRerun": VscDebugRerun,
    "VscDebugRestartFrame": VscDebugRestartFrame,
    "VscDebugRestart": VscDebugRestart,
    "VscDebugReverseContinue": VscDebugReverseContinue,
    "VscDebugStackframeActive": VscDebugStackframeActive,
    "VscDebugStackframeDot": VscDebugStackframeDot,
    "VscDebugStackframe": VscDebugStackframe,
    "VscDebugStart": VscDebugStart,
    "VscDebugStepBack": VscDebugStepBack,
    "VscDebugStepInto": VscDebugStepInto,
    "VscDebugStepOut": VscDebugStepOut,
    "VscDebugStepOver": VscDebugStepOver,
    "VscDebugStop": VscDebugStop,
    "VscDebug": VscDebug,
    "VscDesktopDownload": VscDesktopDownload,
    "VscDeviceCameraVideo": VscDeviceCameraVideo,
    "VscDeviceCamera": VscDeviceCamera,
    "VscDeviceMobile": VscDeviceMobile,
    "VscDiffAdded": VscDiffAdded,
    "VscDiffIgnored": VscDiffIgnored,
    "VscDiffModified": VscDiffModified,
    "VscDiffRemoved": VscDiffRemoved,
    "VscDiffRenamed": VscDiffRenamed,
    "VscDiff": VscDiff,
    "VscDiscard": VscDiscard,
    "VscEdit": VscEdit,
    "VscEditorLayout": VscEditorLayout,
    "VscEllipsis": VscEllipsis,
    "VscEmptyWindow": VscEmptyWindow,
    "VscError": VscError,
    "VscExclude": VscExclude,
    "VscExpandAll": VscExpandAll,
    "VscExport": VscExport,
    "VscExtensions": VscExtensions,
    "VscEyeClosed": VscEyeClosed,
    "VscEye": VscEye,
    "VscFeedback": VscFeedback,
    "VscFileBinary": VscFileBinary,
    "VscFileCode": VscFileCode,
    "VscFileMedia": VscFileMedia,
    "VscFilePdf": VscFilePdf,
    "VscFileSubmodule": VscFileSubmodule,
    "VscFileSymlinkDirectory": VscFileSymlinkDirectory,
    "VscFileSymlinkFile": VscFileSymlinkFile,
    "VscFileZip": VscFileZip,
    "VscFile": VscFile,
    "VscFiles": VscFiles,
    "VscFilterFilled": VscFilterFilled,
    "VscFilter": VscFilter,
    "VscFlame": VscFlame,
    "VscFoldDown": VscFoldDown,
    "VscFoldUp": VscFoldUp,
    "VscFold": VscFold,
    "VscFolderActive": VscFolderActive,
    "VscFolderLibrary": VscFolderLibrary,
    "VscFolderOpened": VscFolderOpened,
    "VscFolder": VscFolder,
    "VscGear": VscGear,
    "VscGift": VscGift,
    "VscGistSecret": VscGistSecret,
    "VscGist": VscGist,
    "VscGitCommit": VscGitCommit,
    "VscGitCompare": VscGitCompare,
    "VscGitMerge": VscGitMerge,
    "VscGitPullRequestClosed": VscGitPullRequestClosed,
    "VscGitPullRequestCreate": VscGitPullRequestCreate,
    "VscGitPullRequestDraft": VscGitPullRequestDraft,
    "VscGitPullRequest": VscGitPullRequest,
    "VscGithubAction": VscGithubAction,
    "VscGithubAlt": VscGithubAlt,
    "VscGithubInverted": VscGithubInverted,
    "VscGithub": VscGithub,
    "VscGlobe": VscGlobe,
    "VscGoToFile": VscGoToFile,
    "VscGrabber": VscGrabber,
    "VscGraphLeft": VscGraphLeft,
    "VscGraphLine": VscGraphLine,
    "VscGraphScatter": VscGraphScatter,
    "VscGraph": VscGraph,
    "VscGripper": VscGripper,
    "VscGroupByRefType": VscGroupByRefType,
    "VscHeart": VscHeart,
    "VscHistory": VscHistory,
    "VscHome": VscHome,
    "VscHorizontalRule": VscHorizontalRule,
    "VscHubot": VscHubot,
    "VscInbox": VscInbox,
    "VscInfo": VscInfo,
    "VscInspect": VscInspect,
    "VscIssueDraft": VscIssueDraft,
    "VscIssueReopened": VscIssueReopened,
    "VscIssues": VscIssues,
    "VscItalic": VscItalic,
    "VscJersey": VscJersey,
    "VscJson": VscJson,
    "VscKebabVertical": VscKebabVertical,
    "VscKey": VscKey,
    "VscLaw": VscLaw,
    "VscLayersActive": VscLayersActive,
    "VscLayersDot": VscLayersDot,
    "VscLayers": VscLayers,
    "VscLibrary": VscLibrary,
    "VscLightbulbAutofix": VscLightbulbAutofix,
    "VscLightbulb": VscLightbulb,
    "VscLinkExternal": VscLinkExternal,
    "VscLink": VscLink,
    "VscListFilter": VscListFilter,
    "VscListFlat": VscListFlat,
    "VscListOrdered": VscListOrdered,
    "VscListSelection": VscListSelection,
    "VscListTree": VscListTree,
    "VscListUnordered": VscListUnordered,
    "VscLiveShare": VscLiveShare,
    "VscLoading": VscLoading,
    "VscLocation": VscLocation,
    "VscLock": VscLock,
    "VscMagnet": VscMagnet,
    "VscMailRead": VscMailRead,
    "VscMail": VscMail,
    "VscMarkdown": VscMarkdown,
    "VscMegaphone": VscMegaphone,
    "VscMention": VscMention,
    "VscMenu": VscMenu,
    "VscMerge": VscMerge,
    "VscMilestone": VscMilestone,
    "VscMirror": VscMirror,
    "VscMortarBoard": VscMortarBoard,
    "VscMove": VscMove,
    "VscMultipleWindows": VscMultipleWindows,
    "VscMute": VscMute,
    "VscNewFile": VscNewFile,
    "VscNewFolder": VscNewFolder,
    "VscNoNewline": VscNoNewline,
    "VscNote": VscNote,
    "VscNotebookTemplate": VscNotebookTemplate,
    "VscNotebook": VscNotebook,
    "VscOctoface": VscOctoface,
    "VscOpenPreview": VscOpenPreview,
    "VscOrganization": VscOrganization,
    "VscOutput": VscOutput,
    "VscPackage": VscPackage,
    "VscPaintcan": VscPaintcan,
    "VscPassFilled": VscPassFilled,
    "VscPass": VscPass,
    "VscPersonAdd": VscPersonAdd,
    "VscPerson": VscPerson,
    "VscPieChart": VscPieChart,
    "VscPin": VscPin,
    "VscPinnedDirty": VscPinnedDirty,
    "VscPinned": VscPinned,
    "VscPlayCircle": VscPlayCircle,
    "VscPlay": VscPlay,
    "VscPlug": VscPlug,
    "VscPreserveCase": VscPreserveCase,
    "VscPreview": VscPreview,
    "VscPrimitiveSquare": VscPrimitiveSquare,
    "VscProject": VscProject,
    "VscPulse": VscPulse,
    "VscQuestion": VscQuestion,
    "VscQuote": VscQuote,
    "VscRadioTower": VscRadioTower,
    "VscReactions": VscReactions,
    "VscRecordKeys": VscRecordKeys,
    "VscRecord": VscRecord,
    "VscRedo": VscRedo,
    "VscReferences": VscReferences,
    "VscRefresh": VscRefresh,
    "VscRegex": VscRegex,
    "VscRemoteExplorer": VscRemoteExplorer,
    "VscRemote": VscRemote,
    "VscRemove": VscRemove,
    "VscReplaceAll": VscReplaceAll,
    "VscReplace": VscReplace,
    "VscReply": VscReply,
    "VscRepoClone": VscRepoClone,
    "VscRepoForcePush": VscRepoForcePush,
    "VscRepoForked": VscRepoForked,
    "VscRepoPull": VscRepoPull,
    "VscRepoPush": VscRepoPush,
    "VscRepo": VscRepo,
    "VscReport": VscReport,
    "VscRequestChanges": VscRequestChanges,
    "VscRocket": VscRocket,
    "VscRootFolderOpened": VscRootFolderOpened,
    "VscRootFolder": VscRootFolder,
    "VscRss": VscRss,
    "VscRuby": VscRuby,
    "VscRunAbove": VscRunAbove,
    "VscRunAll": VscRunAll,
    "VscRunBelow": VscRunBelow,
    "VscRunErrors": VscRunErrors,
    "VscSaveAll": VscSaveAll,
    "VscSaveAs": VscSaveAs,
    "VscSave": VscSave,
    "VscScreenFull": VscScreenFull,
    "VscScreenNormal": VscScreenNormal,
    "VscSearchStop": VscSearchStop,
    "VscSearch": VscSearch,
    "VscServerEnvironment": VscServerEnvironment,
    "VscServerProcess": VscServerProcess,
    "VscServer": VscServer,
    "VscSettingsGear": VscSettingsGear,
    "VscSettings": VscSettings,
    "VscShield": VscShield,
    "VscSignIn": VscSignIn,
    "VscSignOut": VscSignOut,
    "VscSmiley": VscSmiley,
    "VscSortPrecedence": VscSortPrecedence,
    "VscSourceControl": VscSourceControl,
    "VscSplitHorizontal": VscSplitHorizontal,
    "VscSplitVertical": VscSplitVertical,
    "VscSquirrel": VscSquirrel,
    "VscStarEmpty": VscStarEmpty,
    "VscStarFull": VscStarFull,
    "VscStarHalf": VscStarHalf,
    "VscStopCircle": VscStopCircle,
    "VscSymbolArray": VscSymbolArray,
    "VscSymbolBoolean": VscSymbolBoolean,
    "VscSymbolClass": VscSymbolClass,
    "VscSymbolColor": VscSymbolColor,
    "VscSymbolConstant": VscSymbolConstant,
    "VscSymbolEnumMember": VscSymbolEnumMember,
    "VscSymbolEnum": VscSymbolEnum,
    "VscSymbolEvent": VscSymbolEvent,
    "VscSymbolField": VscSymbolField,
    "VscSymbolFile": VscSymbolFile,
    "VscSymbolInterface": VscSymbolInterface,
    "VscSymbolKey": VscSymbolKey,
    "VscSymbolKeyword": VscSymbolKeyword,
    "VscSymbolMethod": VscSymbolMethod,
    "VscSymbolMisc": VscSymbolMisc,
    "VscSymbolNamespace": VscSymbolNamespace,
    "VscSymbolNumeric": VscSymbolNumeric,
    "VscSymbolOperator": VscSymbolOperator,
    "VscSymbolParameter": VscSymbolParameter,
    "VscSymbolProperty": VscSymbolProperty,
    "VscSymbolRuler": VscSymbolRuler,
    "VscSymbolSnippet": VscSymbolSnippet,
    "VscSymbolString": VscSymbolString,
    "VscSymbolStructure": VscSymbolStructure,
    "VscSymbolVariable": VscSymbolVariable,
    "VscSyncIgnored": VscSyncIgnored,
    "VscSync": VscSync,
    "VscTable": VscTable,
    "VscTag": VscTag,
    "VscTasklist": VscTasklist,
    "VscTelescope": VscTelescope,
    "VscTerminalBash": VscTerminalBash,
    "VscTerminalCmd": VscTerminalCmd,
    "VscTerminalDebian": VscTerminalDebian,
    "VscTerminalLinux": VscTerminalLinux,
    "VscTerminalPowershell": VscTerminalPowershell,
    "VscTerminalTmux": VscTerminalTmux,
    "VscTerminalUbuntu": VscTerminalUbuntu,
    "VscTerminal": VscTerminal,
    "VscTextSize": VscTextSize,
    "VscThreeBars": VscThreeBars,
    "VscThumbsdown": VscThumbsdown,
    "VscThumbsup": VscThumbsup,
    "VscTools": VscTools,
    "VscTrash": VscTrash,
    "VscTriangleDown": VscTriangleDown,
    "VscTriangleLeft": VscTriangleLeft,
    "VscTriangleRight": VscTriangleRight,
    "VscTriangleUp": VscTriangleUp,
    "VscTwitter": VscTwitter,
    "VscTypeHierarchySub": VscTypeHierarchySub,
    "VscTypeHierarchySuper": VscTypeHierarchySuper,
    "VscTypeHierarchy": VscTypeHierarchy,
    "VscUnfold": VscUnfold,
    "VscUngroupByRefType": VscUngroupByRefType,
    "VscUnlock": VscUnlock,
    "VscUnmute": VscUnmute,
    "VscUnverified": VscUnverified,
    "VscVariableGroup": VscVariableGroup,
    "VscVerified": VscVerified,
    "VscVersions": VscVersions,
    "VscVmActive": VscVmActive,
    "VscVmConnect": VscVmConnect,
    "VscVmOutline": VscVmOutline,
    "VscVmRunning": VscVmRunning,
    "VscVm": VscVm,
    "VscWand": VscWand,
    "VscWarning": VscWarning,
    "VscWatch": VscWatch,
    "VscWhitespace": VscWhitespace,
    "VscWholeWord": VscWholeWord,
    "VscWindow": VscWindow,
    "VscWordWrap": VscWordWrap,
    "VscWorkspaceTrusted": VscWorkspaceTrusted,
    "VscWorkspaceUnknown": VscWorkspaceUnknown,
    "VscWorkspaceUntrusted": VscWorkspaceUntrusted,
    "VscZoomIn": VscZoomIn,
    "VscZoomOut": VscZoomOut,
}