import { 
    WiAlien,
WiBarometer,
WiCelsius,
WiCloudDown,
WiCloudRefresh,
WiCloudUp,
WiCloud,
WiCloudyGusts,
WiCloudyWindy,
WiCloudy,
WiDayCloudyGusts,
WiDayCloudyHigh,
WiDayCloudyWindy,
WiDayCloudy,
WiDayFog,
WiDayHail,
WiDayHaze,
WiDayLightWind,
WiDayLightning,
WiDayRainMix,
WiDayRainWind,
WiDayRain,
WiDayShowers,
WiDaySleetStorm,
WiDaySleet,
WiDaySnowThunderstorm,
WiDaySnowWind,
WiDaySnow,
WiDaySprinkle,
WiDayStormShowers,
WiDaySunnyOvercast,
WiDaySunny,
WiDayThunderstorm,
WiDayWindy,
WiDegrees,
WiDirectionDownLeft,
WiDirectionDownRight,
WiDirectionDown,
WiDirectionLeft,
WiDirectionRight,
WiDirectionUpLeft,
WiDirectionUpRight,
WiDirectionUp,
WiDust,
WiEarthquake,
WiFahrenheit,
WiFire,
WiFlood,
WiFog,
WiGaleWarning,
WiHail,
WiHorizonAlt,
WiHorizon,
WiHot,
WiHumidity,
WiHurricaneWarning,
WiHurricane,
WiLightning,
WiLunarEclipse,
WiMeteor,
WiMoonAltFirstQuarter,
WiMoonAltFull,
WiMoonAltNew,
WiMoonAltThirdQuarter,
WiMoonAltWaningCrescent1,
WiMoonAltWaningCrescent2,
WiMoonAltWaningCrescent3,
WiMoonAltWaningCrescent4,
WiMoonAltWaningCrescent5,
WiMoonAltWaningCrescent6,
WiMoonAltWaningGibbous1,
WiMoonAltWaningGibbous2,
WiMoonAltWaningGibbous3,
WiMoonAltWaningGibbous4,
WiMoonAltWaningGibbous5,
WiMoonAltWaningGibbous6,
WiMoonAltWaxingCrescent1,
WiMoonAltWaxingCrescent2,
WiMoonAltWaxingCrescent3,
WiMoonAltWaxingCrescent4,
WiMoonAltWaxingCrescent5,
WiMoonAltWaxingCrescent6,
WiMoonAltWaxingGibbous1,
WiMoonAltWaxingGibbous2,
WiMoonAltWaxingGibbous3,
WiMoonAltWaxingGibbous4,
WiMoonAltWaxingGibbous5,
WiMoonAltWaxingGibbous6,
WiMoonFirstQuarter,
WiMoonFull,
WiMoonNew,
WiMoonThirdQuarter,
WiMoonWaningCrescent1,
WiMoonWaningCrescent2,
WiMoonWaningCrescent3,
WiMoonWaningCrescent4,
WiMoonWaningCrescent5,
WiMoonWaningCrescent6,
WiMoonWaningGibbous1,
WiMoonWaningGibbous2,
WiMoonWaningGibbous3,
WiMoonWaningGibbous4,
WiMoonWaningGibbous5,
WiMoonWaningGibbous6,
WiMoonWaxing6,
WiMoonWaxingCrescent1,
WiMoonWaxingCrescent2,
WiMoonWaxingCrescent3,
WiMoonWaxingCrescent4,
WiMoonWaxingCrescent5,
WiMoonWaxingGibbous1,
WiMoonWaxingGibbous2,
WiMoonWaxingGibbous3,
WiMoonWaxingGibbous4,
WiMoonWaxingGibbous5,
WiMoonWaxingGibbous6,
WiMoonrise,
WiMoonset,
WiNa,
WiNightAltCloudyGusts,
WiNightAltCloudyHigh,
WiNightAltCloudyWindy,
WiNightAltCloudy,
WiNightAltHail,
WiNightAltLightning,
WiNightAltPartlyCloudy,
WiNightAltRainMix,
WiNightAltRainWind,
WiNightAltRain,
WiNightAltShowers,
WiNightAltSleetStorm,
WiNightAltSleet,
WiNightAltSnowThunderstorm,
WiNightAltSnowWind,
WiNightAltSnow,
WiNightAltSprinkle,
WiNightAltStormShowers,
WiNightAltThunderstorm,
WiNightClear,
WiNightCloudyGusts,
WiNightCloudyHigh,
WiNightCloudyWindy,
WiNightCloudy,
WiNightFog,
WiNightHail,
WiNightLightning,
WiNightPartlyCloudy,
WiNightRainMix,
WiNightRainWind,
WiNightRain,
WiNightShowers,
WiNightSleetStorm,
WiNightSleet,
WiNightSnowThunderstorm,
WiNightSnowWind,
WiNightSnow,
WiNightSprinkle,
WiNightStormShowers,
WiNightThunderstorm,
WiRainMix,
WiRainWind,
WiRain,
WiRaindrop,
WiRaindrops,
WiRefreshAlt,
WiRefresh,
WiSandstorm,
WiShowers,
WiSleet,
WiSmallCraftAdvisory,
WiSmog,
WiSmoke,
WiSnowWind,
WiSnow,
WiSnowflakeCold,
WiSolarEclipse,
WiSprinkle,
WiStars,
WiStormShowers,
WiStormWarning,
WiStrongWind,
WiSunrise,
WiSunset,
WiThermometerExterior,
WiThermometerInternal,
WiThermometer,
WiThunderstorm,
WiTime1,
WiTime10,
WiTime11,
WiTime12,
WiTime2,
WiTime3,
WiTime4,
WiTime5,
WiTime6,
WiTime7,
WiTime8,
WiTime9,
WiTornado,
WiTrain,
WiTsunami,
WiUmbrella,
WiVolcano,
WiWindBeaufort0,
WiWindBeaufort1,
WiWindBeaufort10,
WiWindBeaufort11,
WiWindBeaufort12,
WiWindBeaufort2,
WiWindBeaufort3,
WiWindBeaufort4,
WiWindBeaufort5,
WiWindBeaufort6,
WiWindBeaufort7,
WiWindBeaufort8,
WiWindBeaufort9,
WiWindDeg,
WiWindy
 } from "react-icons/wi";

export const WeatherIcons = {
    "WiAlien": WiAlien,
    "WiBarometer": WiBarometer,
    "WiCelsius": WiCelsius,
    "WiCloudDown": WiCloudDown,
    "WiCloudRefresh": WiCloudRefresh,
    "WiCloudUp": WiCloudUp,
    "WiCloud": WiCloud,
    "WiCloudyGusts": WiCloudyGusts,
    "WiCloudyWindy": WiCloudyWindy,
    "WiCloudy": WiCloudy,
    "WiDayCloudyGusts": WiDayCloudyGusts,
    "WiDayCloudyHigh": WiDayCloudyHigh,
    "WiDayCloudyWindy": WiDayCloudyWindy,
    "WiDayCloudy": WiDayCloudy,
    "WiDayFog": WiDayFog,
    "WiDayHail": WiDayHail,
    "WiDayHaze": WiDayHaze,
    "WiDayLightWind": WiDayLightWind,
    "WiDayLightning": WiDayLightning,
    "WiDayRainMix": WiDayRainMix,
    "WiDayRainWind": WiDayRainWind,
    "WiDayRain": WiDayRain,
    "WiDayShowers": WiDayShowers,
    "WiDaySleetStorm": WiDaySleetStorm,
    "WiDaySleet": WiDaySleet,
    "WiDaySnowThunderstorm": WiDaySnowThunderstorm,
    "WiDaySnowWind": WiDaySnowWind,
    "WiDaySnow": WiDaySnow,
    "WiDaySprinkle": WiDaySprinkle,
    "WiDayStormShowers": WiDayStormShowers,
    "WiDaySunnyOvercast": WiDaySunnyOvercast,
    "WiDaySunny": WiDaySunny,
    "WiDayThunderstorm": WiDayThunderstorm,
    "WiDayWindy": WiDayWindy,
    "WiDegrees": WiDegrees,
    "WiDirectionDownLeft": WiDirectionDownLeft,
    "WiDirectionDownRight": WiDirectionDownRight,
    "WiDirectionDown": WiDirectionDown,
    "WiDirectionLeft": WiDirectionLeft,
    "WiDirectionRight": WiDirectionRight,
    "WiDirectionUpLeft": WiDirectionUpLeft,
    "WiDirectionUpRight": WiDirectionUpRight,
    "WiDirectionUp": WiDirectionUp,
    "WiDust": WiDust,
    "WiEarthquake": WiEarthquake,
    "WiFahrenheit": WiFahrenheit,
    "WiFire": WiFire,
    "WiFlood": WiFlood,
    "WiFog": WiFog,
    "WiGaleWarning": WiGaleWarning,
    "WiHail": WiHail,
    "WiHorizonAlt": WiHorizonAlt,
    "WiHorizon": WiHorizon,
    "WiHot": WiHot,
    "WiHumidity": WiHumidity,
    "WiHurricaneWarning": WiHurricaneWarning,
    "WiHurricane": WiHurricane,
    "WiLightning": WiLightning,
    "WiLunarEclipse": WiLunarEclipse,
    "WiMeteor": WiMeteor,
    "WiMoonAltFirstQuarter": WiMoonAltFirstQuarter,
    "WiMoonAltFull": WiMoonAltFull,
    "WiMoonAltNew": WiMoonAltNew,
    "WiMoonAltThirdQuarter": WiMoonAltThirdQuarter,
    "WiMoonAltWaningCrescent1": WiMoonAltWaningCrescent1,
    "WiMoonAltWaningCrescent2": WiMoonAltWaningCrescent2,
    "WiMoonAltWaningCrescent3": WiMoonAltWaningCrescent3,
    "WiMoonAltWaningCrescent4": WiMoonAltWaningCrescent4,
    "WiMoonAltWaningCrescent5": WiMoonAltWaningCrescent5,
    "WiMoonAltWaningCrescent6": WiMoonAltWaningCrescent6,
    "WiMoonAltWaningGibbous1": WiMoonAltWaningGibbous1,
    "WiMoonAltWaningGibbous2": WiMoonAltWaningGibbous2,
    "WiMoonAltWaningGibbous3": WiMoonAltWaningGibbous3,
    "WiMoonAltWaningGibbous4": WiMoonAltWaningGibbous4,
    "WiMoonAltWaningGibbous5": WiMoonAltWaningGibbous5,
    "WiMoonAltWaningGibbous6": WiMoonAltWaningGibbous6,
    "WiMoonAltWaxingCrescent1": WiMoonAltWaxingCrescent1,
    "WiMoonAltWaxingCrescent2": WiMoonAltWaxingCrescent2,
    "WiMoonAltWaxingCrescent3": WiMoonAltWaxingCrescent3,
    "WiMoonAltWaxingCrescent4": WiMoonAltWaxingCrescent4,
    "WiMoonAltWaxingCrescent5": WiMoonAltWaxingCrescent5,
    "WiMoonAltWaxingCrescent6": WiMoonAltWaxingCrescent6,
    "WiMoonAltWaxingGibbous1": WiMoonAltWaxingGibbous1,
    "WiMoonAltWaxingGibbous2": WiMoonAltWaxingGibbous2,
    "WiMoonAltWaxingGibbous3": WiMoonAltWaxingGibbous3,
    "WiMoonAltWaxingGibbous4": WiMoonAltWaxingGibbous4,
    "WiMoonAltWaxingGibbous5": WiMoonAltWaxingGibbous5,
    "WiMoonAltWaxingGibbous6": WiMoonAltWaxingGibbous6,
    "WiMoonFirstQuarter": WiMoonFirstQuarter,
    "WiMoonFull": WiMoonFull,
    "WiMoonNew": WiMoonNew,
    "WiMoonThirdQuarter": WiMoonThirdQuarter,
    "WiMoonWaningCrescent1": WiMoonWaningCrescent1,
    "WiMoonWaningCrescent2": WiMoonWaningCrescent2,
    "WiMoonWaningCrescent3": WiMoonWaningCrescent3,
    "WiMoonWaningCrescent4": WiMoonWaningCrescent4,
    "WiMoonWaningCrescent5": WiMoonWaningCrescent5,
    "WiMoonWaningCrescent6": WiMoonWaningCrescent6,
    "WiMoonWaningGibbous1": WiMoonWaningGibbous1,
    "WiMoonWaningGibbous2": WiMoonWaningGibbous2,
    "WiMoonWaningGibbous3": WiMoonWaningGibbous3,
    "WiMoonWaningGibbous4": WiMoonWaningGibbous4,
    "WiMoonWaningGibbous5": WiMoonWaningGibbous5,
    "WiMoonWaningGibbous6": WiMoonWaningGibbous6,
    "WiMoonWaxing6": WiMoonWaxing6,
    "WiMoonWaxingCrescent1": WiMoonWaxingCrescent1,
    "WiMoonWaxingCrescent2": WiMoonWaxingCrescent2,
    "WiMoonWaxingCrescent3": WiMoonWaxingCrescent3,
    "WiMoonWaxingCrescent4": WiMoonWaxingCrescent4,
    "WiMoonWaxingCrescent5": WiMoonWaxingCrescent5,
    "WiMoonWaxingGibbous1": WiMoonWaxingGibbous1,
    "WiMoonWaxingGibbous2": WiMoonWaxingGibbous2,
    "WiMoonWaxingGibbous3": WiMoonWaxingGibbous3,
    "WiMoonWaxingGibbous4": WiMoonWaxingGibbous4,
    "WiMoonWaxingGibbous5": WiMoonWaxingGibbous5,
    "WiMoonWaxingGibbous6": WiMoonWaxingGibbous6,
    "WiMoonrise": WiMoonrise,
    "WiMoonset": WiMoonset,
    "WiNa": WiNa,
    "WiNightAltCloudyGusts": WiNightAltCloudyGusts,
    "WiNightAltCloudyHigh": WiNightAltCloudyHigh,
    "WiNightAltCloudyWindy": WiNightAltCloudyWindy,
    "WiNightAltCloudy": WiNightAltCloudy,
    "WiNightAltHail": WiNightAltHail,
    "WiNightAltLightning": WiNightAltLightning,
    "WiNightAltPartlyCloudy": WiNightAltPartlyCloudy,
    "WiNightAltRainMix": WiNightAltRainMix,
    "WiNightAltRainWind": WiNightAltRainWind,
    "WiNightAltRain": WiNightAltRain,
    "WiNightAltShowers": WiNightAltShowers,
    "WiNightAltSleetStorm": WiNightAltSleetStorm,
    "WiNightAltSleet": WiNightAltSleet,
    "WiNightAltSnowThunderstorm": WiNightAltSnowThunderstorm,
    "WiNightAltSnowWind": WiNightAltSnowWind,
    "WiNightAltSnow": WiNightAltSnow,
    "WiNightAltSprinkle": WiNightAltSprinkle,
    "WiNightAltStormShowers": WiNightAltStormShowers,
    "WiNightAltThunderstorm": WiNightAltThunderstorm,
    "WiNightClear": WiNightClear,
    "WiNightCloudyGusts": WiNightCloudyGusts,
    "WiNightCloudyHigh": WiNightCloudyHigh,
    "WiNightCloudyWindy": WiNightCloudyWindy,
    "WiNightCloudy": WiNightCloudy,
    "WiNightFog": WiNightFog,
    "WiNightHail": WiNightHail,
    "WiNightLightning": WiNightLightning,
    "WiNightPartlyCloudy": WiNightPartlyCloudy,
    "WiNightRainMix": WiNightRainMix,
    "WiNightRainWind": WiNightRainWind,
    "WiNightRain": WiNightRain,
    "WiNightShowers": WiNightShowers,
    "WiNightSleetStorm": WiNightSleetStorm,
    "WiNightSleet": WiNightSleet,
    "WiNightSnowThunderstorm": WiNightSnowThunderstorm,
    "WiNightSnowWind": WiNightSnowWind,
    "WiNightSnow": WiNightSnow,
    "WiNightSprinkle": WiNightSprinkle,
    "WiNightStormShowers": WiNightStormShowers,
    "WiNightThunderstorm": WiNightThunderstorm,
    "WiRainMix": WiRainMix,
    "WiRainWind": WiRainWind,
    "WiRain": WiRain,
    "WiRaindrop": WiRaindrop,
    "WiRaindrops": WiRaindrops,
    "WiRefreshAlt": WiRefreshAlt,
    "WiRefresh": WiRefresh,
    "WiSandstorm": WiSandstorm,
    "WiShowers": WiShowers,
    "WiSleet": WiSleet,
    "WiSmallCraftAdvisory": WiSmallCraftAdvisory,
    "WiSmog": WiSmog,
    "WiSmoke": WiSmoke,
    "WiSnowWind": WiSnowWind,
    "WiSnow": WiSnow,
    "WiSnowflakeCold": WiSnowflakeCold,
    "WiSolarEclipse": WiSolarEclipse,
    "WiSprinkle": WiSprinkle,
    "WiStars": WiStars,
    "WiStormShowers": WiStormShowers,
    "WiStormWarning": WiStormWarning,
    "WiStrongWind": WiStrongWind,
    "WiSunrise": WiSunrise,
    "WiSunset": WiSunset,
    "WiThermometerExterior": WiThermometerExterior,
    "WiThermometerInternal": WiThermometerInternal,
    "WiThermometer": WiThermometer,
    "WiThunderstorm": WiThunderstorm,
    "WiTime1": WiTime1,
    "WiTime10": WiTime10,
    "WiTime11": WiTime11,
    "WiTime12": WiTime12,
    "WiTime2": WiTime2,
    "WiTime3": WiTime3,
    "WiTime4": WiTime4,
    "WiTime5": WiTime5,
    "WiTime6": WiTime6,
    "WiTime7": WiTime7,
    "WiTime8": WiTime8,
    "WiTime9": WiTime9,
    "WiTornado": WiTornado,
    "WiTrain": WiTrain,
    "WiTsunami": WiTsunami,
    "WiUmbrella": WiUmbrella,
    "WiVolcano": WiVolcano,
    "WiWindBeaufort0": WiWindBeaufort0,
    "WiWindBeaufort1": WiWindBeaufort1,
    "WiWindBeaufort10": WiWindBeaufort10,
    "WiWindBeaufort11": WiWindBeaufort11,
    "WiWindBeaufort12": WiWindBeaufort12,
    "WiWindBeaufort2": WiWindBeaufort2,
    "WiWindBeaufort3": WiWindBeaufort3,
    "WiWindBeaufort4": WiWindBeaufort4,
    "WiWindBeaufort5": WiWindBeaufort5,
    "WiWindBeaufort6": WiWindBeaufort6,
    "WiWindBeaufort7": WiWindBeaufort7,
    "WiWindBeaufort8": WiWindBeaufort8,
    "WiWindBeaufort9": WiWindBeaufort9,
    "WiWindDeg": WiWindDeg,
    "WiWindy": WiWindy,
}