import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";
import useSpacingProps from "../../utils/spacing-props";
import { color } from "../properties";
import { AiFillAccountBook, 
  AiFillAlert,
  AiFillAlipayCircle,
  AiFillAlipaySquare,
  AiFillAliwangwang,
  AiFillAmazonCircle,
  AiFillAmazonSquare,
  AiFillAndroid,
  AiFillApi,
  AiFillApple,
  AiFillAppstore,
  AiFillAudio,
  AiFillBackward,
  AiFillBank,
  AiFillBehanceCircle,
  AiFillBehanceSquare,
  AiFillBell,
  AiFillBook,
  AiFillBoxPlot,
  AiFillBug,
  AiFillBuild,
  AiFillBulb,
  AiFillCalculator,
  AiFillCalendar,
  AiFillCamera,
  AiFillCar,
  AiFillCaretDown,
  AiFillCaretLeft,
  AiFillCaretRight,
  AiFillCaretUp,
  AiFillCarryOut,
  AiFillCheckCircle,
  AiFillCheckSquare,
  AiFillChrome,
  AiFillCiCircle,
  AiFillClockCircle,
  AiFillCloseCircle,
  AiFillCloseSquare,
  AiFillCloud,
  AiFillCodeSandboxCircle,
  AiFillCodeSandboxSquare,
  AiFillCode,
  AiFillCodepenCircle,
  AiFillCodepenSquare,
  AiFillCompass,
  AiFillContacts,
  AiFillContainer,
  AiFillControl,
  AiFillCopy,
  AiFillCopyrightCircle,
  AiFillCreditCard,
  AiFillCrown,
  AiFillCustomerService,
  AiFillDashboard,
  AiFillDatabase,
  AiFillDelete,
  AiFillDiff,
  AiFillDingtalkCircle,
  AiFillDingtalkSquare,
  AiFillDislike,
  AiFillDollarCircle,
  AiFillDownCircle,
  AiFillDownSquare,
  AiFillDribbbleCircle,
  AiFillDribbbleSquare,
  AiFillDropboxCircle,
  AiFillDropboxSquare,
  AiFillEdit,
  AiFillEnvironment,
  AiFillEuroCircle,
  AiFillExclamationCircle,
  AiFillExperiment,
  AiFillEyeInvisible,
  AiFillEye,
  AiFillFacebook,
  AiFillFastBackward,
  AiFillFastForward,
  AiFillFileAdd,
  AiFillFileExcel,
  AiFillFileExclamation,
  AiFillFileImage,
  AiFillFileMarkdown,
  AiFillFilePdf,
  AiFillFilePpt,
  AiFillFileText,
  AiFillFileUnknown,
  AiFillFileWord,
  AiFillFileZip,
  AiFillFile,
  AiFillFilter,
  AiFillFire,
  AiFillFlag,
  AiFillFolderAdd,
  AiFillFolderOpen,
  AiFillFolder,
  AiFillFormatPainter,
  AiFillForward,
  AiFillFrown,
  AiFillFund,
  AiFillFunnelPlot,
  AiFillGift,
  AiFillGithub,
  AiFillGitlab,
  AiFillGold,
  AiFillGolden,
  AiFillGoogleCircle,
  AiFillGooglePlusCircle,
  AiFillGooglePlusSquare,
  AiFillGoogleSquare,
  AiFillHdd,
  AiFillHeart,
  AiFillHighlight,
  AiFillHome,
  AiFillHourglass,
  AiFillHtml5,
  AiFillIdcard,
  AiFillIeCircle,
  AiFillIeSquare,
  AiFillInfoCircle,
  AiFillInstagram,
  AiFillInsurance,
  AiFillInteraction,
  AiFillLayout,
  AiFillLeftCircle,
  AiFillLeftSquare,
  AiFillLike,
  AiFillLinkedin,
  AiFillLock,
  AiFillMacCommand,
  AiFillMail,
  AiFillMedicineBox,
  AiFillMediumCircle,
  AiFillMediumSquare,
  AiFillMeh,
  AiFillMessage,
  AiFillMinusCircle,
  AiFillMinusSquare,
  AiFillMobile,
  AiFillMoneyCollect,
  AiFillNotification,
  AiFillPauseCircle,
  AiFillPayCircle,
  AiFillPhone,
  AiFillPicture,
  AiFillPieChart,
  AiFillPlayCircle,
  AiFillPlaySquare,
  AiFillPlusCircle,
  AiFillPlusSquare,
  AiFillPoundCircle,
  AiFillPrinter,
  AiFillProfile,
  AiFillProject,
  AiFillPropertySafety,
  AiFillPushpin,
  AiFillQqCircle,
  AiFillQqSquare,
  AiFillQuestionCircle,
  AiFillRead,
  AiFillReconciliation,
  AiFillRedEnvelope,
  AiFillRedditCircle,
  AiFillRedditSquare,
  AiFillRest,
  AiFillRightCircle,
  AiFillRightSquare,
  AiFillRobot,
  AiFillRocket,
  AiFillSafetyCertificate,
  AiFillSave,
  AiFillSchedule,
  AiFillSecurityScan,
  AiFillSetting,
  AiFillShop,
  AiFillShopping,
  AiFillSignal,
  AiFillSketchCircle,
  AiFillSketchSquare,
  AiFillSkin,
  AiFillSkype,
  AiFillSlackCircle,
  AiFillSlackSquare,
  AiFillSliders,
  AiFillSmile,
  AiFillSnippets,
  AiFillSound,
  AiFillStar,
  AiFillStepBackward,
  AiFillStepForward,
  AiFillStop,
  AiFillSwitcher,
  AiFillTablet,
  AiFillTag,
  AiFillTags,
  AiFillTaobaoCircle,
  AiFillTaobaoSquare,
  AiFillThunderbolt,
  AiFillTool,
  AiFillTrademarkCircle,
  AiFillTrophy,
  AiFillTwitterCircle,
  AiFillTwitterSquare,
  AiFillUnlock,
  AiFillUpCircle,
  AiFillUpSquare,
  AiFillUsb,
  AiFillVideoCamera,
  AiFillWallet,
  AiFillWarning,
  AiFillWechat,
  AiFillWeiboCircle,
  AiFillWeiboSquare,
  AiFillWindows,
  AiFillYahoo,
  AiFillYoutube,
  AiFillYuque,
  AiFillZhihuCircle,
  AiFillZhihuSquare,
  AiOutlineAccountBook,
  AiOutlineAim,
  AiOutlineAlert,
  AiOutlineAlibaba,
  AiOutlineAlignCenter,
  AiOutlineAlignLeft,
  AiOutlineAlignRight,
  AiOutlineAlipayCircle,
  AiOutlineAlipay,
  AiOutlineAliwangwang,
  AiOutlineAliyun,
  AiOutlineAmazon,
  AiOutlineAndroid,
  AiOutlineAntCloud,
  AiOutlineAntDesign,
  AiOutlineApartment,
  AiOutlineApi,
  AiOutlineApple,
  AiOutlineAppstoreAdd,
  AiOutlineAppstore,
  AiOutlineAreaChart,
  AiOutlineArrowDown,
  AiOutlineArrowLeft,
  AiOutlineArrowRight,
  AiOutlineArrowUp,
  AiOutlineArrowsAlt,
  AiOutlineAudioMuted,
  AiOutlineAudio,
  AiOutlineAudit,
  AiOutlineBackward,
  AiOutlineBank,
  AiOutlineBarChart,
  AiOutlineBarcode,
  AiOutlineBars,
  AiOutlineBehanceSquare,
  AiOutlineBehance,
  AiOutlineBell,
  AiOutlineBgColors,
  AiOutlineBlock,
  AiOutlineBold,
  AiOutlineBook,
  AiOutlineBorderBottom,
  AiOutlineBorderHorizontal,
  AiOutlineBorderInner,
  AiOutlineBorderLeft,
  AiOutlineBorderOuter,
  AiOutlineBorderRight,
  AiOutlineBorderTop,
  AiOutlineBorderVerticle,
  AiOutlineBorder,
  AiOutlineBorderlessTable,
  AiOutlineBoxPlot,
  AiOutlineBranches,
  AiOutlineBug,
  AiOutlineBuild,
  AiOutlineBulb,
  AiOutlineCalculator,
  AiOutlineCalendar,
  AiOutlineCamera,
  AiOutlineCar,
  AiOutlineCaretDown,
  AiOutlineCaretLeft,
  AiOutlineCaretRight,
  AiOutlineCaretUp,
  AiOutlineCarryOut,
  AiOutlineCheckCircle,
  AiOutlineCheckSquare,
  AiOutlineCheck,
  AiOutlineChrome,
  AiOutlineCiCircle,
  AiOutlineCi,
  AiOutlineClear,
  AiOutlineClockCircle,
  AiOutlineCloseCircle,
  AiOutlineCloseSquare,
  AiOutlineClose,
  AiOutlineCloudDownload,
  AiOutlineCloudServer,
  AiOutlineCloudSync,
  AiOutlineCloudUpload,
  AiOutlineCloud,
  AiOutlineCluster,
  AiOutlineCodeSandbox,
  AiOutlineCode,
  AiOutlineCodepenCircle,
  AiOutlineCodepen,
  AiOutlineCoffee,
  AiOutlineColumnHeight,
  AiOutlineColumnWidth,
  AiOutlineComment,
  AiOutlineCompass,
  AiOutlineCompress,
  AiOutlineConsoleSql,
  AiOutlineContacts,
  AiOutlineContainer,
  AiOutlineControl,
  AiOutlineCopy,
  AiOutlineCopyrightCircle,
  AiOutlineCopyright,
  AiOutlineCreditCard,
  AiOutlineCrown,
  AiOutlineCustomerService,
  AiOutlineDash,
  AiOutlineDashboard,
  AiOutlineDatabase,
  AiOutlineDeleteColumn,
  AiOutlineDeleteRow,
  AiOutlineDelete,
  AiOutlineDeliveredProcedure,
  AiOutlineDeploymentUnit,
  AiOutlineDesktop,
  AiOutlineDiff,
  AiOutlineDingding,
  AiOutlineDingtalk,
  AiOutlineDisconnect,
  AiOutlineDislike,
  AiOutlineDollarCircle,
  AiOutlineDollar,
  AiOutlineDotChart,
  AiOutlineDoubleLeft,
  AiOutlineDoubleRight,
  AiOutlineDownCircle,
  AiOutlineDownSquare,
  AiOutlineDown,
  AiOutlineDownload,
  AiOutlineDrag,
  AiOutlineDribbbleSquare,
  AiOutlineDribbble,
  AiOutlineDropbox,
  AiOutlineEdit,
  AiOutlineEllipsis,
  AiOutlineEnter,
  AiOutlineEnvironment,
  AiOutlineEuroCircle,
  AiOutlineEuro,
  AiOutlineException,
  AiOutlineExclamationCircle,
  AiOutlineExclamation,
  AiOutlineExpandAlt,
  AiOutlineExpand,
  AiOutlineExperiment,
  AiOutlineExport,
  AiOutlineEyeInvisible,
  AiOutlineEye,
  AiOutlineFacebook,
  AiOutlineFall,
  AiOutlineFastBackward,
  AiOutlineFastForward,
  AiOutlineFieldBinary,
  AiOutlineFieldNumber,
  AiOutlineFieldString,
  AiOutlineFieldTime,
  AiOutlineFileAdd,
  AiOutlineFileDone,
  AiOutlineFileExcel,
  AiOutlineFileExclamation,
  AiOutlineFileGif,
  AiOutlineFileImage,
  AiOutlineFileJpg,
  AiOutlineFileMarkdown,
  AiOutlineFilePdf,
  AiOutlineFilePpt,
  AiOutlineFileProtect,
  AiOutlineFileSearch,
  AiOutlineFileSync,
  AiOutlineFileText,
  AiOutlineFileUnknown,
  AiOutlineFileWord,
  AiOutlineFileZip,
  AiOutlineFile,
  AiOutlineFilter,
  AiOutlineFire,
  AiOutlineFlag,
  AiOutlineFolderAdd,
  AiOutlineFolderOpen,
  AiOutlineFolderView,
  AiOutlineFolder,
  AiOutlineFontColors,
  AiOutlineFontSize,
  AiOutlineFork,
  AiOutlineForm,
  AiOutlineFormatPainter,
  AiOutlineForward,
  AiOutlineFrown,
  AiOutlineFullscreenExit,
  AiOutlineFullscreen,
  AiOutlineFunction,
  AiOutlineFundProjectionScreen,
  AiOutlineFundView,
  AiOutlineFund,
  AiOutlineFunnelPlot,
  AiOutlineGateway,
  AiOutlineGif,
  AiOutlineGift,
  AiOutlineGithub,
  AiOutlineGitlab,
  AiOutlineGlobal,
  AiOutlineGold,
  AiOutlineGooglePlus,
  AiOutlineGoogle,
  AiOutlineGroup,
  AiOutlineHdd,
  AiOutlineHeart,
  AiOutlineHeatMap,
  AiOutlineHighlight,
  AiOutlineHistory,
  AiOutlineHolder,
  AiOutlineHome,
  AiOutlineHourglass,
  AiOutlineHtml5,
  AiOutlineIdcard,
  AiOutlineIe,
  AiOutlineImport,
  AiOutlineInbox,
  AiOutlineInfoCircle,
  AiOutlineInfo,
  AiOutlineInsertRowAbove,
  AiOutlineInsertRowBelow,
  AiOutlineInsertRowLeft,
  AiOutlineInsertRowRight,
  AiOutlineInstagram,
  AiOutlineInsurance,
  AiOutlineInteraction,
  AiOutlineIssuesClose,
  AiOutlineItalic,
  AiOutlineKey,
  AiOutlineLaptop,
  AiOutlineLayout,
  AiOutlineLeftCircle,
  AiOutlineLeftSquare,
  AiOutlineLeft,
  AiOutlineLike,
  AiOutlineLineChart,
  AiOutlineLineHeight,
  AiOutlineLine,
  AiOutlineLink,
  AiOutlineLinkedin,
  AiOutlineLoading3Quarters,
  AiOutlineLoading,
  AiOutlineLock,
  AiOutlineLogin,
  AiOutlineLogout,
  AiOutlineMacCommand,
  AiOutlineMail,
  AiOutlineMan,
  AiOutlineMedicineBox,
  AiOutlineMediumWorkmark,
  AiOutlineMedium,
  AiOutlineMeh,
  AiOutlineMenuFold,
  AiOutlineMenuUnfold,
  AiOutlineMenu,
  AiOutlineMergeCells,
  AiOutlineMessage,
  AiOutlineMinusCircle,
  AiOutlineMinusSquare,
  AiOutlineMinus,
  AiOutlineMobile,
  AiOutlineMoneyCollect,
  AiOutlineMonitor,
  AiOutlineMore,
  AiOutlineNodeCollapse,
  AiOutlineNodeExpand,
  AiOutlineNodeIndex,
  AiOutlineNotification,
  AiOutlineNumber,
  AiOutlineOneToOne,
  AiOutlineOrderedList,
  AiOutlinePaperClip,
  AiOutlinePartition,
  AiOutlinePauseCircle,
  AiOutlinePause,
  AiOutlinePayCircle,
  AiOutlinePercentage,
  AiOutlinePhone,
  AiOutlinePicCenter,
  AiOutlinePicLeft,
  AiOutlinePicRight,
  AiOutlinePicture,
  AiOutlinePieChart,
  AiOutlinePlayCircle,
  AiOutlinePlaySquare,
  AiOutlinePlusCircle,
  AiOutlinePlusSquare,
  AiOutlinePlus,
  AiOutlinePoundCircle,
  AiOutlinePound,
  AiOutlinePoweroff,
  AiOutlinePrinter,
  AiOutlineProfile,
  AiOutlineProject,
  AiOutlinePropertySafety,
  AiOutlinePullRequest,
  AiOutlinePushpin,
  AiOutlineQq,
  AiOutlineQrcode,
  AiOutlineQuestionCircle,
  AiOutlineQuestion,
  AiOutlineRadarChart,
  AiOutlineRadiusBottomleft,
  AiOutlineRadiusBottomright,
  AiOutlineRadiusSetting,
  AiOutlineRadiusUpleft,
  AiOutlineRadiusUpright,
  AiOutlineRead,
  AiOutlineReconciliation,
  AiOutlineRedEnvelope,
  AiOutlineReddit,
  AiOutlineRedo,
  AiOutlineReload,
  AiOutlineRest,
  AiOutlineRetweet,
  AiOutlineRightCircle,
  AiOutlineRightSquare,
  AiOutlineRight,
  AiOutlineRise,
  AiOutlineRobot,
  AiOutlineRocket,
  AiOutlineRollback,
  AiOutlineRotateLeft,
  AiOutlineRotateRight,
  AiOutlineSafetyCertificate,
  AiOutlineSafety,
  AiOutlineSave,
  AiOutlineScan,
  AiOutlineSchedule,
  AiOutlineScissor,
  AiOutlineSearch,
  AiOutlineSecurityScan,
  AiOutlineSelect,
  AiOutlineSend,
  AiOutlineSetting,
  AiOutlineShake,
  AiOutlineShareAlt,
  AiOutlineShop,
  AiOutlineShoppingCart,
  AiOutlineShopping,
  AiOutlineShrink,
  AiOutlineSisternode,
  AiOutlineSketch,
  AiOutlineSkin,
  AiOutlineSkype,
  AiOutlineSlackSquare,
  AiOutlineSlack,
  AiOutlineSliders,
  AiOutlineSmallDash,
  AiOutlineSmile,
  AiOutlineSnippets,
  AiOutlineSolution,
  AiOutlineSortAscending,
  AiOutlineSortDescending,
  AiOutlineSound,
  AiOutlineSplitCells,
  AiOutlineStar,
  AiOutlineStepBackward,
  AiOutlineStepForward,
  AiOutlineStock,
  AiOutlineStop,
  AiOutlineStrikethrough,
  AiOutlineSubnode,
  AiOutlineSwapLeft,
  AiOutlineSwapRight,
  AiOutlineSwap,
  AiOutlineSwitcher,
  AiOutlineSync,
  AiOutlineTable,
  AiOutlineTablet,
  AiOutlineTag,
  AiOutlineTags,
  AiOutlineTaobaoCircle,
  AiOutlineTaobao,
  AiOutlineTeam,
  AiOutlineThunderbolt,
  AiOutlineToTop,
  AiOutlineTool,
  AiOutlineTrademarkCircle,
  AiOutlineTrademark,
  AiOutlineTransaction,
  AiOutlineTranslation,
  AiOutlineTrophy,
  AiOutlineTwitter,
  AiOutlineUnderline,
  AiOutlineUndo,
  AiOutlineUngroup,
  AiOutlineUnlock,
  AiOutlineUnorderedList,
  AiOutlineUpCircle,
  AiOutlineUpSquare,
  AiOutlineUp,
  AiOutlineUpload,
  AiOutlineUsb,
  AiOutlineUserAdd,
  AiOutlineUserDelete,
  AiOutlineUserSwitch,
  AiOutlineUser,
  AiOutlineUsergroupAdd,
  AiOutlineUsergroupDelete,
  AiOutlineVerified,
  AiOutlineVerticalAlignBottom,
  AiOutlineVerticalAlignMiddle,
  AiOutlineVerticalAlignTop,
  AiOutlineVerticalLeft,
  AiOutlineVerticalRight,
  AiOutlineVideoCameraAdd,
  AiOutlineVideoCamera,
  AiOutlineWallet,
  AiOutlineWarning,
  AiOutlineWechat,
  AiOutlineWeiboCircle,
  AiOutlineWeiboSquare,
  AiOutlineWeibo,
  AiOutlineWhatsApp,
  AiOutlineWifi,
  AiOutlineWindows,
  AiOutlineWoman,
  AiOutlineYahoo,
  AiOutlineYoutube,
  AiOutlineYuque,
  AiOutlineZhihu,
  AiOutlineZoomIn,
  AiOutlineZoomOut,
  AiTwotoneAccountBook,
  AiTwotoneAlert,
  AiTwotoneApi,
  AiTwotoneAppstore,
  AiTwotoneAudio,
  AiTwotoneBank,
  AiTwotoneBell,
  AiTwotoneBook,
  AiTwotoneBoxPlot,
  AiTwotoneBug,
  AiTwotoneBuild,
  AiTwotoneBulb,
  AiTwotoneCalculator,
  AiTwotoneCalendar,
  AiTwotoneCamera,
  AiTwotoneCar,
  AiTwotoneCarryOut,
  AiTwotoneCheckCircle,
  AiTwotoneCheckSquare,
  AiTwotoneCiCircle,
  AiTwotoneCi,
  AiTwotoneClockCircle,
  AiTwotoneCloseCircle,
  AiTwotoneCloseSquare,
  AiTwotoneCloud,
  AiTwotoneCode,
  AiTwotoneCompass,
  AiTwotoneContacts,
  AiTwotoneContainer,
  AiTwotoneControl,
  AiTwotoneCopy,
  AiTwotoneCopyrightCircle,
  AiTwotoneCopyright,
  AiTwotoneCreditCard,
  AiTwotoneCrown,
  AiTwotoneCustomerService,
  AiTwotoneDashboard,
  AiTwotoneDatabase,
  AiTwotoneDelete,
  AiTwotoneDiff,
  AiTwotoneDislike,
  AiTwotoneDollarCircle,
  AiTwotoneDollar,
  AiTwotoneDownCircle,
  AiTwotoneDownSquare,
  AiTwotoneEdit,
  AiTwotoneEnvironment,
  AiTwotoneEuroCircle,
  AiTwotoneEuro,
  AiTwotoneExclamationCircle,
  AiTwotoneExperiment,
  AiTwotoneEyeInvisible,
  AiTwotoneEye,
  AiTwotoneFileAdd,
  AiTwotoneFileExcel,
  AiTwotoneFileExclamation,
  AiTwotoneFileImage,
  AiTwotoneFileMarkdown,
  AiTwotoneFilePdf,
  AiTwotoneFilePpt,
  AiTwotoneFileText,
  AiTwotoneFileUnknown,
  AiTwotoneFileWord,
  AiTwotoneFileZip,
  AiTwotoneFile,
  AiTwotoneFilter,
  AiTwotoneFire,
  AiTwotoneFlag,
  AiTwotoneFolderAdd,
  AiTwotoneFolderOpen,
  AiTwotoneFolder,
  AiTwotoneFrown,
  AiTwotoneFund,
  AiTwotoneFunnelPlot,
  AiTwotoneGift,
  AiTwotoneGold,
  AiTwotoneHdd,
  AiTwotoneHeart,
  AiTwotoneHighlight,
  AiTwotoneHome,
  AiTwotoneHourglass,
  AiTwotoneHtml5,
  AiTwotoneIdcard,
  AiTwotoneInfoCircle,
  AiTwotoneInsurance,
  AiTwotoneInteraction,
  AiTwotoneLayout,
  AiTwotoneLeftCircle,
  AiTwotoneLeftSquare,
  AiTwotoneLike,
  AiTwotoneLock,
  AiTwotoneMail,
  AiTwotoneMedicineBox,
  AiTwotoneMeh,
  AiTwotoneMessage,
  AiTwotoneMinusCircle,
  AiTwotoneMinusSquare,
  AiTwotoneMobile,
  AiTwotoneMoneyCollect,
  AiTwotoneNotification,
  AiTwotonePauseCircle,
  AiTwotonePhone,
  AiTwotonePicture,
  AiTwotonePieChart,
  AiTwotonePlayCircle,
  AiTwotonePlaySquare,
  AiTwotonePlusCircle,
  AiTwotonePlusSquare,
  AiTwotonePoundCircle,
  AiTwotonePrinter,
  AiTwotoneProfile,
  AiTwotoneProject,
  AiTwotonePropertySafety,
  AiTwotonePushpin,
  AiTwotoneQuestionCircle,
  AiTwotoneReconciliation,
  AiTwotoneRedEnvelope,
  AiTwotoneRest,
  AiTwotoneRightCircle,
  AiTwotoneRightSquare,
  AiTwotoneRocket,
  AiTwotoneSafetyCertificate,
  AiTwotoneSave,
  AiTwotoneSchedule,
  AiTwotoneSecurityScan,
  AiTwotoneSetting,
  AiTwotoneShop,
  AiTwotoneShopping,
  AiTwotoneSkin,
  AiTwotoneSliders,
  AiTwotoneSmile,
  AiTwotoneSnippets,
  AiTwotoneSound,
  AiTwotoneStar,
  AiTwotoneStop,
  AiTwotoneSwitcher,
  AiTwotoneTablet,
  AiTwotoneTag,
  AiTwotoneTags,
  AiTwotoneThunderbolt,
  AiTwotoneTool,
  AiTwotoneTrademarkCircle,
  AiTwotoneTrophy,
  AiTwotoneUnlock,
  AiTwotoneUpCircle,
  AiTwotoneUpSquare,
  AiTwotoneUsb,
  AiTwotoneVideoCamera,
  AiTwotoneWallet,
  AiTwotoneWarning
} from 'react-icons/ai'

export const availableIcons = {
  
"AiFillAccountBook": AiFillAccountBook,
"AiFillAlert": AiFillAlert,
"AiFillAlipayCircle": AiFillAlipayCircle,
"AiFillAlipaySquare": AiFillAlipaySquare,
"AiFillAliwangwang": AiFillAliwangwang,
"AiFillAmazonCircle": AiFillAmazonCircle,
"AiFillAmazonSquare": AiFillAmazonSquare,
"AiFillAndroid": AiFillAndroid,
"AiFillApi": AiFillApi,
"AiFillApple": AiFillApple,
"AiFillAppstore": AiFillAppstore,
"AiFillAudio": AiFillAudio,
"AiFillBackward": AiFillBackward,
"AiFillBank": AiFillBank,
"AiFillBehanceCircle": AiFillBehanceCircle,
"AiFillBehanceSquare": AiFillBehanceSquare,
"AiFillBell": AiFillBell,
"AiFillBook": AiFillBook,
"AiFillBoxPlot": AiFillBoxPlot,
"AiFillBug": AiFillBug,
"AiFillBuild": AiFillBuild,
"AiFillBulb": AiFillBulb,
"AiFillCalculator": AiFillCalculator,
"AiFillCalendar": AiFillCalendar,
"AiFillCamera": AiFillCamera,
"AiFillCar": AiFillCar,
"AiFillCaretDown": AiFillCaretDown,
"AiFillCaretLeft": AiFillCaretLeft,
"AiFillCaretRight": AiFillCaretRight,
"AiFillCaretUp": AiFillCaretUp,
"AiFillCarryOut": AiFillCarryOut,
"AiFillCheckCircle": AiFillCheckCircle,
"AiFillCheckSquare": AiFillCheckSquare,
"AiFillChrome": AiFillChrome,
"AiFillCiCircle": AiFillCiCircle,
"AiFillClockCircle": AiFillClockCircle,
"AiFillCloseCircle": AiFillCloseCircle,
"AiFillCloseSquare": AiFillCloseSquare,
"AiFillCloud": AiFillCloud,
"AiFillCodeSandboxCircle": AiFillCodeSandboxCircle,
"AiFillCodeSandboxSquare": AiFillCodeSandboxSquare,
"AiFillCode": AiFillCode,
"AiFillCodepenCircle": AiFillCodepenCircle,
"AiFillCodepenSquare": AiFillCodepenSquare,
"AiFillCompass": AiFillCompass,
"AiFillContacts": AiFillContacts,
"AiFillContainer": AiFillContainer,
"AiFillControl": AiFillControl,
"AiFillCopy": AiFillCopy,
"AiFillCopyrightCircle": AiFillCopyrightCircle,
"AiFillCreditCard": AiFillCreditCard,
"AiFillCrown": AiFillCrown,
"AiFillCustomerService": AiFillCustomerService,
"AiFillDashboard": AiFillDashboard,
"AiFillDatabase": AiFillDatabase,
"AiFillDelete": AiFillDelete,
"AiFillDiff": AiFillDiff,
"AiFillDingtalkCircle": AiFillDingtalkCircle,
"AiFillDingtalkSquare": AiFillDingtalkSquare,
"AiFillDislike": AiFillDislike,
"AiFillDollarCircle": AiFillDollarCircle,
"AiFillDownCircle": AiFillDownCircle,
"AiFillDownSquare": AiFillDownSquare,
"AiFillDribbbleCircle": AiFillDribbbleCircle,
"AiFillDribbbleSquare": AiFillDribbbleSquare,
"AiFillDropboxCircle": AiFillDropboxCircle,
"AiFillDropboxSquare": AiFillDropboxSquare,
"AiFillEdit": AiFillEdit,
"AiFillEnvironment": AiFillEnvironment,
"AiFillEuroCircle": AiFillEuroCircle,
"AiFillExclamationCircle": AiFillExclamationCircle,
"AiFillExperiment": AiFillExperiment,
"AiFillEyeInvisible": AiFillEyeInvisible,
"AiFillEye": AiFillEye,
"AiFillFacebook": AiFillFacebook,
"AiFillFastBackward": AiFillFastBackward,
"AiFillFastForward": AiFillFastForward,
"AiFillFileAdd": AiFillFileAdd,
"AiFillFileExcel": AiFillFileExcel,
"AiFillFileExclamation": AiFillFileExclamation,
"AiFillFileImage": AiFillFileImage,
"AiFillFileMarkdown": AiFillFileMarkdown,
"AiFillFilePdf": AiFillFilePdf,
"AiFillFilePpt": AiFillFilePpt,
"AiFillFileText": AiFillFileText,
"AiFillFileUnknown": AiFillFileUnknown,
"AiFillFileWord": AiFillFileWord,
"AiFillFileZip": AiFillFileZip,
"AiFillFile": AiFillFile,
"AiFillFilter": AiFillFilter,
"AiFillFire": AiFillFire,
"AiFillFlag": AiFillFlag,
"AiFillFolderAdd": AiFillFolderAdd,
"AiFillFolderOpen": AiFillFolderOpen,
"AiFillFolder": AiFillFolder,
"AiFillFormatPainter": AiFillFormatPainter,
"AiFillForward": AiFillForward,
"AiFillFrown": AiFillFrown,
"AiFillFund": AiFillFund,
"AiFillFunnelPlot": AiFillFunnelPlot,
"AiFillGift": AiFillGift,
"AiFillGithub": AiFillGithub,
"AiFillGitlab": AiFillGitlab,
"AiFillGold": AiFillGold,
"AiFillGolden": AiFillGolden,
"AiFillGoogleCircle": AiFillGoogleCircle,
"AiFillGooglePlusCircle": AiFillGooglePlusCircle,
"AiFillGooglePlusSquare": AiFillGooglePlusSquare,
"AiFillGoogleSquare": AiFillGoogleSquare,
"AiFillHdd": AiFillHdd,
"AiFillHeart": AiFillHeart,
"AiFillHighlight": AiFillHighlight,
"AiFillHome": AiFillHome,
"AiFillHourglass": AiFillHourglass,
"AiFillHtml5": AiFillHtml5,
"AiFillIdcard": AiFillIdcard,
"AiFillIeCircle": AiFillIeCircle,
"AiFillIeSquare": AiFillIeSquare,
"AiFillInfoCircle": AiFillInfoCircle,
"AiFillInstagram": AiFillInstagram,
"AiFillInsurance": AiFillInsurance,
"AiFillInteraction": AiFillInteraction,
"AiFillLayout": AiFillLayout,
"AiFillLeftCircle": AiFillLeftCircle,
"AiFillLeftSquare": AiFillLeftSquare,
"AiFillLike": AiFillLike,
"AiFillLinkedin": AiFillLinkedin,
"AiFillLock": AiFillLock,
"AiFillMacCommand": AiFillMacCommand,
"AiFillMail": AiFillMail,
"AiFillMedicineBox": AiFillMedicineBox,
"AiFillMediumCircle": AiFillMediumCircle,
"AiFillMediumSquare": AiFillMediumSquare,
"AiFillMeh": AiFillMeh,
"AiFillMessage": AiFillMessage,
"AiFillMinusCircle": AiFillMinusCircle,
"AiFillMinusSquare": AiFillMinusSquare,
"AiFillMobile": AiFillMobile,
"AiFillMoneyCollect": AiFillMoneyCollect,
"AiFillNotification": AiFillNotification,
"AiFillPauseCircle": AiFillPauseCircle,
"AiFillPayCircle": AiFillPayCircle,
"AiFillPhone": AiFillPhone,
"AiFillPicture": AiFillPicture,
"AiFillPieChart": AiFillPieChart,
"AiFillPlayCircle": AiFillPlayCircle,
"AiFillPlaySquare": AiFillPlaySquare,
"AiFillPlusCircle": AiFillPlusCircle,
"AiFillPlusSquare": AiFillPlusSquare,
"AiFillPoundCircle": AiFillPoundCircle,
"AiFillPrinter": AiFillPrinter,
"AiFillProfile": AiFillProfile,
"AiFillProject": AiFillProject,
"AiFillPropertySafety": AiFillPropertySafety,
"AiFillPushpin": AiFillPushpin,
"AiFillQqCircle": AiFillQqCircle,
"AiFillQqSquare": AiFillQqSquare,
"AiFillQuestionCircle": AiFillQuestionCircle,
"AiFillRead": AiFillRead,
"AiFillReconciliation": AiFillReconciliation,
"AiFillRedEnvelope": AiFillRedEnvelope,
"AiFillRedditCircle": AiFillRedditCircle,
"AiFillRedditSquare": AiFillRedditSquare,
"AiFillRest": AiFillRest,
"AiFillRightCircle": AiFillRightCircle,
"AiFillRightSquare": AiFillRightSquare,
"AiFillRobot": AiFillRobot,
"AiFillRocket": AiFillRocket,
"AiFillSafetyCertificate": AiFillSafetyCertificate,
"AiFillSave": AiFillSave,
"AiFillSchedule": AiFillSchedule,
"AiFillSecurityScan": AiFillSecurityScan,
"AiFillSetting": AiFillSetting,
"AiFillShop": AiFillShop,
"AiFillShopping": AiFillShopping,
"AiFillSignal": AiFillSignal,
"AiFillSketchCircle": AiFillSketchCircle,
"AiFillSketchSquare": AiFillSketchSquare,
"AiFillSkin": AiFillSkin,
"AiFillSkype": AiFillSkype,
"AiFillSlackCircle": AiFillSlackCircle,
"AiFillSlackSquare": AiFillSlackSquare,
"AiFillSliders": AiFillSliders,
"AiFillSmile": AiFillSmile,
"AiFillSnippets": AiFillSnippets,
"AiFillSound": AiFillSound,
"AiFillStar": AiFillStar,
"AiFillStepBackward": AiFillStepBackward,
"AiFillStepForward": AiFillStepForward,
"AiFillStop": AiFillStop,
"AiFillSwitcher": AiFillSwitcher,
"AiFillTablet": AiFillTablet,
"AiFillTag": AiFillTag,
"AiFillTags": AiFillTags,
"AiFillTaobaoCircle": AiFillTaobaoCircle,
"AiFillTaobaoSquare": AiFillTaobaoSquare,
"AiFillThunderbolt": AiFillThunderbolt,
"AiFillTool": AiFillTool,
"AiFillTrademarkCircle": AiFillTrademarkCircle,
"AiFillTrophy": AiFillTrophy,
"AiFillTwitterCircle": AiFillTwitterCircle,
"AiFillTwitterSquare": AiFillTwitterSquare,
"AiFillUnlock": AiFillUnlock,
"AiFillUpCircle": AiFillUpCircle,
"AiFillUpSquare": AiFillUpSquare,
"AiFillUsb": AiFillUsb,
"AiFillVideoCamera": AiFillVideoCamera,
"AiFillWallet": AiFillWallet,
"AiFillWarning": AiFillWarning,
"AiFillWechat": AiFillWechat,
"AiFillWeiboCircle": AiFillWeiboCircle,
"AiFillWeiboSquare": AiFillWeiboSquare,
"AiFillWindows": AiFillWindows,
"AiFillYahoo": AiFillYahoo,
"AiFillYoutube": AiFillYoutube,
"AiFillYuque": AiFillYuque,
"AiFillZhihuCircle": AiFillZhihuCircle,
"AiFillZhihuSquare": AiFillZhihuSquare,
"AiOutlineAccountBook": AiOutlineAccountBook,
"AiOutlineAim": AiOutlineAim,
"AiOutlineAlert": AiOutlineAlert,
"AiOutlineAlibaba": AiOutlineAlibaba,
"AiOutlineAlignCenter": AiOutlineAlignCenter,
"AiOutlineAlignLeft": AiOutlineAlignLeft,
"AiOutlineAlignRight": AiOutlineAlignRight,
"AiOutlineAlipayCircle": AiOutlineAlipayCircle,
"AiOutlineAlipay": AiOutlineAlipay,
"AiOutlineAliwangwang": AiOutlineAliwangwang,
"AiOutlineAliyun": AiOutlineAliyun,
"AiOutlineAmazon": AiOutlineAmazon,
"AiOutlineAndroid": AiOutlineAndroid,
"AiOutlineAntCloud": AiOutlineAntCloud,
"AiOutlineAntDesign": AiOutlineAntDesign,
"AiOutlineApartment": AiOutlineApartment,
"AiOutlineApi": AiOutlineApi,
"AiOutlineApple": AiOutlineApple,
"AiOutlineAppstoreAdd": AiOutlineAppstoreAdd,
"AiOutlineAppstore": AiOutlineAppstore,
"AiOutlineAreaChart": AiOutlineAreaChart,
"AiOutlineArrowDown": AiOutlineArrowDown,
"AiOutlineArrowLeft": AiOutlineArrowLeft,
"AiOutlineArrowRight": AiOutlineArrowRight,
"AiOutlineArrowUp": AiOutlineArrowUp,
"AiOutlineArrowsAlt": AiOutlineArrowsAlt,
"AiOutlineAudioMuted": AiOutlineAudioMuted,
"AiOutlineAudio": AiOutlineAudio,
"AiOutlineAudit": AiOutlineAudit,
"AiOutlineBackward": AiOutlineBackward,
"AiOutlineBank": AiOutlineBank,
"AiOutlineBarChart": AiOutlineBarChart,
"AiOutlineBarcode": AiOutlineBarcode,
"AiOutlineBars": AiOutlineBars,
"AiOutlineBehanceSquare": AiOutlineBehanceSquare,
"AiOutlineBehance": AiOutlineBehance,
"AiOutlineBell": AiOutlineBell,
"AiOutlineBgColors": AiOutlineBgColors,
"AiOutlineBlock": AiOutlineBlock,
"AiOutlineBold": AiOutlineBold,
"AiOutlineBook": AiOutlineBook,
"AiOutlineBorderBottom": AiOutlineBorderBottom,
"AiOutlineBorderHorizontal": AiOutlineBorderHorizontal,
"AiOutlineBorderInner": AiOutlineBorderInner,
"AiOutlineBorderLeft": AiOutlineBorderLeft,
"AiOutlineBorderOuter": AiOutlineBorderOuter,
"AiOutlineBorderRight": AiOutlineBorderRight,
"AiOutlineBorderTop": AiOutlineBorderTop,
"AiOutlineBorderVerticle": AiOutlineBorderVerticle,
"AiOutlineBorder": AiOutlineBorder,
"AiOutlineBorderlessTable": AiOutlineBorderlessTable,
"AiOutlineBoxPlot": AiOutlineBoxPlot,
"AiOutlineBranches": AiOutlineBranches,
"AiOutlineBug": AiOutlineBug,
"AiOutlineBuild": AiOutlineBuild,
"AiOutlineBulb": AiOutlineBulb,
"AiOutlineCalculator": AiOutlineCalculator,
"AiOutlineCalendar": AiOutlineCalendar,
"AiOutlineCamera": AiOutlineCamera,
"AiOutlineCar": AiOutlineCar,
"AiOutlineCaretDown": AiOutlineCaretDown,
"AiOutlineCaretLeft": AiOutlineCaretLeft,
"AiOutlineCaretRight": AiOutlineCaretRight,
"AiOutlineCaretUp": AiOutlineCaretUp,
"AiOutlineCarryOut": AiOutlineCarryOut,
"AiOutlineCheckCircle": AiOutlineCheckCircle,
"AiOutlineCheckSquare": AiOutlineCheckSquare,
"AiOutlineCheck": AiOutlineCheck,
"AiOutlineChrome": AiOutlineChrome,
"AiOutlineCiCircle": AiOutlineCiCircle,
"AiOutlineCi": AiOutlineCi,
"AiOutlineClear": AiOutlineClear,
"AiOutlineClockCircle": AiOutlineClockCircle,
"AiOutlineCloseCircle": AiOutlineCloseCircle,
"AiOutlineCloseSquare": AiOutlineCloseSquare,
"AiOutlineClose": AiOutlineClose,
"AiOutlineCloudDownload": AiOutlineCloudDownload,
"AiOutlineCloudServer": AiOutlineCloudServer,
"AiOutlineCloudSync": AiOutlineCloudSync,
"AiOutlineCloudUpload": AiOutlineCloudUpload,
"AiOutlineCloud": AiOutlineCloud,
"AiOutlineCluster": AiOutlineCluster,
"AiOutlineCodeSandbox": AiOutlineCodeSandbox,
"AiOutlineCode": AiOutlineCode,
"AiOutlineCodepenCircle": AiOutlineCodepenCircle,
"AiOutlineCodepen": AiOutlineCodepen,
"AiOutlineCoffee": AiOutlineCoffee,
"AiOutlineColumnHeight": AiOutlineColumnHeight,
"AiOutlineColumnWidth": AiOutlineColumnWidth,
"AiOutlineComment": AiOutlineComment,
"AiOutlineCompass": AiOutlineCompass,
"AiOutlineCompress": AiOutlineCompress,
"AiOutlineConsoleSql": AiOutlineConsoleSql,
"AiOutlineContacts": AiOutlineContacts,
"AiOutlineContainer": AiOutlineContainer,
"AiOutlineControl": AiOutlineControl,
"AiOutlineCopy": AiOutlineCopy,
"AiOutlineCopyrightCircle": AiOutlineCopyrightCircle,
"AiOutlineCopyright": AiOutlineCopyright,
"AiOutlineCreditCard": AiOutlineCreditCard,
"AiOutlineCrown": AiOutlineCrown,
"AiOutlineCustomerService": AiOutlineCustomerService,
"AiOutlineDash": AiOutlineDash,
"AiOutlineDashboard": AiOutlineDashboard,
"AiOutlineDatabase": AiOutlineDatabase,
"AiOutlineDeleteColumn": AiOutlineDeleteColumn,
"AiOutlineDeleteRow": AiOutlineDeleteRow,
"AiOutlineDelete": AiOutlineDelete,
"AiOutlineDeliveredProcedure": AiOutlineDeliveredProcedure,
"AiOutlineDeploymentUnit": AiOutlineDeploymentUnit,
"AiOutlineDesktop": AiOutlineDesktop,
"AiOutlineDiff": AiOutlineDiff,
"AiOutlineDingding": AiOutlineDingding,
"AiOutlineDingtalk": AiOutlineDingtalk,
"AiOutlineDisconnect": AiOutlineDisconnect,
"AiOutlineDislike": AiOutlineDislike,
"AiOutlineDollarCircle": AiOutlineDollarCircle,
"AiOutlineDollar": AiOutlineDollar,
"AiOutlineDotChart": AiOutlineDotChart,
"AiOutlineDoubleLeft": AiOutlineDoubleLeft,
"AiOutlineDoubleRight": AiOutlineDoubleRight,
"AiOutlineDownCircle": AiOutlineDownCircle,
"AiOutlineDownSquare": AiOutlineDownSquare,
"AiOutlineDown": AiOutlineDown,
"AiOutlineDownload": AiOutlineDownload,
"AiOutlineDrag": AiOutlineDrag,
"AiOutlineDribbbleSquare": AiOutlineDribbbleSquare,
"AiOutlineDribbble": AiOutlineDribbble,
"AiOutlineDropbox": AiOutlineDropbox,
"AiOutlineEdit": AiOutlineEdit,
"AiOutlineEllipsis": AiOutlineEllipsis,
"AiOutlineEnter": AiOutlineEnter,
"AiOutlineEnvironment": AiOutlineEnvironment,
"AiOutlineEuroCircle": AiOutlineEuroCircle,
"AiOutlineEuro": AiOutlineEuro,
"AiOutlineException": AiOutlineException,
"AiOutlineExclamationCircle": AiOutlineExclamationCircle,
"AiOutlineExclamation": AiOutlineExclamation,
"AiOutlineExpandAlt": AiOutlineExpandAlt,
"AiOutlineExpand": AiOutlineExpand,
"AiOutlineExperiment": AiOutlineExperiment,
"AiOutlineExport": AiOutlineExport,
"AiOutlineEyeInvisible": AiOutlineEyeInvisible,
"AiOutlineEye": AiOutlineEye,
"AiOutlineFacebook": AiOutlineFacebook,
"AiOutlineFall": AiOutlineFall,
"AiOutlineFastBackward": AiOutlineFastBackward,
"AiOutlineFastForward": AiOutlineFastForward,
"AiOutlineFieldBinary": AiOutlineFieldBinary,
"AiOutlineFieldNumber": AiOutlineFieldNumber,
"AiOutlineFieldString": AiOutlineFieldString,
"AiOutlineFieldTime": AiOutlineFieldTime,
"AiOutlineFileAdd": AiOutlineFileAdd,
"AiOutlineFileDone": AiOutlineFileDone,
"AiOutlineFileExcel": AiOutlineFileExcel,
"AiOutlineFileExclamation": AiOutlineFileExclamation,
"AiOutlineFileGif": AiOutlineFileGif,
"AiOutlineFileImage": AiOutlineFileImage,
"AiOutlineFileJpg": AiOutlineFileJpg,
"AiOutlineFileMarkdown": AiOutlineFileMarkdown,
"AiOutlineFilePdf": AiOutlineFilePdf,
"AiOutlineFilePpt": AiOutlineFilePpt,
"AiOutlineFileProtect": AiOutlineFileProtect,
"AiOutlineFileSearch": AiOutlineFileSearch,
"AiOutlineFileSync": AiOutlineFileSync,
"AiOutlineFileText": AiOutlineFileText,
"AiOutlineFileUnknown": AiOutlineFileUnknown,
"AiOutlineFileWord": AiOutlineFileWord,
"AiOutlineFileZip": AiOutlineFileZip,
"AiOutlineFile": AiOutlineFile,
"AiOutlineFilter": AiOutlineFilter,
"AiOutlineFire": AiOutlineFire,
"AiOutlineFlag": AiOutlineFlag,
"AiOutlineFolderAdd": AiOutlineFolderAdd,
"AiOutlineFolderOpen": AiOutlineFolderOpen,
"AiOutlineFolderView": AiOutlineFolderView,
"AiOutlineFolder": AiOutlineFolder,
"AiOutlineFontColors": AiOutlineFontColors,
"AiOutlineFontSize": AiOutlineFontSize,
"AiOutlineFork": AiOutlineFork,
"AiOutlineForm": AiOutlineForm,
"AiOutlineFormatPainter": AiOutlineFormatPainter,
"AiOutlineForward": AiOutlineForward,
"AiOutlineFrown": AiOutlineFrown,
"AiOutlineFullscreenExit": AiOutlineFullscreenExit,
"AiOutlineFullscreen": AiOutlineFullscreen,
"AiOutlineFunction": AiOutlineFunction,
"AiOutlineFundProjectionScreen": AiOutlineFundProjectionScreen,
"AiOutlineFundView": AiOutlineFundView,
"AiOutlineFund": AiOutlineFund,
"AiOutlineFunnelPlot": AiOutlineFunnelPlot,
"AiOutlineGateway": AiOutlineGateway,
"AiOutlineGif": AiOutlineGif,
"AiOutlineGift": AiOutlineGift,
"AiOutlineGithub": AiOutlineGithub,
"AiOutlineGitlab": AiOutlineGitlab,
"AiOutlineGlobal": AiOutlineGlobal,
"AiOutlineGold": AiOutlineGold,
"AiOutlineGooglePlus": AiOutlineGooglePlus,
"AiOutlineGoogle": AiOutlineGoogle,
"AiOutlineGroup": AiOutlineGroup,
"AiOutlineHdd": AiOutlineHdd,
"AiOutlineHeart": AiOutlineHeart,
"AiOutlineHeatMap": AiOutlineHeatMap,
"AiOutlineHighlight": AiOutlineHighlight,
"AiOutlineHistory": AiOutlineHistory,
"AiOutlineHolder": AiOutlineHolder,
"AiOutlineHome": AiOutlineHome,
"AiOutlineHourglass": AiOutlineHourglass,
"AiOutlineHtml5": AiOutlineHtml5,
"AiOutlineIdcard": AiOutlineIdcard,
"AiOutlineIe": AiOutlineIe,
"AiOutlineImport": AiOutlineImport,
"AiOutlineInbox": AiOutlineInbox,
"AiOutlineInfoCircle": AiOutlineInfoCircle,
"AiOutlineInfo": AiOutlineInfo,
"AiOutlineInsertRowAbove": AiOutlineInsertRowAbove,
"AiOutlineInsertRowBelow": AiOutlineInsertRowBelow,
"AiOutlineInsertRowLeft": AiOutlineInsertRowLeft,
"AiOutlineInsertRowRight": AiOutlineInsertRowRight,
"AiOutlineInstagram": AiOutlineInstagram,
"AiOutlineInsurance": AiOutlineInsurance,
"AiOutlineInteraction": AiOutlineInteraction,
"AiOutlineIssuesClose": AiOutlineIssuesClose,
"AiOutlineItalic": AiOutlineItalic,
"AiOutlineKey": AiOutlineKey,
"AiOutlineLaptop": AiOutlineLaptop,
"AiOutlineLayout": AiOutlineLayout,
"AiOutlineLeftCircle": AiOutlineLeftCircle,
"AiOutlineLeftSquare": AiOutlineLeftSquare,
"AiOutlineLeft": AiOutlineLeft,
"AiOutlineLike": AiOutlineLike,
"AiOutlineLineChart": AiOutlineLineChart,
"AiOutlineLineHeight": AiOutlineLineHeight,
"AiOutlineLine": AiOutlineLine,
"AiOutlineLink": AiOutlineLink,
"AiOutlineLinkedin": AiOutlineLinkedin,
"AiOutlineLoading3Quarters": AiOutlineLoading3Quarters,
"AiOutlineLoading": AiOutlineLoading,
"AiOutlineLock": AiOutlineLock,
"AiOutlineLogin": AiOutlineLogin,
"AiOutlineLogout": AiOutlineLogout,
"AiOutlineMacCommand": AiOutlineMacCommand,
"AiOutlineMail": AiOutlineMail,
"AiOutlineMan": AiOutlineMan,
"AiOutlineMedicineBox": AiOutlineMedicineBox,
"AiOutlineMediumWorkmark": AiOutlineMediumWorkmark,
"AiOutlineMedium": AiOutlineMedium,
"AiOutlineMeh": AiOutlineMeh,
"AiOutlineMenuFold": AiOutlineMenuFold,
"AiOutlineMenuUnfold": AiOutlineMenuUnfold,
"AiOutlineMenu": AiOutlineMenu,
"AiOutlineMergeCells": AiOutlineMergeCells,
"AiOutlineMessage": AiOutlineMessage,
"AiOutlineMinusCircle": AiOutlineMinusCircle,
"AiOutlineMinusSquare": AiOutlineMinusSquare,
"AiOutlineMinus": AiOutlineMinus,
"AiOutlineMobile": AiOutlineMobile,
"AiOutlineMoneyCollect": AiOutlineMoneyCollect,
"AiOutlineMonitor": AiOutlineMonitor,
"AiOutlineMore": AiOutlineMore,
"AiOutlineNodeCollapse": AiOutlineNodeCollapse,
"AiOutlineNodeExpand": AiOutlineNodeExpand,
"AiOutlineNodeIndex": AiOutlineNodeIndex,
"AiOutlineNotification": AiOutlineNotification,
"AiOutlineNumber": AiOutlineNumber,
"AiOutlineOneToOne": AiOutlineOneToOne,
"AiOutlineOrderedList": AiOutlineOrderedList,
"AiOutlinePaperClip": AiOutlinePaperClip,
"AiOutlinePartition": AiOutlinePartition,
"AiOutlinePauseCircle": AiOutlinePauseCircle,
"AiOutlinePause": AiOutlinePause,
"AiOutlinePayCircle": AiOutlinePayCircle,
"AiOutlinePercentage": AiOutlinePercentage,
"AiOutlinePhone": AiOutlinePhone,
"AiOutlinePicCenter": AiOutlinePicCenter,
"AiOutlinePicLeft": AiOutlinePicLeft,
"AiOutlinePicRight": AiOutlinePicRight,
"AiOutlinePicture": AiOutlinePicture,
"AiOutlinePieChart": AiOutlinePieChart,
"AiOutlinePlayCircle": AiOutlinePlayCircle,
"AiOutlinePlaySquare": AiOutlinePlaySquare,
"AiOutlinePlusCircle": AiOutlinePlusCircle,
"AiOutlinePlusSquare": AiOutlinePlusSquare,
"AiOutlinePlus": AiOutlinePlus,
"AiOutlinePoundCircle": AiOutlinePoundCircle,
"AiOutlinePound": AiOutlinePound,
"AiOutlinePoweroff": AiOutlinePoweroff,
"AiOutlinePrinter": AiOutlinePrinter,
"AiOutlineProfile": AiOutlineProfile,
"AiOutlineProject": AiOutlineProject,
"AiOutlinePropertySafety": AiOutlinePropertySafety,
"AiOutlinePullRequest": AiOutlinePullRequest,
"AiOutlinePushpin": AiOutlinePushpin,
"AiOutlineQq": AiOutlineQq,
"AiOutlineQrcode": AiOutlineQrcode,
"AiOutlineQuestionCircle": AiOutlineQuestionCircle,
"AiOutlineQuestion": AiOutlineQuestion,
"AiOutlineRadarChart": AiOutlineRadarChart,
"AiOutlineRadiusBottomleft": AiOutlineRadiusBottomleft,
"AiOutlineRadiusBottomright": AiOutlineRadiusBottomright,
"AiOutlineRadiusSetting": AiOutlineRadiusSetting,
"AiOutlineRadiusUpleft": AiOutlineRadiusUpleft,
"AiOutlineRadiusUpright": AiOutlineRadiusUpright,
"AiOutlineRead": AiOutlineRead,
"AiOutlineReconciliation": AiOutlineReconciliation,
"AiOutlineRedEnvelope": AiOutlineRedEnvelope,
"AiOutlineReddit": AiOutlineReddit,
"AiOutlineRedo": AiOutlineRedo,
"AiOutlineReload": AiOutlineReload,
"AiOutlineRest": AiOutlineRest,
"AiOutlineRetweet": AiOutlineRetweet,
"AiOutlineRightCircle": AiOutlineRightCircle,
"AiOutlineRightSquare": AiOutlineRightSquare,
"AiOutlineRight": AiOutlineRight,
"AiOutlineRise": AiOutlineRise,
"AiOutlineRobot": AiOutlineRobot,
"AiOutlineRocket": AiOutlineRocket,
"AiOutlineRollback": AiOutlineRollback,
"AiOutlineRotateLeft": AiOutlineRotateLeft,
"AiOutlineRotateRight": AiOutlineRotateRight,
"AiOutlineSafetyCertificate": AiOutlineSafetyCertificate,
"AiOutlineSafety": AiOutlineSafety,
"AiOutlineSave": AiOutlineSave,
"AiOutlineScan": AiOutlineScan,
"AiOutlineSchedule": AiOutlineSchedule,
"AiOutlineScissor": AiOutlineScissor,
"AiOutlineSearch": AiOutlineSearch,
"AiOutlineSecurityScan": AiOutlineSecurityScan,
"AiOutlineSelect": AiOutlineSelect,
"AiOutlineSend": AiOutlineSend,
"AiOutlineSetting": AiOutlineSetting,
"AiOutlineShake": AiOutlineShake,
"AiOutlineShareAlt": AiOutlineShareAlt,
"AiOutlineShop": AiOutlineShop,
"AiOutlineShoppingCart": AiOutlineShoppingCart,
"AiOutlineShopping": AiOutlineShopping,
"AiOutlineShrink": AiOutlineShrink,
"AiOutlineSisternode": AiOutlineSisternode,
"AiOutlineSketch": AiOutlineSketch,
"AiOutlineSkin": AiOutlineSkin,
"AiOutlineSkype": AiOutlineSkype,
"AiOutlineSlackSquare": AiOutlineSlackSquare,
"AiOutlineSlack": AiOutlineSlack,
"AiOutlineSliders": AiOutlineSliders,
"AiOutlineSmallDash": AiOutlineSmallDash,
"AiOutlineSmile": AiOutlineSmile,
"AiOutlineSnippets": AiOutlineSnippets,
"AiOutlineSolution": AiOutlineSolution,
"AiOutlineSortAscending": AiOutlineSortAscending,
"AiOutlineSortDescending": AiOutlineSortDescending,
"AiOutlineSound": AiOutlineSound,
"AiOutlineSplitCells": AiOutlineSplitCells,
"AiOutlineStar": AiOutlineStar,
"AiOutlineStepBackward": AiOutlineStepBackward,
"AiOutlineStepForward": AiOutlineStepForward,
"AiOutlineStock": AiOutlineStock,
"AiOutlineStop": AiOutlineStop,
"AiOutlineStrikethrough": AiOutlineStrikethrough,
"AiOutlineSubnode": AiOutlineSubnode,
"AiOutlineSwapLeft": AiOutlineSwapLeft,
"AiOutlineSwapRight": AiOutlineSwapRight,
"AiOutlineSwap": AiOutlineSwap,
"AiOutlineSwitcher": AiOutlineSwitcher,
"AiOutlineSync": AiOutlineSync,
"AiOutlineTable": AiOutlineTable,
"AiOutlineTablet": AiOutlineTablet,
"AiOutlineTag": AiOutlineTag,
"AiOutlineTags": AiOutlineTags,
"AiOutlineTaobaoCircle": AiOutlineTaobaoCircle,
"AiOutlineTaobao": AiOutlineTaobao,
"AiOutlineTeam": AiOutlineTeam,
"AiOutlineThunderbolt": AiOutlineThunderbolt,
"AiOutlineToTop": AiOutlineToTop,
"AiOutlineTool": AiOutlineTool,
"AiOutlineTrademarkCircle": AiOutlineTrademarkCircle,
"AiOutlineTrademark": AiOutlineTrademark,
"AiOutlineTransaction": AiOutlineTransaction,
"AiOutlineTranslation": AiOutlineTranslation,
"AiOutlineTrophy": AiOutlineTrophy,
"AiOutlineTwitter": AiOutlineTwitter,
"AiOutlineUnderline": AiOutlineUnderline,
"AiOutlineUndo": AiOutlineUndo,
"AiOutlineUngroup": AiOutlineUngroup,
"AiOutlineUnlock": AiOutlineUnlock,
"AiOutlineUnorderedList": AiOutlineUnorderedList,
"AiOutlineUpCircle": AiOutlineUpCircle,
"AiOutlineUpSquare": AiOutlineUpSquare,
"AiOutlineUp": AiOutlineUp,
"AiOutlineUpload": AiOutlineUpload,
"AiOutlineUsb": AiOutlineUsb,
"AiOutlineUserAdd": AiOutlineUserAdd,
"AiOutlineUserDelete": AiOutlineUserDelete,
"AiOutlineUserSwitch": AiOutlineUserSwitch,
"AiOutlineUser": AiOutlineUser,
"AiOutlineUsergroupAdd": AiOutlineUsergroupAdd,
"AiOutlineUsergroupDelete": AiOutlineUsergroupDelete,
"AiOutlineVerified": AiOutlineVerified,
"AiOutlineVerticalAlignBottom": AiOutlineVerticalAlignBottom,
"AiOutlineVerticalAlignMiddle": AiOutlineVerticalAlignMiddle,
"AiOutlineVerticalAlignTop": AiOutlineVerticalAlignTop,
"AiOutlineVerticalLeft": AiOutlineVerticalLeft,
"AiOutlineVerticalRight": AiOutlineVerticalRight,
"AiOutlineVideoCameraAdd": AiOutlineVideoCameraAdd,
"AiOutlineVideoCamera": AiOutlineVideoCamera,
"AiOutlineWallet": AiOutlineWallet,
"AiOutlineWarning": AiOutlineWarning,
"AiOutlineWechat": AiOutlineWechat,
"AiOutlineWeiboCircle": AiOutlineWeiboCircle,
"AiOutlineWeiboSquare": AiOutlineWeiboSquare,
"AiOutlineWeibo": AiOutlineWeibo,
"AiOutlineWhatsApp": AiOutlineWhatsApp,
"AiOutlineWifi": AiOutlineWifi,
"AiOutlineWindows": AiOutlineWindows,
"AiOutlineWoman": AiOutlineWoman,
"AiOutlineYahoo": AiOutlineYahoo,
"AiOutlineYoutube": AiOutlineYoutube,
"AiOutlineYuque": AiOutlineYuque,
"AiOutlineZhihu": AiOutlineZhihu,
"AiOutlineZoomIn": AiOutlineZoomIn,
"AiOutlineZoomOut": AiOutlineZoomOut,
"AiTwotoneAccountBook": AiTwotoneAccountBook,
"AiTwotoneAlert": AiTwotoneAlert,
"AiTwotoneApi": AiTwotoneApi,
"AiTwotoneAppstore": AiTwotoneAppstore,
"AiTwotoneAudio": AiTwotoneAudio,
"AiTwotoneBank": AiTwotoneBank,
"AiTwotoneBell": AiTwotoneBell,
"AiTwotoneBook": AiTwotoneBook,
"AiTwotoneBoxPlot": AiTwotoneBoxPlot,
"AiTwotoneBug": AiTwotoneBug,
"AiTwotoneBuild": AiTwotoneBuild,
"AiTwotoneBulb": AiTwotoneBulb,
"AiTwotoneCalculator": AiTwotoneCalculator,
"AiTwotoneCalendar": AiTwotoneCalendar,
"AiTwotoneCamera": AiTwotoneCamera,
"AiTwotoneCar": AiTwotoneCar,
"AiTwotoneCarryOut": AiTwotoneCarryOut,
"AiTwotoneCheckCircle": AiTwotoneCheckCircle,
"AiTwotoneCheckSquare": AiTwotoneCheckSquare,
"AiTwotoneCiCircle": AiTwotoneCiCircle,
"AiTwotoneCi": AiTwotoneCi,
"AiTwotoneClockCircle": AiTwotoneClockCircle,
"AiTwotoneCloseCircle": AiTwotoneCloseCircle,
"AiTwotoneCloseSquare": AiTwotoneCloseSquare,
"AiTwotoneCloud": AiTwotoneCloud,
"AiTwotoneCode": AiTwotoneCode,
"AiTwotoneCompass": AiTwotoneCompass,
"AiTwotoneContacts": AiTwotoneContacts,
"AiTwotoneContainer": AiTwotoneContainer,
"AiTwotoneControl": AiTwotoneControl,
"AiTwotoneCopy": AiTwotoneCopy,
"AiTwotoneCopyrightCircle": AiTwotoneCopyrightCircle,
"AiTwotoneCopyright": AiTwotoneCopyright,
"AiTwotoneCreditCard": AiTwotoneCreditCard,
"AiTwotoneCrown": AiTwotoneCrown,
"AiTwotoneCustomerService": AiTwotoneCustomerService,
"AiTwotoneDashboard": AiTwotoneDashboard,
"AiTwotoneDatabase": AiTwotoneDatabase,
"AiTwotoneDelete": AiTwotoneDelete,
"AiTwotoneDiff": AiTwotoneDiff,
"AiTwotoneDislike": AiTwotoneDislike,
"AiTwotoneDollarCircle": AiTwotoneDollarCircle,
"AiTwotoneDollar": AiTwotoneDollar,
"AiTwotoneDownCircle": AiTwotoneDownCircle,
"AiTwotoneDownSquare": AiTwotoneDownSquare,
"AiTwotoneEdit": AiTwotoneEdit,
"AiTwotoneEnvironment": AiTwotoneEnvironment,
"AiTwotoneEuroCircle": AiTwotoneEuroCircle,
"AiTwotoneEuro": AiTwotoneEuro,
"AiTwotoneExclamationCircle": AiTwotoneExclamationCircle,
"AiTwotoneExperiment": AiTwotoneExperiment,
"AiTwotoneEyeInvisible": AiTwotoneEyeInvisible,
"AiTwotoneEye": AiTwotoneEye,
"AiTwotoneFileAdd": AiTwotoneFileAdd,
"AiTwotoneFileExcel": AiTwotoneFileExcel,
"AiTwotoneFileExclamation": AiTwotoneFileExclamation,
"AiTwotoneFileImage": AiTwotoneFileImage,
"AiTwotoneFileMarkdown": AiTwotoneFileMarkdown,
"AiTwotoneFilePdf": AiTwotoneFilePdf,
"AiTwotoneFilePpt": AiTwotoneFilePpt,
"AiTwotoneFileText": AiTwotoneFileText,
"AiTwotoneFileUnknown": AiTwotoneFileUnknown,
"AiTwotoneFileWord": AiTwotoneFileWord,
"AiTwotoneFileZip": AiTwotoneFileZip,
"AiTwotoneFile": AiTwotoneFile,
"AiTwotoneFilter": AiTwotoneFilter,
"AiTwotoneFire": AiTwotoneFire,
"AiTwotoneFlag": AiTwotoneFlag,
"AiTwotoneFolderAdd": AiTwotoneFolderAdd,
"AiTwotoneFolderOpen": AiTwotoneFolderOpen,
"AiTwotoneFolder": AiTwotoneFolder,
"AiTwotoneFrown": AiTwotoneFrown,
"AiTwotoneFund": AiTwotoneFund,
"AiTwotoneFunnelPlot": AiTwotoneFunnelPlot,
"AiTwotoneGift": AiTwotoneGift,
"AiTwotoneGold": AiTwotoneGold,
"AiTwotoneHdd": AiTwotoneHdd,
"AiTwotoneHeart": AiTwotoneHeart,
"AiTwotoneHighlight": AiTwotoneHighlight,
"AiTwotoneHome": AiTwotoneHome,
"AiTwotoneHourglass": AiTwotoneHourglass,
"AiTwotoneHtml5": AiTwotoneHtml5,
"AiTwotoneIdcard": AiTwotoneIdcard,
"AiTwotoneInfoCircle": AiTwotoneInfoCircle,
"AiTwotoneInsurance": AiTwotoneInsurance,
"AiTwotoneInteraction": AiTwotoneInteraction,
"AiTwotoneLayout": AiTwotoneLayout,
"AiTwotoneLeftCircle": AiTwotoneLeftCircle,
"AiTwotoneLeftSquare": AiTwotoneLeftSquare,
"AiTwotoneLike": AiTwotoneLike,
"AiTwotoneLock": AiTwotoneLock,
"AiTwotoneMail": AiTwotoneMail,
"AiTwotoneMedicineBox": AiTwotoneMedicineBox,
"AiTwotoneMeh": AiTwotoneMeh,
"AiTwotoneMessage": AiTwotoneMessage,
"AiTwotoneMinusCircle": AiTwotoneMinusCircle,
"AiTwotoneMinusSquare": AiTwotoneMinusSquare,
"AiTwotoneMobile": AiTwotoneMobile,
"AiTwotoneMoneyCollect": AiTwotoneMoneyCollect,
"AiTwotoneNotification": AiTwotoneNotification,
"AiTwotonePauseCircle": AiTwotonePauseCircle,
"AiTwotonePhone": AiTwotonePhone,
"AiTwotonePicture": AiTwotonePicture,
"AiTwotonePieChart": AiTwotonePieChart,
"AiTwotonePlayCircle": AiTwotonePlayCircle,
"AiTwotonePlaySquare": AiTwotonePlaySquare,
"AiTwotonePlusCircle": AiTwotonePlusCircle,
"AiTwotonePlusSquare": AiTwotonePlusSquare,
"AiTwotonePoundCircle": AiTwotonePoundCircle,
"AiTwotonePrinter": AiTwotonePrinter,
"AiTwotoneProfile": AiTwotoneProfile,
"AiTwotoneProject": AiTwotoneProject,
"AiTwotonePropertySafety": AiTwotonePropertySafety,
"AiTwotonePushpin": AiTwotonePushpin,
"AiTwotoneQuestionCircle": AiTwotoneQuestionCircle,
"AiTwotoneReconciliation": AiTwotoneReconciliation,
"AiTwotoneRedEnvelope": AiTwotoneRedEnvelope,
"AiTwotoneRest": AiTwotoneRest,
"AiTwotoneRightCircle": AiTwotoneRightCircle,
"AiTwotoneRightSquare": AiTwotoneRightSquare,
"AiTwotoneRocket": AiTwotoneRocket,
"AiTwotoneSafetyCertificate": AiTwotoneSafetyCertificate,
"AiTwotoneSave": AiTwotoneSave,
"AiTwotoneSchedule": AiTwotoneSchedule,
"AiTwotoneSecurityScan": AiTwotoneSecurityScan,
"AiTwotoneSetting": AiTwotoneSetting,
"AiTwotoneShop": AiTwotoneShop,
"AiTwotoneShopping": AiTwotoneShopping,
"AiTwotoneSkin": AiTwotoneSkin,
"AiTwotoneSliders": AiTwotoneSliders,
"AiTwotoneSmile": AiTwotoneSmile,
"AiTwotoneSnippets": AiTwotoneSnippets,
"AiTwotoneSound": AiTwotoneSound,
"AiTwotoneStar": AiTwotoneStar,
"AiTwotoneStop": AiTwotoneStop,
"AiTwotoneSwitcher": AiTwotoneSwitcher,
"AiTwotoneTablet": AiTwotoneTablet,
"AiTwotoneTag": AiTwotoneTag,
"AiTwotoneTags": AiTwotoneTags,
"AiTwotoneThunderbolt": AiTwotoneThunderbolt,
"AiTwotoneTool": AiTwotoneTool,
"AiTwotoneTrademarkCircle": AiTwotoneTrademarkCircle,
"AiTwotoneTrophy": AiTwotoneTrophy,
"AiTwotoneUnlock": AiTwotoneUnlock,
"AiTwotoneUpCircle": AiTwotoneUpCircle,
"AiTwotoneUpSquare": AiTwotoneUpSquare,
"AiTwotoneUsb": AiTwotoneUsb,
"AiTwotoneVideoCamera": AiTwotoneVideoCamera,
"AiTwotoneWallet": AiTwotoneWallet,
"AiTwotoneWarning": AiTwotoneWarning
 
};

export const iconNames = Object.keys(availableIcons);
const IconSvg = styled(({ spacing, icon, width, height, color, className, onClick }) => {
  const Icon = availableIcons[icon];

  if(!Icon){
    throw `Missing icon named: "${icon}", please check your version of ui-components`;
  }

  return <Icon onClick={onClick} spacing={spacing} width={width} color={color} className={className} />;
})`
  ${useSpacingProps}
  ${color}

  ${({ width, height }) =>
    width &&
    `
      width: ${width};
      height: ${height};
    `}
`;

IconSvg.propTypes = {
  icon: PropTypes.oneOf(Object.keys(availableIcons)).isRequired,
  color: PropTypes.string,
  width: PropTypes.string,
};

IconSvg.defaultProps = {
  width: "24px",
  height: "auto",
  color: "inherit",
};

export default IconSvg;
